### ISSUE TITLE
Do stuff to units on creation without a "race condition"

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#1025]
### User story

I'm creating a unit with something important about it, encoded as a rules param. An existing example is "morphed from" so that other wupgets can copy some data over from the old unit. But it could be anything that warrants tracking (unit is hero, unit is infested etc). I look for the param in other wupgets' `wupget:UnitCreated`: 
```lua
local unitID = Spring.CreateUnit(...)
Spring.SetUnitRulesParam(unitID, "foo", "bar")
Spring.SetUnitRulesParam(unitID, "baz", 123, { visibility = "private" })
```
But this doesn't actually let other gadgets know about this trait because all `wupget:UnitCreated` are resolved as part of the `CreateUnit` call, and the `SetRulesParam` happens after they all already ran.

### Workarounds and how they fail

* you can set a global game (or team) rules param beforehand and have wupgets read that instead of the actual unit rules param This is inelegant, bug-prone and doesn't work if units are created recursively.
* you can set the unit rules param and then manually call some custom `wupget:UnitCreatedForReal`. This is inelegant and relies on a game-specific mechanism.

### The request

The request is to expose some clean engine way to do this. Probably just a table parameter:
```lua
Spring.CreateUnit(..., { foo = "bar", baz = { value = 123, visibility = "private" } })
```

**Comment by Krogoth100** [comment]
There is an alternative:

local function UnitCreationProcess(unit)
    SetUnitRulesParam(unit, <...>)
    ...
end
...
Spring.CreateUnitFunc(..., UnitCreationProcess)

It is better because you can do more besides rule params.

**Comment by sprunk** [comment]
Looks like it may be easy in Lua after all.
```lua
-- gadget
GG.onCreateUnit = function(unitID) bla end
Spring.CreateUnit(bla)
```
```lua
-- gadget handler
function gadgetHandler:UnitCreated(unitID, bla)
  if GG.onCreateUnit then
    GG.onCreateUnit(unitID)
    GG.onCreateUnit = nil
  end

  for _, g in pairs(gadgets) do
    g:UnitCreated(bla)
  end
end
```
Perhaps not even gadget handler but a regular gadget with `layer = -math.huge`.
