### ISSUE TITLE
Customizable fac bugger off position/radius

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#103]
Bugger off is currently always in front of the fac and its radius depends on factory modelradius: https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Sim/Units/UnitTypes/Factory.cpp#L110

This creates some issues for offset buildpads, like in this old ZK exaggerated example:
![image](https://user-images.githubusercontent.com/2573076/138460682-e8123292-4a1f-43b6-9862-6946c18ca37b.png)

The request is for these to become customizable, ideally by something like `Spring.BuggerOff(x, z, radius[, bool forced[, bool spherical[, int excludedUnitID]]])` because that's the most generic, but maybe also by unit def tags so that non-LUS (ie. BOS/COB) can use it.

**Comment by lhog** [comment]
See https://github.com/beyond-all-reason/spring/commit/d85f5263c586f11df663b5868b4c03a5b95a4696 for implementation details

**Comment by lhog** [comment]
Actually `boExcludeSelf` is redundant in the context of Factory, will be removed later.

**Comment by sprunk** [comment]
Cool, thanks. Any way to easily visualize the bugger off radius for debugging, something like in `/debugcolvol`?

**Comment by lhog** [comment]
Enjoy https://github.com/beyond-all-reason/spring/commit/f4d612626b751e4e5141d62b4dd3341969668201
