### ISSUE TITLE
gl.Texture apparently oversized bitmap

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#1033]
When attempting to load an 8K 16-bit grayscale png texture I get the following error
`Error: [TexMemPool::AllocRaw] failed to allocate bitmap of size 536870912u from pool of total size 536870912u`

Clearly, 8K 16-bit grayscale is 134217728 bytes, not 536870912
":l:"/":n:" parameter is used too, thus no mip. Which results in a modest texture size, so it should work perfectly.
Also, even if it was that big, statement that it cant allocate X out of X doesn't make much sense to me.

Error is presumably somewhere here:
https://github.com/beyond-all-reason/spring/blob/2e7513d50ff9e733cfa69694eb98812768ab81cb/rts/Rendering/Textures/Bitmap.cpp#L1127C4-L1127C4

**Comment by lhog** [comment]
Why don't you attach the `.png` in question?

**Comment by lhog** [comment]
Also by convention `gl.Texture()` calls load `GL_RGBA` textures, which will lead to `134217728 * 4 = 536870912`

**Comment by Krogoth100** [comment]
> Why don't you attach the `.png` in question?

No need, because

> Also by convention `gl.Texture()` calls load `GL_RGBA` textures, which will lead to `134217728 * 4 = 536870912`

This.
I think this should be changed.
Bitmap Load code must deal with specific formats properly as it should.
I will be making a custom function on my own fork, dealing with this issue later, so no rush with this.

**Comment by lhog** [comment]
> No need, because

Well yes, but it's an extra effort to first create such png and then reproduce your issue or make a possible fix. Doesn't make sense to not give me the file if you want a fix.

Also I see you mention your fork and I may well accept this way suits you better. In the end that's how we started when `spring/spring` lost its ways, but as your fork will be diverging more and more from the main line you will have to make a decision if you prefer to push fixes in your fork or make issues here. Your call.

**Comment by Krogoth100** [comment]
> > No need, because
> 
> Well yes, but it's an extra effort to first create such png and then reproduce your issue or make a possible fix. Doesn't make sense to not give me the file if you want a fix.
> 
> Also I see you mention your fork and I may well accept this way suits you better. In the end that's how we started when `spring/spring` lost its ways, but as your fork will be diverging more and more from the main line you will have to make a decision if you prefer to push fixes in your fork or make issues here. Your call.

Of course
Here is the file: https://drive.google.com/file/d/14IiNEOPOYJV78uFxb31zD5YzkwFrKS9J/view

No, the thing is, anyone will stumble upon this problem once they start working with large textures. Only reason we don't see complaints rn because people haven't used large textures.
If you fix it first I my peek into your solution, and vice versa.

**Comment by lhog** [comment]
Please check if https://github.com/beyond-all-reason/spring/commit/a43db7ea72bdf2412a218e3ad86b394a33405270 does what I think it should.

**Comment by Krogoth100** [comment]
> Please check if [a43db7e](https://github.com/beyond-all-reason/spring/commit/a43db7ea72bdf2412a218e3ad86b394a33405270) does what I think it should.

Unfortunately will be able to do it only by the end of the week
Thanks for endeavour, will test when I can

**Comment by lhog** [comment]
No worries. Even if it solves the issue, it will be merged only after a stable version is released (as it may potentially break `Lua{UI,Rules,Intro}` textures).

**Comment by Krogoth100** [comment]
Finally tested it! It appears to have fixed the problem, gj!

**Comment by Krogoth100** [comment]
^
