### ISSUE TITLE
Review `Spring.GetSelectionBox` return values

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#1035]
Doxygen says
```
 * @treturn ?nil|number bottomLeftX
 * @treturn ?nil|number topRightX
 * @treturn ?nil|number topRightY
 * @treturn ?nil|number bottomLeftY
```
but code says
```
lua_pushnumber(L, bottomLeft.x);
lua_pushnumber(L, topRight.y);
lua_pushnumber(L, topRight.x);
lua_pushnumber(L, bottomLeft.y);
```

There is a mismatch. But on closer look this order looks weird either way. It looks like it actually returns the top-left and bottom-right corner despite the var names?
* x1 >= x2 but y1 <= y2. Perhaps this is because the 2D screen origin is bottom-left while the 3D world origin is top-left?
* why not use topLeft and bottomRight directly (they should be available via the `tl` and `br` vars in the func) and then have a natural AABB order instead of ABBA?
* if this is done for a reason it could use a comment.

**Comment by sprunk** [comment]
Perhaps @badosu would know?

**Comment by badosu** [comment]
What is the desired response? Or is just the documentation wrong?

**Comment by badosu** [comment]
So, I looked at it, the format is such to replicate what `Spring.GetUnitsInScreenRectangle` receives.

I updated documentation to reflect that.

If we want to change the actual format of the calls I think that merits a separate issue, I agree that we should have a standard AABB definition.
