### ISSUE TITLE
Add radial bugger off to Lua API

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#1042]
See #905, probably a boolean param for existing bugger off interfaces.

**Comment by loveridge** [comment]
How is this different from the current buggeroff behavior after https://github.com/beyond-all-reason/spring/pull/983?

**Comment by sprunk** [comment]
https://github.com/beyond-all-reason/spring/blame/BAR105/rts/Lua/LuaSyncedCtrl.cpp#L3823-L3832

This interface has no boolean choice between "move to random spot outside the circle" vs "move towards the closest edge of the circle" (as seen in the picture on top of #905). The reason you'd sometimes not want the closest-edge behaviour is because units entering a freestanding bugger-off area would turn 180' and go back in the direction they came from, so after they're done buggering off they would do a 180' again and come right back into the bugger-off area, getting stuck in a loop. Eventually they would migrate to the sides but this could take a while and produce a sort of traffic congestion if there's more units.
![image](https://github.com/user-attachments/assets/2321ca1d-d8f6-4523-b299-b64e38a1ceb0)

I am not necessarily saying that the non-closest-edge option should specifically be random, but that's what exists already (I didn't check whether #983 replaced it wholesale or just added an alternative, but #905 asked to keep factories random, and also the implementation is still there in git history regardless). Perhaps the better approach would be to have a choice between handled automatically (closest edge) and not handled by the engine at all and producing a Lua event instead. But that needs some design work (e.g. how do I distinguish bugger offs? do they now need an ID? etc) so using the existing random behaviour under a bool sounds easiest.

Also keep in mind this is very low priority.

**Comment by loveridge** [comment]
I think bugger-off only gives nonmoving units new commands, a unit wont just enter the area and turn around. BuggerOff just sets parameters that then have an effect when NonMoving: https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Sim/Units/CommandAI/MobileCAI.cpp#L1032. Newly created factory units seem to use https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Sim/Units/UnitTypes/Factory.cpp#L337, not buggeroffs to move them out of the factory.

**Comment by sprunk** [comment]
Hm, alright. I'll think about it but it looks like it's fine as-is.
