### ISSUE TITLE
[FR] Select: Make IdMatches OR with other IdMatches calls in same select command

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/spring#1058]
Currently it's impossible to filter specifically one unit OR another in a selection command.

### Proposed Implementation

- Make [IdMatches filter](https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Game/UI/SelectionKeyHandler.cpp#L179-L184) append to a list outside its closure and return always true
- [After all filters have been passed through](https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Game/UI/SelectionKeyHandler.cpp#L417-L417) use the list to check if _any_ of the names in list is contained, e.g. `unit->unitDef->name.compare(name)`
- Do the same in a separated list for negated IdMatches to be AND'ed (tricky)

There's probably a more elegant solution but this would be the first thing I'd try

**Comment by sprunk** [comment]
ideally the harmless separator would be `_IdMatches_`

**Comment by badosu** [comment]
You mean `_IdMatches_unitok_IdMatches_unitop` ?

**Comment by sprunk** [comment]
Yes, the `IdMatches` operator would just be ORed with other instances of itself instead of AND (since right now it doesn't make much sense - nothing can match 2+ names). This may require a change in the parser though.

**Comment by badosu** [comment]
Yeah, it's more difficult. You'd basically have to store state of the OR'ed unitids and make it run only after the whole filter list has been passed through.

Making it a single command would be a simpler implementation, but less flexible for sure

**Comment by sprunk** [comment]
Over the years I've seen multiple people assume it was an OR (what else would it be? AND is obviously silly) and get disappointed. Fortunately selections are trivial to do via Lua actions so at least ZK doesn't mind that much.

**Comment by badosu** [comment]
Sounds good, I like the design
