### ISSUE TITLE
Defective D on impact

### ISSUE THREAD

**Issue by TheSilverHornet** [beyond-all-reason/spring#1079]
While trying to make a sane flamethrower, with a cone of flame rather than 'column', I tried particles that were larger the further they were from their emission source, via **sizegrowth = "0.3 d+5"** ... which worked, to a point.

A video is worth ten thousand words so here's an example, a beautiful flame cone, that loses the plot on unit impact https://discord.com/channels/549281623154229250/551411485901979659/1173203510100250654

**Comment by lhog** [comment]
This is not a good report. The way to make it good is to:
1) Upload videos directly here
2) Link source code of your effect (with issue / without issue)
3) The effect should have minimum number of classes / instances. Basically a minimal example to reproduce.

**Comment by TheSilverHornet** [comment]
Noted then, I'll distill that shortly.

**Comment by TheSilverHornet** [comment]
https://github.com/beyond-all-reason/spring/assets/37483246/eed4fd13-6b52-4c08-a79b-5318f8780220


https://github.com/beyond-all-reason/spring/assets/37483246/b54b791a-5897-4d00-9b65-cd02e484c331

The first is normal, the second I used /reloadcegs to change the sizegrowth alone, all else being equal.

Example effect configs, only difference being `sizegrowth= "2.3 r3",`, or   `sizegrowth = "2.3 d+5"`:


defective:

`  ["burnthermite"] = {
    flame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.98,
        colormap           = [[0.7 0.4 0.1 0.3   1 1 1 1   0.95 0.8 0.66 1   0.45 0.25 0.1 0.6   0.023 0.022 0.022 0.3   0.023 0.022 0.022 0.05   0 0 0 0.03   0 0 0 0.01]],
        directional        = false,
        emitrot            = 70,
        emitrotspread      = 40,
        emitvector         = [[0.3, 1, 0.3]],
        gravity            = [[0, 0.11, 0]],
        numparticles       = 1,
        particlelife       = 9,
        particlelifespread = 5,
        particlesize       = 20,
        particlesizespread = 16,
        particlespeed      = 0.5,
        particlespeedspread = 0.7,
        pos                = [[-3 r6, -3 r6, -3 r6]],
        sizegrowth         = "2.3 d+5",
        sizemod            = 0.97,
        rotParams          = [[-8 r16, 0, -180 r360]],
        animParams         = [[16,6,80 r55]],
        texture            = [[BARFlame02]],
        castShadow         = true,
      },
    },
  },`
  
  fine: 
  `  ["burnthermite"] = {
    flame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        airdrag            = 0.98,
        colormap           = [[0.7 0.4 0.1 0.3   1 1 1 1   0.95 0.8 0.66 1   0.45 0.25 0.1 0.6   0.023 0.022 0.022 0.3   0.023 0.022 0.022 0.05   0 0 0 0.03   0 0 0 0.01]],
        directional        = false,
        emitrot            = 70,
        emitrotspread      = 40,
        emitvector         = [[0.3, 1, 0.3]],
        gravity            = [[0, 0.11, 0]],
        numparticles       = 1,
        particlelife       = 9,
        particlelifespread = 5,
        particlesize       = 20,
        particlesizespread = 16,
        particlespeed      = 0.5,
        particlespeedspread = 0.7,
        pos                = [[-3 r6, -3 r6, -3 r6]],
        sizegrowth         = "2.3 r3",
        sizemod            = 0.97,
        rotParams          = [[-8 r16, 0, -180 r360]],
        animParams         = [[16,6,80 r55]],
        texture            = [[BARFlame02]],
        castShadow         = true,
      },
    },
  },`
  
  The absolute minumum that will trigger it:
  
  `
    ["burnthermite"] = {
    flame = {
      air                = true,
      class              = [[CSimpleParticleSystem]],
      count              = 1,
      ground             = true,
      properties = {
        numparticles       = 1,
        particlelife       = 8,
        pos                = [[-3 r6, -3 r6, -3 r6]],
        sizegrowth         = "4.3 d+5",-- [[1.2 r2.99]],--0.3 d+5
        sizemod            = 0.97,--if this is 0.001 then the explosion is minimised
        animParams         = [[16,6,80 r55]],--not needed for 'explosion' bug but looks fully broken without it
        texture            = [[BARFlame02]],
        castShadow         = true,
      },
    },
  },
  `

**Comment by TheSilverHornet** [comment]
hold the phone, the issue might be a D value on an effect that's used as an explosion, that effect was in two places. will investigate more later.

**Comment by sprunk** [comment]
I'm not sure if putting `d` in sizeGrowth is a good idea for the cegtrail either. If anything it should probably be the regular size (so it shrinks over time, as opposed to growing over time with the growth slowing down over time).

**Comment by sprunk** [comment]
Haven't seen any evidence this isn't working as intended.
* the CEG is also used on the explosion in addition to the trail, so it's expected it would get bigger when modified
* `d` tends to have comparatively large values so it's expected that putting it in `sizeGrowth` would make the sprites grow very fast.
