### ISSUE TITLE
Units gets trapped inside enemy factory

### ISSUE THREAD

**Issue by marcushutchings** [beyond-all-reason/spring#1080]
In BAR you can move a Dolphin T1 ship into or through an enemy sea factory. When the dolphin touches a unit being built in the sea factory, it gets teleported away - often into one of the factory's support pillars. The dolphin is now trapped between the support pillar and the telporting effect - which keeps moving the unit back into the support pillar every time it tries to move out.

**Comment by sprunk** [comment]
Sounds like a gameside issue? Don't teleport units into stupid places.

**Comment by marcushutchings** [comment]
I suspect you're right. I just don't have time to check and I don't want to lose track of the issue.
