### ISSUE TITLE
Missing weapontag for weaponAimAdjustPriority

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/spring#1083]
### Proposed solution

Add a `WEAPONTAG` similar to others defined here: https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Sim/Weapons/WeaponDef.cpp#L87

**Comment by badosu** [comment]
Makes sense, we need to add some form of unitdef autodoc

**Comment by badosu** [comment]
I'd prefer having a separate issue for that, but sure. Care to provide a description body?

**Comment by sprunk** [comment]
Makes sense, made a separate ticket #1087
