### ISSUE TITLE
Missing weapontags

### ISSUE THREAD

**Issue by TheSilverHornet** [beyond-all-reason/spring#1084]
Looks like fastQueryPointUpdate and fastautoretargeting are undocumented extras also
Will update this if, as & when I find more

**Comment by sprunk** [comment]
Duplicate of #1083 which also links to the full list

**Comment by TheSilverHornet** [comment]
It wasn't a dupe at the time, it came from the same conversation I started. As long as they're known and listed somewhere that's all good.
