### ISSUE TITLE
2131 Access violation early in an AI game

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#1107]
[ai.zip](https://github.com/beyond-all-reason/spring/files/13533387/ai.zip)

[infolog.txt](https://github.com/beyond-all-reason/spring/files/13533388/infolog.txt)

Reproduces https://github.com/ZeroK-RTS/CrashReports/issues/85127

It spawns and makes units from its factory and with its commander. Then crashes.

**Comment by GoogleFrog** [comment]
Here is a log using the circuit packaged by the engine https://github.com/ZeroK-RTS/CrashReports/issues/85130

**Comment by marcushutchings** [comment]
How repeatble is this issue? And how does setup Zero-K to run that version of the engine?

**Comment by GoogleFrog** [comment]
It has now worked for me 1/1 times with 2141.
