### ISSUE TITLE
Improve load performance by speeding up font blur

### ISSUE THREAD

**Issue by bigbluejay9** [beyond-all-reason/spring#1126]
About ~2 seconds is spent every loading screen [blurring font shadow textures](https://github.com/beyond-all-reason/spring/blob/60ac1a4af0380d164eb64b9f7a40e90b05d03ae9/rts/Rendering/Fonts/CFontTexture.cpp#L1057). Additionally, the execution of the blur filter corresponds to the periods of peak CPU usage during the load sequence.  *Note this only affects non-headless builds.*

Linux
![Screenshot from 2023-12-10 05-54-27](https://github.com/beyond-all-reason/spring/assets/2730943/3a8d70f1-3f07-43dd-81c8-b644abdd3056)

Windows
![Screenshot from 2023-12-10 05-59-59](https://github.com/beyond-all-reason/spring/assets/2730943/27d221bd-4814-46b7-a983-7a8b4a496e23)

Blurring the font's shadow texture gives a nice visual effect when outlining text. See the following images of text with and without blur.

With Blur
![oac](https://github.com/beyond-all-reason/spring/assets/2730943/8b628fc0-6e0d-4e23-804c-3681e28a7f63)

Without Blur
![noblur_oac](https://github.com/beyond-all-reason/spring/assets/2730943/c3d5f621-3ab7-4f1f-942a-d1db9d62ab02)

This issue proposes enhancements to the load speed by addressing the expensive blur process.

## Font Textures Background

Font textures are [created or updated](https://github.com/beyond-all-reason/spring/blob/60ac1a4af0380d164eb64b9f7a40e90b05d03ae9/rts/Rendering/Fonts/CFontTexture.cpp#L841) whenever spring needs a glyph that has not been loaded in the current font texture. When loading any font file, spring loads [glyphs at codepoints 32 - 127](https://github.com/beyond-all-reason/spring/blob/60ac1a4af0380d164eb64b9f7a40e90b05d03ae9/rts/Rendering/Fonts/CFontTexture.cpp#L601) into the initial font texture.

Spring uses a unique font texture for every `<font file name, font size, outline size, outline weight>` tuple. This tuple corresponds to an instance of a [CFontTexture class](https://github.com/beyond-all-reason/spring/blob/60ac1a4af0380d164eb64b9f7a40e90b05d03ae9/rts/Rendering/Fonts/CFontTexture.cpp#L535C72-L535C72).  As a rough estimate, a BAR game loads about ~40 instances of CFontTextures.

When a glyph is loaded into a font texture, the bitmap is loaded into two different locations of the texture [one for the actual glyph](https://github.com/beyond-all-reason/spring/blob/60ac1a4af0380d164eb64b9f7a40e90b05d03ae9/rts/Rendering/Fonts/CFontTexture.cpp#L831) and [another for the shadow of the glyph](https://github.com/beyond-all-reason/spring/blob/60ac1a4af0380d164eb64b9f7a40e90b05d03ae9/rts/Rendering/Fonts/CFontTexture.cpp#L833).  Prior to [handing the texture over to opengl](https://github.com/beyond-all-reason/spring/blob/60ac1a4af0380d164eb64b9f7a40e90b05d03ae9/rts/Rendering/Fonts/CFontTexture.cpp#L1084), the [shadow glyphs are blurred](https://github.com/beyond-all-reason/spring/blob/60ac1a4af0380d164eb64b9f7a40e90b05d03ae9/rts/Rendering/Fonts/CFontTexture.cpp#L1057).

The [guassian blur uses a CPU implementation](https://github.com/beyond-all-reason/spring/blob/60ac1a4af0380d164eb64b9f7a40e90b05d03ae9/rts/Rendering/Textures/Bitmap.cpp#L656) which is visible in the Tracy profiles above. Most notably, the initial blur of the 'Poppins' font for the initial codepoints 32-127 typically takes ~1 second.

## Speeding Up Blur

There are three main ways of speeding up blur: caching, shader offload, and alternate blur algorithms. These paths are not mutually exclusive.

#### On Demand

We could make spring cache  font textures by saving the textures into a file, e.g. `cache/fonts/$FONT_$SIZE_$OUTLINEatlasTexture.png`. This method will slow loading the first time a new font texture is created, but subsequent loads will just hit the cache.

I ran a very brief test and determined that only about ~5 font textures are used by the time the game is loaded. Saving textures into `bmp` files results in an additional 50ms in the load screen with each `bmp` file of size ~10MiB.  Saving textures into `png` files results in an additional 200ms in the load screen, with each file of size ~200KiB.

As font textures are dynamically generated depending on the new glyphs requested from spring, saving font textures in an on disk cache will also require saving the [glyph info map](https://github.com/beyond-all-reason/spring/blob/60ac1a4af0380d164eb64b9f7a40e90b05d03ae9/rts/Rendering/Fonts/CFontTexture.h#L186) as well. The glyph info map is a map of glyph codepoints to texture coordinates.

#### At Installation

Similar to caching on demand, we could pre-generate font texture maps cache entries and distribute them in `sdp` packages. This method increases the download size of updates but ensures that users don't pay the initial cache entry generation cost.

### Shader

The blur algorithm is currently implemented in CPU. This work can be offloaded into a shader, which then would then update the texture. See [this link](https://gamedev.stackexchange.com/questions/31162/updating-texture-memory-via-shader) for ideas on how to update the font texture via a shader.

Alternatively, we could use a shader to blur glyphs on demand. However, this would incur a performance penalty whenever we want to render a glyph which I think is unacceptable.

### Alternate Algorithms

The blur algorithm creates pretty outlines for text - giving them a 'depth' as well as improving clarity. Alternative algorithms exists to outline text without a gaussian blur as outlined [here](https://gamedev.stackexchange.com/questions/46490/font-outline-in-opengl-ftgl).  I have yet to try any of these, so we don't know the quality degredation of using these algorithms.

Finally, we can simply try to find a faster implementation of gaussian blur as a drop in replacement for the [current one](https://github.com/beyond-all-reason/spring/blob/60ac1a4af0380d164eb64b9f7a40e90b05d03ae9/rts/Rendering/Textures/Bitmap.cpp#L656).

## Proposal

I will try the 'On Demand Caching' method. This method will improve subsequent load times with no effect on visual quality nor download sizes. Let me know if you think otherwise.

**Comment by lhog** [comment]
Thanks for an outstanding quality report!

I haven't noticed blur is such costly. Is your CPU decent?

I'd actually start from the Alternative Algorithms: Gaussian Blur is axis separable so it should be possible to reduce the computation cost quite a bit.

Longer term we're considering alternative Fonts implementations, especially if https://github.com/mikke89/RmlUi integration is merged.

**Comment by 6AKU66** [comment]
Not related, but maybe useful: As i remember we had in-game gfx_guishader being pretty expensive until someone (probably Beherith) rewrited it.

**Comment by lazau** [comment]
CPU is a Ryzen 7 3700X [Steam specs.txt](https://github.com/beyond-all-reason/spring/files/13649996/specs.txt).

I tried axis separation. Implementation in (see ~line 631) [Bitmap.axis_separate_with_weight.cpp.txt](https://github.com/beyond-all-reason/spring/files/13650043/Bitmap.axis_separate_with_weight.cpp.txt). The speedup was from about 1.9 sec -> 1.5 sec. This smaller amount of gain is explainable by the kernel size of the blur: the original blur algorithm requires (3x3) 9 multiplications per kernel pass. The axis separated version requires (2 x 3) 6 multiplications per pass. Axis separation sees much more significant gains when the kernel size is larger.

Moreover, the original algorithm is not technically a gaussian blur. This additional [weight](https://github.com/beyond-all-reason/spring/blob/60ac1a4af0380d164eb64b9f7a40e90b05d03ae9/rts/Rendering/Textures/Bitmap.cpp#L673) makes the original pixel weight a bit more for the final pixel result. To replicate this in the axis separated algorithm, we need to create two temporary bitmaps for the blur passes (as opposed to using only a single temporary):

- first pass blurs `src` in the x dimension, saves to `tmp[0]`
- second pass blurs `tmp[0]` in the y dimension, saves to `tmp[1]`
- second pass needs to look back at the original  `src` and add an additional weight to match the current algorithm.

Tracy original algorithm
![Screenshot from 2023-12-12 07-41-47](https://github.com/beyond-all-reason/spring/assets/2730943/46f81e16-adfb-4290-8b23-483dc3f10418)

Tracy axis separated blur
![Screenshot from 2023-12-12 07-42-03](https://github.com/beyond-all-reason/spring/assets/2730943/e1f5b804-f5bc-4ed9-9f6f-9ef51a54a69f)

Output comparison (rendering only the shadow texture which is blurred)

Original blur text
![orig_blur](https://github.com/beyond-all-reason/spring/assets/2730943/90f34254-d45f-4781-9f1e-ffd6a94fa48c)

Axis separated gaussian blur (i.e. no weighting as done in the original)
![axis_separated_no_weight](https://github.com/beyond-all-reason/spring/assets/2730943/f2ab54c1-c7a1-4e0e-a756-3fd389ba0e28)

Axis separated with weighting
![axis_separated_with_weight](https://github.com/beyond-all-reason/spring/assets/2730943/b0395388-abbf-4a0d-aca9-70e8905c839a)

**Comment by lhog** [comment]
Yeah the perf gain here is not stellar.

In the same it seems I misdiagnosed where the compute cost is coming from. Once the BAR load screen starts one of the fonts is requested to get blurred 18 times (YMMV as this parameter is most likely dynamic and depends on the screen resolution):
`atlasUpdateShadow.Blur(outlineSize, outlineWeight);` `outlineSize was 18 for one of the Fonts` This is where it gets costly. Even with a compute shader or FBO ping-pong it will be quite costly to blur so many times.

Maybe we should switch to http://freetype.org/freetype2/docs/reference/ft2-outline_processing.html instead of reinventing the wheel.

**Comment by lhog** [comment]
Btw, here is the sequence of bitmaps that helps visualize the process:

![atlasUpdate](https://github.com/beyond-all-reason/spring/assets/1476261/0bcda21a-d443-446c-a17a-76385723fecb)
![atlasUpdateSh](https://github.com/beyond-all-reason/spring/assets/1476261/c00fd416-ab62-4352-a484-8707c0f5c158)
![atlasUpdateShBlur](https://github.com/beyond-all-reason/spring/assets/1476261/df50171c-aa89-43b9-b328-5e478191f787)
![atlasUpdateOr](https://github.com/beyond-all-reason/spring/assets/1476261/a813d829-f1ac-4d3e-873c-ff10672bd6f7)

**Comment by lazau** [comment]
Given that I've already done the implementation for axis separation and there is a bit of gain with no visual difference, does it make sense to merge that?

I'll take a look at using the outline functionality in freetype. Although I expect we'll get slightly degraded visual quality since the current implementation is more like a shadow (with alphas and all).

Overall, the blur is ~10% of the load time, so I think it still make sense to explore moderately complex solutions even though RmlUI is the long term goal.

**Comment by lhog** [comment]
Oh yes, your work won't be wasted. Feel free to make a PR request with all the changes.
Just be aware that the engine is currently in the feature freeze period as we're trying to release the next stable, so will only be able to merge your change after the stable is out.

**Comment by sprunk** [comment]
696e69ab482d5c0147250d6d961776b87bd496a9
