### ISSUE TITLE
EngineCrash [2142] global unit limit

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/spring#1133]
Reproduce: spawn max amount of units for every team (included gaia faction), destroy all units (except of commander), try to build anything with commander.

**Engine Version**
105.1.1-2142-g72b2d55 bar

[infolog.txt](https://github.com/beyond-all-reason/spring/files/13654320/infolog.txt)
[2023-12-12_23-50-22-358_Ancient Vault v1_105.1.1-2142-g35a026a BAR105.zip](https://github.com/beyond-all-reason/spring/files/13654321/2023-12-12_23-50-22-358_Ancient.Vault.v1_105.1.1-2142-g35a026a.BAR105.zip)

**Comment by lhog** [comment]
What means did you use to remove units spawned in the first batch?

**Comment by 6AKU66** [comment]
> What means did you use to remove units spawned in the first batch?

I used self-d command for units as i remember.

**Comment by lhog** [comment]
N2S: `SimObjectIDPool` corner case.
