### ISSUE TITLE
overrides for glow and normals information for 3do textures

### ISSUE THREAD

**Issue by springraaar** [beyond-all-reason/spring#1134]
Apparently there's no way to set glow or normals for 3d model textures used by 3do models (tatex). This is about finding a simple backward compatible way to add such information for specific textures.

I'm aware 3do is deprecated and the tools for s3o conversion have improved but it doesn't hurt to ask.

For such texture images:
- rgb controls the texture
- alpha controls reflectivity
- listing on teamtex.txt makes pixels with r=b and g=0 match the team color

Suggestion:
- make listing glowtex.txt generate a glow mask for the texture. Use brightened grayscale variant of the original image as a mask.
(probably allows reusing some of the logic used to process teamtex.txt, but would allow for glow only)
OR
- when processing/loading each texture image, "imageName.bmp", look for for a "imageName.ex" file containing the extra information (normals in rgb and glow in alpha) and use it instead of the defaults if it exists

**Comment by lhog** [comment]
Generate the needed textures (glow, reflectivity, normal) by yourself and use CUS or GL4_CUS to render 3do models as you like.
Internally 3do is not much different than other modern formats, so nothing prevents you from using custom shading with 3do.
Doing an additional engine work on 3do is a waste of time.
