### ISSUE TITLE
105-2152 Rover Assembly makes units at an angle

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#1140]
http://zero-k.info/Battles/Detail/1782588

(factoryveh)

![image](https://github.com/beyond-all-reason/spring/assets/1318249/157485eb-3e6f-4f26-8aa1-c80d7ac01da8)

![image](https://github.com/beyond-all-reason/spring/assets/1318249/6b2a97af-46ee-4825-b86e-0d8fa4774ca1)

In 1821 it builds straight:

![image](https://github.com/beyond-all-reason/spring/assets/1318249/30a58bdb-73c7-4212-a5fe-e23d57113a7b)

**Comment by marcushutchings** [comment]
The factory requests `buildPiece = script->QueryBuildInfo();`  then `script->GetPieceMatrix(buildPiece);` and then `buildPieceHeading = GetHeadingFromVector(buildPieceMat[2], buildPieceMat[10]);` which comes out as `1316` instead of `0`, which is why the units are rotated slightly.

**Comment by marcushutchings** [comment]
@lhog you know more about pieces and such, Has something changed that could cause this?

This is the line where the unit's off-centre rotation is being applied: https://github.com/beyond-all-reason/spring/blob/d8a04f68a3c49964a931e19018ad06b87eb73ea1/rts/Sim/Units/UnitTypes/Factory.cpp#L226C6-L226C6
