### ISSUE TITLE
105-2152 Spectator desync in first game, maybe rejoin?

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#1142]
http://zero-k.info/Battles/Detail/1782588

I wasn't paying a lot of attention, but it felt like every spectator in this game desynced. This was potentially because almost every spectator joined midway through.

**Comment by marcushutchings** [comment]
We will need the client game-state dump of one of those spectators.

**Comment by marcushutchings** [comment]
The frame 0 desync is a concern. I'm glad Zero-K ran on HAPFS, because BAR has a similar issue, but runs on QTPFS. So that suggests I've either managed to introduce the same problem to both pathfinders at the same time or the problem isn't with the pathfinders.

**Comment by marcushutchings** [comment]
One of the spectator observed they got the desync even after rejoining, which is interesting.

**Comment by lhog** [comment]
Next time it happens send at least infolog.

**Comment by GoogleFrog** [comment]
Many infologs for the game in question are the first ones here: https://github.com/ZeroK-RTS/CrashReports/issues?q=is%3Aissue+is%3Aopen+2152

I don't know what a ClientDesync log is.

**Comment by lhog** [comment]
I checked a few infologs selectively and they were truncated. Normal `infolog.txt` files are therefore preferred (and sometimes required).

> ClientDesync log is.

We discussed it in the past, there's a setting ZK is currently enacting via
https://github.com/beyond-all-reason/spring/wiki/Engine-Settings-Config-File

that forces game state dumps on all player machines upon a desync event. A write-dir will have a file named `ClientGameState-<some negative or positive number>-<desync frame>-<desync frame>`, the file is usually quite big, several hundreds of megabytes sized. We will need two or more files: one from one of the players that didn't desync (representing a majority frame checksum) and one or more from desyncees.

Hope that explains what ClientDesync/ClientGameState log is.

I'm gonna release a new engine candidate version soon. It has path cache version bumped up and a content checksum related debug added. It'd be great if you could run the same map on this new engine.

**Comment by lhog** [comment]
https://github.com/beyond-all-reason/spring/releases/tag/spring_bar_%7BBAR105%7D105.1.1-2156-g5cfd088

**Comment by GoogleFrog** [comment]
My ZK folder doesn't have any files with ClientGameState in the name. This is the steam one, I don't think it is set up to read any other write dirs. It could be to do with how chobby launches an extra Spring to run non-server engines.

```
[t=00:00:00.048454] [DataDirLocater::FindWriteableDataDir] using writeable data-directory "B:\Steam\steamapps\common\Zero-K\"
[t=00:00:00.048455] Using writeable configuration source: "B:\Steam\steamapps\common\Zero-K\springsettings.cfg"
[t=00:00:00.048456] Using additional read-only configuration source: "B:\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-1821-gaca6f20\springsettings.cfg"
[t=00:00:00.048481] LogOutput initialized. Logging to B:\Steam\steamapps\common\Zero-K\infolog.txt
```

**Comment by lhog** [comment]
It's supposed to be in `B:\Steam\steamapps\common\Zero-K\` for you, if ZK has enabled `DumpGameStateOnDesync = 1` in the server's springsettings.

**Comment by GoogleFrog** [comment]
I don't have the file.

**Comment by marcushutchings** [comment]
I believe only BAR servers have been configured with that option up to this point. I don't believe Zero-K enabled it on their servers.

**Comment by sprunk** [comment]
Looks like we put it into startscript by mistake instead of the server's springsettings https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/9242fbe848bc389c97f273e74f59c46683ee2bc6/Shared/LobbyClient/ScriptGenerator.cs#L61

**Comment by marcushutchings** [comment]
And here, I thought, Zero-K didn't want it enabled!  :)

**Comment by lhog** [comment]
Actually I think we need to move this option from spring-settings to startscript or modrules.

**Comment by marcushutchings** [comment]
The server is the place where the sync detection happens.

**Comment by lhog** [comment]
No disagreement here, but `springsettings` toggle feels less centralized / enforceable. For example: if the modrule is set, it will be the same for all participants, so a server can read it to send the net message to enforce the state dump, while with springsettings I'm sure half of the people will set the toggle in a wrong place (i.e. on the client side).

**Comment by marcushutchings** [comment]
I sense some confusion here. The clients will action the dump when the server tells them to. There is nothing that needs to be set client set. We just have to set the option, on the server, to make the server command the clients to dump state on the first time it detects a desync.

**Comment by sprunk** [comment]
Old engine and there was no dump.
