### ISSUE TITLE
buildeeBuildRadius doesn't seem to work for nanolathing

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#1151]
I set everything to 999 buildeeBuildRadius. Nanoframes are spawned at that range but constructors then walk into their usual 100-ish range to pour buildpower into the nanoframe.

**Comment by sprunk** [comment]
Perhaps it's because these two still use the radius from the object and not the def?
https://github.com/beyond-all-reason/spring/blob/dd087d4e158747e931293a4b4832aa5a19e22341/rts/Sim/Units/CommandAI/BuilderCAI.cpp#L260
https://github.com/beyond-all-reason/spring/blob/dd087d4e158747e931293a4b4832aa5a19e22341/rts/Sim/Units/CommandAI/BuilderCAI.cpp#L275

**Comment by marcushutchings** [comment]
buildeeBuildRadius, at this stage (i.e. while we're in hotfixing) is not intended to override the object radius. It is a hotfix for the engine not being able to use object->radius for unts that do not yet exist. However, it seems perhaps maybe it is best that I do roll it out further.
