### ISSUE TITLE
Replay desync (2152)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/spring#1154]
Reproduce: watch replay.
https://youtu.be/JVZ82S9YHSw
https://www.beyondallreason.info/replays?gameId=257287651f49230c66257477495c5449

**Comment by marcushutchings** [comment]
Time into the replay does the desync happen? How many players desync?

Normally, we will need the desyncing player's client state dump. Without it, we can't investigate further. The only time we don't is if we have one machine that always agrees with the desyncee and one that doesn't. Does your machine agree with the player or players that desynced?

**Comment by 6AKU66** [comment]
The thing is that people in match itself didn't desync, but rewatching replay cause desync for spectator.

**Comment by 6AKU66** [comment]
Most likely fixed by
https://github.com/beyond-all-reason/Beyond-All-Reason/commit/8d3e92733d92f4642c689fc069dd437ad3826621
