### ISSUE TITLE
105-2191 Access violation

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#1164]
https://github.com/ZeroK-RTS/CrashReports/issues/87958

[infolog.txt](https://github.com/beyond-all-reason/spring/files/13797552/infolog.txt)

https://github.com/ZeroK-RTS/Zero-K/commit/901a671bd0ce1d1e21f185e2fadc5aae0c744ef4

[2023-12-30_08-25-53-361_Fool's mate v0_105.1.1-2191-g75c601c BAR105.sdfz.txt](https://github.com/beyond-all-reason/spring/files/13797553/2023-12-30_08-25-53-361_Fool.s.mate.v0_105.1.1-2191-g75c601c.BAR105.sdfz.txt)

**Comment by lhog** [comment]
Translated stack trace:

```
-g75c601c\spring.exe | 0x1409f0185 | rts/Sim/MoveTypes/Systems/GroundMoveSystem.cpp :61 (https://github.com/beyond-all-reason/spring/blob/75c601c/rts/Sim/MoveTypes/Systems/GroundMoveSystem.cpp#L61)
-g75c601c\spring.exe | 0x1409eff9d | /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/13.2.0/include/c++/bits/atomic_base.h :426
-g75c601c\spring.exe | 0x140691215 | rts/System/Threading/ThreadPool.h :139 (https://github.com/beyond-all-reason/spring/blob/75c601c/rts/System/Threading/ThreadPool.h#L139)
-g75c601c\spring.exe | 0x140e926df | rwlock.c :1 (https://github.com/beyond-all-reason/spring/blob/75c601c/rwlock.c#L1)
-g75c601c\spring.exe | 0x140b8f2cb | /mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-13.2.0.build_/mingw-w64-v11.0.0/mingw-w64-libraries/winpthreads/src/thread.c :1527
\System32\msvcrt.dll | 0x000000000003e634 | ?? :0
\System32\msvcrt.dll | 0x000000000003e70c | ?? :0
s\SYSTEM32\ntdll.dll | 0x000000000005aa58 | ?? :0
```

**Comment by marcushutchings** [comment]
This may be fixed by: https://github.com/beyond-all-reason/spring/commit/575f94f1b8f28c9cef8b3cd722cb6b9ce2b0955a

**Comment by marcushutchings** [comment]
This should fix it. If it doesn't then the ticket can be reopened.
