### ISSUE TITLE
`Spring.GetTeamUnitsByDefs` soft-reveals decoys

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#1166]
Returned units are sorted according to their real unitDefID.

**Comment by lhog** [comment]
Hmm, can you provide a test example / point to an existing gadget?

**Comment by sprunk** [comment]
1) game: https://github.com/ZeroK-RTS/Zero-K/tree/decoy-repro
2) [script.txt](https://github.com/beyond-all-reason/spring/files/13805409/script_decoy.txt)

3) example output:
```
2072, is REAL
18909, is DECOY
31534, is REAL
3367, is DECOY
29132, is REAL
19858, is DECOY
28829, is REAL
17483, is DECOY
2017, is REAL
279, is DECOY

returned units:
1, 2072
2, 31534
3, 29132
4, 28829
5, 2017
6, 18909
7, 3367
8, 19858
9, 17483
10, 279
```
Notice how units 1-5 are the real ones and 6-10 are the decoys.

This doesn't necessarily tell you which are the decoys and which aren't (maybe all 10 are real? 1-3 are real and 4-10 are decoys? all are decoys?) but often there are extra constraints which do (e.g. in BAR you only have one real commander so you can deduce the 2nd and further are decoys).

**Comment by sprunk** [comment]
The lazy fix would be to just shuffle the whole list. But the "group by type" is convenient and would be sad to lose it.
