### ISSUE TITLE
105-2193 is broken in a few ways

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#1167]
I ran half a test game. Here were the issues:
- [x] Units sometimes spin in small circles while following paths.
- [ ] Some sort of non-zero exit code crash on launch: https://github.com/ZeroK-RTS/CrashReports/issues/88219 Possibly only an issue with external launch.
- [ ] Desync early in the game. I confirmed that it was a real divergence, but doing so was hard enough that I doubt I we can get anything more.
- [x] Constructor stuck not responding to an order, with no terrain nearby.

- Game http://zero-k.info/Battles/Detail/1795292
- Replay [2024-01-01_01-47-08-525_Tabula-v6_105.1.1-2193-g575f94f BAR105 - Copy.sdfz.txt](https://github.com/beyond-all-reason/spring/files/13802577/2024-01-01_01-47-08-525_Tabula-v6_105.1.1-2193-g575f94f.BAR105.-.Copy.sdfz.txt)
- My infolog https://github.com/ZeroK-RTS/CrashReports/issues/88220
- You'll have to ask @sprunk whether we've managed anything extra on the server.

I don't know where the different path caches are, but I have two recently modified Tabula files in cache\105dev-BAR105\paths.
[Tabula-v6.1.pe2-3ded42fd.zip](https://github.com/beyond-all-reason/spring/files/13802581/Tabula-v6.1.pe2-3ded42fd.zip)
[Tabula-v6.1.pe-3ded42ed.zip](https://github.com/beyond-all-reason/spring/files/13802582/Tabula-v6.1.pe-3ded42ed.zip)

Units spinning in circles:
![image](https://github.com/beyond-all-reason/spring/assets/1318249/737add5e-d99b-486f-8a21-3612b4fe8592)
Happened several seconds ago, and several seconds before that as well.

Stuck constructor:
![image](https://github.com/beyond-all-reason/spring/assets/1318249/ad3e033e-f8f6-4996-83e9-f751e50edbd5)
It has a move order.

![image](https://github.com/beyond-all-reason/spring/assets/1318249/7d164dc0-0f7c-48d9-a4ed-7438a830165e)
It then stops when given a build order. It looks like it is going to sit there forever.

![image](https://github.com/beyond-all-reason/spring/assets/1318249/b628f92d-b98a-43d9-96f3-c022c2301551)
This move goal looks like an anti-stuck measure I put in the raw move gadget. Basically, lua has detected that the unit is not moving. Shortly after this the player interferes with some orders so we don't know what it would do next.

**Comment by sprunk** [comment]
> You'll have to ask @sprunk whether we've managed anything extra on the server.

We did just now, so the above replay produced no desync dumps but any further tests on 2193 should have them. Though there are other things broken in addition to desync (pathing etc) so it would be good to test on a new engine where these are fixed, which in turn means a new engine where springsettings won't have been inflicted since it isn't there by default. See #1168

**Comment by marcushutchings** [comment]
https://github.com/beyond-all-reason/spring/commit/df4bb2601a9a3359d3a9f932dfcc12a1c204b168 to mitigate units spinning as they walk.

**Comment by GoogleFrog** [comment]
> [df4bb26](https://github.com/beyond-all-reason/spring/commit/df4bb2601a9a3359d3a9f932dfcc12a1c204b168) to mitigate units spinning as they walk.

Great, do you know why it happened?

**Comment by marcushutchings** [comment]
A waypoint is being created not far enough forward and the unit has to turn around to 'touch it'. Waypoints are created in batches: HAPFS consumes lower-res path points to build a high res path, which provides the waypoints. Due to how the system works, I need to build the high-res path starting far enough ahead of the unit and that wasn't always happening.

**Comment by marcushutchings** [comment]
For: "Constructor stuck not responding to an order, with no terrain nearby" - I tried out the latest engine and that didn't seem to have the problem - the replay is on a different engine, but the welder was there at the right time and was given the move and build orders as originally done and it didn't seem to get stuck. May be worth checking whether the latest engine is any better for you.

**Comment by GoogleFrog** [comment]
I don't think the constructor thing is going to be reproduced in closed testing.

**Comment by marcushutchings** [comment]
Fixed the constructor stopping issue https://github.com/beyond-all-reason/spring/commit/959721160af12301ed79ab078d6df1726f714657

**Comment by sprunk** [comment]
Seems like everything actionable got handled.
