### ISSUE TITLE
Feature: Allow overriding color on building grid during structure placement game-side

### ISSUE THREAD

**Issue by thehobojoe** [beyond-all-reason/spring#1177]
There are times where a game wants to disallow the placement of a building, for reasons other than terrain or surface (water etc) or building clashing. For example, BAR disallows placement of mexes unless they're on a metal spot. By intercepting commands, the game can easily prevent building placement, but the build-preview provided by the engine shows it as a valid placement, even when it's not, via game-side restrictions.

![spring_XDHA8qT2Jo](https://github.com/beyond-all-reason/spring/assets/3493638/118ee58c-8e34-47c9-96ec-98660834f9b2)
![spring_VtdLdELeUF](https://github.com/beyond-all-reason/spring/assets/3493638/4e314c2d-7629-4bf5-b956-c79d4dce4b73)

I would like an API to change the color of the building grid, whether in whole or in part, to help indicate to players when something won't be valid (even when the engine thinks it is).

An example of what this should look like would be geothermals in BAR - when not placed on the appropriate feature, they show all-yellow, even when the terrain is valid

![image](https://github.com/beyond-all-reason/spring/assets/3493638/8a744478-c61e-4ab7-9930-1bce0cc1910c)

**Comment by lhog** [comment]
https://beyond-all-reason.github.io/spring/ldoc/modules/SyncedCtrl.html#Spring.SetSquareBuildingMask is the proper tool for disallowing (or allowing) placement of buildings in "special" places.
The implementation drawing these green/yellow/red rectangles respects these masks. No need to reinvent the wheel.
