### ISSUE TITLE
Investigate using SAIL instead of DevIL for image manipulation

### ISSUE THREAD

**Issue by lazau** [beyond-all-reason/spring#1182]
[DevIL](https://openil.sourceforge.net) is the image loading library used in Spring. Although quite [fast](https://github.com/HappySeaFox/sail#benchmarks), it has the following major disadvantages

- No multithreading support.
- No support for modern image formats.

Without multithreading support, all DevIL calls must be guarded by a [lock](https://github.com/beyond-all-reason/spring/blob/5615ab668460856fbf966d07242f8d8d9c1da3f1/rts/Rendering/Textures/Bitmap.cpp#L1209), which makes it impossible to parallelize loading bitmaps.

[SAIL](https://github.com/HappySeaFox/sail) offers all the features of DevIL that Spring uses, and supports multithreading as well as newer image formats. The major feature missing from SAIL is the ability to load textures directly into OpenGL ([ilutOglBindTexImage](https://openil.sourceforge.net/tuts/tut_10/index.htm) and  ilutGLBindTexImage calls) which Spring does not use.

Usage of DevIL is limited to `rts/Rendering/Textures/Bitmap.cpp` for loading, transforming, and saving images. There are also additional usages in the `tools/mapcompile` submodule, which is not as critical performance-wise.

**Comment by lhog** [comment]
Ok, I checked SAIL once again and it doesn't look like it has support for all image formats we potentially require:

- Not a single common HDR format is supported (.hdr, .exr)
- Only the most common formats can be saved (except surprising .bmp).

Overall looks like it's premature to switch to SAIL yet.
