### ISSUE TITLE
[FR] Separate Unit Limit for Mobile and Static

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#1196]
Unit Limit must be separate for **mobile** and **static** units (**structures**)
When you build up your base and economy, especially cheap one, you must not be weighed down by the fact that your army capacity will be reduced because of the total unit count consumed by your structures
When you build your army, especially cheap one, you must not be weighed down by the fact that your base will not be able to expand with cheap structures because of that

Goal is to get sane restriction with reasonable distribution between mobile and static into the late game

**Comment by lhog** [comment]
What exactly do you mean when you mention "unit limit", there are at least a few, and I'm not entirely sure what we're talking about.

Also be aware of https://github.com/beyond-all-reason/spring/issues/1073

**Comment by sprunk** [comment]
I think this is essentially a request for supply cap, with buildings taking up 1 building!supply and 0 mobile!supply, and mobiles taking 1 mobile!supply and 0 building!supply

**Comment by Krogoth100** [comment]
What **sprunk** has said!
This is orthogonal to per-team limit and such.

**Comment by Krogoth100** [comment]
About implementation, maybe it should go like this.
In addition to MaxUnits setting:
+**MaxMobileUnits**
+**MaxStaticUnits**
Whenever MaxMobileUnits or MaxStaticUnits is set, apply this unit limit mode.
If only 1 is specified, deduce another by MaxUnits; or MaxUnits by others, any combination of 3.
Compatible with what we have.

**Comment by lhog** [comment]
Any reasons why you can't implement that with Lua and need the dedicated engine support?

**Comment by Beherith** [comment]
Yeah, this should totes be doable Lua side.

**Comment by lhog** [comment]
For the future reference I'm very much against duplicating any functionality available through Lua API already (unless it's justified by performance reasons or what not).

**Comment by Krogoth100** [comment]
Right, easily doable in Lua
However, I thought it simply makes sense to have it as a core feature
Now that I think of it, it probably doesn't
Closing
