### ISSUE TITLE
Incorrect documentation for cmdOptions

### ISSUE THREAD

**Issue by Arch-Shaman** [beyond-all-reason/spring#1211]
Found here: https://beyond-all-reason.github.io/spring/ldoc/modules/SyncedRead.html#cmd
issue: _cmdOpts_ does not exist, it is _options_.

for k, v in pairs(cmd) do Spring.Echo(k) end output:
![image](https://github.com/beyond-all-reason/spring/assets/48730089/63f7f6c3-6273-495c-ab0e-50d3c2c1686e)

**Comment by lhog** [comment]
Yes, here and in a few other places it's stated incorrectly.
I'm working on another issue, will fix later.
