### ISSUE TITLE
Use LuaJit instead of basic LUA

### ISSUE THREAD

**Issue by alexpyattaev** [beyond-all-reason/spring#1213]
It would seem that spring engine is using vanilla interpreted LUA for its scripting, which means it is missing out on a massive amount of free performance available with JIT compilation. Has anyone considered trying to drop https://luajit.org/install.html instead of basic LUA to see what happens? Or is there some blocker for that?

**Comment by 6AKU66** [comment]
There's a thread in discord:
https://discord.com/channels/549281623154229250/1147616557883727942/1147616560312234106
And there's this:
https://github.com/pts1667/spring-1

**Comment by alexpyattaev** [comment]
Wow I had no idea! If you need help testing let me know!

**Comment by lhog** [comment]
IIRC, we came to the conclusion that it'd be incredibly hard to make LuaJIT leverage streflop math for all floating point operations, and also many functions of Lua need to be reworked to be sync aware. For example https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Lua/LuaHandleSynced.h#L142-L146

**Comment by alexpyattaev** [comment]
Well lots of stuff that Lua does does not need to be streflop aware. plenty of stuff is related to UI and unit AI. That would benefit massively and does not need to run in synced code.

**Comment by lhog** [comment]
That said the Lua part of the engine doesn't really have its maintainer. So if you feel brave, you can have a look based on https://github.com/pts1667/spring-1 or your own effort.

**Comment by sprunk** [comment]
IIRC main blocker: https://luajit.org/faq.html ctrl+F "pairs"

**Comment by alexpyattaev** [comment]
As far as pairs() implementation goes, changing the underlying data structure to something with deterministic order is not a problem. Python has a relevant implementation, and it is even in C. I'll join the discord discussion.
