### ISSUE TITLE
Add `Spring.GetUnitHeadingInRadians`

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#1224]
The 0-65535 heading is a bad inhouse unit and many interfaces (like script `Turn`) expect radians anyway. In ZK codebase most uses of `Spring.GetUnitHeading` seem to immediately convert it to radians: https://github.com/search?q=repo%3AZeroK-RTS%2FZero-K%20getunitheading&type=code

Add something that returns heading in radians (hopefully with a better name than literally "heading in radians").

**Comment by Beherith** [comment]
Drop the 'in' :p

**Comment by sprunk** [comment]
HeadingRadians is still a fairly crappy name. Ideally just "GetUnitHeading" would return radians and there would be "GetUnitHeadingInAnnoyingLegacy16BitUnit" with the current behaviour but that ship has sailed.

**Comment by lhog** [comment]
Just extend `GetUnitHeading` with the second returnable

**Comment by sprunk** [comment]
Will I have to do `local _, heading =` every time to get the non-annoying unit? What if I want to do `GetUnitHeading() + math.pi` since that uses the first value? Generally I'd like the interface to be convenient without the legacy getting in the way.

**Comment by Beherith** [comment]
Give it a bool arg for inradians?
