### ISSUE TITLE
2141 Terrain texture does not return on luarules reload

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#1231]
![image](https://github.com/beyond-all-reason/spring/assets/1318249/e0b28862-391f-4653-a471-e0aa7c249b91)

Usually luarules reload turns any map squares that had terraform on them black, but the blackness can be removed by zooming the camera in and out a bit. With 2141 this no longer works.

**Comment by lhog** [comment]
Terrain diffuse texture streaming is turned off by default now: what made sense in 2006, doesn't make sense anymore.
You can still turn it on by setting `SMFTextureStreaming = 1` in ss.cfg, but note that you rely on an occasional behavior.
The clean way and the way it should be handled, you should fix your gadget to switch back the engine diffuse textures upon the gadget shutdown.

**Comment by GoogleFrog** [comment]
> The clean way and the way it should be handled, you should fix your gadget to switch back the engine diffuse textures upon the gadget shutdown.

How do you do that? As far as I know there is no way. Spring.GetMapSquareTexture copies the map texture into a "lua texture". I can set the map square texture to the original "lua texture", but the map still goes black. I don't try to make the map black, it just ends up that way. I assume that the "lua textures" "die" on luarules reload or something.

Perhaps there is a magic string to send Spring.SetMapSquareTexture that will set it back to the right "engine texture". I don't know what that would be though or where the magic strings are stored.

**Comment by lhog** [comment]
`Spring.SetMapSquareTexture(x, y, "")` should do the trick.

**Comment by GoogleFrog** [comment]
```
local function Shutdown()
	-- Iterating over a map here but it's so rare that I don't care!
	for x = 0, SQUARES_X-1 do
		if mapTex[x] then
			for z = 0, SQUARES_Z-1 do
				if mapTex[x][z] then
					spSetMapSquareTexture(x,z, "")
					gl.DeleteTextureFBO(mapTex[x][z].cur)
					gl.DeleteTextureFBO(mapTex[x][z].orig)
				end
			end
		end
	end
	
	gadgetHandler.RemoveSyncAction("changeBlockList")
	gadgetHandler.RemoveSyncAction("UpdateAll")
	gadgetHandler.RemoveSyncAction("Shutdown")
end
```

This has been run on shutdown forever. I tried the simple version which just loops over and resets the whole map in gadget:Shutdown, and there was no effect.

**Comment by lhog** [comment]
Ok, let me see where it fails

**Comment by lhog** [comment]
Fixed for both texture streaming and persistent cases.
