### ISSUE TITLE
LuaVAO and LuaVBO call failures only print the first entry in the stack

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#125]
Which makes telling exactly what stack called the the api incorrectly. This will become more important as more features use GL4.

Error in UnitCreated(): [LuaUtils::InstanceDataFromGetData] Non-existing UnitID (13435) is supplied
Removed widget: Ground AO Plates GL4 

Ivand, could you see if you can print the entire lua stack when a call failure like this occurs? Because I cant debug the above error without knowing where the InstanceDataFromGetData was called from.

**Comment by lhog** [comment]
Still wanted or do you have it game-side?

**Comment by Beherith** [comment]
Fixed via TraceFullEcho
