### ISSUE TITLE
Engine version 2291 crashes, supreme isthmus with some AI's

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#1256]
https://github.com/beyond-all-reason/spring/blame/ffa4baa5023130b867991d87d752d642f7c02793/rts/Sim/MoveTypes/MoveDefHandler.cpp#L450

<html><body>
Pastebin url: <a href="https://imolarpg.dyndns.org/bar/stacktrace_translator/frontend/index.php" target="_blank"></a>
	<h1>translated with links to github source ('Spring 105.1.1-2291-gffa4baa BAR105 ' detected)</h1>

module | address | file
-- | -- | --
a4baa bar\spring.exe | 0x1409dcf84 | rts/Sim/MoveTypes/MoveDefHandler.cpp :450 (https://github.com/beyond-all-reason/spring/blob/ffa4baa/rts/Sim/MoveTypes/MoveDefHandler.cpp#L450)
a4baa bar\spring.exe | 0x1409c8a58 | rts/Sim/MoveTypes/GroundMoveType.cpp :3233 (https://github.com/beyond-all-reason/spring/blob/ffa4baa/rts/Sim/MoveTypes/GroundMoveType.cpp#L3233)
a4baa bar\spring.exe | 0x1409d7763 | rts/Sim/MoveTypes/GroundMoveType.cpp :3304 (https://github.com/beyond-all-reason/spring/blob/ffa4baa/rts/Sim/MoveTypes/GroundMoveType.cpp#L3304)
a4baa bar\spring.exe | 0x1409d7e28 | rts/System/float3.h :342 (https://github.com/beyond-all-reason/spring/blob/ffa4baa/rts/System/float3.h#L342)
a4baa bar\spring.exe | 0x1409f148d | /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/13.2.0/include/c++/bits/atomic_base.h :426
a4baa bar\spring.exe | 0x140691e42 | rts/System/Threading/ThreadPool.h :139 (https://github.com/beyond-all-reason/spring/blob/ffa4baa/rts/System/Threading/ThreadPool.h#L139)
a4baa bar\spring.exe | 0x140e9a25f | rwlock.c :1 (https://github.com/beyond-all-reason/spring/blob/ffa4baa/rwlock.c#L1)
a4baa bar\spring.exe | 0x140b9290b | /mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-13.2.0.build_/mingw-w64-v11.0.0/mingw-w64-libraries/winpthreads/src/thread.c :1527
\System32\msvcrt.dll | 0x000000000003af5a | ?? :0

</body>
</html>

**Comment by Beherith** [comment]
No replay was produced from this game :( Both participants crashed out.
[20240128173747_infolog.txt](https://github.com/beyond-all-reason/spring/files/14077053/20240128173747_infolog.txt)

**Comment by 6AKU66** [comment]
[2024-01-28_17-26-03-119_Supreme_Isthmus_v1.6_105.1.1-2291-gffa4baa_BAR105.zip](https://github.com/beyond-all-reason/spring/files/14077083/2024-01-28_17-26-03-119_Supreme_Isthmus_v1.6_105.1.1-2291-gffa4baa_BAR105.zip)
DP have it. Reproducible in replay.

**Comment by Beherith** [comment]
[2024-01-28_17-06-10-072_Supreme Isthmus v1.6_105.1.1-2291-gffa4baa BAR105.sdfz.zip](https://github.com/beyond-all-reason/spring/files/14077315/2024-01-28_17-06-10-072_Supreme.Isthmus.v1.6_105.1.1-2291-gffa4baa.BAR105.sdfz.zip)
Replay from server attached too.

**Comment by lhog** [comment]
Additional concern. At the frame:
`gs->frameNum == 7687`

Hitting this assert in the debug mode:
https://github.com/beyond-all-reason/spring/blob/spring_bar_%7BBAR105%7D105.1.1-2291-gffa4baa/rts/Sim/Path/QTPFS/PathSearch.cpp#L943

**Comment by marcushutchings** [comment]
Assert fixed by: https://github.com/beyond-all-reason/spring/commit/1dde17bfc090eff9d3bd691087a137ee0d64f41a

**Comment by marcushutchings** [comment]
Crash fixed by: https://github.com/beyond-all-reason/spring/commit/52a39f3dec5ad5021ce2e164f15f897cc7ce91ee
