### ISSUE TITLE
'Phantom Target' bug

### ISSUE THREAD

**Issue by TheSilverHornet** [beyond-all-reason/spring#1269]
There is an erratic issue without known trigger, that is most likely to manifest on sweepfire weapons but -can- occur on others, Demon for example, wherein a phantom target is 'seen' by the unit and it goes full ham on said figment. Usually this target is about 90 to 120 degrees behind it, for some reason.

A notable example video can be found on discord here:
https://discord.com/channels/549281623154229250/724924957074915358/1181723963018182797

The replay of that game is here: https://www.beyondallreason.info/replays?gameId=998e6a657fd743555e1ed61343a30e59

**Comment by lhog** [comment]
> [2023-12-16_08-22-28-468_Quicksilver Remake 1_105.1.1-2152-gb91f41c BAR105.sdfz.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/13691855/2023-12-16_08-22-28-468_Quicksilver.Remake.1_105.1.1-2152-gb91f41c.BAR105.sdfz.zip)
> 
> this is a static tower doing the same thing, and it behaves itself the moment the emit-sfx line is commented
> 
> ![image](https://private-user-images.githubusercontent.com/37483246/290981548-d5f92c8e-5478-412e-bc75-11c03cced6b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NDg1NDIsIm5iZiI6MTcwNjg0ODI0MiwicGF0aCI6Ii8zNzQ4MzI0Ni8yOTA5ODE1NDgtZDVmOTJjOGUtNTQ3OC00MTJlLWJjNzUtMTFjMDNjY2VkNmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA0MzA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViODEwZWYzM2EwZDk2YzRkNjgxOTNjM2IxN2IxZmE2OWM5NDEwZWMwNDFiMGQ0NmRhZDljMGFjMDRmNjM4YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4vlAo_9aJalgEnBG-etLkGBBNs3GRr5mmnUhgXWQkTk)

I don't think there is any issue or erratic behavior in that replay

> [2023-12-05_23-01-44-837_All That Glitters v2_105.1.1-2142-g35a026a BAR105.sdfz.zip](https://github.com/beyond-all-reason/Beyond-All-Reason/files/13573843/2023-12-05_23-01-44-837_All.That.Glitters.v2_105.1.1-2142-g35a026a.BAR105.sdfz.zip) ![image](https://private-user-images.githubusercontent.com/37483246/288230945-79195905-ac71-4539-96f0-3ff073c52e76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NDg1NDIsIm5iZiI6MTcwNjg0ODI0MiwicGF0aCI6Ii8zNzQ4MzI0Ni8yODgyMzA5NDUtNzkxOTU5MDUtYWM3MS00NTM5LTk2ZjAtM2ZmMDczYzUyZTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA0MzA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMTg2Yjk5NTE5ZGIxNDUwNjdiZWNhZjFhNzhkNmJmMzM0YzgxZjA5ZmRiOGUwYmFmOGEzODgxY2MxNTY3ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c5uK2bVsN97nLvqEKQONlnStQoM5U9TGIikIOGrJHns)
> 
> hopefully enough data here to wrangle something useful from?

I totally don't see units you have on your screenshot in this demo. Did you modify some files in the game locally?

**Comment by TheSilverHornet** [comment]
> I don't think there is any issue or erratic behavior in that replay

The bastion has been edited since then, specifically to avoid this bug, so at this point it may not reflect what actually happened.  I'll clear my replays folder out and check.

> I totally don't see units you have on your screenshot in this demo. Did you modify some files in the game locally?

No more than a normal dev build, I don't believe I'd changed anything about the units in question, and relatively sure others haven't altered those since either. Again will check replay for sanity's sake and get back to you.

I can (re)make a version of a Bastion that does the same on current engine, but the replay I sent on discord on the engine version you provided might be best for debugging, if that contains related code that's pending merge?  That only contains Incinerators but they manifest the same bug still, eg shooting imaginary targets somewhere behind them.

**Comment by lhog** [comment]
[erraticfire_2024-02-05_05-09-08-271_All_That_Glitters_v2_105.1.1-2300-g43959c9_BAR105.sdfz.zip](https://github.com/beyond-all-reason/spring/files/14177925/erraticfire_2024-02-05_05-09-08-271_All_That_Glitters_v2_105.1.1-2300-g43959c9_BAR105.sdfz.zip)
Updated replay

**Comment by sprunk** [comment]
#1279 merged, can be closed?

**Comment by lhog** [comment]
Reopen or better create a new one, if it still occurs
