### ISSUE TITLE
EngineCrash [2300] at [rts/Game/PreGame.cpp :601]

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#1272]
**URL of infolog.txt**

https://server4.beyondallreason.info/telemetry/infolog/203804
https://server4.beyondallreason.info/telemetry/infolog/203785
https://server4.beyondallreason.info/telemetry/infolog/203767
https://server4.beyondallreason.info/telemetry/infolog/203725
https://server4.beyondallreason.info/telemetry/infolog/203719
https://server4.beyondallreason.info/telemetry/infolog/203718
https://server4.beyondallreason.info/telemetry/infolog/203701
https://server4.beyondallreason.info/telemetry/infolog/203699
https://server4.beyondallreason.info/telemetry/infolog/203652
https://server4.beyondallreason.info/telemetry/infolog/203639
https://server4.beyondallreason.info/telemetry/infolog/203625

**Engine Version**
105.1.1-2300 bar

**Translated Stack Trace with links**
```
module | address | file
-- | -- | --
959c9 bar\spring.exe | 0x14007fad7 | rts/Game/PreGame.cpp :601 (https://github.com/beyond-all-reason/spring/blob/43959c9/rts/Game/PreGame.cpp#L601)
959c9 bar\spring.exe | 0x140080639 | /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/13.2.0/include/c++/bits/shared_ptr_base.h :1070
959c9 bar\spring.exe | 0x140080c72 | rts/Game/PreGame.cpp :205 (https://github.com/beyond-all-reason/spring/blob/43959c9/rts/Game/PreGame.cpp#L205)
959c9 bar\spring.exe | 0x14066bd4c | rts/System/Threading/WrappedSync.h :25 (https://github.com/beyond-all-reason/spring/blob/43959c9/rts/System/Threading/WrappedSync.h#L25)
959c9 bar\spring.exe | 0x1406711b4 | rts/System/SpringApp.cpp :890 (https://github.com/beyond-all-reason/spring/blob/43959c9/rts/System/SpringApp.cpp#L890)
959c9 bar\spring.exe | 0x140650f3d | rts/System/Main.cpp :48 (https://github.com/beyond-all-reason/spring/blob/43959c9/rts/System/Main.cpp#L48)
959c9 bar\spring.exe | 0x1400012ee | /mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-13.2.0.build_/mingw-w64-v11.0.0/mingw-w64-crt/crt/crtexe.c :273
959c9 bar\spring.exe | 0x1400013e6 | /mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-13.2.0.build_/mingw-w64-v11.0.0/mingw-w64-crt/crt/crtexe.c :164
```

**Additional context**
# VERY IMPORTANT ALL OF THESE CRASHES HAPPEN RIGHT AFTER LOADING BITMAPS.SDZ:

```
[t=00:08:23.100357][f=-000001] [CAS::GASCB] Archive file="bitmaps.sdz" cs="ed5fc4f7d9e73b042c36ab1bbab84c1699bc25f327ea61bac92e86d89ffb780b8bfaa27e254ca7975ab27990723bcf2ad65db2650689e93c90aeded31f975de5"
[t=00:08:23.107257][f=-000001] Error: Spring 105.1.1-2300-g43959c9 BAR105 has crashed.
[t=00:08:23.216211][f=-000001] Error: DLL information:
[t=00:08:23.216469][f=-000001] Error: 0x00007ff637de0000	spring
```
This could be a result of long load times previously, such as:
`[t=00:08:22.982380][f=-000001] [~CPoolArchive] archiveFile="C:\Users\huese\AppData\Local\Programs\Beyond-All-Reason\data\packages\9bd383577927dc7895433e6c79886d53.sdp" numZipFiles=15722 sumInflSize=2039386kb sumReadTime=392269ms`

`[t=00:01:01.798268][f=-000001] [~CPoolArchive] archiveFile="C:\Users\accou\AppData\Local\Programs\Beyond-All-Reason\data\packages\9bd383577927dc7895433e6c79886d53.sdp" numZipFiles=15722 sumInflSize=2039386kb sumReadTime=22635ms`

`[t=00:08:09.545937][f=-000001] [~CPoolArchive] archiveFile="C:\Users\AzraE\AppData\Local\Programs\Beyond-All-Reason\data\packages\9bd383577927dc7895433e6c79886d53.sdp" numZipFiles=15722 sumInflSize=2039386kb sumReadTime=429000ms`

`[t=00:06:21.914230][f=-000001] [~CPoolArchive] archiveFile="C:\Users\guz00\AppData\Local\Programs\Beyond-All-Reason\data\packages\e6c6903a7b60802d3c18115feebf5dd9.sdp" numZipFiles=15722 sumInflSize=2039386kb sumReadTime=36156ms`

So these could be from the player exiting during load, and this point being hit is just because this is the first time we return from loading archives?

**Comment by 6AKU66** [comment]
I actually asked a player with msvcrt.dll crash once and he said "maybe i caused this by pressing esc?"

**Comment by lhog** [comment]
I believe https://github.com/beyond-all-reason/spring/commit/34ffb96d0593671a2004d4d987e56ae1a3328878 should improve user experience while waiting for check-summing to complete.
