### ISSUE TITLE
Fix shameful decals close-up view

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#13]

**Comment by Beherith** [comment]
Didnt kloot (or jK) fix this when they ported the (horrid) decaldrawer to GL4 in develop? Also, do you mind me commenting on your issues here? Even a blind chicken may find a kernel.

**Comment by lhog** [comment]
All your comments are golden.
GL4 decals are ported, yet on close up things tend to break up. I checked and it's not a matrix issue. So probably something is wrong in the shader.
