### ISSUE TITLE
Engine always crashes when air transport unloads unit for a specific user

### ISSUE THREAD

**Issue by springraaar** [beyond-all-reason/spring#1319]
Metal factions v2.36
Map Ravaged_Lava_v2

If a player loads a unit on an air transport, then unloads it without using area unload, the game crashes for a specific user (old laptop with linux and 8gb ram and locally built engine). It always crashes for him even if he rejoins or is watching the replay.

**URL of infolog.txt**
[infolog_2303_airtrans_unload_crash.txt](https://github.com/beyond-all-reason/spring/files/14391549/infolog_2303_airtrans_unload_crash.txt)

for that log the user said this

> [04:56:33] ximes: this is 2.36 with 2303, hangs with that process addr2line running at 100%cpu and ram usage increasing. Sent a SIGTERM to addr2line.

**Engine Version**
BAR105-105.1.1-2303-g5f26a29

**Additional context**
- it crashes on engine 2303 and 2378, but not on engine 1774
- none of the other players is able to reproduce the crash
- he tried updating binutils to version 2.42 and it didn't fix the issue
- it doesn't crash if the unit is unloaded with area-unload, even if the circle spans the entire map!
- disabling luarules to bypass https://github.com/springraaar/metal_factions/blob/master/luarules/gadgets/air_transports.lua does not fix the issue
- despite always crashing on this specific situation, the player is normally able to play battles even late game with hundreds of units in play

Since it may be hard to reproduce, we could arrange a situation where the engine developers would suggest tentative changes to specific files, then ximes would try to build locally and do the test.

**Comment by lhog** [comment]
Attach the crashing replay please.

**Comment by lhog** [comment]
@springraaar confirmed it was fixed. The user was running the debug build or had asserts enabled.
