### ISSUE TITLE
Investigate water 0 looking like if it was opaque

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#1323]
![image](https://github.com/beyond-all-reason/spring/assets/1476261/220ea526-bc37-4c9f-814b-ebce997f6dff)

**Comment by springraaar** [comment]
i get than on engine 2392, but not 2314. 2314 and earlier seem visually identical to earlier ones.

**Comment by springraaar** [comment]
notes:
- water 2 also seems broken : it shows as dark and opaque layer
- water 1 and 3 seem unchanged
- water 2 is noticeably heavier in terms of fps drop compared to all other modes
- if water 2 is to be discontinued, maybe the engine should override it with a supported mode
