### ISSUE TITLE
AI: Do not build in player bases

### ISSUE THREAD

**Issue by WatchTheFort** [beyond-all-reason/spring#1336]
See issue https://github.com/beyond-all-reason/Beyond-All-Reason/issues/2620

A point of frustration for players that has come up repeatedly is the AI building inside the players' bases. The player will have to destroy or reclaim the AI's structure, which the AI will frequently rebuild in the same place.

**Comment by sprunk** [comment]
Belongs to AI, not engine rlcevg/CircuitAI#132
