### ISSUE TITLE
Feature request: GetUnitInBuildStance(..)

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#134]
Add GetUnitInBuildStance(unit) call returning unit's inBuildStance flag.
Function should work similarly to GetUnitArmored(..) and GetUnitIsActive(..) with inLos visibility for unsynced.

It may have several uses.
One particular would be
```
<on AllowUnitBuildStep(builder):>
    return GetUnitInBuildStance(builder)
```
which is one way to solve the issue with inBuildStance flag not being respected by repair command (a common situation when builders start repairing before their nano turrets are facing the target)

**Comment by lhog** [comment]
Done (blindly) in https://github.com/beyond-all-reason/spring/commit/f6c1a753ef6df4e842eac9cad21f27114d00ce29
