### ISSUE TITLE
[Website] Internal names are not listed in weapon defs guide

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/spring#1377]
Some weaponDefs might have a property called internalName, see:

```
    "tolerance": {
      "internalName": "maxAngle",
      "defaultValue": 3000,
      "scaleValue": 9.58738e-05,
      "scaleValueString": "TAANG2RAD",
      "type": "float"
    },
    "firetolerance": {
      "internalName": "maxFireAngle",
      "defaultValue": 3640,
      "scaleValue": 9.58738e-05,
      "scaleValueString": "TAANG2RAD",
      "type": "float"
    },
```

Make `internalName` visible in the table [here](https://beyond-all-reason.github.io/spring/guides/weapon-defs/#tolerance):

![2024-03-19T07:47:38,347297612-03:00](https://github.com/beyond-all-reason/spring/assets/347552/3689882e-8669-4db0-bf73-fdedcfe2d3af)

The page to change is: https://github.com/beyond-all-reason/spring/blob/BAR105/doc/site/guides/weapondefs.markdown#L18-L39

**Comment by sprunk** [comment]
The internal name is useless though, it's just the name of the variable inside the engine's implementation and game devs never have to deal with it. Perhaps just rename the vars to their external name.

**Comment by badosu** [comment]
It seems internal names are exposed by lua so gamedevs/modders can see them and get confused, a case in particular is one of a modder mapping out bars unitdefs (using [this](https://discord.com/channels/549281623154229250/858397131148623892/1219650435011448883)) and stumbling into them

**Comment by lhog** [comment]
IMO you have it already the way it should be, i.e. you display the external name aka Lua name. This is all gamedevs should care about.

**Comment by sprunk** [comment]
There's two Lua names though, but it would be ideal if there was only one. See #801

**Comment by badosu** [comment]
From sprunk:

description of how things currently work
there are three names each trait has.

    internal, aka the name of the var in C++
    external, aka the name expected of thing.lua def files
    the name under which it is exposed to its respective FooDefs table in wupgets


weapons (and only weapons; not units nor features) make a fancy attempt at systematizing the above via a bunch of macros. in this system:

    the external key is set up to be automatically read from thing.lua files. in rare cases (usually marked as dummy) it is handled manually
    the internal key is not wired up to anything. this is why i earlier said the internal name is never exposed
    the FooDefs name is not part of this system, but for weapons it happens to usually match the internal key. as you've noticed with groundslip sometimes it's a completely unrelated name to either of the two though


so? bug? intended?
the fact that the FooDefs name is not wired, and each entry is an explicit line of code, means that there is technically no bug here - somebody explicitly made it so. but of course this design is pretty crap

on top of this, each of those 3 facets of a trait has its own unit of measurement. usually they match, but don't have to (regardless of name - even if all 3 names match the units may not). e.g. speed external key (thing.lua def file input) is sometimes specified in elmo/s while external is in elmo/frame, or other such nonsense. this is also pretty explicitly specified in the code so technically no bug, but also obviously crap so i wouldn't say "intended"

how things imo should work

    the FooDefs name and the external (thing.lua def file) name should be made to match, and so should their units
    i am not specifying which side should change its name. it may be both
    the internal name should probably match the two above, but since it isn't exposed its for C++ dev convenience only
    if there is a unit mismatch there is usually an obviously superior unit to pick
    this is #801
