### ISSUE TITLE
Add missing weapondef descriptions

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/spring#1379]
Generated all missing descriptions with `/spring --list-def-tags | grep -v "^\[t="  | jq '.["WeaponDefs"] | to_entries[] | select(.value | has("description"
) | not) | [.key, .value]'`

See [here](https://gist.github.com/badosu/584669cfbdd0da0c49a279aabf078bed) for more detailed data

### Not done
- [x] scarGlowColorMap: 
- [x] scarDotElimination: 
- [x] scarProjVector: 

Note to self (stole up to texture1 here https://springrts.com/wiki/Gamedev:WeaponDefs until now)

### Done

- [x] weaponType: 
- [x] id: (was fbiId, removed)
- [x] size: 
- [x] largeBeamLaser: 
- [x] textures.1: 
- [x] textures.2: 
- [x] textures.3: 
- [x] textures.4: 
- [x] impulseFactor: A multiplier to the impulse given to units within the explosion areaOfEffect, which is otherwise equal to the damage dealt after edgeEffectiveness is taken into account. For #Melee weapons this is instead multiplied by the owning unit's mass.
- [x] impulseBoost: A constant amount added to the weapon's impulse, regardless of distance from the epicentre or the damage potential of the explosion, prior to the application of impulseFactor
- [x] craterMult: A multiplier to depth of terrain crater the weapon's explosion will create, which is otherwise based on the damage potential.
- [x] craterBoost:     A constant amount, added to the weapon's cratering depth before the application of craterMult.
- [x] heightmod: Changes the spherical weapon range into an ellipsoid. Values above 1.0 mean the weapon cannot target as high as it can far, values below 1.0 mean it can target higher than it can far. For example 0.5 would allow the weapon to target twice as high as far.
- [x] cylinderTargeting: Controls whether the weapon range is calculated in a sphere or a cylinder. The height of the cylinder is determined by the value of this tag multiplied by the range. Clamped between 0.0 and 128.0.
- [x] tolerance: The amount (in cau) to which the weapon's "real" aim can be off while the weapon will still be able to fire accurately at the target. For turret = false or fixedLauncher = true weapons this determines in what arc the unit will fire.
- [x] firetolerance: Final check to prevent weapons from shooting sideways. If a weapon is about to fire but the difference between its old aim and requested aim is greater than this angle (in cau) then it will not fire.
- [x] trajectoryHeight: 
- [x] wobble: 
- [x] gravityAffected: 
- [x] myGravity:     Overrides the map gravity for ballistic weapons. The default of 0.0 disables the tag in favour of map gravity.
- [x] canAttackGround:     Determines if the weapon can be force-fired on ground positions or only fire on targeted units.
- [x] heightBoostFactor: 
- [x] proximityPriority:     Acts as a multiplier for the distance to the target in the priority calculation. Note that negative values make weapons prefer distant targets.
- [x] targetMoveError: The degree to which a weapon's aiming will fail to keep up with its target's movement. It adds a fraction of the target's speed (per second) as a random error to the targetting. So if the target moves 50 units per second and the targetmoveerror is 0.5 a random error of 25 will be added to the target position. If set very low or not set at all, a weapon will lead its target and almost always hit.
- [x] leadLimit:     Limits the maximum distance a unit will lead a target. The default of -1 allows an infinite distance.
- [x] leadBonus: Controls how experience boosts the weapon's target leading. Is multiplied with the unit's experience and added to the leadLimit.
- [x] predictBoost: Controls how well the weapon predicts unit speeds. Works in a similar way to targetMoveError except that it is 1-dimensional. This tag spreads the shots in a line based on the direction of the target whereas targetMoveError spreads the shots all around based on the movement.
- [x] duration: 
- [x] beamtime: 
- [x] beamburst: 
- [x] sizeGrowth: 
- [x] flameGfxTime: 
- [x] metalPerShot: Metal used per shot. If the specified amount is not available, the weapon cannot be fired. Can also be used to specify how much a stockpile weapon will cost to build.
- [x] energyPerShot: Energy used per shot. If the specified amount is not available, the weapon cannot be fired. Can also be used to specify how much a stockpile weapon will cost to build.
- [x] scarColorTint: 
- [x] sizeDecay: 
- [x] alphaDecay: 
- [x] separation: 
- [x] noGap: 
- [x] stages: 
- [x] laserFlareSize: 
- [x] tileLength: 
- [x] scrollSpeed: 
- [x] pulseSpeed: 
- [x] beamDecay: 
- [x] colormap: 
- [x] soundHitWetVolume: 
- [x] bounceExplosionGenerator: For weapons which can use groundBounce = true, the name of a CEG, with custom: prefix, to spawn when weapon the bounces.
- [x] explosionGenerator: The name of a CEG, with custom: prefix, to spawn as the weapon's explosion. Does not currently work for #Melee and #Rifle.
- [x] soundTrigger:     Does the weapon play soundStart only once for each salvo (true) or for every round in a burst (false)?
- [x] soundStart:     The name of a SoundItem or filename of a sound to play when the weapon fires.
- [x] soundHitDry: The name of a SoundItem  or filename of a sound to play when the weapon collides with solid ground. Note that a BeamLaser will play this sound every frame of its lifetime.
- [x] soundHitWet:     The name of a SoundItem (See Sounds.lua) or filename of a sound to play when the weapon collides with water. Note that a #BeamLaser will play this sound every frame of its lifetime.
- [x] soundStartVolume: 
- [x] soundHitDryVolume: 
- [x] customParams: 
- [x] avoidFriendly:     Should the weapon avoid firing if a friendly unit is in the line of fire?
- [x] avoidFeature:     Should the weapon avoid firing if a static map feature is in the line of fire?
- [x] avoidNeutral:     Should the weapon avoid firing if a neutral unit is in the line of fire?
- [x] avoidGround:     Should the weapon avoid firing if terrain blocks the line of fire?
- [x] avoidCloaked: 
- [x] collideEnemy: Does the weapon projectile collide with enemy units or pass through?
- [x] collideFriendly:     Does the weapon projectile collide with friendly units or pass through?
- [x] collideFeature:     Does the weapon projectile collide with static map features or pass through?
- [x] collideNeutral: Does the weapon projectile collide with neutral units or pass through?
- [x] collideFireBase:     Does the weapon projectile collide with friendly firebase units the owner is loaded onto, or pass through?
- [x] collideNonTarget: 
- [x] collideGround: 
- [x] collideCloaked: 
- [x] damage: 
- [x] damage.default: 
- [x] explosionSpeed: The speed at which the weapon's explosion propagates from the epicentre. The default is calculated by this complex formula: defExpSpeed = {8.0 + [max(30.0, default_damage / 20.0) * 2.5]} / {9.0f + [sqrt(max(30.0, default_damage / 20.0f)) * 0.7]} * 0.5.
- [x] impactOnly: Does the weapon only deal damage through direct hits and not 'splash' damage through areaOfEffect
- [x] noSelfDamage: Can the weapon's explosion damage the unit which fires it? Useful for preventing bombers with high-yield weapons destroying themselves.
- [x] noExplode: Does the weapon explode on impact with a target or continue through? Note that these weapons will do damage every single frame they are inside the collision volume of an object, underground or under water, massively multiplying their damage.
- [x] burnblow: Does the weapon explode when it reaches its maximum range or continue on its path? The name is an OTAism.
- [x] damageAreaOfEffect: 
- [x] edgeEffectiveness: Determines what percent of a weapon's maximum damage value will be applied to units within the weapon's areaOfEffect. Falls off from the epicentre according to the formula damageApplied = damage * [(areaOfEffect - distToUnit) / (areaOfEffect - (distToUnit * edgeEffectiveness))], a graph of the function for various values is available here.
- [x] collisionSize: Modifies visual size of EMG and Flame projectiles, and physical size only for hitscan interceptor weapons (e.g. antinuke lasers).

- [x] weaponVelocity: The velocity in elmos per second of the weapon projectile.
- [x] startvelocity: 
- [x] weaponacceleration: 
- [x] reloadTime: The time in seconds between shots fired.
- [x] burstRate:     The time in seconds between shots in a burst. Note that reloadTime starts to count down from the first round fired, not the last so if reloadTime < burst * burstRate the weapon will fire continuously.
- [x] burst:     How many shots to fire per burst.
- [x] projectiles: How many projectiles released per shot (shotgun style). e.g. a weapon with burst = 5, burstRate = 0.5 and projectiles = 2 will shoot 5 lots of 2 for 10 projectiles total, with gaps of 0.5 seconds, before waiting for reloadTime. Best used in conjunction with sprayAngle or changing the firing piece using ShotX as otherwise they'll all be clumped in one shot.
- [x] waterBounce:     Does the weapon bounce on water impacts?
- [x] groundBounce:     Does the weapon bounce on ground impacts?
- [x] bounceSlip:     The decimal-percentage amount of horizontal velocity a projectile keeps when it bounces.
- [x] bounceRebound:     The decimal-percentage amount of vertical velocity a projectile keeps when it bounces.
- [x] numBounce: The number of times the weapon will bounce on impact before exploding. The default value of -1 allows infinite bounces (at least until velocity reaches 0).
- [x] craterAreaOfEffect:     The radius in elmos in which the weapons explosion will cause terrain cratering.
- [x] waterweapon:     Determines if the weapon can pass through water and target underwater units.
- [x] submissile: 
- [x] fireSubmersed:     Determines if the weapon can fire whilst underwater.
- [x] commandfire:     Determines if the weapon will automatically fire on enemy units in range or only when manually ordered to attack.
- [x] range: The maximum range in elmos that the weapon can fire at.
- [x] fixedLauncher: 
- [x] targetBorder: Controls whether the weapon aims for the centre or the edge of its target's collision volume. Clamped between -1.0 - target the far border, and 1.0 - target the near border.z
- [x] highTrajectory: 
- [x] tracks: 
- [x] dance: 
- [x] weaponTimer: 
- [x] accuracy:     How accurate the weapon is. Lower values are more accurate. Accuracy is relative to the distance to the target; for instance, if the target is very close, even a very high value will probably still hit. If a target is very far away, even a very low value will likely cause the weapon to miss.
- [x] sprayAngle: How wide the the angle of a burst from a burst weapon can be. Very similar to accuracy, except that this tag affects each projectile in a burst, whilst the former does not.
- [x] turnrate: 
- [x] model: The filename of a 3D model to use when rendering the projectile. Note that only the root piece of a projectile model is rendered. Currently only for #Cannon, #LaserCannon, #MissileLauncher, #StarburstLauncher and #TorpedoLauncher.
- [x] beamTTL: 
- [x] ownerExpAccWeight: A multiplier to accuracy and sprayAngle that reduces inaccuracy as a units experience increases.
- [x] movingAccuracy: A weapon's accuracy whilst the owning unit is moving.
- [x] scarIndices: 
- [x] explosionScar:     Does the weapon's explosion leave a scar decal on the ground? For all types except #Melee and #Rifle.
- [x] scarAlpha: 
- [x] scarGlow: 
- [x] scarTtl: 
- [x] scarGlowTtl: 
- [x] alwaysVisible:     If true the weapon is always rendered regardless of whether or not it is in LOS range of a player's units.
- [x] cameraShake: Passed to the ShockFront() callin as the first argument. Intended as a means to make the camera shake if in range of detonation.
- [x] smokeTrail: 
- [x] smokeTrailCastShadow: 
- [x] smokePeriod: 
- [x] smokeTime: 
- [x] smokeSize: 
- [x] smokeColor: 
- [x] castShadow: 
- [x] lodDistance: 
- [x] thickness: 
- [x] coreThickness: 
- [x] falloffRate: 
- [x] hardstop: 
- [x] rgbColor:     The primary colour for sprite rendering weapons. Additional defaults are as follows:    #Cannon - {1.0, 0.5, 0.0}    #EmgCannon - {0.9, 0.9, 0.2}
- [x] rgbColor2:

**Comment by lhog** [comment]
Unsure what is the action for this issue?

**Comment by sprunk** [comment]
Aww I saw that some entries in the OP are filled and some are empty, but I assumed the filled ones are just those that already have a description in the code so I ignored what they say when making the commit. Why not just put the ready ones in code directly (or via PR for review, if there are doubts) instead of putting them here first?

**Comment by badosu** [comment]
>  Why not just put the ready ones in code directly (or via PR for review, if there are doubts) instead of putting them here first?

These are all missing defs at time I started it, when you have one in the code, tick them (edit the PR description put an x between `[ ]`). When all are ticked, the issue is closed.
