### ISSUE TITLE
2314 - Underwater structure causing a hovercraft to become stuck

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#1386]
I had my units become stuck on an underwater structure quite frequently in this game: https://zero-k.info/Battles/Detail/1858841

Can be reproduced by placing an Energy Pylon here (normal placement, on the build grid):
![image](https://github.com/beyond-all-reason/spring/assets/1318249/e7db370a-aed4-47fa-b451-9b79f91e7f6a)

1821 works, and I have not had a problem like this for many years.

**Comment by marcushutchings** [comment]
I need more information in the reproduction steps: Which map, which hover unit, which underwater unit? How do I determine the exact coordinates in ZK?

**Comment by GoogleFrog** [comment]
![image](https://github.com/beyond-all-reason/spring/assets/1318249/f309eefc-2095-4699-be2a-46236d19ecfa)

![image](https://github.com/beyond-all-reason/spring/assets/1318249/a6c88c48-31f4-423d-bb3e-69bba5fd6882)

hovercon

hold space (or luaui disable and use the engine UI)

**Comment by marcushutchings** [comment]
Ah, HAPFS. Likely an issue with its own blend of raw move. I can sort that out.
