### ISSUE TITLE
2441 Spider pathfinding failure.

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#1398]
https://www.youtube.com/watch?v=U346Sks1GOg

![image](https://github.com/beyond-all-reason/spring/assets/1318249/0a9441df-fb2a-4172-ae94-16038eb391f1)

I saw this in the wild recently and it is quite easy to reproduce. The direct route is much faster and the detour is probably dangerous, and not what the player expects. I recall something about pathfinding no longer taking the direction of slopes into account a few years ago, so perhaps the unit is trying to avoid the cliffs.

[2024-03-31_08-11-55-753_Fields_Of_Isis_105.1.1-2441-gf9a23b0 BAR105.sdfz.txt](https://github.com/beyond-all-reason/spring/files/14814639/2024-03-31_08-11-55-753_Fields_Of_Isis_105.1.1-2441-gf9a23b0.BAR105.sdfz.txt)

ZK 1.12.1.2, spidercrabe.

**Comment by marcushutchings** [comment]
That's right. The pathing data doesn't have the concept of directionality. Those links between verticies are generated one-way for performance reasons. To generate them both ways would double the cost of updating the pathing map dynamically. If that's acceptable then I can modify to HAPFS support two way linking and add a modrule to toggle.

Alternately, we could mark certain MoveDefs as only use shortest-route and ignore speed data. That could be supported by both HAPFS and QTPFS.

**Comment by sprunk** [comment]
Isnt there already a modrule? `allowDirectionalPathing`

**Comment by marcushutchings** [comment]
Yes, good point. We can use that.

**Comment by GoogleFrog** [comment]
Could certain movedefs be given directional pathing? I'd enable it on the few that have this problem. I would also like to try pathing that ignores slope costs, but I suspect there would be bad cases with that too.

**Comment by marcushutchings** [comment]
Possibly, but I suspect that players will prefer the shortest path method. Spiders often completely ignore pathing cost (even across long distances) because of raw move. So if shortest path is used, they will most closely match player expectations - especailly as virtually every other RTS paths that way.

I'll have some changes up soon that will enable directionalPathing on a per-movedef basis if HAPFS is used. I'll also look to have shortest path as an option as well so that you can try it out and compare the results.

**Comment by marcushutchings** [comment]
I have a PR with the changes to allow you to experiment. So you can try directional pathing with HAPFS, and shortest route pathign with QTPFS. The PR is linked to this issue.

**Comment by GoogleFrog** [comment]
I can't run PRs.

**Comment by marcushutchings** [comment]
Are you able to access the artefacts on this page? https://github.com/beyond-all-reason/spring/actions/runs/8519311050

**Comment by GoogleFrog** [comment]
Yes, but it cannot be put in the ZK infrastructure. So I could only do a local test, and then in a bit of an ad hoc way.

**Comment by marcushutchings** [comment]
Here you go: https://github.com/beyond-all-reason/spring/releases/tag/spring_bar_%7BBAR105-allow

**Comment by GoogleFrog** [comment]
I am going to try to do an update on the weekend, a game and engine one at the same time since the decals need to update at the same time. So I will be focusing on that until then.
