### ISSUE TITLE
weapon defs: crater aoe is radius but damage aoe is diameter

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#1399]
Bad design. The big issue is of course that games exist and set both values already.

**Comment by WatchTheFort** [comment]
How many of the def parameters have this problem?

**Comment by sprunk** [comment]
Figuring that out is a good task for somebody.

**Comment by lhog** [comment]
TODO: harmonize parameter names to radius or diameter, leave the current ones as fallbacks.

**Comment by sprunk** [comment]
I checked the claim and actually both are diameter. It may look like crater radius is smaller but it's because only half of it is the hole and the other half is the raised rim.

**Comment by lhog** [comment]
Hmm, idk about that one.

`craterAreaOfEffect` weapontag has scaleValue(0.5f);
There's also
`const float craterRadius = craterAOE - altitude;`
which hints it's radius.

**Comment by sprunk** [comment]
> `craterAreaOfEffect` weapontag has `scaleValue(0.5f)`

Yes, but `damageAreaOfEffect` has that too. So they are both input as diameter, and then scaled by 0.5 to be stored as radius internally.

> There's also
`const float craterRadius = craterAOE - altitude;`
which hints it's radius.

Yes, it's radius in C++ code, but that's after the 0.5 scaling. It is input as diameter from Lua unit defs (which is what I care about because that's the interface for gamedevs).

**Comment by lhog** [comment]
Yeah, you're right, I got confused.
