### ISSUE TITLE
2449 Weird graphical glitch on screen

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#1405]
https://github.com/beyond-all-reason/spring/assets/1318249/c1bd7b37-894f-40fa-a22a-3d1efc1af3bc

Chungoose has this bug. I have yet to get an infolog, but apparently it reproduces in the replay. Apparently he will try /luaui disable when he next gets the chance.

**Comment by 6AKU66** [comment]
I had something similar and it's was only first launch bug with atlas as i remember? It's was long time ago...

**Comment by GoogleFrog** [comment]
Might my decals have overloaded the atlas? But I thought everything was supposed to crash if that happened, and the strict atlas size should make it not depend on hardware.

**Comment by GoogleFrog** [comment]
It was a new widget.
