### ISSUE TITLE
Lost of connection leads to desync if some player do resign

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/spring#1406]
[Desync end report.zip](https://github.com/beyond-all-reason/spring/files/14817532/Desync.end.report.zip) Lexon desync.
P.S Bonus, replay from cluster https://bar-rts.com/replays/94b70966c6456c6bb244637ba50f0096

Reproduce steps:
Put yourself in one team and another person in another team;
Force to lose internet connection for one player during loading to match;
Endgame graph should appear on the screen (if didn't repeat again);
Reenable your connection;
Place commanders, start the game;
As soon commander spawned, trigger self-D for commander;
As soon as commander dies desync messages should appear.

**Comment by Beherith** [comment]
The replay files also differ:

![image](https://github.com/beyond-all-reason/spring/assets/109391/1386ccca-94c3-47bf-b8b8-e908ed68bb58)

**Comment by 6AKU66** [comment]
In this replay constructions units was placing order underground
https://www.beyondallreason.info/replays?gameId=9feaff6506167f77e2c80c5df916f03b
![89](https://github.com/beyond-all-reason/spring/assets/89547444/3f4d8064-a082-42ca-bde4-4554ca0f20cf)

Also i tried to cheat in Lexon desynced replay and i got same result:
![88](https://github.com/beyond-all-reason/spring/assets/89547444/e36554e1-6a65-482a-b869-650a62711a08)

**Comment by marcushutchings** [comment]
Does this only happen when Lua-based AIs are controlled by the player that self-d their commander?

**Comment by 6AKU66** [comment]
> Does this only happen when Lua-based AIs are controlled by the player that self-d their commander?

It's was just me and Lexon. No any AIs.

**Comment by marcushutchings** [comment]
Does this happen if the com was destroyed by enemy fire or just with the self-d?

**Comment by marcushutchings** [comment]
A Commander death triggers a KillTeam call, which is handled by the clients, not the server (not sure why, but it is.) So it seems the clients made the KillTeam call happen on different frames.

**Comment by 6AKU66** [comment]
> Does this happen if the com was destroyed by enemy fire or just with the self-d?

I triggered self-d in commander.

**Comment by marcushutchings** [comment]
Can't the desync be recreated by using enemy fire instead of a self-d?

**Comment by 6AKU66** [comment]
I think it's can, but self-d option allowed me don't move commanders at all, so my intention was less noise.

**Comment by 6AKU66** [comment]
I guess something happened here.
Also i think this is could be a precursor. It's only happened on Lexon side before desync.

[t=00:04:15.403795][f=-000001] [Initial Spawn] manual spawning based on positions chosen by players in start boxes
[t=00:04:25.444335][f=-000001] Error: [GameEnd] lost connection to server; terminating game
[t=00:04:25.444853][f=-000001] EndGame Graph disabled
[t=00:04:25.447600][f=-000001] Input grabbing is disabled!

**Comment by marcushutchings** [comment]
The point I'm trying to make is that self-d coms has special code and conditions - that may be why the desync happens, which is why I asked if the desync can be reproduced via other means, like the com being killed by enemy fire. So that the moment, the answer is: we don't know.

**Comment by 6AKU66** [comment]
@marcushutchings Wait, actually during testings AKU and Lexon was killing commanders with testnuke and we managed to get a desync.

**Comment by 6AKU66** [comment]
Here a video with killing via nukes:
https://youtu.be/79Y268CJDaw

**Comment by marcushutchings** [comment]
@6AKU66, I'll look to get a special debug version of the engine to you. Then when you trigger a desync we'll get more information about what is going on.
