### ISSUE TITLE
Tracking issue for RmlUi integration.

### ISSUE THREAD

**Issue by blaisemccourtney** [beyond-all-reason/spring#1412]
This is a development tracking issue for RmlUi integration.

Background for this can be found in the Discord server: [GUI Framework Selection](https://discord.com/channels/549281623154229250/995701295430242307) and [RmlUi integration](https://discord.com/channels/549281623154229250/1151549624985854022) .

Current tasks for the system integration. For the sake of avoiding confusion, "completion" means that the main relevant changes have been merged into the BAR105 main branch. Note that a lot of these PRs are not merged into the BAR105 main branch, but merged into other branch(es):

- #1019
- #1020
- #1022
- #1023
- #1040
- #1064
- #1066
- #1069
- #1070
- #1076
- #1261
- #1304
- #1415
- #1418
- #1419
- #1427
- #1431
- https://github.com/beyond-all-reason/Beyond-All-Reason/pull/2546

Various UI widgets to make/remake:

- #1368 
- https://github.com/beyond-all-reason/Beyond-All-Reason/pull/2607

Bugs:

Other related issues:

- #448

General information:

RmlUi's repository: https://github.com/mikke89/RmlUi .

RmlUi's main documentation site: https://mikke89.github.io/RmlUiDoc/ .

**Comment by blaisemccourtney** [comment]
Please feel free to edit or close this issue as seen fit, I am not really part of this project, and this issue may not make sense.

**Comment by ChrisFloofyKitsune** [comment]
The EVERYTHING has been rebased into one branch!

https://github.com/ChrisFloofyKitsune/spring/tree/rmlui-integration-development

please let us just go from here with that branch (preferably in this repo instead of in my fork) and the preview branch

**Comment by sprunk** [comment]
5572e330d87c3e5be5b4802b5cbd8839a191c9d6
