### ISSUE TITLE
Reverse built units can retain velocity

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#1413]
Reverse built units can end up phasing over the map, and even off the map, because they retain some velocity gained by pushing against other units.

![image](https://github.com/beyond-all-reason/spring/assets/1318249/b45a9b33-6158-4997-b7ee-00c17f6f075c)

1. Spawn 100 cloakraid, set them to repeat, and tell them to move to a point.
2. Reclaim one near the centre
3. Watch its nanoframe slide out of the mass of units.

This correct behaviour would be to zero their velocity when they are reclaimed, and prevent any new velocity being gained from pushing.

![spring_2MD2d4atRv](https://github.com/beyond-all-reason/spring/assets/1318249/cadef69b-49e7-457d-8875-493bf4d68875)

![spring_w0QfFuyZg6](https://github.com/beyond-all-reason/spring/assets/1318249/aad5cc00-3dcb-40f2-b61f-c99cdaee73c9)

**Comment by marcushutchings** [comment]
Do you have a replay?

**Comment by marcushutchings** [comment]
Ah, scratch that, I've reproduced the issue.
