### ISSUE TITLE
2449 Nvidia graphics crash

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#1416]
https://github.com/ZeroK-RTS/CrashReports/issues/100145

[t=00:17:18.870179][f=0065440] [~CRectangleOverlapHandler] 15% overlap reduction
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 42971) >= this->size() (which is 42599)
[t=00:17:18.884008][f=0065440] Error: Spring received an ABORT signal
[t=00:17:18.884029][f=0065440] Error: Error handler invoked for Spring 105.1.1-2449-gf1234a9 BAR105.
[t=00:17:18.966450][f=0065440] Error: DLL information:
[t=00:17:18.966748][f=0065440] Error: 0x00007ff66a310000	spring
[t=00:17:18.966762][f=0065440] Error: 0x00007ffab88d0000	ntdll
[t=00:17:18.966773][f=0065440] Error: 0x00007ffab7850000	KERNEL32
[t=00:17:18.966784][f=0065440] Error: 0x00007ffab5f40000	KERNELBASE
[t=00:17:18.966794][f=0065440] Error: 0x00007ffab2710000	apphelp
[t=00:17:18.966804][f=0065440] Error: 0x00007ffab6970000	ADVAPI32
[t=00:17:18.966813][f=0065440] Error: 0x00007ffab7fb0000	msvcrt
[t=00:17:18.966822][f=0065440] Error: 0x00007ffab7b80000	sechost
[t=00:17:18.966831][f=0065440] Error: 0x00007ffab5c10000	bcrypt
[t=00:17:18.966840][f=0065440] Error: 0x00007ffab7c30000	RPCRT4
[t=00:17:18.966850][f=0065440] Error: 0x00007ffab8060000	imagehlp
[t=00:17:18.966859][f=0065440] Error: 0x00007ffab6360000	ucrtbase
[t=00:17:18.966869][f=0065440] Error: 0x00007ffab6d30000	SHELL32
[t=00:17:18.966879][f=0065440] Error: 0x00007ffab5ea0000	msvcp_win
[t=00:17:18.966888][f=0065440] Error: 0x00007ffa79740000	GLU32
[t=00:17:18.966897][f=0065440] Error: 0x00007ffab7d50000	USER32
[t=00:17:18.966906][f=0065440] Error: 0x00007ffab46d0000	IPHLPAPI
[t=00:17:18.966915][f=0065440] Error: 0x00007ffab5d00000	win32u
[t=00:17:18.966926][f=0065440] Error: 0x00007ffa50620000	OPENGL32
[t=00:17:18.966935][f=0065440] Error: 0x00007ffab6620000	GDI32
[t=00:17:18.966944][f=0065440] Error: 0x00007ffab8080000	combase
[t=00:17:18.966955][f=0065440] Error: 0x00007ffab6500000	gdi32full
[t=00:17:18.966964][f=0065440] Error: 0x00007ffab76e0000	SHLWAPI
[t=00:17:18.966973][f=0065440] Error: 0x00007ffab7b00000	WS2_32
[t=00:17:18.966982][f=0065440] Error: 0x00007ffab2ef0000	dxcore
[t=00:17:18.966991][f=0065440] Error: 0x000000006ed80000	glew32
[t=00:17:18.967000][f=0065440] Error: 0x000000006b600000	OpenAL32
[t=00:17:18.967009][f=0065440] Error: 0x000000006a1c0000	libIL
[t=00:17:18.967018][f=0065440] Error: 0x00007ffa40590000	SDL2
[t=00:17:18.967028][f=0065440] Error: 0x00007ffab6a30000	ole32
[t=00:17:18.967037][f=0065440] Error: 0x00007ffab6890000	IMM32
[t=00:17:18.967046][f=0065440] Error: 0x00007ffab7920000	OLEAUT32
[t=00:17:18.967055][f=0065440] Error: 0x00007ffab8410000	SETUPAPI
[t=00:17:18.967065][f=0065440] Error: 0x00007ffa62e60000	libfontconfig-1
[t=00:17:18.967075][f=0065440] Error: 0x00007ffa39290000	libcurl
[t=00:17:18.967085][f=0065440] Error: 0x000000006b3c0000	libvorbisfile-3
[t=00:17:18.967095][f=0065440] Error: 0x00007ffa51040000	libfreetype-6
[t=00:17:18.967110][f=0065440] Error: 0x00007ffab5d30000	CRYPT32
[t=00:17:18.967120][f=0065440] Error: 0x00007ffab6960000	Normaliz
[t=00:17:18.967129][f=0065440] Error: 0x00007ffab7740000	WLDAP32
[t=00:17:18.967138][f=0065440] Error: 0x00007ffaab3b0000	WINMM
[t=00:17:18.967147][f=0065440] Error: 0x00007ffaaa190000	VERSION
[t=00:17:18.967156][f=0065440] Error: 0x00007ffa633a0000	zlib1
[t=00:17:18.967165][f=0065440] Error: 0x000000006d540000	libvorbis-0
[t=00:17:18.967174][f=0065440] Error: 0x00007ffa5d270000	libexpat-1
[t=00:17:18.967184][f=0065440] Error: 0x00007ffa90ec0000	libgcc_s_seh-1
[t=00:17:18.967192][f=0065440] Error: 0x00007ffa87da0000	libintl-8
[t=00:17:18.967200][f=0065440] Error: 0x0000000070680000	libogg-0
[t=00:17:18.967209][f=0065440] Error: 0x00007ffa402c0000	libharfbuzz-0
[t=00:17:18.967219][f=0065440] Error: 0x00007ffa5cc10000	libpng16-16
[t=00:17:18.967229][f=0065440] Error: 0x00007ffa7f160000	libbz2
[t=00:17:18.967239][f=0065440] Error: 0x00007ffa79e30000	libwinpthread-1
[t=00:17:18.967249][f=0065440] Error: 0x00007ffa4bc20000	libiconv-2
[t=00:17:18.967367][f=0065440] Error: 0x00007ffa41c10000	libglib-2.0-0
[t=00:17:18.967377][f=0065440] Error: 0x00007ffab58d0000	cfgmgr32
[t=00:17:18.967390][f=0065440] Error: 0x00007ffa5ad50000	libpcre-1
[t=00:17:18.967401][f=0065440] Error: 0x00007ffa51430000	gameoverlayrenderer64
[t=00:17:18.967410][f=0065440] Error: 0x00007ffab6650000	PSAPI
[t=00:17:18.967419][f=0065440] Error: 0x00007ffaa5740000	nvapi64
[t=00:17:18.967427][f=0065440] Error: 0x00007ffab58b0000	msasn1
[t=00:17:18.967435][f=0065440] Error: 0x00007ffaaa150000	cryptnet
[t=00:17:18.967447][f=0065440] Error: 0x00007ffaa7560000	drvstore
[t=00:17:18.967456][f=0065440] Error: 0x00007ffab5920000	devobj
[t=00:17:18.967464][f=0065440] Error: 0x00007ffab54c0000	wldp
[t=00:17:18.967473][f=0065440] Error: 0x00007ffab5410000	cryptbase
[t=00:17:18.967482][f=0065440] Error: 0x00007ffab2810000	uxtheme
[t=00:17:18.967490][f=0065440] Error: 0x00007ffab75e0000	SHCORE
[t=00:17:18.967498][f=0065440] Error: 0x00007ffaaeac0000	mscms
[t=00:17:18.967506][f=0065440] Error: 0x00007ffa54aa0000	icm32
[t=00:17:18.967516][f=0065440] Error: 0x00007ffa750a0000	AudioDevProps2
[t=00:17:18.967525][f=0065440] Error: 0x00007ffab6bd0000	MSCTF
[t=00:17:18.967535][f=0065440] Error: 0x00007ffaaf060000	directxdatabasehelper
[t=00:17:18.967546][f=0065440] Error: 0x00007ffab4d40000	kernel.appcore
[t=00:17:18.967556][f=0065440] Error: 0x00007ffab6480000	bcryptPrimitives
[t=00:17:18.967565][f=0065440] Error: 0x000002468c360000	clbcatq
[t=00:17:18.967577][f=0065440] Error: 0x00007ffa259d0000	nvoglv64
[t=00:17:18.967588][f=0065440] Error: 0x00007ffab4aa0000	WTSAPI32
[t=00:17:18.967597][f=0065440] Error: 0x00007ffab62f0000	WINTRUST
[t=00:17:18.967606][f=0065440] Error: 0x00007ffab4d60000	ntmarta
[t=00:17:18.967616][f=0065440] Error: 0x00007ffab3b80000	windows.storage
[t=00:17:18.967625][f=0065440] Error: 0x00007ffab3a40000	wintypes
[t=00:17:18.967635][f=0065440] Error: 0x00007ffa3fc10000	nvspcap64
[t=00:17:18.967644][f=0065440] Error: 0x00007ffab5b40000	profapi
[t=00:17:18.967653][f=0065440] Error: 0x00007ffab2e80000	dwmapi
[t=00:17:18.967663][f=0065440] Error: 0x00007ffab4ac0000	powrprof
[t=00:17:18.967672][f=0065440] Error: 0x00007ffab4a80000	UMPDC
[t=00:17:18.967680][f=0065440] Error: 0x00007ffab4800000	WINSTA
[t=00:17:18.967691][f=0065440] Error: 0x00007ffaa1cc0000	textinputframework
[t=00:17:18.967701][f=0065440] Error: 0x00007ffab2340000	CoreMessaging
[t=00:17:18.967711][f=0065440] Error: 0x00007ffaa9b40000	CoreUIComponents
[t=00:17:18.967721][f=0065440] Error: 0x00007ffa80fd0000	shfolder
[t=00:17:18.967730][f=0065440] Error: 0x00007ffab2d70000	dxgi
[t=00:17:18.967739][f=0065440] Error: 0x00007ffab1a60000	d3d11
[t=00:17:18.967748][f=0065440] Error: 0x00007ffa4b680000	nvldumdx
[t=00:17:18.967757][f=0065440] Error: 0x00007ffab5420000	CRYPTSP
[t=00:17:18.967766][f=0065440] Error: 0x00007ffab4ca0000	rsaenh
[t=00:17:18.967775][f=0065440] Error: 0x00007ff9e5c60000	nvwgf2umx
[t=00:17:18.967785][f=0065440] Error: 0x00007ffaa7ed0000	MMDevApi
[t=00:17:18.967795][f=0065440] Error: 0x00007ffaa29c0000	AudioSes
[t=00:17:18.967804][f=0065440] Error: 0x00007ffa76e80000	ProductInfo
[t=00:17:18.967815][f=0065440] Error: 0x00007ffa98ec0000	ASM.Plugin.AudioDevProps2
[t=00:17:18.967825][f=0065440] Error: 0x00007ffaaff20000	PropSys
[t=00:17:18.967833][f=0065440] Error: 0x00007ffa8fdc0000	Windows.UI
[t=00:17:18.967843][f=0065440] Error: 0x00007ffaa71d0000	igd10iumd64
[t=00:17:18.967852][f=0065440] Error: 0x00007ffaa5f70000	igd10um64xe
[t=00:17:18.967860][f=0065440] Error: 0x00007ffaa5f30000	ControlLib
[t=00:17:18.967870][f=0065440] Error: 0x00007ffaa5eb0000	IntelControlLib
[t=00:17:18.967878][f=0065440] Error: 0x00007ffaa52e0000	igdgmm64
[t=00:17:18.967886][f=0065440] Error: 0x00007ffa9c7b0000	igc64
[t=00:17:18.967897][f=0065440] Error: 0x00007ffab3230000	resourcepolicyclient
[t=00:17:18.967906][f=0065440] Error: 0x00007ffab4b20000	secur32
[t=00:17:18.967915][f=0065440] Error: 0x00007ffab4fa0000	SSPICLI
[t=00:17:18.967923][f=0065440] Error: 0x00007ffab6880000	NSI
[t=00:17:18.967933][f=0065440] Error: 0x00007ffaaef00000	dhcpcsvc
[t=00:17:18.967942][f=0065440] Error: 0x00007ffab51c0000	mswsock
[t=00:17:18.967950][f=0065440] Error: 0x00007ffa7d430000	napinsp
[t=00:17:18.967959][f=0065440] Error: 0x00007ffa7d410000	pnrpnsp
[t=00:17:18.967967][f=0065440] Error: 0x00007ffab4700000	DNSAPI
[t=00:17:18.967975][f=0065440] Error: 0x00007ffa7a760000	winrnr
[t=00:17:18.967983][f=0065440] Error: 0x00007ffaab0e0000	wshbth
[t=00:17:18.967992][f=0065440] Error: 0x00007ffa7a730000	nlansp_c
[t=00:17:18.968000][f=0065440] Error: 0x00007ffaab5e0000	fwpuclnt
[t=00:17:18.968009][f=0065440] Error: 0x00007ffaaaeb0000	rasadhlp
[t=00:17:18.968017][f=0065440] Error: 0x00007ffa77360000	TextShaping
[t=00:17:18.968107][f=0065440] Error: 0x00007ffab3630000	dbghelp
[t=00:17:18.968128][f=0065440] Error: Stacktrace for Spring 105.1.1-2449-gf1234a9 BAR105:
[t=00:17:18.969036][f=0065440] Error: 	[ProgCtr=00007ff66aa66a8d StackPtr=0000004f013fca00 FramePtr=0000000000000000]
[t=00:17:18.969052][f=0065440] Error: 	(0) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66aa66a8d]
[t=00:17:18.969065][f=0065440] Error: 	(1) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66aa67601]
[t=00:17:18.969076][f=0065440] Error: 	(2) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66aa676c1]
[t=00:17:18.969086][f=0065440] Error: 	(3) C:\WINDOWS\System32\msvcrt.dll [0x000000000002e0ac]
[t=00:17:18.969095][f=0065440] Error: 	(4) C:\WINDOWS\System32\msvcrt.dll [0x000000000003255b]
[t=00:17:18.969106][f=0065440] Error: 	(5) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66b05c8e6]
[t=00:17:18.969117][f=0065440] Error: 	(6) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66af16826]
[t=00:17:18.969129][f=0065440] Error: 	(7) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66b20fd93]
[t=00:17:18.969140][f=0065440] Error: 	(8) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66af16cf9]
[t=00:17:18.969151][f=0065440] Error: 	(9) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66aef0f4d]
[t=00:17:18.969162][f=0065440] Error: 	(10) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66b210495]
[t=00:17:18.969172][f=0065440] Error: 	(11) C:\WINDOWS\SYSTEM32\ntdll.dll [0x00000000000a441f]
[t=00:17:18.969180][f=0065440] Error: 	(12) C:\WINDOWS\SYSTEM32\ntdll.dll [0x000000000001e466]
[t=00:17:18.969189][f=0065440] Error: 	(13) C:\WINDOWS\SYSTEM32\ntdll.dll [0x0000000000054475]
[t=00:17:18.969200][f=0065440] Error: 	(14) C:\WINDOWS\System32\KERNELBASE.dll [0x0000000000065b0c]
[t=00:17:18.969211][f=0065440] Error: 	(15) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66aef1001]
[t=00:17:18.969222][f=0065440] Error: 	(16) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66b210319]
[t=00:17:18.969232][f=0065440] Error: 	(17) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66b1fc96f]
[t=00:17:18.969242][f=0065440] Error: 	(18) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66a7389a6]
[t=00:17:18.969252][f=0065440] Error: 	(19) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66a8b750a]
[t=00:17:18.969262][f=0065440] Error: 	(20) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66a8b7a9d]
[t=00:17:18.969272][f=0065440] Error: 	(21) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66a8d8ce6]
[t=00:17:18.969282][f=0065440] Error: 	(22) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66a347d5b]
[t=00:17:18.969292][f=0065440] Error: 	(23) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66a35a355]
[t=00:17:18.969303][f=0065440] Error: 	(24) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66a35a78d]
[t=00:17:18.969313][f=0065440] Error: 	(25) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66a9a814f]
[t=00:17:18.969323][f=0065440] Error: 	(26) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66a999a4e]
[t=00:17:18.969333][f=0065440] Error: 	(27) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66a9adcf9]
[t=00:17:18.969344][f=0065440] Error: 	(28) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66a98c728]
[t=00:17:18.969401][f=0065440] Error: 	(29) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66a3112ee]
[t=00:17:18.969412][f=0065440] Error: 	(30) C:\Program Files (x86)\Steam\steamapps\common\Zero-K\engine\win64\105.1.1-2449-gf1234a9\spring.exe [0x00007ff66a3113e6]
[t=00:17:18.969422][f=0065440] Error: 	(31) C:\WINDOWS\System32\KERNEL32.DLL [0x000000000001257d]
[t=00:17:18.969431][f=0065440] Error: 	(32) C:\WINDOWS\SYSTEM32\ntdll.dll [0x000000000005aa58]
[t=00:17:18.972829][f=0065440] Error: [Watchdog::DeregisterThread] invalid thread number 0
[t=00:17:20.932689][f=0065440] Error: [ExitSpringProcess] errorMsg="Abort / abnormal termination" msgCaption="Spring: Fatal Error" mainThread=1
[t=00:17:21.032443][f=0065440] Error: Spring 105.1.1-2449-gf1234a9 BAR105 has crashed.
[t=00:17:21.091914][f=0065440] Error: DLL information:
[t=00:17:21.091935][f=0065440] Error: 0x00007ff66a310000	spring
[t=00:17:21.091940][f=0065440] Error: 0x00007ffab88d0000	ntdll
[t=00:17:21.091945][f=0065440] Error: 0x00007ffab7850000	KERNEL32
[t=00:17:21.091949][f=0065440] Error: 0x00007ffab5f40000	KERNELBASE
[t=00:17:21.091954][f=0065440] Error: 0x00007ffab2710000	apphelp
[t=00:17:21.091958][f=0065440] Error: 0x00007ffab6970000	ADVAPI32
[t=00:17:21.091963][f=0065440] Error: 0x00007ffab7fb0000	msvcrt
[t=00:17:21.091967][f=0065440] Error: 0x00007ffab7b80000	sechost
[t=00:17:21.091971][f=0065440] Error: 0x00007ffab5c10000	bcrypt
[t=00:17:21.091975][f=0065440] Error: 0x00007ffab7c30000	RPCRT4
[t=00:17:21.091979][f=0065440] Error: 0x00007ffab8060000	imagehlp
[t=00:17:21.091983][f=0065440] Error: 0x00007ffab6360000	ucrtbase
[t=00:17:21.091987][f=0065440] Error: 0x00007ffab6d30000	SHELL32
[t=00:17:21.091991][f=0065440] Error: 0x00007ffab5ea0000	msvcp_win
[t=00:17:21.091995][f=0065440] Error: 0x00007ffa79740000	GLU32
[t=00:17:21.091999][f=0065440] Error: 0x00007ffab7d50000	USER32
[t=00:17:21.092003][f=0065440] Error: 0x00007ffab46d0000	IPHLPAPI
[t=00:17:21.092007][f=0065440] Error: 0x00007ffab5d00000	win32u
[t=00:17:21.092011][f=0065440] Error: 0x00007ffa50620000	OPENGL32
[t=00:17:21.092014][f=0065440] Error: 0x00007ffab6620000	GDI32
[t=00:17:21.092018][f=0065440] Error: 0x00007ffab8080000	combase
[t=00:17:21.092022][f=0065440] Error: 0x00007ffab6500000	gdi32full
[t=00:17:21.092026][f=0065440] Error: 0x00007ffab76e0000	SHLWAPI
[t=00:17:21.092034][f=0065440] Error: 0x00007ffab7b00000	WS2_32
[t=00:17:21.092038][f=0065440] Error: 0x00007ffab2ef0000	dxcore
[t=00:17:21.092064][f=0065440] Error: 0x000000006ed80000	glew32
[t=00:17:21.092071][f=0065440] Error: 0x000000006b600000	OpenAL32
[t=00:17:21.092077][f=0065440] Error: 0x000000006a1c0000	libIL
[t=00:17:21.092092][f=0065440] Error: 0x00007ffa40590000	SDL2
[t=00:17:21.092107][f=0065440] Error: 0x00007ffab6a30000	ole32
[t=00:17:21.092115][f=0065440] Error: 0x00007ffab6890000	IMM32
[t=00:17:21.092120][f=0065440] Error: 0x00007ffab7920000	OLEAUT32
[t=00:17:21.092125][f=0065440] Error: 0x00007ffab8410000	SETUPAPI
[t=00:17:21.092132][f=0065440] Error: 0x00007ffa62e60000	libfontconfig-1
[t=00:17:21.092137][f=0065440] Error: 0x00007ffa39290000	libcurl
[t=00:17:21.092143][f=0065440] Error: 0x000000006b3c0000	libvorbisfile-3
[t=00:17:21.092148][f=0065440] Error: 0x00007ffa51040000	libfreetype-6
[t=00:17:21.092153][f=0065440] Error: 0x00007ffab5d30000	CRYPT32
[t=00:17:21.092157][f=0065440] Error: 0x00007ffab6960000	Normaliz

**Comment by lhog** [comment]
Dup of https://github.com/beyond-all-reason/spring/issues/1417
