### ISSUE TITLE
Docs publishing failures

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#1429]
https://github.com/beyond-all-reason/spring/actions/runs/8639659024/job/23686362114

>   Liquid Exception: Could not find document 'guides/headless-and-dedi' in tag 'link'. Make sure the document exists and the path is correct. in articles/wupget-communication.markdown

**Comment by sprunk** [comment]
6dd062e77c42c4df700a239c2ddf8c61a55fcc0d

Deployed successfully https://github.com/beyond-all-reason/spring/actions/runs/8655098247/job/23733502048
