### ISSUE TITLE
Add a lua callout to tell LOAM to update.

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#143]
Currently I do this by changing grounddetail. There should be a dedicated callout for this.

**Comment by lhog** [comment]
@Beherith is the a trigger to set inside LOAM to update it?

**Comment by Beherith** [comment]
Ill have to check or write one, as there are several bools that trigger an update.

**Comment by Beherith** [comment]
https://github.com/beyond-all-reason/spring/blob/e6c5d5deb8d3edc86a140badf9c68a705c9e45e1/rts/Map/SMF/ROAM/RoamMeshDrawer.cpp#L42

**Comment by lhog** [comment]
All right. I'm gonna add the call on a next occasion.

**Comment by lhog** [comment]
Wasn't tested but should work.
`Spring.ForceTesselationUpdate(updateNormalMesh, updateShadowMesh)`

**Comment by GoogleFrog** [comment]
Thanks.

**Comment by sprunk** [comment]
> Wasn't tested but should work

story of my life

**Comment by lhog** [comment]
NP. Closing for now. Re-open in case it won't work.

**Comment by GoogleFrog** [comment]
Doesn't work
![image](https://user-images.githubusercontent.com/1318249/151683744-64fdd2ed-bedc-4656-a061-6f15b5285de2.png)
![image](https://user-images.githubusercontent.com/1318249/151683742-87843a1a-6a60-4ded-a1ec-ed39db1b7f69.png)

```
	if BAR_COMPAT then
		Spring.ForceTesselationUpdate(true, true)
		Spring.Echo("ForceTesselationUpdate", math.random())
	else
		toSet = Spring.GetConfigInt("GroundDetail", 90) -- Default in epic menu
		Spring.SendCommands{"GroundDetail " .. (toSet + 1)}
	end
	wantMapTessellateUpdate = false
	```
