### ISSUE TITLE
Engine crash when calling LuaVBOImpl::InstanceDataFromFeatureIDs on geothermal vent feature

### ISSUE THREAD

**Issue by salinecitrine** [beyond-all-reason/spring#1437]
**URL of infolog.txt**
https://log.beyondallreason.dev/logs-20240413T1755-op_VmwQP.zip
*note: there's a lot of widget debugging messages in there; this crash was encountered while developing a new widget*

**Engine Version**
105.1.1-2314-g9e0bf7d bar

**Translated Stack Trace with links**

(I don't know how to do this; https://imolarpg.dyndns.org/bar/stacktrace_translator/frontend/index.php didn't work)

**Additional context**
The last log message before the crash is `Error: [MatrixUploader::GetElemOffsetImpl] Supplied invalid CFeature (id:27697)` (id varies).

As far as I can tell, the call sequence looks something like this:

[LuaVBOImpl::InstanceDataFromFeatureIDs](https://github.com/beyond-all-reason/spring/blob/1b18eeaa67475bfc8585676bd98780020ae7ef9b/rts/Lua/LuaVBOImpl.cpp#L1297)
[LuaVBOImpl::InstanceDataFromImpl](https://github.com/beyond-all-reason/spring/blob/1b18eeaa67475bfc8585676bd98780020ae7ef9b/rts/Lua/LuaVBOImpl.cpp#L1016)
[LuaVBOImpl::InstanceDataFromGetData](https://github.com/beyond-all-reason/spring/blob/1b18eeaa67475bfc8585676bd98780020ae7ef9b/rts/Lua/LuaVBOImpl.cpp#L984)
[TypedStorageBufferUploader::GetElemOffset](https://github.com/beyond-all-reason/spring/blob/1b18eeaa67475bfc8585676bd98780020ae7ef9b/rts/Rendering/ModelsDataUploader.h#L46)
[MatrixUploader::GetElemOffsetImpl](https://github.com/beyond-all-reason/spring/blob/1b18eeaa67475bfc8585676bd98780020ae7ef9b/rts/Rendering/ModelsDataUploader.cpp#L249)
[ Error: [MatrixUploader::GetElemOffsetImpl] Supplied invalid CFeature (id:...)](https://github.com/beyond-all-reason/spring/blob/1b18eeaa67475bfc8585676bd98780020ae7ef9b/rts/Rendering/ModelsDataUploader.cpp#L260)

and then at some point before returning from `LuaVBOImpl::InstanceDataFromFeatureIDs`, it crashes.

The only feature I've seen this occur with so far is geothermal vents.

**Comment by lhog** [comment]
Can you send your widget so I can reproduce?

**Comment by salinecitrine** [comment]
> Can you send your widget so I can reproduce?

Here's a minimal reproducer: https://gist.github.com/salinecitrine/c7633fc6053d20bcd907d4dfae8bc436
*To reproduce, load a map with a geo, and enable the widget. Tested on "Rosetta 1.42", "Hotlips Remake 3.1.1", and "Erebos Lakes 1.0"*

Here's the original widgets, with crash protection commented out: [Widgets.zip](https://github.com/beyond-all-reason/spring/files/14970247/Widgets.zip)
*To reproduce, disable "Smart Area Reclaim", enable both of these widgets, activate the reclaim command, alt+leftclick+drag starting on a tree, and expand the area to include a geo. Tested on "Hotlips Remake 3.1.1"*

**Comment by salinecitrine** [comment]
Thank you for the quick fix!

**Comment by lhog** [comment]
Always a pleasure when it's easy to reproduce
