### ISSUE TITLE
Crash in: rts/Sim/Path/TKPFS/PathManager.cpp 	154

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#147]
@marcushutchings , could you perhaps take a look at this possible crash? 

C:\Games\BAR\data\engine\105.1.1-714-ge909643 bar\spring.exe 0x000000014008384c /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/bits/stl_vector.h:111
C:\Games\BAR\data\engine\105.1.1-714-ge909643 bar\spring.exe 0x000000014009631d /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/bits/stl_vector.h:919
C:\Games\BAR\data\engine\105.1.1-714-ge909643 bar\spring.exe 0x00000001400964be rts/Sim/Path/TKPFS/PathManager.cpp:154
C:\Games\BAR\data\engine\105.1.1-714-ge909643 bar\spring.exe 0x000000014009b4e2 rts/Sim/Path/IPathManager.cpp:34
C:\Games\BAR\data\engine\105.1.1-714-ge909643 bar\spring.exe 0x000000013f908d7f rts/Game/Game.cpp:945
C:\Games\BAR\data\engine\105.1.1-714-ge909643 bar\spring.exe 0x000000013f9095a5 rts/Game/Game.cpp:295
C:\Games\BAR\data\engine\105.1.1-714-ge909643 bar\spring.exe 0x000000013f9097ce rts/Game/Game.cpp:303
C:\Games\BAR\data\engine\105.1.1-714-ge909643 bar\spring.exe 0x000000013fd907d5 rts/System/SafeUtil.h:25
C:\Games\BAR\data\engine\105.1.1-714-ge909643 bar\spring.exe 0x000000013fd95d79 rts/System/Platform/Threading.h:188
C:\Games\BAR\data\engine\105.1.1-714-ge909643 bar\spring.exe 0x000000013fd7e70c rts/System/Main.cpp:48

Infolog here: 

https://server2.beyondallreason.info/teiserver/reports/infolog/42

@6AKU66, this seems to be coming from you, could you please confirm that watching the replay of this games also crashes? 

{
  "engineversion": "105.1.1-714-ge909643105",
  "errortype": "EngineCrash",
  "filename": "log\\20211227010237_infolog.txt",
  "gameversion": "BAR-18486-feffdce",
  "private": false,
  "shorterror": "[t=00:00:12.064000][f=-000001] Error: \\t(0) C:\\Games\\BAR\\data\\engine\\105.1.1-714-ge909643 bar\\spring.exe [0x000000014008384c]"
}

**Comment by 6AKU66** [comment]
>  this seems to be coming from you, could you please confirm that watching the replay of this games also crashes
Not sure if it's from me and i don't see link to replay.

**Comment by lhog** [comment]
Attn @marcushutchings

**Comment by Beherith** [comment]
@6AKU66  recording demo to "C:\Games\BAR\data\demos\20211227_010232_Eye of Horus v13_105.1.1-714-ge909643 BAR105.sdfz"

Do you happen to have this file?

**Comment by 6AKU66** [comment]
> Do you happen to have this file?

I don't have it.
And i don't remember playing or spectate Eye of Horus in recent time.

**Comment by marcushutchings** [comment]
I looked the logs. The game aborted during load. The crash reported location is the same issue as for https://github.com/beyond-all-reason/spring/issues/166 where the pathing system didn't shutdown cleanly if it isn't properly initialized.
