### ISSUE TITLE
Footprint decal stretch regression

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#1491]
/give striderbantha

The decal only looks different for units with trackStretch != 1. I suspect the sign of an exponent was flipped somewhere in the new decal system.

2457
![image](https://github.com/beyond-all-reason/spring/assets/1318249/02af0840-1987-4153-b756-5fc2d3a4f5f3)

2031
![image](https://github.com/beyond-all-reason/spring/assets/1318249/ddfe57af-2af8-4624-a144-40c58d73f5f7)

**Comment by GoogleFrog** [comment]
Well, more of an unintended(?) behaviour change than a regression. But I'm not going to account for it until I know it is intentional, because it impacts a lot of places that are hard to reach (ie modding and other games).

**Comment by sprunk** [comment]
I think it's a good change because now a 0.5 stretch factor (like bantha has) makes each segment 0.5 the size. Smaller factor -> smaller segments.

**Comment by lhog** [comment]
Yeah I may have made it reciprocal accidentally. Since you're first to notice tell me if you want it the old way or is the new way fine?

**Comment by sprunk** [comment]
I prefer the new way because it is more intuitive and a gameside fix is trivial https://github.com/ZeroK-RTS/Zero-K/commit/00c47d467f757587fd92602c97246074506b391d

**Comment by GoogleFrog** [comment]
I have no preference for ZK, but it would nice to have one fewer thing to fix when updating an old game to work on modern spring.

**Comment by lhog** [comment]
Well seems like [you have posted the fix to ZK already](http://zero-k.info/Forum/Thread/37613) with the parameter read as is, so I assume we will move forward with that new semantics.

**Comment by sprunk** [comment]
There are other games than ZK though, but I think I can just PR the trivial fix for them approximately this weekend

**Comment by sprunk** [comment]
https://github.com/FluidPlay/TAP/pull/11
https://github.com/techannihilation/TA/pull/1678
MF and SF seem to have nothing to fix

Others TBD

**Comment by sprunk** [comment]
Looks like that's all.
