### ISSUE TITLE
Add `SetUnitIconDraw` as an alias for `UnitIconSetDraw`

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#1531]
There's `Spring.UnitIconSetDraw` which breaks the convention that such interfaces are always called `Spring.SetUnitFoo`. This is confusing enough to be a real problem (see e.g. https://github.com/beyond-all-reason/Beyond-All-Reason/commit/c2701c0b1a34e77abefe87b8493e513c8278eec0#commitcomment-92166066 ).

* add a properly-named function. Deprecate the current one but keep it as an alias for now to let games migrate.
* check whether there are any other names that break convention and handle them as well.

**Comment by harsha-mangena** [comment]
Hey @sprunk, Can I pick this issue up?

**Comment by sprunk** [comment]
sure

**Comment by harsha-mangena** [comment]
@sprunk, could you review the above pull request?
I searched for inconsistent names but found none in the respective files.

**Comment by sprunk** [comment]
eae2809daba963d6682fdbc1f91cd117ef9cf60a
