### ISSUE TITLE
Debug view with smooth air mesh overlay isn't working

### ISSUE THREAD

**Issue by springraaar** [beyond-all-reason/spring#1555]
engine: reproduced the issue on builds from 1011 to 2511
any game/map

typing /airmesh should enable the smooth air mesh overlay. It does so on 105.0 :
![image](https://github.com/beyond-all-reason/spring/assets/11828472/a2d7ced9-e73e-41f3-aec7-d88deabfa90b)

On the Recoil builds i get the console message saying that it's enabled
`[t=00:00:19.328966][f=0000040] smooth air-mesh map overlay is enabled!`

but it's not visible.

**Comment by sprunk** [comment]
Works for me, but there was an undocumented change that it requires `/cheat` since it lets you see terrain changes outside of LoS.

**Comment by springraaar** [comment]
you're right, thanks

seems like the wiki/site needs updating, then : the airmesh description could use the "CHEAT" label some of the others have
https://beyond-all-reason.github.io/spring/guides/unsynced-commands/#airmesh
