### ISSUE TITLE
Add sprite animation (from spritesheet) to weaponDef projectiles

### ISSUE THREAD

**Issue by MaDDoXbr** [beyond-all-reason/spring#1565]
There's not currently a way to "attach" an animated sprite (from a spritesheet/atlased animation) to the projectile itself, only to the particles it emits, which limits the kinds of effects we can do, as the particles are left behind, while the projectile keeps moving. There's a "model" tag in weapondefs, so we can assign a simple textured quad mesh to it, but then its texture would be static - and it wouldn't always be pointing at the camera, like particles do. 

My suggestion to work out this glaring omission (I can't recall a single game engine with a particle system which doesn't have this) is to add a new parameter to weapondef. Since the texture1 weapondef parameter is used as the projectile, beam, flare or shield sprite for practically all weapon types, is to take animation parameters from a string, just like _animParams_ does within a effect 'properties' table. 

The name of that new weapondef parameter would be something like "texture1animParams", and take a string value (xcount, ycount, duration). A randomizable startframe in-string parameter would be very advisable, to prevent excessive uniformity when multiple projectiles are shot at once. The default playback mode would be 'loop', but others, like 'pingpong' and 'playonce', could be added as a final string parameter. 

Eg:

texture1animparms = "4 1 8 3r1"   _-- could start from frames 2, 3 or 4_
texture1animparms = "4 1 8 3r1 pingpong"  _-- plays forward then in reverse, alternating_

**Comment by lhog** [comment]
Can you please link a weaponDef / unitDef with "static" `texture1` so I can have a look at something concrete?

**Comment by MaDDoXbr** [comment]
Hey @lhog I tweaked the guardsml (NPC floating alien rock thingy) weapon to use the alien-shot texture1, which is set as a spritesheet (4 cells width, 1 cell height). I removed the cegtag entry too, to make it more clear what it's doing, and added the texture1animparms to the weapon entry as described in my original request. Of course it's being ignored at the moment, but should work for your tests. Here's the commit, it's in the 'chiliUI' branch of the TAP repo:
https://github.com/FluidPlay/TAP/commit/389286be9464b81726153e649f01539916c9fa2c

**Comment by MaDDoXbr** [comment]
I also thought that maybe it would be much easier and powerful to have a `texture1cegtag` param instead, to replace texture1 (if it exists) with a cegtag. What do you think?

**Comment by MaDDoXbr** [comment]
Here are some screenshots of how it works (horizontally squished with no anim, of course). You may spawn one of those units with `/give guardsml` and, with godmode, attack ground with the "F" shortcut. Also, as TAP overrides all unit.lua data with whatever is in unitdefs_data, you tweak need to tweak the weapondef parameters here directly: https://github.com/FluidPlay/TAP/blob/ChiliUI/gamedata/configs/unitdefs_data.lua#L524  

If that's too cumbersome, let me know and I'll create a new unit which doesn't use the override system (actually any new unit not in the spreadsheet would do just that)

![spring_8BaWyaCabm](https://github.com/user-attachments/assets/2f663583-4964-4ee9-bb13-0ab4e2c2b501)
![spring_iv5Zwchh1N](https://github.com/user-attachments/assets/a292b97f-1d6c-4645-b02b-8dbc3baa1bc5)

**Comment by lhog** [comment]
![screen_2024-07-23_18-50-51-234](https://github.com/user-attachments/assets/7284b621-6050-4860-abc8-0458f87d22fe)

I increased the `size` to 128, `weaponvelocity` to 150 and `animParams` to "4 1 8".

**Comment by MaDDoXbr** [comment]
Thank you very much, Ivand. I'll test it out once there's an engine release (test or not) with it.

PS: Why is the TAP UI so screwed up for you? Jeez.. O_o'

**Comment by lhog** [comment]
@MaDDoXbr this will take some as the addition of new features is frozen for now.
