### ISSUE TITLE
DrawParticles Called twice (once for above and once for below water) even if no water present on map. 

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#1572]
Called once for abovewater, once for belowwater, even if no water present. 

![image](https://github.com/beyond-all-reason/spring/assets/109391/f900814e-aa3a-4c91-b2ae-be04dfba4142)
Only tangentially related to #1547

**Comment by Beherith** [comment]
Possibly, the water rendering check could be done gameside, with the unsyncedctrl `Spring.SetDrawWater(bool draw)`

**Comment by sprunk** [comment]
Does `Spring.SetMapRenderingParams( { voidwater = true } )` help? Perhaps it should.
