### ISSUE TITLE
Something is wrong with wrap-around for FPS/rot camera

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#16]
`Spring.SetCameraState(Spring.GetCameraState(), cameraTransitionTime)`

causes this issue.

spring camera is immune.

**Comment by lhog** [comment]
```switch to CTRL-F1 or CTRL-F4 cam modes (FPS/Rotate) - then do camera turns more than 180 degrees
you will probably hit a 'jump-back' when reaching 180.
happens in both directions for me```

**Comment by Beherith** [comment]
I kind of understand why this line is even bad to begin with:

Spring.SetCameraState(Spring.GetCameraState(), cameraTransitionTime)

Since we are essentially telling the camera to go where it is right now, in transition time.

**Comment by 6AKU66** [comment]
This don't happening with /luaui disable!

**Comment by 6AKU66** [comment]
If someone want avoid bug type /option camerasmoothness 0 in chat.

**Comment by Beherith** [comment]
![kép](https://user-images.githubusercontent.com/109391/150085712-c57ce87f-94cb-4718-988c-cd5d65b7edba.png)

**Comment by 6AKU66** [comment]
Yeah, with OFF it's working ok.

**Comment by Beherith** [comment]
And no other ill side effects on any other camera mode?

**Comment by Beherith** [comment]
@Ruwetuin , this is pertaining to Spring.SetCameraState(nil, cameraTransitionTime) every frame, why is it there, supposed it has to do with middle click pan?

```is this in gui_options.lua still needed at all? 
    if WG['advplayerlist_api'] and not WG['advplayerlist_api'].GetLockPlayerID() then
        --if select(7, Spring.GetMouseState()) then    -- when camera panning
        --    Spring.SetCameraState(nil, cameraPanTransitionTime)
        --else
        Spring.SetCameraState(nil, cameraTransitionTime)
        --end
    end
[4:11 PM] Beherith: Cause its what is causing spring camera up down rotate to judder
[4:25 PM] IceXuick: REMOVE!
[4:54 PM] ivand: It adds smoothness
[4:54 PM] ivand: Maybe not here, but somewhere
[5:02 PM] IceXuick: oh noo KEEP IT!
[5:21 PM] Floris:
Image
[5:22 PM] Floris: it indeed adds smoothness
[5:27 PM] IceXuick: ah yes, keep it definately
[5:37 PM] Beherith: I think our camera needs a bit of unification
[5:37 PM] Beherith: What is our standard camera mode?
[5:37 PM] Beherith: Ta F2 or sPRING F3?
[5:44 PM] Born2Crawl: F3 for me```

**Comment by Beherith** [comment]
Upon further testing, it seems that this command smooths camera panning, on not just middle click, but edge move

**Comment by dzosz** [comment]
I can take a look. Spring camera was having similar issues due to manipulating camera position instead of waiting for camera handler to pick it up.

**Comment by lhog** [comment]
That would be great!
Thanks!

**Comment by lhog** [comment]
N2S:
`LOG_L(L_DEBUG, "%s (%f %f %f) -> (%f %f %f)", __func__, camTransState.startRot.x, camTransState.startRot.y, camTransState.startRot.z, camera->GetRot().x, camera->GetRot().y, camera->GetRot().z);`

`Debug: CameraTransition (1.962671 3.062622 0.000000) -> (1.962670 -1.132468 0.000000)`

**Comment by dzosz** [comment]
> N2S: `LOG_L(L_DEBUG, "%s (%f %f %f) -> (%f %f %f)", __func__, camTransState.startRot.x, camTransState.startRot.y, camTransState.startRot.z, camera->GetRot().x, camera->GetRot().y, camera->GetRot().z);`
> 
> `Debug: CameraTransition (1.962671 3.062622 0.000000) -> (1.962670 -1.132468 0.000000)`

Default mix function can't smooth properly values between -pi and pi and the other way around.

**Comment by lhog** [comment]
Yes, I thought so as well, but yesterday I didn't have time to produce reliable mix for radians.
