### ISSUE TITLE
Fix/Improve Lightning Cannon

### ISSUE THREAD

**Issue by icexuick** [beyond-all-reason/spring#161]
Add more configurability and control to **lightningcannon** weapon (used by armzeus, armclaw, armthor).
This is for using the texture1 property - though it might also help with no texture 1 lightning arcs

In order of importance:

1. **Texture1** length should be configurable and be a fixed length globally, not based on distance of the lightning-arc.

2 **Random rotation** over length-axis, to give a lot more variety to the arc looks
This can probably be just a one-time spawn rotation of `-180 r 360`, but if possible, having it rotate over time could possibly be extra awesome. This weapon fires in burst, so it should apply random rotation for each separate shot in burstfire.
2B. Optionally also (on/off-able) random flipping/mirroring of texture1 in length, for even more variety/realistic looks

3. Get control over amount of 'iterations' of the lightning 'forks' (how many, and how far they can bend outwards)

concept of what to achieve
![image](https://user-images.githubusercontent.com/23189106/148657064-6fc333cc-6291-42b9-82c1-167da9dd7932.png)

**Comment by icexuick** [comment]
instead of:
![image](https://user-images.githubusercontent.com/23189106/148657076-854db70b-a3a5-4d2a-a07e-a83caa620957.png)

**Comment by sprunk** [comment]
I copied the request and pictures to #387, closing #161 as duplicate.
