### ISSUE TITLE
Add `math.normalize`

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#1628]
There's this naive pattern to normalize a vector:
```lua
local len = math.sqrt(x^2 + y^2 + z^2 + w^2 + ...)
x = x / len
y = y / len
z = z / len
w = w / len
...
```
This leaves you vulnerable to div0 and is pretty verbose. Consider instead:
```lua
x, y, z, w, ... = math.normalize(x, y, z, w, ...)
```

**Comment by viv511** [comment]
Hi! 

I'd like to try to help with this issue.

@viv511

**Comment by sprunk** [comment]
Check out (and probably build upon) `LuaMathExtra::diag`.

**Comment by WatchTheFort** [comment]
Should any of the functions in here be included?
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/common/numberfunctions.lua

**Comment by sprunk** [comment]
Feel free to.

**Comment by lhog** [comment]
Many functions there are very use case specific, please be mindful of what to include.

**Comment by sprunk** [comment]
From that file:
* `round`, `cross_product`, and `HSLtoRGB` sound fine.
* `triangulate` and `getClosestPosition` sound useful to have but would probably need some thought over the interface first.
* `isInRect` is trivial so probably not, but perhaps could be part of a larger vector lib.
* `distance{2,3}d{,Squared}` are just trivial wrappers over `math.diag` so probably not.

**Comment by viv511** [comment]
Hi! I'm very very sorry, but I don't have much experience with Lua and I'm not sure if I can help out with this project right now. I'm going to remove myself from "assignees" so that someone else can take a shot at this. :)

Thank you for your understanding,
@viv511

**Comment by sprunk** [comment]
No problem

**Comment by sprunk** [comment]
#1642
