### ISSUE TITLE
Add some sort of `table.allocate(n_hash, n_array)`

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#1632]
Consider this pattern:
```lua
local foo = {}
for i = 1, #UnitDefs do
  foo[i] = bar(UnitDefs[i])
end
```

This results in a lot of memory thrashing because the array keeps getting reallocated as the table grows. At i=5, it reallocates to size 8. At i=9, it reallocates to size 16. At i=17, it reallocates, etc etc. It would be good if you could pass a size hint e.g. `local foo = table.allocate(0, #UnitDefs)` like you can do in C++ with `lua_createtable`.

Remarks:
* FAF [seems to have a feature](https://github.com/FAForever/fa/blob/053d4bd41776a7bd05aaa871044b3182ed339165/lua/system/class.lua#L643) where you can pass constants like `local x = { &7 &2 }`. Don't do this, it is not valid Lua syntax and will break all external tools. I couldn't find the source to verify but I assume it works off the existing parameters to the `NEWTABLE` Lua VM opcode so I don't believe it accepts dynamic args either (which is the big use case via `#FooDefs`).
* I am aware of loadstring bytecode [and I disapprove](https://github.com/beyond-all-reason/spring/issues/1575).

**Comment by WatchTheFort** [comment]
Are the performance impacts of this significant enough to warrant introducing a new potential class of bugs?

**Comment by sprunk** [comment]
If BAR is scared of bugs it can `table.allocate = nil`.

**Comment by sprunk** [comment]
#1633 and 1f11c97e64cc64d9960e0bc8776a6fb4b5762875
