### ISSUE TITLE
Pass weaponDefID to UnitDestroyed

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#1639]
Bill of materials to be done before starting this ticket:
* #1638 

----

Add a new weaponDefID parameter to `CUnit::KillUnit` and pass it along such that it ends up in `CLuaHandle`. Use the new values added in #1638. The value ends up in `CLuaHandle::UnitDestroyed` at some point - pass the value to Lua as the 7th arg using `lua_pushnumber`. Don't forget to adjust the "number of passed values" parameter there from 6 to 7.

**Comment by keelefi** [comment]
Closed by https://github.com/beyond-all-reason/spring/pull/1669.
