### ISSUE TITLE
Map Missing (739)

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#164]
![image](https://user-images.githubusercontent.com/1318249/149452038-3d066e50-e3ca-4341-8e78-0aa8dc3ffba1.png)

Also some models are white. I saw white models with advmodelshading disabled so I suspect it and advmapshading are disabled or unavailible, and I suspect no admapshading either. This is approximately the 10th person who has tested the engine recently (for frequency estimates).

![image](https://user-images.githubusercontent.com/1318249/149452064-84cf6670-e4ed-41ae-a74d-c827a2c267ee.png)

**Comment by GoogleFrog** [comment]
I think this is an infolog from the player: https://github.com/ZeroK-RTS/CrashReports/issues/51240

**Comment by lhog** [comment]
This one is not a potatoe player. Good CPU, good GPU, yet they they config force disabled shaders and modern render paths.

I ll have a look, but generally such setups dont make much sense, as it also knocks out performant GL4 rendering.
