### ISSUE TITLE
Non upright units(spiders tanks etc), don't follow terrain orientation until they turn.

### ISSUE THREAD

**Issue by Tharsy** [beyond-all-reason/spring#1641]
###reproduction steps:
- Place any lab with tanks or spider bots facing a slope
- build units

https://github.com/user-attachments/assets/8d9284c6-9363-4971-b59e-750a0bbf75cd

[2024-08-11_00-52-45-443_Quicksilver Remake 1_105.1.1-2572-g7e87fc1 BAR105.zip](https://github.com/user-attachments/files/16571250/2024-08-11_00-52-45-443_Quicksilver.Remake.1_105.1.1-2572-g7e87fc1.BAR105.zip)

**Comment by lostsquirrel1** [comment]
That replay shared, as far as I can tell, doesn't show the problem. It doesn't look like the set up used in the video.

**Comment by lostsquirrel1** [comment]
I may have a fix for the issue, but I'll need to be able to show the problem. I'll try and find some time tomorrow, but if you have a replay that shows the issue then that would be very helpful.

**Comment by lhog** [comment]
You can order any unit to go straight on more or less even ground and observe that this unit only gets `UpdateDirVectors` calls in case of tiny changes in the direction, otherwise the code is not called.
