### ISSUE TITLE
Instant crash (761)

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#165]
This build crashes immediately. This is a wrapper launch: https://github.com/ZeroK-RTS/CrashReports/issues/51251

This is spring.exe directly:
![image](https://user-images.githubusercontent.com/1318249/149458346-f9e2b66f-452b-432e-ba2d-7f21f2a804b3.png)
No infolog.txt is created.

**Comment by lhog** [comment]
My bad, should be fixed in the next release.
