### ISSUE TITLE
TKPFS crash on very large map

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#166]
Hi @marcushutchings , may I ask you to look into a specific crash of a very large map with TKPFS?

The map is: Vaubanv3, avail here: https://springfiles.springrts.com/?type=2&filter=6edf40aac0672715d52bb3022bea3d7c

And when trying to load it, I get the following stack trace: 

This happens with engine version 714.
```
<html><body>
<!--StartFragment--><a href="http://imolarpg.dyndns.org/bar/stacktrace_translator/frontend/index.php" target="_blank"></a>
	<h1>translated with links to github source ('' detected)</h1>


module | address | file | line
-- | -- | -- | --
C:\Users\Peti\Documents\My Games\Spring\engine\spring_bar_.BAR105.105.1.1-714-ge909643_windows-64-minimal-portable\spring.exe | 0x00007ff6f6d0384c | /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/bits/stl_vector.h | 111
C:\Users\Peti\Documents\My Games\Spring\engine\spring_bar_.BAR105.105.1.1-714-ge909643_windows-64-minimal-portable\spring.exe | 0x00007ff6f6d1631d | /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/bits/stl_vector.h | 919
C:\Users\Peti\Documents\My Games\Spring\engine\spring_bar_.BAR105.105.1.1-714-ge909643_windows-64-minimal-portable\spring.exe | 0x00007ff6f6d164be | rts/Sim/Path/TKPFS/PathManager.cpp | 154
C:\Users\Peti\Documents\My Games\Spring\engine\spring_bar_.BAR105.105.1.1-714-ge909643_windows-64-minimal-portable\spring.exe | 0x00007ff6f6d1b4e2 | rts/Sim/Path/IPathManager.cpp | 34
C:\Users\Peti\Documents\My Games\Spring\engine\spring_bar_.BAR105.105.1.1-714-ge909643_windows-64-minimal-portable\spring.exe | 0x00007ff6f6588d7f | rts/Game/Game.cpp | 945
C:\Users\Peti\Documents\My Games\Spring\engine\spring_bar_.BAR105.105.1.1-714-ge909643_windows-64-minimal-portable\spring.exe | 0x00007ff6f65895a5 | rts/Game/Game.cpp | 295
C:\Users\Peti\Documents\My Games\Spring\engine\spring_bar_.BAR105.105.1.1-714-ge909643_windows-64-minimal-portable\spring.exe | 0x00007ff6f65897ce | rts/Game/Game.cpp | 303
C:\Users\Peti\Documents\My Games\Spring\engine\spring_bar_.BAR105.105.1.1-714-ge909643_windows-64-minimal-portable\spring.exe | 0x00007ff6f6a107d5 | rts/System/SafeUtil.h | 25
C:\Users\Peti\Documents\My Games\Spring\engine\spring_bar_.BAR105.105.1.1-714-ge909643_windows-64-minimal-portable\spring.exe | 0x00007ff6f6a15d79 | rts/System/Platform/Threading.h | 188
C:\Users\Peti\Documents\My Games\Spring\engine\spring_bar_.BAR105.105.1.1-714-ge909643_windows-64-minimal-portable\spring.exe | 0x00007ff6f69fe70c | rts/System/Main.cpp | 48
C:\Users\Peti\Documents\My Games\Spring\engine\spring_bar_.BAR105.105.1.1-714-ge909643_windows-64-minimal-portable\spring.exe | 0x00007ff6f65513c1 | /mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c | 323
C:\Users\Peti\Documents\My Games\Spring\engine\spring_bar_.BAR105.105.1.1-714-ge909643_windows-64-minimal-portable\spring.exe | 0x00007ff6f65514d6 | /mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c | 178
C:\Windows\SYSTEM32\ntdll.dll | 0x00007ff600052651 | ?? | 0

<!--EndFragment-->
</body>
</html>
```

**Comment by marcushutchings** [comment]
@Beherith 

The crash location is a mis-direction. The application hit a fault loading the map and caused spring to shutdown before pathing could be properly initialized. I will make the code more robust to this scenario; however, the root cause of the problem I believe is that the map is faulty or corrupt. See below:

I get the follwoing spring log report when loading the map:

[2022-01-20 16:03:30.760] [error] Unexpected error occurred.
[2022-01-20 16:03:30.761] [error] Error: Data Error : maps\VaubanV3.smt
    at Object.fromBuffer (C:\Users\greyw\AppData\Local\Programs\Beyond-All-Reason\resources\app.asar\node_modules\node-7z\src\error.js:30:15)
    at C:\Users\greyw\AppData\Local\Programs\Beyond-All-Reason\resources\app.asar\node_modules\node-7z\src\events.js:25:19
    at Socket.<anonymous> (C:\Users\greyw\AppData\Local\Programs\Beyond-All-Reason\resources\app.asar\node_modules\node-7z\src\lifecycle.js:64:51)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
[2022-01-20 16:03:30.762] [error] Error: Data Error : maps\VaubanV3.smt
    at Object.fromBuffer (C:\Users\greyw\AppData\Local\Programs\Beyond-All-Reason\resources\app.asar\node_modules\node-7z\src\error.js:30:15)
    at C:\Users\greyw\AppData\Local\Programs\Beyond-All-Reason\resources\app.asar\node_modules\node-7z\src\events.js:25:19
    at Socket.<anonymous> (C:\Users\greyw\AppData\Local\Programs\Beyond-All-Reason\resources\app.asar\node_modules\node-7z\src\lifecycle.js:64:51)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
