### ISSUE TITLE
Factory repeat: Commands queued with alt still repeat when they are issued with CMD.INSERT

### ISSUE THREAD

**Issue by hihoman23** [beyond-all-reason/spring#1675]
When a build command is issued with `CMD.INSERT` and `CMD.OPT_ALT` as a third parameter (which applies to the inserted command), if the factory is on repeat mode, it still repeats the unit.

**Comment by sprunk** [comment]
The "no repeat" modifier is probably OPT_INTERNAL

**Comment by hihoman23** [comment]
> The "no repeat" modifier is probably OPT_INTERNAL

Yes, adding that fixes the issue.
