### ISSUE TITLE
windows | spring.exe substittue in data\

### ISSUE THREAD

**Issue by FIr3baL** [beyond-all-reason/spring#168]
Hey,
a lot of programs load theirs configs by recognized started path\program.exe.
For example:
- windows sound mixer saves volume levels
- Logitech driver tool saves mouse dpi 
- Logitech sound equalizer
- ati/intel VGA driver tools

Since every spring update creates a new directory, the new spring.exe is recognized as an new program and those programs give default configs to it.

Users need to adjust sound mixer volumes, mouse settings etc. on every update over and over.

Why not start 1st spring thread from PathToGame\data\springMainThread.exe ?
This could load the real spring.exe from PathToGame\data\engine\105.x\spring.exe

Maybe those programs use other detections as mentioned. But there should be a well established way of giving those programs the ability to detect correctly.

As a naive suggestion, why not use symbolic link ?
cd \data
mklink spring.exe \engine\105.x\spring.exe

best regards
Fireball

**Comment by lhog** [comment]
Sounds more like a packaging thing, because both we and legacy spring are distributed as self-contained entity.

**Comment by FIr3baL** [comment]
Yes - my fault.
You can close here. I open up another one on Bayond All Reason.
