### ISSUE TITLE
780: some matrices seem like they dont get uploaded for immobile/idle units

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#169]
On this image, there are 8 windgens, they are all selected, but only 4 of them have selection platters, and I can also see, that the ones that dont have selection platters, also dont have ground ao plates or selection highlights. 
![image](https://user-images.githubusercontent.com/109391/149828810-9383abb5-947f-425a-8a37-d3f83d07a140.png)

**Comment by Beherith** [comment]
This is the wierdes thing, the first 8 buildings I built didnt have their matrices accessible (or I dont know yet), ill keep reporting if i find relevant stuff

**Comment by Beherith** [comment]
In this screenshot, every single unit is selected: (ctrl - A)
![image](https://user-images.githubusercontent.com/109391/149830355-3fb0c061-b851-473d-83b3-6fe5ea5ce81f.png)
Note how all not idle mobile units get their selprims drawn, while most buildings dont.

**Comment by Beherith** [comment]
Ok MOST IMPORTANT: The advanced con bot, that is right next to the Moho Geo in the bottom center of the image, was also selected. It suddenly got its selection primitive rendered when I gave it a move order.

**Comment by lhog** [comment]
Seems resolved
