### ISSUE TITLE
Ticks getting confused on which way to move past buildings

### ISSUE THREAD

**Issue by lostsquirrel1** [beyond-all-reason/spring#1695]
Reported by Rippsy on Discord.

https://cdn.discordapp.com/attachments/1285715959193010196/1285715961759928523/Spring_2024.09.17_-_22.34.06.05.mp4?ex=66f3d98c&is=66f2880c&hm=777ec40390362eadc1d6b67e1edde2cd3464fc7ec0aefbcef71d34274ae586e3&

Replay available at: https://www.beyondallreason.info/replays?gameId=3ff1e966d5780a3efa160d326c76f410

About 16:28 into the match here:

![image](https://github.com/user-attachments/assets/e365c449-c3c8-4300-9731-8fb63367341c)

**Comment by lostsquirrel1** [comment]
I see what is going on here. The factory seems to issue two move orders to the ticks coming out. The first point is technically unreachable - you can see the first path has a yellow part to the path. The unit gives up trying to reach it and moves onto the next part of the path. I don't know what is deciding that the first move goal should be so close to the energy converter - is that a game side widget?

**Comment by lostsquirrel1** [comment]
Okay. Closing this ticket for now. If someone wants to reopen it with more information and whether it is an engine problem rather than a game-side problem, then feel free.

**Comment by loveridge** [comment]
> I see what is going on here. The factory seems to issue two move orders to the ticks coming out. The first point is technically unreachable - you can see the first path has a yellow part to the path. The unit gives up trying to reach it and moves onto the next part of the path. I don't know what is deciding that the first move goal should be so close to the energy converter - is that a game side widget? If that first move target wasn't there then the unit be able to exhibit this behaviour.

The engine inserts a move command when units are first created. https://github.com/beyond-all-reason/spring/issues/1538
