### ISSUE TITLE
incorrect direction for enemy buildings that are out of LoS (ghosted unitshape)

### ISSUE THREAD

**Issue by Ruwetuin** [beyond-all-reason/spring#170]

**Comment by Ruwetuin** [comment]
![screen01486](https://user-images.githubusercontent.com/11016921/149829710-7d535a5b-85b3-4728-82c2-db209a52c26f.jpg)
![screen01487](https://user-images.githubusercontent.com/11016921/149829714-44635bb9-85cb-454d-a5a9-3d8f555203d6.jpg)

**Comment by Ruwetuin** [comment]
the ghostsite widget draws unitshape for units under construction, so with this issue above makes it really apparent something is wrong for everyone now
![screen01485](https://user-images.githubusercontent.com/11016921/149829815-42b88268-24b4-4cfb-bf27-0eb6ca9d9790.jpg)

**Comment by Beherith** [comment]
Just to be clear, its not lua drawing these, right?

**Comment by Ruwetuin** [comment]
no, they still show with luaui disabled

**Comment by lhog** [comment]
Fixed
