### ISSUE TITLE
Check the "crash on model load fail" feature

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#1739]
#1724 was resolved as "no can do, missing model" but 34fa44d2b54296d258f863bd65e96d266bfdeb65 was supposed to prevent that and crash at initialisation if a model fails to load. I guess the assert just gets compiled out and does nothing in release builds?

**Comment by saurtron** [comment]
Seems like this is controlled with the NDEBUG flag.

Not totally sure about how the release binaries are compiled, but the flag is most probably set for release builds. To bail out in standard operation a different mechanism should be used.

as seen in different places through the project, guess NDEBUG is standard for release builds:

* [main CMakeLists.txt](https://github.com/beyond-all-reason/spring/blob/master/CMakeLists.txt#L488)
* [tools/dirchange/dirchange.vcproj](https://github.com/beyond-all-reason/spring/blob/master/tools/dirchange/dirchange.vcproj#L69)
* [rts/build/cmake/OverrideFlags.cmake](https://github.com/beyond-all-reason/spring/blob/master/rts/build/cmake/OverrideFlags.cmake#L19)
* [docker-build-v2/scripts/configure.sh](https://github.com/beyond-all-reason/spring/blob/master/docker-build-v2/scripts/configure.sh)

**Comment by lhog** [comment]
Yep every assert() is a noop in the release code.
That said I need to double-check how good this code works and possibly change that assert to a terminal error.
