### ISSUE TITLE
Investigate CEGs "leak"

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#18]
https://www.youtube.com/watch?v=6FVCGRglnPY

**Comment by icexuick** [comment]
This could/might be fixed since rocket(smoke)trails are now properly calculated.

See: https://github.com/beyond-all-reason/spring/commit/c0e13bcaac1d8343525190c96a36c7779898a390

**Comment by lhog** [comment]
Closing for now. Let's reopen if leak pops up again
