### ISSUE TITLE
Units under construction no longer have radar icons (798)

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#180]
They are supposed to have radar icons.

![image](https://user-images.githubusercontent.com/1318249/150629893-75c297c3-558d-4b47-ac3f-49266219eba0.png)
![image](https://user-images.githubusercontent.com/1318249/150629896-0f45cf5c-5dc7-4c49-ba52-1bd18ad883a0.png)

**Comment by lhog** [comment]
Fixed here https://github.com/beyond-all-reason/spring/commit/f89899b9f69049c66e347bdfb80ae5fe45d13a23

+ Made callouts to get/set icons rendering. Currently they can only turn off an icon that otherwise would be displayed, but can't force model rendering instead. Let me know if it's not desired.
