### ISSUE TITLE
Player reports 5-10 minute loading time, white units after some point midgame.

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#182]
[infolog(11).txt](https://github.com/beyond-all-reason/spring/files/7918440/infolog.11.txt)

**Comment by lhog** [comment]
This is Atom CPU from 2014: https://www.intel.com/content/www/us/en/products/sku/82105/intel-pentium-processor-n3540-2m-cache-up-to-2-66-ghz/specifications.html
It's hard to expect perf wonders here.

Slow by itself + nominal GPU. From formal point of view we're compatible even to such machines, but increased VRAM consumption might give such effects. 

Please ask this guy to either put `DebugGL = 1` in springsettings.cfg or issue `/debuggl 1` in game console (Debug context is now enabled permanently).
