### ISSUE TITLE
Resources utilization bug?

### ISSUE THREAD

**Issue by R4nd0m0** [beyond-all-reason/spring#1827]
| 
While spectating the whole game under heavy load (see screenshots below), i checked how the cpu is used and got surprised.
Is this common or is there something wrong how the engine uses the cores and it's threads?
|
sys spec: (ubuntu 24.04.1 lts)
dell precision t1650
e3-1280v2
4x4gb 1600mhz ram
Asrock A380 Challenger ITX 6GB OC
|
![tt](https://github.com/user-attachments/assets/f345ee12-a52b-48e5-8ab6-2fb744a72ae3)
![ttt](https://github.com/user-attachments/assets/3f563d71-fa5d-4072-8a71-51a1eb54ed8d)

**Comment by p2004a** [comment]
> how the cpu is used and got surprised.

What is surprising?

**Comment by R4nd0m0** [comment]
For me, why it uses (mainly) one thread only?

**Comment by p2004a** [comment]
Large parts of execution and game simulation are single threaded, some subset of functions like path finding are multi threaded.

There isn't anything wrong here, multi threading isn't magic that you can just do always without consequences. Maybe over time we will manage to parallelize more and more pieces but heavy single core issue is expected.
