### ISSUE TITLE
10 FPS at the start of the game

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#185]
Infolog https://github.com/ZeroK-RTS/CrashReports/issues/52407

debug

![image](https://user-images.githubusercontent.com/1318249/150642916-b8a9894a-6011-46de-a94b-0386b33038c6.png)

Apparently it's fine in some games from the start, but not in most.

**Comment by lhog** [comment]
Also `DebugGL = 1` in springsettings.cfg and then another infolog report.

Could be same as in https://github.com/beyond-all-reason/spring/issues/182:
`GPU memory  : 1024MB (total) / 692MB (available)`

**Comment by GoogleFrog** [comment]
Here it is https://github.com/ZeroK-RTS/CrashReports/issues/52431

**Comment by lhog** [comment]
No obvious OOM VRAM issues are reported. Could he run better on 104.x? The springsettings configuration is leaning towards higher end:
```
[t=00:00:00.030000]   ShadowMapSize = 8192
[t=00:00:00.030000]   Shadows = 1
[t=00:00:00.029000]   AllowDeferredMapRendering = 1
[t=00:00:00.029000]   AllowDeferredModelRendering = 1
[t=00:00:00.029000]   MSAALevel = 8
[t=00:00:00.029000]   MaxParticles = 25000
```

For now It's advisable to try a few things:
* springsettings.cfg: `ForceDisablePersistentMapping = 1` run, test, remove
* game console issue pair of commands. Test and remember each one
  * `/unitdrawer 3 0` and  `/featuredrawer 3 0`
  * `/unitdrawer 2 0` and  `/featuredrawer 2 0`

Also for the sake ruling out VRAM OOM issue to play with `/shadow 0` `/shadow 1` or with ``/shadow 1 2048` ` `/shadow 1 8192` and see if changes anything.

**Comment by lhog** [comment]
> [ffc] — 02/09/2022
I forgot to speak about this, but I did figure out that I just didn't know how to update drivers, and finally doing that fixed it. But bar works way better than zk, actually getting up to 60 fps when nothing is happening and just runs much smoother in general
