### ISSUE TITLE
Reports of white models (798)

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#186]
![image](https://user-images.githubusercontent.com/1318249/150643212-89e78e46-9dcb-4bf9-b519-e4f165114349.png)

Here is an infolog from the player, but unfortunately on a different engine version for now https://github.com/ZeroK-RTS/CrashReports/issues/51753

![image](https://user-images.githubusercontent.com/1318249/150643298-7141cf65-2982-42f3-9658-b3ece60f37f7.png)

**Comment by lhog** [comment]
Probably fixed. Reopen if not.
