### ISSUE TITLE
Unit icons missing on bottom half of minimap

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#188]
![image](https://user-images.githubusercontent.com/1318249/150646897-6c7f92fd-392e-47d9-85d2-44dcd617720d.png)

Apparently it happened ingame and in the replay.
[infolog(13).txt](https://github.com/beyond-all-reason/spring/files/7918718/infolog.13.txt)

**Comment by lhog** [comment]
Does it look same with `/luaui disable` ?

**Comment by lhog** [comment]
Also please attach the replay if it happens to reproduce the issue.

**Comment by lhog** [comment]
https://github.com/beyond-all-reason/spring/commit/a12f8b02c6f29559282883456d6f5dd61a69804c should fix it
