### ISSUE TITLE
Crash without infolog (798)

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#190]
I have a report of a crash without writing an infolog https://github.com/ZeroK-RTS/CrashReports/issues/52628

Usually I assume these are download or first start problems, but the player contacted me and it seems to be constant.

![image](https://user-images.githubusercontent.com/1318249/150670191-793f8c9f-dbcf-4a1e-a3f1-4294e51f47bd.png)

**Comment by GoogleFrog** [comment]
I think launching spring.exe directly gives him this:

![image](https://user-images.githubusercontent.com/1318249/150670565-21bb4d32-d386-420f-bd81-1c1bcb7fdae9.png)

#184

**Comment by GoogleFrog** [comment]
[20220122032958_infolog.txt](https://github.com/beyond-all-reason/spring/files/7920186/20220122032958_infolog.txt)

Here is a log from the player.

**Comment by lhog** [comment]
Is it still related to vcruntime140?

**Comment by GoogleFrog** [comment]
Sounds like it.

**Comment by lhog** [comment]
The current release will hopefully rectify it. MSVC libs were removed and replaced with mingw counterparts
