### ISSUE TITLE
TKPFS processes terrain changes very slowly

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#193]
The new pathfinder seems to process blocking changes 16x slower than the old one. Here is a comparison on a 10x10 random map. The entire map is repathed at the start (a different issue) and the last blocks to be processed are in the top left. I just screenshot the time and blocks remaining.

Old:
![image](https://user-images.githubusercontent.com/1318249/150887998-cce75bdb-061c-486a-82d6-f84a1d35e2e2.png)

New:
![image](https://user-images.githubusercontent.com/1318249/150889066-34cb59f2-dc6b-46fd-b2c3-8afb3bda574c.png)

I'm aware that this test case is itself a bug, and that random maps should not even need to repath after the game starts. It just makes a good test case for now.

Here is a real game on an 8x8 map. The map was mostly yellow throughout the whole game.
![image](https://user-images.githubusercontent.com/1318249/150889896-9ed2af98-bbe7-4e1d-a719-fb7ee213f271.png)

I am sure this slow rate will cause issues at some point. It should at least be configurable.

**Comment by GoogleFrog** [comment]
Zero-K has
```
	pathFinderUpdateRate = 0.0000001,
	pathFinderRawDistMult = 100000,
```
under system in modrules.

**Comment by marcushutchings** [comment]
Fix applied to latest BAR105.
