### ISSUE TITLE
Pathfinder does not instantly update changes that happen before the game starts

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#194]
The pathfinder used to somehow instantly take changes to the map that happen while loading luarules into account. It no longer does so. This breaks random maps:

![image](https://user-images.githubusercontent.com/1318249/150891240-a4c2b8a0-d8ab-4c1c-9b60-aee05c44c277.png)

![image](https://user-images.githubusercontent.com/1318249/150891313-f5e9b65f-6847-40ec-b590-219276c3d71a.png)

It also causes maps that use any sort of feature-placement lua initialise full of repath requests, which is going to break things later in the game.

![image](https://user-images.githubusercontent.com/1318249/150891438-1b59c7b0-3f06-42f0-aad4-b15d3e5834e1.png)

https://zero-k.info/Maps/Detail/61184
https://zero-k.info/Maps/Detail/59190

**Comment by GoogleFrog** [comment]
There is no difference between pathfinder 0 and 2 for this bug, but the update speed after the game starts is different.

**Comment by marcushutchings** [comment]
This was caused by save/load changes. I've added extra step during game load to apply any map updates prior to player deployment.

**Comment by marcushutchings** [comment]
Fix applied (for TKPFS) to latest BAR105.

**Comment by marcushutchings** [comment]
Fix applied (for HAPFS).

**Comment by marcushutchings** [comment]
QTPFS seems fine.
