### ISSUE TITLE
BAR Crashes on wayland when SDL_VIDEODRIVER=wayland is set

### ISSUE THREAD

**Issue by HellToupee1** [beyond-all-reason/spring#199]
BAR crashes with SDL_VIDEODRIVER=wayland set, it crashes before it loads the lobby, and without lobby it will bring up the spring menu but when loading a map will crash after loading water. Only affects those who set SDL video driver to wayland but SDL2 looks to soon prefer wayland over x11.

[barchobby.log](https://github.com/beyond-all-reason/spring/files/7946456/barchobby.log)
[barnomenu.log](https://github.com/beyond-all-reason/spring/files/7946459/barnomenu.log)

DIstro: Arch
NVIDIA GeForce RTX 3070 driver: 510.39.01 
Tried with kwin_wayland and sway

**Comment by lhog** [comment]
Yes, known issue, we have a volunteer making wayland backend.
If you have some wayland experience you are welcome to join the effort.

**Comment by HellToupee1** [comment]
No experience with wayland or C unfortunately, so don't really know what im doing but i did manage to get it working by commenting out this block of code. 

`// resize images
	for (XcursorImage*& ci: cimages)
		resizeImage(ci, squaresize, squaresize);

	XcursorImages* cis = XcursorImagesCreate(cimages.size());
	cis->nimage = cimages.size();

	for (size_t i = 0; i < cimages.size(); ++i) {
		XcursorImage* ci = cimages[i];
		ci->xhot = (hotSpot == CMouseCursor::TopLeft) ? 0 : xmaxsize / 2;
		ci->yhot = (hotSpot == CMouseCursor::TopLeft) ? 0 : ymaxsize / 2;
		cis->images[i] = ci;
	}

	SDL_SysWMinfo info;
	SDL_VERSION(&info.version);
	if (!SDL_GetWindowWMInfo(globalRendering->GetWindow(0), &info)) {
		LOG_L(L_ERROR, "SDL error: can't get X11 window info");
		XcursorImagesDestroy(cis);
		cimages.clear();
		return;
	}

	cursor = XcursorImagesLoadCursor(info.info.x11.display, cis);
	XcursorImagesDestroy(cis);
	cimages.clear();`

**Comment by lhog** [comment]
@badosu you've got the second customer.

**Comment by badosu** [comment]
Ok, so I assume he's not using hardware rendering.

For compatibility purposes, until this is fixed, we can just disable hwcursor when backend is wayland.

**Comment by lhog** [comment]
Better put together fully fledged backend selection infrastructure and then in WL backend put HW Cursor items as TODO/stub

**Comment by badosu** [comment]
> Better put together fully fledged backend selection infrastructure and then in WL backend put HW Cursor items as TODO/stub

What do you mean by backend selection?

We can only check if SDL is using wayland or not at runtime and run this condition on all overloads of HWCursor, or is there another way?
