### ISSUE TITLE
Tiny ghost structure radar icon

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#201]
I noticed this happen in a game.

![image](https://user-images.githubusercontent.com/1318249/151273735-f8641960-1b94-4982-8890-fea2c36de1d3.png)

The radar icon was very small for the airplane plant. It should be about the size of the pink hovercraft factory below. The size difference persists when zooming out.

When the airplane plant entered LOS, it's icon reset to the correct size.

![image](https://user-images.githubusercontent.com/1318249/151273844-88aad5e8-b77c-408b-a326-3a6b04dbcbe0.png)

I tried to reproduce it locally but have no idea how.

[20220127_002134_Tangerine_105.1.1-822-ga2f88fe BAR105.sdfz.txt](https://github.com/beyond-all-reason/spring/files/7946758/20220127_002134_Tangerine_105.1.1-822-ga2f88fe.BAR105.sdfz.txt)

This replay possibly reproduces the issue if watched without full spec LOS.

**Comment by lhog** [comment]
Maybe fixed here: https://github.com/beyond-all-reason/spring/commit/eff2882c22459284f871fe84b4513a95ef60a4a1
I didn't find exact reason, but cleaned up the code and made icons data stem from one source of truth. More or less.

This needs testing.

**Comment by lhog** [comment]
Reopen if something weird happens with icons again.
