### ISSUE TITLE
Tank treads and other similar pieces disappear after some time

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#202]
https://github.com/ZeroK-RTS/Zero-K/issues/4610

**Comment by sprunk** [comment]
These look like pieces that get `Hide` called on them, but then `Show` afterwards.

**Comment by lhog** [comment]
Usually tank threads were done via UV manipulation in custom unit shader. Does ZK rotate threads in any other way?

**Comment by Beherith** [comment]
I think ZK does it by having multiple pieces of treads with different offsets, and show-hide cycling them. Only BAR uses CUS treads (as they are very heavily UV map dependant)

**Comment by sprunk** [comment]
Yes, ZK animates treads by just having 4 overlapping pieces and iterating over them with Show/Hide. Same story with the airfac pad.

**Comment by lhog** [comment]
Unsure what was wrong, but https://github.com/beyond-all-reason/spring/commit/085299e24cf4d63c51f05568d2ee72986c8ca372 seems to fix it.
