### ISSUE TITLE
Window lobby and fullscreen game becomes progressively flatter from game to game

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#203]
Chobby saves the location of the window when the game is launched into fullscreen, so that the window can be set back to the old size when the game ends. This worked in maintenance but has broken with the BAR engine. Each cycle causes the window to be slightly flatter than the last. I suspect that chobby is reading the height of the drawable part of the window, but when setting the height spring interprets it as including the taskbar. So reading then setting the same number causes the window to be smaller.

This is more of a note-stage ticket at the moment. I'm sure I could hack something into the lobby but I don't want to hardcode the width of the top of the window border. This could be rolled into the general TODO of improving display handling.

**Comment by lhog** [comment]
Does it just read springsettings params (pos, size) before switching to fullscreen and set them back afterwards?

**Comment by GoogleFrog** [comment]
It reads window geometry.
```
local function SaveWindowPos(width, height, x, y)
	local Configuration = WG.Chobby.Configuration

	if not width then
		width, height, x, y = Spring.GetViewGeometry()
	end
	local screenX, screenY = Spring.GetScreenGeometry()
	y = screenY - height - y

	if x then
		Configuration:SetConfigValue("window_WindowPosX", x)
	end
	if y then
		Configuration:SetConfigValue("window_WindowPosY", y)
	end
	if width then
		Configuration:SetConfigValue("window_XResolutionWindowed", width)
	end
	if height then
		Configuration:SetConfigValue("window_YResolutionWindowed", height)
	end

	-- WindowState is not saved by Spring. See https://springrts.com/mantis/view.php?id=5624
	Spring.SetConfigInt("WindowState", (x == 0 and 1) or 0, false)
end
```

**Comment by lhog** [comment]
Should be fixed, please verify.
