### ISSUE TITLE
Support for high precision textures

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#207]
Current image loader is only capable of loading textures with low precision like 8 bit per channel, which may not be enough for many tasks, for example, loading quality HDRI environment map.
Suggestion is to enable lossless loading of image formats like _.hdr_, _EXR_ or _TIFF_ with at least 16-bit floating point precision.

**Comment by Krogoth100** [comment]
After learning more about formats, removed mentions of .hdr and png. Either EXR or TIFF is more important as more precise and straightforward.

**Comment by lhog** [comment]
Please test: use Docker build (see wiki) to compile.
https://github.com/beyond-all-reason/spring/pull/213/files

In theory I also enabled EXR, but practically I won't be surprised DevIL would need to be recompiled with EXR enabled.

I had issues with the current version of widget not showing up in `DrawScreenEffects()` something in BAR was apparently overwriting my pic, so I had to put it where it's now:

```
function widget:GetInfo()
	return {
		name = "HDR",
		enabled = false,
	}
end

local vsSrc = [[
#version 150 compatibility
#line 1010
void main() {
	gl_Position    = gl_Vertex;
	gl_TexCoord[0] = gl_MultiTexCoord0;
}
]]

local fsSrc = [[
#version 150 compatibility
#line 2019

uniform sampler2D tex;

void main() {
	vec4 col = texture(tex, gl_TexCoord[0].xy);
	//gl_FragColor = vec4(vec3(any(greaterThan(col.rgb * 1.0, vec3(1.0)))), 1.0);
	//gl_FragColor = vec4((col.rgb), 1.0);
	gl_FragColor = vec4(col);
	gl_FragColor = vec4(greaterThan(col, vec4(1.0)));
}
]]

local shader
function widget:Initialize()
	shader = gl.CreateShader({
		vertex   = vsSrc,
		fragment = fsSrc,
		uniformInt = {
			tex = 0,
		},
	})
	Spring.Echo(gl.GetShaderLog())
end

function widget:Shutdown()
	gl.DeleteShader(shader)
end

--[[now insert this on DrawScreen:]]
function widget:DrawScreenPost()
	gl.Blending(false)
	gl.UseShader(shader)
	--gl.TextureInfo(":l:bitmaps/Krogoth/dome.hdr")
	gl.Texture(0, ":l:bitmaps/Krogoth/dome.hdr")
	--gl.Texture(0, "bitmaps/logo.png")
	gl.TexRect(-1, -1, 1, 1)
	gl.Texture(0, false)
	gl.Blending(true)
end
```

**Comment by lhog** [comment]
I merged the branch. Report bugs, if any.
