### ISSUE TITLE
Change effect of named texture 'c' opt to CLAMP_TO_EDGE

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#208]
1. *New*
Suggest to change 'c' opt for gl.Texture(..) from GL_CLAMP to GL_CLAMP_TO_EDGE because the latter, at least in my experience, is generally superior and more commonly used. If I am not mistaken, GL_CLAMP is also deprecated for pretty much that reason.
2. (Old post:)
Currently existing clamping opt 'c' (_gl.Texture(":c:$PATH")_) enables clamping in both directions.
In some cases, for example, long-lat texture of environment, the texture should remain repeated by _x_ coordinate while clamped by _y_.
Suggestion is to extend clamping options with "_cx_" and "_cy_" to allow clamping in only 1 direction.

**Comment by lhog** [comment]
`gl.Texture` is already doing way too much. Especially in the domain of `:opt:`, where half of the options are already redundant.
I think I'm gonna leave `gl.Texture` as is and add a few separate calls doing one particular task well.

**Comment by Krogoth100** [comment]
Sure, any interface would do

**Comment by lhog** [comment]
TODO: Harmonize `LuaTextures::Texture` and `CNamedTextures::TexInfo` to enable this through gl.ChangeTextureParams()
