### ISSUE TITLE
harvestStorage unitDef can't be read

### ISSUE THREAD

**Issue by MaDDoXbr** [beyond-all-reason/spring#209]
The harvestStorage unitDef implementation is unfinished, it can be set in UnitDefs but it can't be read in-game.

**Suggestion:**
Update it to _harvestMetalStorage_ and _harvestEnergyStorage_ instead, also update **Spring.Get/SetUnitHarvestStorage** to take a resource parameter to be able to set/read the metal and energy resources separately. 
Eg.: Spring.SetUnitHarvestStorage( unitID, 300, "m")

**Comment by lhog** [comment]
https://github.com/beyond-all-reason/spring/commit/871465f5f40bdfe8ea2a7af0c5a49290267cf339 will probably do.

As far as `Spring.SetUnitHarvestStorage()` it doesn't work like wiki says. Instead it can be invoked as following:
`Spring.SetUnitHarvestStorage(unitID, <currStoredMetal>, <metalStorageCapacity>,<currStoredEnergy>, <energyStorageCapacity>)`, which I think covers your needs. Pass `nil` where you don't want change to happen.

Reopen in case it won't work.
