### ISSUE TITLE
Area repair - repair target selection tweak 

### ISSUE THREAD

**Issue by PtaQQ** [beyond-all-reason/spring#211]
I would like to ask if someone could look at area commands code, particularly at area repair command. There is an annoying issue with it that sometimes when you issue the area reclaim it wants to start from the furthest (most north-west?) unit within the selected circle
this means that if you make a big area repair command the repairers will have to run a lot to the first unit, wasting a lot of time and moving in undesirable direction 
instead of doing the most efficient thing which is starting from the closest unit and going outwards
area reclaim already works this way, is there any reason for repair to not follow the same logic?

**Comment by lhog** [comment]
The function responsible for repair targets selection is several pages long and it takes into account tons of circumstances.
https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Sim/Units/CommandAI/BuilderCAI.cpp#L1725-L1835
Distance to the target is one of the criteria, not the topmost though.

Can you screenshot some example with textual description of important aspects, like ally or not, moving or not, same class or not, etc.

**Comment by lhog** [comment]
Last bump before I close it.
