### ISSUE TITLE
Waypoint limit for Spring.DrawUnitCommands

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#212]
Extend the callout to Spring.DrawUnitCommands(unitID[,n]), where setting n tells the engine to only draw the first n commands. This can be used by lua to protect against queue-spam lagout by allies.

**Comment by lhog** [comment]
Test and report/reopen if it won't work.
P.S. The limit is same for all types of the units (Units, Constructors, Fabrics, etc). Given DrawUnitCommands can operate on arrays, I'm not even sure how to make it distinct for different types of units.
