### ISSUE TITLE
Tracescreenray behaves different when enemy

### ISSUE THREAD

**Issue by Ruwetuin** [beyond-all-reason/spring#214]
see: https://www.youtube.com/watch?v=oHB4Cciyv4s

**Comment by Beherith** [comment]
Could be related to: https://github.com/beyond-all-reason/spring/issues/42

**Comment by Beherith** [comment]
@Ruwetuin , have you seen this return since Ivand's fixes to TraceScreenRay?

**Comment by lhog** [comment]
Let's consider fixed, unless told otherwise.
