### ISSUE TITLE
Structures become nonblocking after loading a saved game

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#215]
After loading a saved game, everything seems to work except that buildings that that were built pre-save become non-blocking. This has been an issue for a while, any tips on how to test wether its the game causeing this? 

105.1.1-860-g3b57a8b bar

![image](https://user-images.githubusercontent.com/109391/153065500-6c2c7299-8e5f-4f32-bb78-4690c7476fb8.png)

**Comment by Beherith** [comment]
![screen00018](https://user-images.githubusercontent.com/109391/153065591-fc3fd7cc-5269-40ab-ad1f-3f724888a50c.jpg)

**Comment by lhog** [comment]
Attn: @ashdnazg in case you have some spare time to have a look

**Comment by lhog** [comment]
Probably fixed in https://github.com/beyond-all-reason/spring/commit/e8bf8a965859427bcf5746b897ff3183c1ab9bfb
Huge kudos to hokomoko, who found the issue in a matter of seconds.
