### ISSUE TITLE
Crash in libcurl.ddl

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#220]
Trace doesnt help much:

```
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll 0x000000000000ee2c ??:0
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll 0x0000000000059c3b ??:0
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll 0x0000000000058995 ??:0
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll 0x0000000000016879 ??:0
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll 0x000000000002c43e ??:0
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll 0x000000000002d6e9 ??:0
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll 0x000000000002e7c3 ??:0
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll 0x0000000000024970 ??:0
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe 0x000000013f4b8453 /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/bits/basic_string.h:195
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe 0x000000013f4b8e7f /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/future:257
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe 0x000000013fb3b19b /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/future:575
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe 0x000000013fc48f76 strsafe.c:1
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe 0x000000013f995690 thread.c:1
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe 0x000000013fc3e7d5 /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/mutex:783
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe 0x000000013f4b4d52 /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/future:413
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe 0x000000013fc49181 strsafe.c:1
C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe 0x000000013f99706d thread.c:1
C:\Windows\system32\msvcrt.dll 0x00000000000042bf ??:0
C:\Windows\system32\msvcrt.dll 0x0000000000007459 ??:0
C:\Windows\system32\kernel32.dll 0x000000000001556d ??:0
C:\Windows\SYSTEM32\ntdll.dll 0x000000000005385d ??:0
```

https://server2.beyondallreason.info/teiserver/reports/infolog/832

**Comment by Beherith** [comment]
Full infolog:

[t=00:00:00.051003] [DataDirLocater::FindWriteableDataDir] using writeable data-directory "C:\Beyond-All-Reason\data\"
[t=00:00:00.051003] Using writeable configuration source: "C:\Beyond-All-Reason\data\springsettings.cfg"
[t=00:00:00.051003] Using additional read-only configuration source: "C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\springsettings.cfg"
[t=00:00:00.051003] LogOutput initialized. Logging to C:\Beyond-All-Reason\data\infolog.txt
[t=00:00:00.051003] ============== <Log Sections ([A]vailable, [E]nabled)> ==============
[t=00:00:00.052003]   
    [A] ArchiveScanner
    [A] AutohostInterface
    [A] BumpWater
    [A] CSMFGroundTextures
    [A] CregSerializer
    [A] DecalsDrawerGL4
    [A] DynWater
    [A] FarTextureHandler
    [A] Font
    [A] GameServer
    [A] GroundMoveType
    [A] KeyBindings
    [A] LuaSocket
    [A] Model
    [A] Net
    [A] Path
    [A] Piece
    [A] RoamMeshDrawer
    [A] Shader
    [A] SkyBox
    [A] Sound
    [A] Texture
    [A] VFS
    [E] Sound (Notice)
    [E] VFS (Info)
[t=00:00:00.052003]   
[t=00:00:00.052003]   Enable or disable log sections using the LogSections configuration key
[t=00:00:00.052003]   or the SPRING_LOG_SECTIONS environment variable (both comma separated).
[t=00:00:00.052003]   Use "none" to disable the default log sections.
[t=00:00:00.052003] ============== </Log Sections> ==============
[t=00:00:00.052003] ============== <User Config> ==============
[t=00:00:00.052003]   AllowDeferredMapRendering = 1
[t=00:00:00.052003]   AllowDeferredModelRendering = 1
[t=00:00:00.052003]   BumpWaterAnisotropy = 2
[t=00:00:00.052003]   BumpWaterBlurReflection = 1
[t=00:00:00.052003]   BumpWaterDepthBits = 32
[t=00:00:00.052003]   BumpWaterReflection = 2
[t=00:00:00.052003]   BumpWaterTexSizeReflection = 128
[t=00:00:00.052003]   CamFreeScrollSpeed = 1000
[t=00:00:00.052003]   CamMode = 1
[t=00:00:00.052003]   CamSpringScrollSpeed = 20
[t=00:00:00.052003]   CrossAlpha = 0
[t=00:00:00.052003]   CubeTexGenerateMipMaps = 1
[t=00:00:00.052003]   CubeTexSizeReflection = 1024
[t=00:00:00.052003]   DualScreenMiniMapOnLeft = 1
[t=00:00:00.052003]   EdgeMoveDynamic = 0
[t=00:00:00.052003]   EdgeMoveWidth = 0.01
[t=00:00:00.052003]   FPSFOV = 90
[t=00:00:00.052003]   FPSScrollSpeed = 20
[t=00:00:00.052003]   FeatureDrawDistance = 600000
[t=00:00:00.052003]   FeatureFadeDistance = 600000
[t=00:00:00.052003]   FontFile = FreeSansBold.otf
[t=00:00:00.052003]   FontOutlineWeight = 2
[t=00:00:00.052003]   Fullscreen = 0
[t=00:00:00.052003]   GrassDetail = 0
[t=00:00:00.052003]   GroundDecals = 2
[t=00:00:00.052003]   GroundDetail = 150
[t=00:00:00.052003]   GroundScarAlphaFade = 1
[t=00:00:00.053003]   HangTimeout = 30
[t=00:00:00.053003]   HardwareCursor = 1
[t=00:00:00.053003]   InitialNetworkTimeout = 0
[t=00:00:00.053003]   InputTextGeo = 0.35 0.72 0.03 0.04
[t=00:00:00.053003]   LinkIncomingMaxPacketRate = 1024
[t=00:00:00.053003]   LinkIncomingPeakBandwidth = 196608
[t=00:00:00.053003]   LinkIncomingSustainedBandwidth = 196608
[t=00:00:00.053003]   LinkOutgoingBandwidth = 196608
[t=00:00:00.053003]   LuaGarbageCollectionMemLoadMult = 2
[t=00:00:00.053003]   MSAALevel = 1
[t=00:00:00.053003]   MaxDynamicModelLights = 0
[t=00:00:00.053003]   MaxNanoParticles = 3000
[t=00:00:00.053003]   MaxParticles = 15000
[t=00:00:00.053003]   MaxSounds = 256
[t=00:00:00.053003]   MaxTextureAtlasSizeX = 8192
[t=00:00:00.053003]   MaxTextureAtlasSizeY = 8192
[t=00:00:00.053003]   MaximumTransmissionUnit = 0
[t=00:00:00.053003]   MiddleClickScrollSpeed = -0.0034
[t=00:00:00.053003]   MiniMapMarker = 0
[t=00:00:00.053003]   MouseDragScrollThreshold = 0
[t=00:00:00.053003]   NetworkLossFactor = 2
[t=00:00:00.053003]   OverheadMaxHeightFactor = 1.39999998
[t=00:00:00.053003]   OverheadScrollSpeed = 20
[t=00:00:00.053003]   ReconnectTimeout = 0
[t=00:00:00.053003]   RotOverheadScrollSpeed = 20
[t=00:00:00.053003]   RotateLogFiles = 1
[t=00:00:00.053003]   ScreenshotCounter = 10
[t=00:00:00.053003]   ScrollWheelSpeed = -20
[t=00:00:00.053003]   ShadowMapSize = 3072
[t=00:00:00.053003]   Shadows = 1
[t=00:00:00.053003]   ShowClock = 0
[t=00:00:00.053003]   ShowFPS = 1
[t=00:00:00.053003]   ShowPlayerInfo = 0
[t=00:00:00.053003]   ShowSpeed = 1
[t=00:00:00.053003]   SmallFontFile = FreeSansBold.otf
[t=00:00:00.053003]   SmallFontOutlineWeight = 2
[t=00:00:00.053003]   SmallFontOutlineWidth = 3
[t=00:00:00.053003]   SmallFontSize = 23
[t=00:00:00.053003]   SplashScreenDir = ./MenuLoadscreens
[t=00:00:00.053003]   TreeRadius = 1200
[t=00:00:00.053003]   UnitIconDist = 160
[t=00:00:00.053003]   UnitIconFadeStart = 2000
[t=00:00:00.053003]   UnitIconFadeVanish = 3000
[t=00:00:00.053003]   UnitIconScaleUI = 1.05
[t=00:00:00.053003]   UnitIconsAsUI = 1
[t=00:00:00.053003]   UnitIconsHideWithUI = 1
[t=00:00:00.053003]   UnitLodDist = 999999
[t=00:00:00.053003]   UseDistToGroundForIcons = 1.10000002
[t=00:00:00.053003]   UseLuaMemPools = 0
[t=00:00:00.053003]   UseNetMessageSmoothingBuffer = 0
[t=00:00:00.053003]   VFSCacheArchiveFiles = 0
[t=00:00:00.053003]   Water = 4
[t=00:00:00.053003]   WindowBorderless = 1
[t=00:00:00.053003]   WindowPosY = 0
[t=00:00:00.053003]   XResolutionWindowed = 1920
[t=00:00:00.053003]   YResolutionWindowed = 1080
[t=00:00:00.053003]   snd_airAbsorption = 0.05
[t=00:00:00.053003]   snd_volmaster = 152
[t=00:00:00.053003]   snd_volmusic = 10
[t=00:00:00.053003] ============== </User Config> ==============
[t=00:00:00.053003] ============== <User System> ==============
[t=00:00:00.053003]   Spring Engine Version: 105.1.1-861-ge8bf8a9 BAR105
[t=00:00:00.053003]       Build Environment: gcc libstdc++ version 20210728
[t=00:00:00.053003]        Compiler Version: gcc-11.2.0
[t=00:00:00.053003]        Operating System: Windows 7 Ultimate Edition, 64-bit (build 7601, 
[t=00:00:00.053003]         Hardware Config: AMD Ryzen 5 1600 Six-Core Processor            ; 16320MB RAM, 33663MB pagefile
[t=00:00:00.054003]        Binary Word Size: 64-bit (native)
[t=00:00:00.054003]           Process Clock: std::chrono::high_resolution_clock
[t=00:00:00.054003]      Physical CPU Cores: 6
[t=00:00:00.054003]       Logical CPU Cores: 12
[t=00:00:00.054003] ============== </User System> ==============
[t=00:00:00.054003] [good_fpu_init][STREFLOP_SSE]
[t=00:00:00.054003] 	SSE 1.0 : 1,  SSE 2.0 : 1
[t=00:00:00.054003] 	SSE 3.0 : 1, SSSE 3.0 : 1
[t=00:00:00.054003] 	SSE 4.1 : 1,  SSE 4.2 : 1
[t=00:00:00.054003] 	SSE 4.0A: 1,  SSE 5.0A: 0
[t=00:00:00.055003] [WatchDog::Install] installed (hang-timeout: 30s)
[t=00:00:00.055003] [WatchDog::RegisterThread] registering controls for thread [main]
[t=00:00:00.065004] [GL::CheckAvailableVideoModes] desktop={1920x1080x24bpp@75Hz} current={1920x1080x24bpp@75Hz}
[t=00:00:00.093006] 	Display (Monitor PnP genérico)=1 modes=86 bounds={x=0, y=0, w=1920, h=1080}
[t=00:00:00.093006] 		[ 1] 1920x1080x24bpp@75Hz
[t=00:00:00.093006] 		[ 9] 1680x1050x24bpp@75Hz
[t=00:00:00.093006] 		[13] 1600x900x24bpp@75Hz
[t=00:00:00.093006] 		[17] 1440x900x24bpp@75Hz
[t=00:00:00.093006] 		[21] 1400x1050x24bpp@75Hz
[t=00:00:00.093006] 		[25] 1366x768x24bpp@75Hz
[t=00:00:00.093006] 		[29] 1280x1024x24bpp@75Hz
[t=00:00:00.093006] 		[33] 1280x800x24bpp@75Hz
[t=00:00:00.093006] 		[37] 1280x720x24bpp@75Hz
[t=00:00:00.093006] 		[45] 1152x864x24bpp@75Hz
[t=00:00:00.093006] 		[51] 1024x768x24bpp@75Hz
[t=00:00:00.093006] 		[55] 800x600x24bpp@75Hz
[t=00:00:00.093006] 		[59] 720x576x24bpp@75Hz
[t=00:00:00.093006] 		[67] 720x480x24bpp@75Hz
[t=00:00:00.093006] 		[73] 720x400x24bpp@75Hz
[t=00:00:00.093006] 		[81] 640x480x24bpp@75Hz
[t=00:00:00.809047] [GR::CreateSDLWindow] using 2x anti-aliasing and 24-bit depth-buffer (PF="SDL_PIXELFORMAT_RGB888") for main window
[t=00:00:00.857049] [GR::CreateSDLWindow] using 2x anti-aliasing and 24-bit depth-buffer (PF="SDL_PIXELFORMAT_RGB888") for hidden window
[t=00:00:00.857049] [GR::SetWindowAttributes][1] cfgFullScreen=0 newRes=<1920,1080>
[t=00:00:01.945111] Error: Spring 105.1.1-861-ge8bf8a9 BAR105 has crashed.
[t=00:00:02.042117] Error: DLL information:
[t=00:00:02.042117] Error: 0x000000013f040000	spring
[t=00:00:02.042117] Error: 0x0000000077820000	ntdll
[t=00:00:02.042117] Error: 0x0000000077600000	kernel32
[t=00:00:02.042117] Error: 0x000007fefd860000	KERNELBASE
[t=00:00:02.043117] Error: 0x000007feec890000	atcuf64
[t=00:00:02.043117] Error: 0x000007feff3a0000	ADVAPI32
[t=00:00:02.043117] Error: 0x000007fefe040000	msvcrt
[t=00:00:02.043117] Error: 0x000007fefd980000	sechost
[t=00:00:02.043117] Error: 0x000007feff9e0000	RPCRT4
[t=00:00:02.043117] Error: 0x000007fed8310000	GLU32
[t=00:00:02.043117] Error: 0x000007fed8340000	OPENGL32
[t=00:00:02.043117] Error: 0x000007feff970000	GDI32
[t=00:00:02.043117] Error: 0x0000000077720000	USER32
[t=00:00:02.043117] Error: 0x000007fefe280000	LPK
[t=00:00:02.043117] Error: 0x000007fefe130000	USP10
[t=00:00:02.043117] Error: 0x000007fed8210000	DDRAW
[t=00:00:02.043117] Error: 0x000007fee3110000	DCIMAN32
[t=00:00:02.043117] Error: 0x000007fefde60000	SETUPAPI
[t=00:00:02.043117] Error: 0x000007fefd820000	CFGMGR32
[t=00:00:02.043117] Error: 0x000007fefe290000	OLEAUT32
[t=00:00:02.043117] Error: 0x000007fefe370000	ole32
[t=00:00:02.043117] Error: 0x000007fefd690000	DEVOBJ
[t=00:00:02.043117] Error: 0x000007fefc0c0000	dwmapi
[t=00:00:02.043117] Error: 0x000007feff950000	imagehlp
[t=00:00:02.043117] Error: 0x000007fefa720000	IPHLPAPI
[t=00:00:02.043117] Error: 0x000007fefddb0000	NSI
[t=00:00:02.043117] Error: 0x000007fefa710000	WINNSI
[t=00:00:02.043117] Error: 0x000007fefe570000	SHELL32
[t=00:00:02.043117] Error: 0x000007fefe200000	SHLWAPI
[t=00:00:02.043117] Error: 0x000007fefe0e0000	WS2_32
[t=00:00:02.043117] Error: 0x000000006b240000	libcurl
[t=00:00:02.043117] Error: 0x000007fefd6b0000	CRYPT32
[t=00:00:02.043117] Error: 0x000007fefd5c0000	MSASN1
[t=00:00:02.043117] Error: 0x000007feff480000	WLDAP32
[t=00:00:02.043117] Error: 0x000000006b600000	OpenAL32
[t=00:00:02.043117] Error: 0x000007fef8c90000	WINMM
[t=00:00:02.043117] Error: 0x000000006b3c0000	libvorbisfile-3
[t=00:00:02.043117] Error: 0x000000006d540000	libvorbis-0
[t=00:00:02.043117] Error: 0x0000000070680000	libogg-0
[t=00:00:02.043117] Error: 0x000007feead40000	zlib1
[t=00:00:02.043117] Error: 0x000000006a1c0000	libIL
[t=00:00:02.044117] Error: 0x000007fec6b00000	libfreetype-6
[t=00:00:02.044117] Error: 0x000007fec6ae0000	libbz2
[t=00:00:02.044117] Error: 0x000007febcf10000	libharfbuzz-0
[t=00:00:02.044117] Error: 0x000007fec6ac0000	libgcc_s_seh-1
[t=00:00:02.044117] Error: 0x000007fec6aa0000	libwinpthread-1
[t=00:00:02.044117] Error: 0x000007febf0e0000	libglib-2.0-0
[t=00:00:02.044117] Error: 0x000007fec6a80000	libintl-8
[t=00:00:02.044117] Error: 0x000007febefe0000	libiconv-2
[t=00:00:02.044117] Error: 0x000007fec6a30000	libpcre-1
[t=00:00:02.044117] Error: 0x000007fec69e0000	libpng16-16
[t=00:00:02.044117] Error: 0x000007febceb0000	libfontconfig-1
[t=00:00:02.044117] Error: 0x000007febce70000	libexpat-1
[t=00:00:02.044117] Error: 0x000000006ed80000	glew32
[t=00:00:02.044117] Error: 0x000007febcc40000	SDL2
[t=00:00:02.044117] Error: 0x000007fefdd80000	IMM32
[t=00:00:02.044117] Error: 0x000007fefd9a0000	MSCTF
[t=00:00:02.044117] Error: 0x000007fefc690000	VERSION
[t=00:00:02.044117] Error: 0x000007fee3330000	mscms
[t=00:00:02.044117] Error: 0x000007fefd5f0000	USERENV
[t=00:00:02.044117] Error: 0x000007fefd5d0000	profapi
[t=00:00:02.044117] Error: 0x000007fef58e0000	icm32
[t=00:00:02.044117] Error: 0x000007fed7f40000	atig6pxx
[t=00:00:02.044117] Error: 0x000007fefc110000	api-ms-win-core-synch-l1-2-0
[t=00:00:02.044117] Error: 0x000007feca420000	atio6axx
[t=00:00:02.044117] Error: 0x000007fee3230000	dxva2
[t=00:00:02.044117] Error: 0x000007fef8a80000	DXGIDebug
[t=00:00:02.044117] Error: 0x000007fefd610000	WINTRUST
[t=00:00:02.044117] Error: 0x000007fed3a30000	atig6txx
[t=00:00:02.044117] Error: 0x000007fed8050000	atiadlxx
[t=00:00:02.044117] Error: 0x000007fefba50000	PROPSYS
[t=00:00:02.044117] Error: 0x00000000779d0000	PSAPI
[t=00:00:02.044117] Error: 0x000007fee31e0000	pdh
[t=00:00:02.044117] Error: 0x000007fefd460000	CRYPTBASE
[t=00:00:02.044117] Error: 0x000007fefd200000	secur32
[t=00:00:02.044117] Error: 0x000007fefd3d0000	SSPICLI
[t=00:00:02.044117] Error: 0x000007fefcd50000	mswsock
[t=00:00:02.044117] Error: 0x000007fefcd40000	wship6
[t=00:00:02.044117] Error: 0x000007fefc780000	wshtcpip
[t=00:00:02.044117] Error: 0x000007fefcbd0000	DNSAPI
[t=00:00:02.044117] Error: 0x000007fef9f40000	rasadhlp
[t=00:00:02.044117] Error: 0x000007fefa5d0000	fwpuclnt
[t=00:00:02.044117] Error: 0x000007fefca00000	credssp
[t=00:00:02.044117] Error: 0x000007fefcb40000	schannel
[t=00:00:02.044117] Error: 0x000007fefc120000	dbghelp
[t=00:00:02.045117] Error: Exception: Access violation (0xc0000005)
[t=00:00:02.045117] Error: Exception Address: 0x000000006b24ee2c
[t=00:00:02.045117] Error: Stacktrace for Spring 105.1.1-861-ge8bf8a9 BAR105:
[t=00:00:02.050117] Error: 	[ProgCtr=000000006b24ee2c StackPtr=00000000128cee30 FramePtr=0000000011543b40]
[t=00:00:02.050117] Error: 	(0) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll [0x000000000000ee2c]
[t=00:00:02.050117] Error: 	(1) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll [0x0000000000059c3b]
[t=00:00:02.050117] Error: 	(2) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll [0x0000000000058995]
[t=00:00:02.050117] Error: 	(3) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll [0x0000000000016879]
[t=00:00:02.050117] Error: 	(4) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll [0x000000000002c43e]
[t=00:00:02.050117] Error: 	(5) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll [0x000000000002d6e9]
[t=00:00:02.050117] Error: 	(6) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll [0x000000000002e7c3]
[t=00:00:02.051118] Error: 	(7) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\libcurl.dll [0x0000000000024970]
[t=00:00:02.051118] Error: 	(8) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe [0x000000013f4b8453]
[t=00:00:02.051118] Error: 	(9) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe [0x000000013f4b8e7f]
[t=00:00:02.051118] Error: 	(10) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe [0x000000013fb3b19b]
[t=00:00:02.051118] Error: 	(11) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe [0x000000013fc48f76]
[t=00:00:02.051118] Error: 	(12) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe [0x000000013f995690]
[t=00:00:02.051118] Error: 	(13) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe [0x000000013fc3e7d5]
[t=00:00:02.051118] Error: 	(14) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe [0x000000013f4b4d52]
[t=00:00:02.051118] Error: 	(15) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe [0x000000013fc49181]
[t=00:00:02.051118] Error: 	(16) C:\Beyond-All-Reason\data\engine\105.1.1-861-ge8bf8a9 bar\spring.exe [0x000000013f99706d]
[t=00:00:02.051118] Error: 	(17) C:\Windows\system32\msvcrt.dll [0x00000000000042bf]
[t=00:00:02.051118] Error: 	(18) C:\Windows\system32\msvcrt.dll [0x0000000000007459]
[t=00:00:02.051118] Error: 	(19) C:\Windows\system32\kernel32.dll [0x000000000001556d]
[t=00:00:02.051118] Error: 	(20) C:\Windows\SYSTEM32\ntdll.dll [0x000000000005385d]
[t=00:00:02.070119] Error: [ExitSpringProcess] errorMsg="Spring has crashed:
  Access violation.
A stacktrace has been written to:
  C:\Beyond-All-Reason\data\infolog.txt" msgCaption="Spring: Unhandled exception" mainThread=0

**Comment by lhog** [comment]
Likely some unique circumstance. Also not likely to ever hit again as per above.
