### ISSUE TITLE
Mipmapping in gl.CreateTextureAtlas and DDS files

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#225]
The default LegacyAtlasAllocator (0) does not allow mipmapping, and will use GL_NEAREST as a filter. (maxMipMaps always 0)

This is no biggie, as QuadTreeAtlasAllocator (1) does allow it, it works, but there is something to note: (  QuadtreeAtlasAlloc::GetMaxMipMaps() seems correct with its bit shifting)

```
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, (maxMipMaps > 0) ? GL_LINEAR_MIPMAP_NEAREST : GL_NEAREST);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S,     GL_CLAMP_TO_EDGE);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T,     GL_CLAMP_TO_EDGE);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAX_LEVEL,  maxMipMaps);
	if (maxMipMaps > 0) {
		glBuildMipmaps(GL_TEXTURE_2D, GL_RGBA8, atlasSize.x, atlasSize.y, GL_RGBA, GL_UNSIGNED_BYTE, pbo.GetPtr()); //FIXME disable texcompression, PBO
	} else {
		glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, atlasSize.x, atlasSize.y, 0, GL_RGBA, GL_UNSIGNED_BYTE, pbo.GetPtr());
	}
```

This ```//FIXME disable texcompression, PBO``` could be worrisome later on.

**Comment by lhog** [comment]
This should do the trick:
https://github.com/beyond-all-reason/spring/commit/9eac44a654965061468dacf52366a5cae0ca24f4
