### ISSUE TITLE
Reloaded non-DDS textures via "/reloadtextures s3o" appear upside down

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#226]
Reloaded non-DDS textures for models via "/reloadtextures s3o" appear upside down
Tested particularly with png

**Comment by lhog** [comment]
Doesn't get y-inverted in BAR, please provide some sample for testing

**Comment by lhog** [comment]
Heh `assimp` textures are different beasts.
The reload was never tested to work with them.

**Comment by Krogoth100** [comment]
Well, documentation says for Assimp, "uses tex1 & tex2 texture system of S3O".
So I assumed, /reloadtextures s3o should take care of Assimp correctly.
Do you want me to update it as "enhancement"?
Do we need it to cover for Assimp? I myself was using only Assimp models, so current reload, as it is, is not much useful.

**Comment by lhog** [comment]
> Do we need it to cover for Assimp?

yeah we need, although "s3o" classifier is misleading then.

> Do you want me to update it as "enhancement"?

I'm on it, probably no need.

**Comment by lhog** [comment]
Have a look if it works with https://github.com/beyond-all-reason/spring/commit/be4b493f799981d9b00b8716da988b100e3e051c

https://github.com/beyond-all-reason/spring/actions/runs/1868424719

**Comment by Krogoth100** [comment]
Just tested it!
Doesn't seem to have change at all, reload looks identical to previous

**Comment by lhog** [comment]
Can you upload the whole game (possibly in PM), or send a link to github?
It takes too much time to set everything up for tests.

**Comment by Krogoth100** [comment]
(To minimize file size:)
1. Copy current BAR version and put "s3o test" tag in modinfo
2. Inject these files:
[s3otest.zip](https://github.com/beyond-all-reason/spring/files/8101952/s3otest.zip)

This will replace arm commander with collada tree model.
When reloaded, tree should stay same. What I am getting now: Alpha channel is inverted and tree is getting full team-color.
