### ISSUE TITLE
Units sometimes start sliding forward

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/spring#232]
https://www.youtube.com/watch?v=c5l9WAu14s0

[20220222_142241_Altored Divide Bar Remake 1_105.1.1-861-ge8bf8a9 BAR105.zip](https://github.com/beyond-all-reason/spring/files/8117405/20220222_142241_Altored.Divide.Bar.Remake.1_105.1.1-861-ge8bf8a9.BAR105.zip)

**Comment by marcushutchings** [comment]
@6AKU66  @Krogoth100  is this still happening? For some reason I can't seem to reproduce this issue now on BAR.

**Comment by Krogoth100** [comment]
I will be able to answer it in about a week when I move my project to the latest version and test it out properly, because it was quite a massive effect, in terms of unit count susceptible to it. Good if it's fixed.

**Comment by 6AKU66** [comment]
@marcushutchings It's still happening even on engine 1148

**Comment by marcushutchings** [comment]
Thanks for confirming. I will try harder to reproduce it!

**Comment by Krogoth100** [comment]
I can only add few observations now.
First of all, it appears a unit doesn't have to be 1x1 footprint. Same occurred with larger footprint too. Probably, less often in that case.
Secondly, units sliding have indeed very slow velocity and very small non-zero deceleration, it would probably take weeks to stop at that pace. To me, it all looks like as if unit was going to stop but the last tick of deceleration didn't click as it should: we gained both velocity and deceleration leftover.
Then I also noticed, unit's orientation (when upright=false) is not properly updated during sliding, so the front of the unit is essentially levitating when sliding down the slope. Maybe, this might help to narrow it down somehow.

**Comment by KyleAnthonyShepherd** [comment]
I was messing around with T2 arty a couple weeks ago (to try to figure out firing angle stuff), and I had some of them start drifting around on flat ground. I'll post again if I get it to replicate.

**Comment by Beherith** [comment]
Best seen when game is at 20x speed :D

**Comment by KyleAnthonyShepherd** [comment]
Still not sure how to best replicate, but moving a Mauser, armmart, seems to trigger the drifting. I have attached mp4 video of the drift, and I think I added the replay file.

(https://user-images.githubusercontent.com/44480662/189628134-0121d71c-a42c-4a11-b7a3-1b91827e24e7.mp4)
[20220912_100045_Quicksilver Remake 1_105.1.1-966-g597222f BAR105.zip](https://github.com/beyond-all-reason/spring/files/9547011/20220912_100045_Quicksilver.Remake.1_105.1.1-966-g597222f.BAR105.zip)

**Comment by Krogoth100** [comment]
> Also, pretty much every unit I tested with upright=false will slowly drift forward when on a slope. upright=true units do not appear to drift.
> 
> Spawning on a slope, or being pushed onto a slope does not result in drifting. Driving/moving onto the slope will result in the drifting behavior.

I have just tested a 2x2 footprint unit with upright=true and it does drift as well. Slope was quite small too.
Statistically probably yes, but in principle, it doesn't seem to depend on upright.

**Comment by marcushutchings** [comment]
Thanks for the information everyone. Those clues do lead me to suspect a certain area of code...

**Comment by marcushutchings** [comment]
Thanks for the information everyone. Those clues do lead me to suspect a certain area of code... 

> Still not sure how to best replicate, but moving a Mauser, armmart, seems to trigger the drifting. I have attached mp4 video of the drift, and I think I added the replay file.
> 
> (https://user-images.githubusercontent.com/44480662/189628134-0121d71c-a42c-4a11-b7a3-1b91827e24e7.mp4) [20220912_100045_Quicksilver Remake 1_105.1.1-966-g597222f BAR105.zip](https://github.com/beyond-all-reason/spring/files/9547011/20220912_100045_Quicksilver.Remake.1_105.1.1-966-g597222f.BAR105.zip)

Would you try to upload the sdfz file for that replay again, please? I was unable to use use the zip file or the file inside from that link.

**Comment by KyleAnthonyShepherd** [comment]
Github was not happy with the sdfz file, uploading to discord bug report channel

**Comment by 6AKU66** [comment]
@KyleAnthonyShepherd you can zip it in next time.

**Comment by KyleAnthonyShepherd** [comment]
Setting allowGroundUnitGravity from false to true in modrules.lua fixes the sliding forward problem.
It is not a desirable solution, due to all the other side effects that switch causes, but it narrows down the code causing the problem. 

Specifically, in GroundMoveType.cpp
CalcSpeedVectorInclGravity has a dragCoeff value
//   ensure speed-vector always decays if
//   wantedSpeed and deltaSpeed are 0
while CalcSpeedVectorExclGravity does not have any dragCoeff value to bring speeds to zero.
