### ISSUE TITLE
(Low priority) Improve missing collada file error

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#233]
Currently, if unit/feature's objectname points to non-existing collada file, it produces unclear "vector::_M_fill_insert" error, crashing Spring (one might try to figure out what is going on).
The best would be to handle this case similar to s3o and give a warning.
How to reproduce: set unit/feature's objectname = "kappa.dae" and run the game (provided you don't have "kappa.dae" file)

**Comment by lhog** [comment]
Doesn't seem to happen any longer.
If you still see it, please provide the test repo reproducing the crash and reopen.
