### ISSUE TITLE
Features dont seem to obey Spring.SetFeatureEngineDrawMask

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#240]
![image](https://user-images.githubusercontent.com/109391/160009928-2a0b8d68-8fc9-4e51-b308-3ae620b0037b.png)
Old CUS is off. Unit is correctly not drawn, while feature is drawn via engine. 

This is with latest cus-gl4 branch.

**Comment by lhog** [comment]
Hmm, the code is nearly identical for both.
Can you trace the call `SetFeatureEngineDrawMask` if it gets the feature correctly (not null)?

**Comment by Beherith** [comment]
Ok, tracing it through:
```static inline CFeature* ParseCtrlFeature(lua_State* L, const char* caller, int index)
{
	CFeature* feature = ParseRawFeature(L, caller, index);

	if (feature == nullptr)
		return nullptr;

	if (CanControlTeam(L, feature->team))
		return feature;

	return nullptr;
}```

ParseRawFeature correctly gets the feature, but CanControlTeam returns false:
```static inline bool CanControlTeam(const lua_State* L, int teamID)
{
	const int ctrlTeam = CtrlTeam(L);

	if (ctrlTeam < 0)
		return (ctrlTeam == CEventClient::AllAccessTeam);

	return (ctrlTeam == teamID);
}```
Here ctrlTeam is 0 , and teamID is 2, as I am a player. Makes sense that one cant 'control' features not on their team, but this seems to be a design issue throughout, as drawflag is unsynced and thus should not need synced permissions to be changed. 

So I looked at whether enemy units also dont get set, and the result is the same, the cus gl4 _widget_ wont set the drawflag of an enemy unit:

![image](https://user-images.githubusercontent.com/109391/160097464-73ec9751-68b4-4b00-9fe0-0d2f107bf050.png)

**Comment by Beherith** [comment]
![image](https://user-images.githubusercontent.com/109391/160097491-462330c8-b2e4-45ca-bfa5-739f529747d3.png)

**Comment by Beherith** [comment]
As a corrollary, this ParseCtrlFeature->CanControlTeam is consistently called throughout, and prevents quite a few callins from working at all, and also might be a problem for the other callins in this family for both features and units.

**Comment by lhog** [comment]
Are you doing the call from a gadget or widget?

**Comment by Beherith** [comment]
Im calling from widget, seems like i have to move to gadget

**Comment by Beherith** [comment]
moved to gadget, problem solved, thx ivand!
