### ISSUE TITLE
Remove hardcoded binds for camera controls 

### ISSUE THREAD

**Issue by PtaQQ** [beyond-all-reason/spring#241]
Please consider decoupling camera control inputs like change angle, rotate from the engine and make them bindable via uikeys. 

Link to the relevant discussion: 
https://discord.com/channels/549281623154229250/724924957074915358/956565757599305738

**Comment by badosu** [comment]
Done. Movetilt and movereset

**Comment by lhog** [comment]
Time to close?

**Comment by Beherith** [comment]
Thank you badosu for fixing a 15 year old bug :D
