### ISSUE TITLE
shadows dissapear when the camera is too close to the ground

### ISSUE THREAD

**Issue by drivver44** [beyond-all-reason/spring#242]
![screen00066](https://user-images.githubusercontent.com/75929927/160344055-fe87962f-2bce-42c0-b872-eaaa4f403869.jpg)
![screen00067](https://user-images.githubusercontent.com/75929927/160344059-072c62c3-b807-475c-be63-7496148d59d7.jpg)

**Comment by Beherith** [comment]
Duplicate of #83
