### ISSUE TITLE
(Low priority) DestroyUnit adjustment

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#243]
A small one, while I haven't forgotten
For DestroyUnit(...), allow use 5th argument (recycleID) with 4th argument (attacker) as nil.
Currently it checks it like this:
https://github.com/beyond-all-reason/spring/blob/83e80315309bc327dc8bfbecb68bf5c098e09fcb/rts/Lua/LuaSyncedCtrl.cpp#L1338
It doesn't affect functionality because a huge id value can be passed that results in a nil attacker, but it is a small inconvenience.

**Comment by lhog** [comment]
Not sure I understand the request.
You should be able to specify `Spring.DestroyUnit(unit, selfDed, reclaimed, nil, recycleID)`. Does it not work?

**Comment by Krogoth100** [comment]
I am sure it doesn't.
As I look at the code now, and I am not a Lua expert on C++ side,
this code would pass _attacker_ via ParseUnit without optional value simply judging by a number of arguments rather than this particular argument holding actual value. If I am not mistaken, I recall getting an error of a sort in this case.
The thing I had to di to make it work was passing a huge ID value that generated a nullptr from ParseUnit.

**Comment by sprunk** [comment]
Confirmed. ParseUnit expects the 4th arg not to be nil, but the `args >= 4` check doesn't protect against 4th being nil. Fix PR: #416
