### ISSUE TITLE
Units who are flying above water more than 2x as deep as their draw radius dont get reflections

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#245]
https://github.com/beyond-all-reason/spring/blob/7ef92455a04a4a5f84e6843d2eaf3273f27d62f2/rts/Rendering/Common/ModelDrawerHelpers.cpp#L27
,
Trying to decipher the old code and why it was wrong, because the new code errors out on too deep stuff. 
```	
if (objPos.y < 0.0f) // if the object is underwater
    // Then draw the object if the ground height at the object is less than the units draw radius?
    return (CGround::GetApproximateHeight(objPos.x, objPos.z, false) <= maxRadius);
    // shouldnt this be draw the object if the the water depth! (not ground height) is greater than the objects draw radius?

// try to trace the line between object and camera (which I think is 'underwater') 
const float dif = objPos.y - camPos.y; // positive if object is above the underwater camera, which is almost always the case, 

float3 zeroPos; // aha the zero pos tracing to the point on waterplane connecting camera and object
zeroPos += (camPos * ( objPos.y / dif));
zeroPos += (objPos * (-camPos.y / dif));

// if the ground height at zeropos is less than the maxradius, then there is probably a reflection (good call) 
return (CGround::GetApproximateHeight(zeroPos.x, zeroPos.z, false) <= maxRadius); 
```

So either I didnt check the math above, or the real issue is just that the first return should rather be:

```
 return ( -1.0 * CGround::GetApproximateHeight(objPos.x, objPos.z, false) <= maxRadius);
 
```
because the problem with the old code was that it almost completely prevent units getting reflecion in shallow waters?

**Comment by Beherith** [comment]
Reopening maybe someone else knows better, but the fix is committed

**Comment by lhog** [comment]
I recall scratching my head how the previously disabled code was supposed to work (and it didn't IIRC) so I put something together quickly as alternative (formerly in `#if 1`). Perhaps it was wrong in the end, if the above fix works, then fine.

Although please double-check no extra units get reflected (I recall the former implementation used to reflect fully underwater units). It'd also be great if no redundant units get submitted (i.e. the units that cannot get reflection given their position and the current camera matrix)

**Comment by Beherith** [comment]
it works now, tested (but I do clip in FS)

**Comment by Beherith** [comment]
I wasnt able to figure out gl.ClipDistance, its probably way better than discard in the fragment shader though, but ill soon figure it out

**Comment by lhog** [comment]
I think you can mostly copy prior art:

https://github.com/beyond-all-reason/spring/blob/BAR105/cont/base/springcontent/shaders/GLSL/ModelVertProgGL4.glsl#L155-L157

https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Rendering/Common/ModelDrawerState.cpp#L651-L653

**Comment by Beherith** [comment]
fixed
