### ISSUE TITLE
Shift+number should add a unit to that group

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/spring#246]
Currently the behaviour is that shift+number selects that group and adds it to the current selection, but as a player I feel this is a lot less useful than simply adding the unit to that group and selecting it.

The desired functionality for adding a unit to the group and then selecting it is ctrl+shift+number, but this is much more awkward to press, especially for higher group numbers.

I suggest swapping the current functionality of shift+ctrl+number and shift+number with each other.

https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Game/UI/Groups/GroupHandler.cpp#L71
https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Game/UI/Groups/GroupHandler.cpp#L106

Arguably these binds should all be handled at game level / uikeys, but for now I think this is place to fix it

**Comment by WatchTheFort** [comment]
That breaks the paradigm of Shift adds to selection. Is there a problem with hitting number, shift+new units, Ctrl+number?

**Comment by Jazcash** [comment]
> That breaks the paradigm of Shift adds to selection

The paradigm is kept because it would still add the units to your current selection. But even if it didn't I would bet nobody uses this functionality and is arguably less intuitive for people coming from other RTS games where shift+number typically adds the selected units to that group.

> Is there a problem with hitting number, shift+new units, Ctrl+number?

That's super awkward compared to shift+number

**Comment by badosu** [comment]
This issue should be better phrased as to define granular group actions.

Retain `groupn` for the consumers that might still use it and people migrating to byar from legacy and add:

- `group_add n`
- `group_set n`
- `group_toggle n`
- `group_select n`
- `group_merge_selection n`

Then the default keybindings would be as:

```
bind 1 group_select 1
bind Ctrl+1 group_set 1
bind Ctrl+Shift+1 group_add 1
bind Shift+1 group_merge_selection 1
bind Alt+1 group_toggle 1
```

And for @Jazcash intended behavior just swap `group_merge_selection` and `group_add` keysets

**Comment by badosu** [comment]
The change should be relatively straightforward. To define new action executors with specific `GroupCommand` calls or allowing the `"Group"` executor to parse optional arguments to have less clutter in engine code, e.g. `bind Ctr+1 group set 1`

See: https://github.com/badosu/spring/blob/e337ae1cfe4604c75d10ae8827d81a7fa14bcee8/rts/Game/UnsyncedGameCommands.cpp#L1129-L1152 for reference

**Comment by MasterBel2** [comment]
> even if it didn't I would bet nobody uses this functionality
I do! :D

I don't really play much other rts at all, but I discovered this because it's self-consistent with how Spring operates, and so I guess intuitive within that environment.
When considering other rts, tho, well…

Anyway, I was really only here to say I use it too.
