### ISSUE TITLE
MSVC support, C++17, and other things

### ISSUE THREAD

**Issue by hugoam** [beyond-all-reason/spring#25]
Hello,

I am a mainly Windows game developer interested in getting into spring development, however I'm facing a few issues trying to compile it on MSVC. I assume this is not supported, since the only docs about building for MSVC + Windows are from almost 10 years ago.

However, I'm almost getting it to work, slowly but surely. First, `vcpkg` helped me a ton in setting up the dependencies, after I was going crazy trying to install them manually, so we might write this down somewhere if another MSVC dev like me comes and wants to build it. So that helped, except for all the includes that are broken because the system is assumed to be Linux, I guess (things like ZLIB headers which are probably almost always reachable on a Linux system)

But here I'm hitting something which doesn't make sense at all. First, the standard has been explicitly set to C++17 for MSVC recently, but did someone manage to build it this way ? On my machine and with VS2019, clearly that can't possibly build. If not, it doesn't make sense to commit things like this: https://github.com/beyond-all-reason/spring/commit/ca1e0542b7e2d269ecbd511ae186a67d18431884 as it's just making things even harder for devs that are new to the codebase

Then the next, harder question, why do the CMake files even pretend to be building with C++17 ? The codebase does not seem at all to be C++17 compliant. For starters, there are tons of `random_shuffle`  which does *not* exist in C++17. How can the CMake files setup a build for C++17 when the codebase is not C++17 ? That doesn't make much sense to me currently. I guess one possible answer is that you are purposefully building with C++17 language feature, but also purposefully using an older version of the STL ? I don't even know if that can possibly work though, but only explanation I can come up with

If someone can shed light on those questions (MSVC build steps, or status, and C++17 compliance), this will probably help me get into this project that I would really like to contribute to :)

**Comment by lhog** [comment]
Thanks for your interest and I'll brief you in with a bit of history & context.

When we forked off from spring the original spring was C++11 compliant. The times when it was possible to compile it with MSVC had been long in the past. The main compiler for Windows and Linux was and still is GCC++.

Upon adding new libraries we had to upgrade to C++17. You are right that C++17 deprecated quite a bit of stuff used in spring such as unary and binary functions, random_shuffle and some other things, but GCC is lenient in this regards and it doesn't enforce their removal. MSVC in turn does. So I replaced all the deprecated std:: functions with spring:: counterparts. I'm not sure if it's in BAR branch or somewhere else but I got rid of deprecated warning as well as some of the headers being missing. Chances are high you will find this commit in BARd or BARng, so somewhere. I was sure I cherry-picked it into BAR as well, but perhaps I did not.

Anyway that alone didn't help because of a few reasons:
* x64 builds of MSVC mandate no asm inlines are possible and unfortunately spring has quite some. Back in the day I couldn't find c++ instrinsics that could do the same in place of old asm code nor the way to force the compilation with asm inlines. So for now, even in theory only x32 builds are doable.
* Previously I used to be able to compile x32 build, but it didn't link because of glew unresolved externals. I tried some manipulations to get it to link, but I was short on time and I never finished it.
* Nowadays MSVC compiler just crashes on spring code. I don't know if it's their compiler got worse over time or our code got too difficult. Nonetheless the fact stays: it crashes. So by now I have no way to fix the two above.

if you are interested in making MSVC work, be my guest. I'm quite struggling with debugging tools under GNU umbrella too. If not - you can install mingw64 on Win and be able to compile with GCC. 

In any case if you feel like it please join Discord's https://discord.gg/ehgyZgbgun #engine channel where I dwell.

**Comment by lhog** [comment]
Seems like I never cherry-picked these two into BAR branch:

https://github.com/beyond-all-reason/spring/commit/4329eac58ab9519e959a74f27947052968028f5e
https://github.com/beyond-all-reason/spring/commit/eceff296a2725f6e0f7884110951387ab5e45822

**Comment by hugoam** [comment]
Thanks for the explanation.

I indeed am making some modifications related to the issues you mentioned.
- The unary and binary functions are quite easy to solve because they are use on functors and are actually not needed there.
- The random_shuffle is a bit more annoying because Spring is probably quite strict on the way it does RNG and I don't want to mess with that, so the fix will be slightly more involved but I think I can find a solution for that too
- The compiler ICEs are the worst indeed, but they seem to happen in the lua `sol` binding code, so I have hope it's possible to get in touch with `sol` author about this, or fiddle around to see what makes the compiler crash and file an issue with MSVC

**Comment by lhog** [comment]
I think `sol` author is aware, I found the reference to MSVC compiler being stupid in one of the issues or even in the code itself. 

Maybe previous `sol` versions didn't crash the MSVC compiler but they had other bugs. In fact we use non-release version, basically master from some date, because the release version OOM'ed spring in rare circumstances. You can try your luck with newer sol or getting in touch with ThePHD, the sol author.

**Comment by lhog** [comment]
Ok, I cherry-picked commits above and updated sol locally. It no longer crashes MSVC, but there are other compilation errors. Not too difficult to fix. Go ahead :)

**Comment by lhog** [comment]
I've got it to the point it almost compiles, but 7z situation needs to be dealt with:
![image](https://user-images.githubusercontent.com/1476261/116621090-53e3a000-a94b-11eb-97bb-f30daccc3f82.png)

https://github.com/beyond-all-reason/spring/commit/1733a2c182844682a4dd57696698741d1b858464
In case you want to continue from here.

**Comment by hugoam** [comment]
Thanks ! Seems like it's only the tip of the iceberg though. I'm not exactly at which step you are or what I'm supposed to build, maybe I'm building stuff that I'm not supposed to, but for example `BARb` is full of stuff that won't compile because it's just not standard C++, like for example designated initializers, variable length arrays, __typeof__, __PRETTY_FUNCTION__ and many more things that are GCC extensions, I guess it doesn't help that this project has not been built with MSVC for so many years :)

**Comment by lhog** [comment]
Build https://github.com/beyond-all-reason/spring/tree/BAR
The rest is either feature branches or some experimental stuff.

I use these libs as `.\vclibs`: https://github.com/spring/vclibs14
I had to replace DevIL .lib and .dll with what can be found here: https://sourceforge.net/projects/openil/files/DevIL%20Windows%20SDK/1.7.8/DevIL-SDK-x86-1.7.8.zip/download?use_mirror=pilotfiber

BuildType: RelWithDebugInfo

**Comment by hugoam** [comment]
Hmmm yep but I meant inside the solution, there are so many projects, I was building the one called `spring`, but I see you're building `engine-legacy`, don't know if I was building projects that are not supposed to be built. But if `BARb` submodule is supposed to be built, there definitely seems to be some work to do there as well to make it compatible

**Comment by lhog** [comment]
Ah yes, `engine-legacy` is what you want to build. `BARb` is external AI by another developer. It's not mandatory to build.

**Comment by hugoam** [comment]
Oh, ok, then I guess CircuitAI too ? That one has a lot of non standard stuff too `__PRETTY_FUNCTION__`

**Comment by lhog** [comment]
CircuitAI is BARb sibling by the same author. No wonder they share some codebase.
You can disable all AIs (you probably should) with AI_TYPES = NONE
![image](https://user-images.githubusercontent.com/1476261/116666705-f29beb00-a9a3-11eb-905d-0d1ffcad0d30.png)

**Comment by hugoam** [comment]
I managed to get to the final link step, but I'm hitting, additionally to the 7z issue, link errors with all the symbols coming from glew, whereas the project is indeed linking `glew32d.lib` which does contain those symbols 😕 I'll look a bit more but if you've got any ideas

**Comment by lhog** [comment]
Impressive! Does it run?

**Comment by hugoam** [comment]
I didn't manage to run it yet because of the data files. It says I maybe forgot to run INSTALL but INSTALL won't work because there are tons of projects that don't build in my solution. So I tried to copy the files manually in my output folder, but it still doesn't work and did not have time to debug why. Now I'm facing another issue which is that this app is impossible to debug in MSVC, because it grabs the mouse input in a way that prevents completely to do anything after breaking the application (the mouse is completely unresponsive in Windows). I don't know if this is a MSVC bug or if something can be done with the code to fix that.

**Comment by lhog** [comment]
Yeah INSTALL is probably useless. It waits in the backlog to be improved.

You'll need to copy all dlls the game requires and minimal content the game needs.
You can see the usual distribution here: https://github.com/beyond-all-reason/spring/releases/download/spring_bar_%7BBAR%7D104.0.1-1872-g109e052/spring_bar_.BAR.104.0.1-1872-g109e052_windows-64-minimal-portable.7z
In the same time you won't need spring-dedicated, spring-headless and pr-downloader for basic run of spring.

I have seen mouse issue before, it's not specific to MSVC. You need to run the game in the window (not in full-screen).

**Comment by hugoam** [comment]
Alright. And if I want to run some BAR game to try things out, how complicated would the dev setup be ?
Also there seem to be nothing yet in https://github.com/beyond-all-reason/spring/wiki, you'd like me to create the first page ?

**Comment by Beherith** [comment]
Clone https://github.com/beyond-all-reason/Beyond-All-Reason/ into spring/games/bar.sdd and run spring.exe

**Comment by lhog** [comment]
Just foreword of warning: you are not likely to sync up with GCC builds for online games, at least it was the case before.

For standalone BAR setup (w/o lobby) it can be done pretty easy:
* you create `games` folder on the same level as `maps`
* you clone BAR git repo into `BAR.sdd` subdir under `games`
* when you launch spring you should be able to see `Beyond-All-Reason $VERSION` under "select game..." menu.
** you might need to launch spring with `SPRING_DATADIR` and `SPRING_WRITEDIR` env variable set to your spring root directory (under which `games` and `maps` exist), some people also use `-write-dir` switch for spring.exe to do same.

You can also kind of trick the official launcher by replacing the files in the currently active engine folder with your own locally built binaries. In such case launcher will launch your own built spring for you.

**Comment by Beherith** [comment]
Oh right you will also need at least one map in maps. Dl this .sd7 file and place it into /maps/, and select it when running spring.exe
https://api.springfiles.com/?type=2&filter=b87ea3be25f4e20b510da90034dc5e02

**Comment by hugoam** [comment]
Hmmm the adventure ended quick. I found a quick asserts or issues triggering on MSVC which I could fix, but now I'm hitting this:
![image](https://user-images.githubusercontent.com/9502098/116746608-09226080-a9fd-11eb-978c-7817acde332d.png)
![image](https://user-images.githubusercontent.com/9502098/116746633-15a6b900-a9fd-11eb-9d3b-76ffa08ccfe1.png)
Looks like I'm receiving some kind of command from the AI which expects to find some height in the height map which is not actually there. Am I hitting those synchronization issues already even in a solo game ?

**Comment by lhog** [comment]
Replace == with !=. This is a bug. I fixed it in one of the feature branches but not in the primary one.

**Comment by hugoam** [comment]
Oh shit, I didn't even notice that ! You're right that didn't make sense, fixing it

**Comment by lhog** [comment]
More or less implemented in-house. More to cherry pick from hokomoko's contribution on 3rd of June here https://github.com/spring/spring/commits/develop

**Comment by lhog** [comment]
Added https://github.com/beyond-all-reason/vclibs64 for MSVC64 and https://github.com/beyond-all-reason/spring/commit/4dc069157b23601c7cfa9a6f47547f95ad517051 to deal with CMake. It works.

There's still an issue with conflicting 7z symbols https://github.com/beyond-all-reason/spring/wiki/Common-MSVC-gotchas#crash-in-7zallocc-7z-linker-warnings but I'm gonna deal with it at convenient occasion.
