### ISSUE TITLE
Implement Wayland HardwareCursor

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/spring#253]
Currently Wayland can't enable HardwareCursor.

This is where the class is defined: https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Game/UI/HwMouseCursor.cpp#L178-L195

References:

- https://wayland-book.com/protocol-design/interfaces-reqs-events.html
- https://bugaevc.gitbooks.io/writing-wayland-clients/content/beyond-the-black-square/cursors.html

**Comment by dzosz** [comment]
looks interesting. is anyone else working on it?

**Comment by lhog** [comment]
No one afaik
