### ISSUE TITLE
Question: Are all drawflags final when the DrawShadowUnitsLua is called?

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#264]
In CUSGL4, drawflags are updated in DrawWorldPreUnit()
This is called after DrawShadowUnitsLua

This means that DrawShadowUnitsLua uses shadow draw flags that are 1 frame late. 

Can I safely collect all drawflags in DrawShadowUnitsLua, instead of using DrawWorldPreUnit? Are all reflection, shadow, deferred, etc flags updated and correct at that point?

**Comment by lhog** [comment]
I'm tracing a few selected calls and for me it goes like this:

`CUnitDrawerData::Update()`
`CFeatureDrawerData::Update()`
`eventHandler.DrawGenesis()`
`CUnitDrawer::DrawShadowPass()`
`eventHandler.DrawWorldPreUnit()`
`CModelDrawerBase<TDrawerData, TDrawer>::DrawImpl(bool drawReflection, bool drawRefraction) const`, which draws deferred models

`*:Update()` calls modify drawFlag of Units and Features.

Respectively the best would be hook into `eventHandler.DrawGenesis()`

**Comment by Beherith** [comment]
Ok, so when DrawGenesis is called, all the flags are correct by then?

**Comment by lhog** [comment]
They should be all set there, yes
