### ISSUE TITLE
merge sping/spring?

### ISSUE THREAD

**Issue by neoedmund** [beyond-all-reason/spring#266]
I want to clarify the attitudes of BAR developers on merging `spring/spring` source.

spring/spring is actually actively developing, now on tag `106.1` or something. 
there should be some meaningful improvements since 105.

I also noticed there is a difficulty because already `This branch is 2497 commits ahead, 2242 commits behind spring/spring:develop. `

IMO BAR being a _superset_ of spring should take benefit from the origin, in long-term.
how do you think ?

**Comment by Damgam** [comment]
BAR engine and "main" Spring engine went in completely diffrent directions in many aspects is how i understand it. GL4 implementation on their end is very diffrent iirc and completely dropped support for older OpenGL, which makes it nearly impossible to port games from 105 to 106.

**Comment by Damgam** [comment]
Not to mention that BAR engine is fork of maintenance branch which was the 104.1 that eventually evolved into 105, instead of develop branch that eventually got released as 106

**Comment by Beherith** [comment]
Upstream spring rejected merge. 

https://github.com/spring/spring/pull/559

https://github.com/spring/spring/pull/567

**Comment by neoedmund** [comment]
so I come to my own conclusions

- BAR is now the most advanced (especially in graphics) and active branch of springrts.

- BAR developers tried to make PR back to spring, but not warmly treated.

keep on BAR's devs, you are doing great. :)

**Comment by Beherith** [comment]
I think 1 is true, and it was warmly treated, just lacked the dev energy to go through with it.

**Comment by marcushutchings** [comment]
While we are not opposed to the code being pulled to spring, the release of 106 of spring just makes it improbable. Closing ticket.

**Comment by Are-s** [comment]
> 

Merge wasn't rejected. The official engine dev asked Ivand to stop moving the goal posts while he was working on the merge. Ivand kept adding more changed, blamed the official engine and then deleted the branch. 

See here: https://github.com/spring/spring/pull/559
