### ISSUE TITLE
Ships cant move after loading savegame, bisected here

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#267]
The bug where ships cannot move after loading a savegame appears first in this commit:

https://github.com/beyond-all-reason/spring/commit/a9112ac366f227b8c92df9e7a69395c440748a45

Maybe someone has an idea?

@lhog  @marcushutchings  @ashdnazg

To repro: load savegame, spawn ship, it cannot move.

**Comment by marcushutchings** [comment]
Fixed in 1e5705e015a76efc366d64bc33298ccaaf93ff40
