### ISSUE TITLE
Speed up headless

### ISSUE THREAD

**Issue by neoedmund** [beyond-all-reason/spring#271]
In headless mode, it take 13 sec to process to frame 0 and a more 4 sec to frame 1.

thing can be tuned like:

```
[LoadScreen::SetLoadMessage] text="Loading Models and Textures"
```
It seems took 4 seconds.

Models and Textures should be useless in headless mode, it's nice if it can be dropped.

**Comment by Beherith** [comment]
Models need to be loaded to find the piece offsets (as animations are synced). Loading a good 1000 units takes a bit of time. Textures are not loaded for headless.
