### ISSUE TITLE
Suggestion: Global parameter for model scale on load

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#276]
Can we have a scale parameter, applied to all Assimp models on load? It could be a global parameter like SpringSettings.cfg:_AssimpModelScale_ (I would prefer this one), or AssimpMetaFile:_scale_ (individual per model).
That should not be hard to implement, as its mostly a simple multiplier (scaling off (0,0,0) point).
The purpose for it is that it would noticeably simplify Blender > Spring workflow, because usual metric system is best to get things of right size and proportions and having auto-conversion on import is of course cleaner than handling it on each export.

A few thoughts of mine further.
The thing is, elmo should not be used as a distance measurement by dev/user, imo. It's purely internal unit of measurement, tied to map grid, pathfinding and other stuff, hardcoded in engine with constants, meanwhile a dev may choose own unit of measurement to fit their game best to required grid density/map size limit. Like, a smaller scale micro-oriented game could use half a meter per elmo for sharper collisions and pathfinding, and larger scale - 2 meter per elmo, allowing for larger map size and quicker pathfinding.

(As for COB, Scriptor program already allows such multiplier of arbitrary value)

**Comment by Beherith** [comment]
Ill actually think this is completely pointless. Spring has a single, consistent internal scale metric. Why cant blender be adjusted to suite this? Im pretty sure its easier to do this in blender than deal with the internal conversion issues. 

And hacking COB's linear constant is just... wow. dont do that.

**Comment by Krogoth100** [comment]
> Ill actually think this is completely pointless. Spring has a single, consistent internal scale metric.

I understand, that it might seem pointless to you, because you have different experience. Many things other people use seem pointless to me too.
But what you just said here, is exactly the reason for this, because internal scale metric is one thing and the one to represent perceivable size is another.
As I said, map grid size of 8 elmo and such stuff are hard-coded, therefore elmo-to-meter relation defines how dense collision/pathfinding calculations will be, related to your basic model size. You can't just scale model by X and expect it to behave same as if all stuff got scaled by X and nothing changed, except some visual indicators. No, you have to scale up your models to fit into the best <map grid size>/<map size limit>/<basic model size> combo so your game looks smooth, performs well and has considerable map size limit, falling back from actual perceivable size (meter) to internal scale metric, which has nothing to do with visual representation in the first place. Not to say that during the test stage, you have to scale up all your models to find these correct proportions, repeatedly.
This is apparently not an obvious thing for BA/BAR developers because its scaling (essentially, a missile truck of 1 screen attack range, taken 800x600 resolution) has been established since 1997 and haven't changed since.

> Im pretty sure its easier to do this in blender than deal with the internal conversion issues.
No, the benefit of this is that you don't have to do any conversions in Blender and necessary Lua shenanigans are automated and trivial.

**Comment by marcushutchings** [comment]
So for the benefit of someone who doesn't do modelling for the Spring engine: where does the modelling get tied to elmos?

**Comment by Beherith** [comment]
1 model-space unit is 1 elmo, as the models-space positions are directly what they are in-engine. 

Do you specifically have a significantly different desire for scale in the engine?

**Comment by marcushutchings** [comment]
I just wanted understand the challenges better. I'm in no place to advocate for the suggested change.

**Comment by lhog** [comment]
No feedback. Closing.
