### ISSUE TITLE
Build Java Interface for Windows

### ISSUE THREAD

**Issue by neoedmund** [beyond-all-reason/spring#277]
Currently java interface is not included in the windows release packages.

**Comment by lhog** [comment]
The reason is simple: no Java AIs covering the games running on BAR fork exist. At least we are not aware of any.
If you feel like this limits you in any way, feel free to test building Java AI in the containers and submit a pull request.

**Comment by neoedmund** [comment]
some info.

 java interface works directly on Linux.(though I made a small patch for JVM finding)
but on windows AFAIK crashes. see log reported by @Sovgut 
[message.txt](https://github.com/beyond-all-reason/spring/files/8703214/message.txt)

so maybe a little fix can make it work again.


I'm writing a java AI, https://github.com/neoedmund/BAR-neoeJavaAI


according to https://sc2ai.net/bots/   , cpp, python, java, dotnetcore should be fond by the community.

I'm also investigating a method to let java interface pretend to work as a C interface. so that release some burden of engine code.

**Comment by lhog** [comment]
Any progress here?

**Comment by neoedmund** [comment]
I'd rather use a Java wrapper for C interface. aka. the project only need to keep the C interface nice and working, other languages binding can be based on C.

**Comment by lhog** [comment]
So, are you planning to implement that?

**Comment by neoedmund** [comment]
Oh, the basic function is already implemented in https://github.com/neoedmund/BAR-neoeJavaAI , 
I was planned to make the AI stronger while the same time make the interface stable , then to release the code.
But I found the AI interface is not enough if lack of some utilities like pathing and alike things. for example, command a unit to move to a place, if the place is unreachable . but the unit will keep trying, or no means to report the unreachability.
when solving the problem , I get stuck. 
I also busy on other things to code, even in this Springs/bar project (like speed up the loading time, improve the replay, drop the foolish checksum, make a Vulkan render, ...).
Also I don't know there is another person on the earth interested in the Java interface like me .
so the likely scenario should be 
1. I feel the AI using the interface is reasonable , then I release the interface and AI as a separate project.
2. some people begin to seek Java interface , then I maybe clear the current interface code to release as a reference java implementation.

**Comment by marcushutchings** [comment]
So what I'm reading here is that the request has been worked around and no further action needs to be taken at this time.
