### ISSUE TITLE
Airmesh needs dynamic updates. Better smart ones.

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#28]

**Comment by marcushutchings** [comment]
I can look into possibly using the same approach as for pathing updates, where we record the 'blocks' of heightmap points updated, and update the mesh over time. I should be able to multi-thread this update.

**Comment by marcushutchings** [comment]
The clarify the current issue for anyone reading this. The problem (though someone please correct me if I am wrong) is that the smooth airmesh does not update in response to changes in the heightmap. This has caused problems where aircraft have become trapped after 'falling' in to craters created by nukes for example.

**Comment by marcushutchings** [comment]
Note. I suspect I will need to give this one a higher priority because the airmesh is not correct for random maps.

**Comment by lhog** [comment]
ZK doesn't use air mesh, but I'm more concerned with things like waterlevel gadget (reports like seaplanes flying underwater can be evidence of the need of airmesh update)

**Comment by marcushutchings** [comment]
Does that happen due to terrain deformation or is the cause due to the change in waterlevel?

**Comment by lhog** [comment]
Waterlevel AFAIK, which in the end is nothing more than the terrain deformation

**Comment by marcushutchings** [comment]
Which map does that happen on?

**Comment by lhog** [comment]
https://github.com/beyond-all-reason/Beyond-All-Reason/issues/495 this one i think.
I never managed to find time and trace it properly

**Comment by marcushutchings** [comment]
From testing, even a small patch update is too expensive for realtime updates to Smooth Mesh - that includes switching to a much faster method (Linear rather than Gaussian.)

**Comment by marcushutchings** [comment]
Perhaps a better approach would be to have the air move code (if smoothing is enabled) to sample points 1/2 second ahead and try to use the heighest point as the ground reference (maybe with a little histogram to avoid the chance of vertical zig-zaging.)

**Comment by marcushutchings** [comment]
Started new wiki section fo capturing new mod options: https://github.com/beyond-all-reason/spring/wiki/Mod-Options

**Comment by marcushutchings** [comment]
Solution deployed to engine https://github.com/beyond-all-reason/spring/commit/aae0f102b6506ad91d3e7d72d8bd3530f927b784
