### ISSUE TITLE
An SDL2 Flash Taskbar Call for LuaMenu

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#282]
Would be very useful for !ring: 
https://wiki.libsdl.org/SDL_FlashWindow

**Comment by lhog** [comment]
SDL version we use for Windows doesn't have this call yet. Most conservative Linux distros won't have SDL2.0.16 either: https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=+libsdl2-dev&searchon=names

**Comment by Beherith** [comment]
Ok, thanks for investigating!
