### ISSUE TITLE
105.1.1-941-g941148f Most widget flickers between drawing correctly and full black

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#286]
![image](https://user-images.githubusercontent.com/1318249/170824203-ecfd8df3-5820-4989-91f8-6d1c064d7699.png)
In world widget graphics flickers between drawing correctly and drawing black, pictured above.

![image](https://user-images.githubusercontent.com/1318249/170824211-5fff8cd8-69b3-46ff-86d0-015f891bc0c7.png)
I disabled every widget besides healthbars, put glColor(1, 1, 1, 1) at the start of DrawWorld, and the bug still occurs, so I don't know what else I am supposed to do.

I think this is an engine bug since it flickers on and off, and it worked fine in 841.

**Comment by GoogleFrog** [comment]
931 has the bug: https://github.com/beyond-all-reason/spring/commit/91ee57e7bd2c56efc6e742bb5c81fe189407c878

902 does not have the bug: https://github.com/beyond-all-reason/spring/commit/34d2eb7a14fa8f316b308a6c6945ae8fcb00f9ce

This is as far as I can bisect with the builds available.

I've been reproducing with a circuit brutal 3v3 on FolsomDamDeluxeV4. It appears fairly quickly with a factory selected.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/becd4d88f68c30b2d95a53b3e64052779a9dbf86 works around it.

**Comment by GoogleFrog** [comment]
I don't think this is directly related to #285.

**Comment by Beherith** [comment]
Yes, the relationship is different, but im sure the cause is https://github.com/beyond-all-reason/spring/commit/ff68bed5ccd7eae43a620874d82a436bbf944fd9

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/171360167-a6c95260-acf8-4c8d-8ae4-56dd1c5b34c2.png)
