### ISSUE TITLE
Borderless window does not minimise

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#287]
Borderless window used to minimise with the view desktop hotkey (Windows+D). It no longer does. I have had complaints from people unable to look at their desktop. I can make it minimise with a random combination of Ctrl+Alt+Delete and Windows+D.

**Comment by GoogleFrog** [comment]
931 has the bug: https://github.com/beyond-all-reason/spring/commit/91ee57e7bd2c56efc6e742bb5c81fe189407c878

902 does not have the bug: https://github.com/beyond-all-reason/spring/commit/34d2eb7a14fa8f316b308a6c6945ae8fcb00f9ce

This is as far as I can bisect with the builds available.

I've been reproducing with a circuit brutal 3v3 on FolsomDamDeluxeV4. It appears fairly quickly with a factory selected.

**Comment by lhog** [comment]
Is it Borderless = 1 and FullScreen = 1?
If so, it's as expected. FS + BS is considered exclusive fullscreen, which is supposed to resist to Alt-Tabs, Win-D and alike.

**Comment by GoogleFrog** [comment]
I think I wrote "borderless window" based on some terminology I was told to use, but it's a pretty abused term so lets drop it. The fact is, whatever you call the window modes, Spring is worse at handling its window than it used to be.

Players don't actually want exclusive fullscreen these days. I don't want exclusive fullscreen. Spring should be able to provide a window, with no borders, that fills exactly the space on a single screen, and that can be tabbed out of or hidden with a show desktop key. This is how modern games work, and Spring used to do it just fine with a reasonable combination of springsettings. Now it can't do it. See https://github.com/beyond-all-reason/spring/issues/183

I don't care what window display modes are technically called. I just want Spring to be as good at window handling as it used to be.

Also see https://github.com/beyond-all-reason/spring/issues/203

**Comment by lhog** [comment]
I've just checked:
* Win-D minimize borderless window for both 105.0 anf the latest BAR105
* Win-M does not for both

Therefore I conclude it's resolved (whatever the issue was)
