### ISSUE TITLE
selections via selection box rectangle

### ISSUE THREAD

**Issue by Ruwetuin** [beyond-all-reason/spring#288]
BAR has the smartselect widget that selects and filters the selection for us, but the engine will select everything in the rectangle-box when you let go, engine will undo the filter and select all for a brief moment. can we toggle this behavior off somehow?

**Comment by lhog** [comment]
So you want an option when selected units array is updated, but the actual selection is not happening?

**Comment by Ruwetuin** [comment]
when you let go of the mouse... that wont select anything, so basically just gimping it wholly, not selecting any array, widget will take care of that instead

**Comment by lhog** [comment]
Do you want that only for multiple selection or for single unit selection too?

**Comment by Ruwetuin** [comment]
i guess for consistency you can make it equal (but single selection doesnt matter much for my purpose)

**Comment by lhog** [comment]
Can you check the latest with `Spring.SetBoxSelectionByEngine(false)` ?

**Comment by lhog** [comment]
Let's assume it's working
