### ISSUE TITLE
Clean up (upgrade) the AI interface

### ISSUE THREAD

**Issue by neoedmund** [beyond-all-reason/spring#291]
when I trying to write AI. I found such situation:
several AI (eg. shard, barb) has customized code in engine.
maybe more difference in Lua interface for AI.

That is a bad practice. 

extra things written for shard or barb should be merged back into unified AI interface. 

AIs should share a fair interface, advantages from Barb or Shard should also be taken by other AI.

Time to upgrade to 0.2 ?

**Comment by lhog** [comment]
Can you give some examples re:
> several AI (eg. shard, barb) has customized code in engine.

**Comment by lhog** [comment]
No feedback.
