### ISSUE TITLE
Noticeable lag spike during network games when a spectator leaves the match

### ISSUE THREAD

**Issue by marcushutchings** [beyond-all-reason/spring#296]
A noticeable lag spike occurs during network games when a spectator leaves the match. This interferres with the user experience of the active players; something, spectators should not be able to do.

**Comment by Damgam** [comment]
Soooo we need someone to run LuaUI profiler during big games and see what spikes when someone leaves...

**Comment by Beherith** [comment]
Does it also happen on the replay?

**Comment by 6AKU66** [comment]
> Does it also happen on the replay?

Pretty sure it's not happening when you are watching replay

**Comment by 6AKU66** [comment]
> Could you please provide validated confirmation that this is the case? My ability to debug/repro this depends on it :D

I couldn't find effects of this bug in offline replayes 

https://www.youtube.com/watch?v=in2CDpniOc0
https://www.youtube.com/watch?v=9EDoWRIWB1k

**Comment by 6AKU66** [comment]
Debug info when player disconnect
https://youtu.be/z1JxX0TXmEk

**Comment by Beherith** [comment]
> Debug info when player disconnect https://youtu.be/z1JxX0TXmEk

Was this one online or replay? Because there doesnt seem to be much of a spike in debug view on this one.

**Comment by Beherith** [comment]
Ok, wow, thank you for that online-offline comparison, makes it clear that the problem doesnt seem to be with the gameside stuff, probably some netcode timeout in the engine that happens when someone leaves, and this ends up looking like lag spikes. 

> > Could you please provide validated confirmation that this is the case? My ability to debug/repro this depends on it :D
> 
> I couldn't find effects of this bug in offline replayes
> 
> https://www.youtube.com/watch?v=in2CDpniOc0 https://www.youtube.com/watch?v=9EDoWRIWB1k

So these two are

**Comment by 6AKU66** [comment]
> Was this one online or replay? Because there doesnt seem to be much of a spike in debug view on this one.

It's was online session. But also pay attention that SimFrameTick is stuck at some point.

**Comment by 6AKU66** [comment]
> netcode timeout in the engine that happens when someone leaves, and this ends up looking like lag spikes.
I'm not sure, but maybe speed sim client estimator doing something bad in process of disconnection?

**Comment by marcushutchings** [comment]
That looks like the server got busy and hasn't submitted new frames.

**Comment by marcushutchings** [comment]
@Beherith the servers are running in dedicated mode or headless? I can't imagine them in headless, that would be too much processing power.
