### ISSUE TITLE
Add shadowSampler option for Lua Texture

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#31]
Currently, shadowSampler texture is not possible to setup because GL_TEXTURE_COMPARE_MODE is always set to GL_NONE.
The proposition is to
- add compareFunc to [Lua/LuaTextures.h]:Texture struct, which would correspond to GL_TEXTURE_COMPARE_FUNC
Note: ShadowSampler might require setting both GL_TEXTURE_COMPARE_MODE and GL_TEXTURE_COMPARE_FUNC, but it looks logical to simplify for Lua into 1 parameter: compareFunc, which is either 0 (_default_, compareMode == GL_NONE) or one of GL_LESS,GL_EQUAL,etc (compareMode == GL_COMPARE_REF_TO_TEXTURE).
- replace following at [Lua/LuaTextures.cpp]:ApplyParams(tex&):
from
glTexParameteri(tex.target, GL_TEXTURE_COMPARE_MODE, GL_NONE);
to
glTexParameteri(tex.target, GL_TEXTURE_COMPARE_MODE, tex.compareFunc? GL_COMPARE_REF_TO_TEXTURE : GL_NONE);
if (tex.compareFunc) glTexParameteri(tex.target, GL_TEXTURE_COMPARE_FUNC, tex.compareFunc);
- account for compareFunc field at [Lua/LuaOpenGL.cpp]:CreateTexture(..) and ChangeTextureParams(..)

P.S. I may not be totally correct with how compareMode setup works, correct me if I'm wrong.

**Comment by lhog** [comment]
Overall agree.
Lua side lets make `compareFunc` either nil or 0 or GL.LESS, GL.EQUAL, etc.

Engine side let's follow the cargo cult and make SM texture like that:
```
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_COMPARE_MODE, GL_COMPARE_R_TO_TEXTURE);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_COMPARE_FUNC, GL_LEQUAL); //replace with requested compare function.
	glTexParameteri(GL_TEXTURE_2D, GL_DEPTH_TEXTURE_MODE, GL_LUMINANCE);
```

Please send a pull request with tested changes. I'll happily merge.

**Comment by lhog** [comment]
Implemented it myself.
