### ISSUE TITLE
Using Asian font causes severe lag

### ISSUE THREAD

**Issue by WatchTheFort** [beyond-all-reason/spring#317]
To reproduce:
1. In bar.sdd, replace the file `language\test_unicode.lua` with the following (zipped because Github doesn't allow attaching Lua files) [test_unicode.lua.gz](https://github.com/beyond-all-reason/spring/files/9143807/test_unicode.lua.gz)
2. Start a match
3. Go to Settings -> Dev tab -> Language (middle of first column), and change language to Chinese (third option)
4. Quickly mouseover build tiles

**Comment by lhog** [comment]
I changed implementation a little bit and it seems to perform slightly faster, but still not fast enough to not cause stuttering.
Currently it looks like the only way is to make render fonts asynchronously, i.e. draw nothing until glyph images are ready.

Ref: https://github.com/beyond-all-reason/spring/commit/78a7a72a16021bd5a84be25990b6025123e2fa52

Please test the current implementation: https://github.com/beyond-all-reason/spring/actions/runs/2732278819 before I start making async one.

**Comment by lhog** [comment]
Good enough for now.
