### ISSUE TITLE
Smoketrails with custom periods: bad rendering

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#339]
https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Rendering/Env/Particles/Classes/SmokeTrailProjectile.cpp#L119

This `age + 8` (and `age + 4` below, possibly other places) seems to assume that `smokePeriod` is still hardcoded at 8. This creates ugliness where adjacent segments' alpha and size do not match each other, especially visible if you lower `smokeTime` as well so the extra frames are a larger percentage of total, here is a pic at smokeTime=18 and smokePeriod=2: 

![image](https://user-images.githubusercontent.com/2573076/184568707-954d53c3-aa6c-4455-abf4-1392379d6333.png)

**Comment by lhog** [comment]
Makes sense, thanks for bringing that up.

**Comment by lhog** [comment]
@sprunk Do you happen to have files needed to re-produce the above at hand?

**Comment by sprunk** [comment]
Nope, but I think I just added
```lua
smokeTime = 18,
smokePeriod = 2,
```
into here: https://github.com/ZeroK-RTS/Zero-K/blob/master/units/chicken_spidermonkey.lua#L103

Looks like it's already done though, thanks!

**Comment by lhog** [comment]
Yep, I added the same, and it looked fine(r).
