### ISSUE TITLE
Request: Support for creation and rendering to 3D texture

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#342]
Request: Add support to create a Lua 3D texture via gl.CreateTexture with ability to render to it via gl.RenderToTexture (_texProps.fbo = true_).

About support of 3D texture as a color attachment for gl.CreateFBO specifically: This _could_ be useful, as we would be able to setup a render to multiple 3D textures (just as 2D, if I am correct). But this task is too uncommon, I recommend ignoring 3D textures for this part of interface if that were to save development time. Functionality of gl.RenderToTexture, rendering to just 1 texture, should be enough.

Current gl.CreateTexture interface: gl.CreateTexture(number intXSize, number intYSize [, table texProps ])
Suggested gl.CreateTexture interface: gl.CreateTexture(number intXSize, number intYSize [, number intZSize] [, table texProps ])

**Comment by Beherith** [comment]
Sounds interesting, what use do you have in mind for this?

**Comment by Krogoth100** [comment]
It will be used for an atmosphere rendering, which sometimes requires a lot of tweaking and re-rendering to produce the desired result.
But the ways to use a dynamically generated 3D texture in modern graphics are vast. Once you get your hands on it and toy with it, you will surely find a lot of cool stuff you can do with it.

**Comment by Krogoth100** [comment]
Also, if you are ever to try out software raytracing, I can point you out to Distance Fields. Distance Fields can be generated by an outside program, but I am sure that an in-game generator is the way to go. You render it to 3D texture and use for a high quality ray-tracing as a speed-up to achieve reasonable FPS.
Now, that is quite a bit off-topic, but I wanted to elaborate on the "vast" word a bit.

**Comment by Beherith** [comment]
Wonderful! Do you have any experience with these? Or were you already working on this and hit a blocker?

**Comment by Krogoth100** [comment]
I have, but not with that last thing I mentioned. Software raytracing - that one I would like someone else to try out : D
No real blockers, all ok. But at some point, I would be glad to see this thing implemented. : )
I am sorry I occasionally talk some probably cool sounding stuff and don't show anything. I will be able to show it once my project is announced. This is a commercial project, thus the "secrecy". (No worries, all the code stuff will be shared as it should be : ))

**Comment by marcushutchings** [comment]
Nice! I never thought the Spring engine would be used commericially, due to the GPL.

**Comment by Krogoth100** [comment]
> Nice! I never thought the Spring engine would be used commericially, due to the GPL.

Honestly, I don't think that's a disadvantage at all! It already is extremely complicated to make a good game _with_ the tools available (aka code base). Mutual sharing (no surprise) is actually good. : )
Like, take a look at those StarCraft 1 clones (few of them out there). They managed to make them even without the source code! ))) That's of course a joke reference, because Spring and such engines are much more complex. But the point is, creating a good game design is always, if not the hardest, but creative-heavy task and what makes the game own thing, even if some large underlying structure is not protected from borrowing by others.

**Comment by lhog** [comment]
https://github.com/beyond-all-reason/spring/commit/441a1f851151367898bc11b77b5b06b6a26d7e99 has some stuff.

I need a widget prototype from you to test.

The example with color0 attachment:
```
local tex = gl.CreateTexture(xsize, ysize, zsize, { target = GL.TEXTURE_3D, format = GL.RGBA8, etc....})
local fbo = gl.CreateFBO({color0  = tex, drawbuffers = { GL_COLOR_ATTACHMENT0_EXT})
-- etc
```

**Comment by Krogoth100** [comment]
Here it is!
[test_3dtexture.zip](https://github.com/beyond-all-reason/spring/files/9434794/test_3dtexture.zip)
If everything works correctly, it should produce a horizontal gradient of blue on the left side of the screen. The right side of the gradient should pulsate from dark blue (0.25) to blue (1.0) over time, meaning going through Z coordinate.

**Comment by lhog** [comment]
I traced gl.CreateTexture and gl.CreateFBO with your widget and to me it worked fine.
I also added FBO completion check to your widget and it returned positive:
`[t=00:07:21.382827][f=0010395] 3DTEX: FBO valid >, true, 36053`

However I've got:
```
[t=00:02:57.141175][f=0002208] Loading:  LuaUI\Widgets\test_3dtexture.lua
[t=00:06:25.197604][f=0002223] Error in DrawScreenPost(): [string "LuaUI\Widgets\test_3dtexture.lua"]:123: bad argument #1 to 'UseShader' (number expected, got nil)
[t=00:06:25.200188][f=0002223] Removed widget: TEST 3D Texture
```
So there's something wrong with your shader and I couldn't confirm the effect of the texture visually.

**Comment by lhog** [comment]
Confirmed to work.
