### ISSUE TITLE
Camera pans when it should remain in place, while user is rotating the camera (Spring camera)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/spring#347]
I'm just rotating camera, but aside of rotation it's start to shift in some direction.
https://www.youtube.com/watch?v=smsLLSjfvcg

105.1.1-1113

**Comment by 6AKU66** [comment]
Not only spring camera

**Comment by lhog** [comment]
@dzosz can you have a look. This reportedly happens on new engines and might be related to your PR.

**Comment by dzosz** [comment]
I took a quick look and reverted latest camera changes (2a311ae8de265b5d1b8e2e2aca4a57f99b320da3 and 5625158e601762f37fed151f45682ff30c05b406) but the issue is still present. I'll have to debug the code to see what's up.

**Comment by lhog** [comment]
Ugh, somehow people report it's new to them. Could be wrong of course.

**Comment by 6AKU66** [comment]
> Ugh, somehow people report it's new to them. Could be wrong of course.

Hm... I decided to test it again on 966. Same issue. So, yeah it's not new! Sorry, i made a mistake claiming it's only >966.
@dzosz

**Comment by 6AKU66** [comment]
UPD: I did testing in 1155 it's still valid bug for spring camera. But i found another bug for 966 and 1155 that need to report.

**Comment by dzosz** [comment]
this seems to be related to CamSpringLockCardinalDirections option. With this command typed in the chat camera behavior is correct.
`/set CamSpringLockCardinalDirections 0`

**Comment by dzosz** [comment]
> Ugh, somehow people report it's new to them. Could be wrong of course.

you were right. I was testing FPS camera which exhibits similar behavior
