### ISSUE TITLE
Spring camera cannot properly handle more than 540 degrees rotations from default position

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/spring#358]
https://youtu.be/GG9DDYMg8io

Only spring camera affected.

**Comment by dzosz** [comment]
is this on dev branch or current official release?

**Comment by 6AKU66** [comment]
> is this on dev branch or current official release?
@dzosz 
Oh, sorry i forgot to mention. It's dev branch.

**Comment by 6AKU66** [comment]
It's fixed.
