### ISSUE TITLE
Audio cable change issue

### ISSUE THREAD

**Issue by Teifion** [beyond-all-reason/spring#37]
When I change my audio cable from one device to another the sound in BAR vanishes. The rest of the system works fine but BAR stops outputting noise.

Subsequent to posting this I realised going from lobby to battle will mean sound comes back on. If I unplug mid battle though the sound goes off again and doesn't resume.

**Comment by lolsteamroller** [comment]
I can try to repro it with my USB thing, but don't think I had issues.

**Comment by Teifion** [comment]
I should add I'm running Linux Mint and the audio cable goes directly into the case. I'm not using an adapter or USB dongle.

**Comment by Damgam** [comment]
Happens to me too on Windows so that's not your side fault.

Spring is just not updating the default audio device, or maybe even crash the audio with missing device, dunno.

**Comment by lhog** [comment]
I checked OpenAL threads on this topic and it sounded like an actual issue, they have been trying to solve. All in all, no low hanging fruit solution is foreseen yet.

**Comment by lhog** [comment]
`UseSDLAudio = 1` in springsettings.cfg suddenly allows for devices hotplug. I've fixed some issues in the code and I'm enabling this option by default in spring next. The extensive testing is needed however as IDK why it was default disabled.

**Comment by lhog** [comment]
Probably solved. Re-open in case it is not.
