### ISSUE TITLE
Unit getting stuck on structure corners and having trouble passing through gaps (1177)

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#374]
On the middle right of this replay I took control of a Scalpel and started moving around the Hovercraft Platform. I noticed it had trouble going around the top right corner and approaching the top side of the factory. I built a Solar with enough space for it to path through and tried to send it through. It would often become stuck or edge forwards very slowly.

Run on https://github.com/ZeroK-RTS/Zero-K/commit/1ce1cb06567d9108044ff6fbaf8de0f715befe56

[20220913_122859_FolsomDamDeluxeV4_105.1.1-1177-gada72b4 BAR105.sdfz.txt](https://github.com/beyond-all-reason/spring/files/9557161/20220913_122859_FolsomDamDeluxeV4_105.1.1-1177-gada72b4.BAR105.sdfz.txt)

**Comment by marcushutchings** [comment]
Just to check. This unit is using the HoverAirMoveType?

**Comment by marcushutchings** [comment]
Playing around with the Hovercraft in BAR on 966, I see that the Hovercraft can struggle to get around through gaps between structures.

**Comment by GoogleFrog** [comment]
What is HoverAirMoveType? I don't think it is. I saw something in NOTA that made hovercraft able to strafe. ZK has nothing like that, the hovercraft drive like normal vehicles.
