### ISSUE TITLE
Using SHIFT affects movespeed & zoomspeed by an engine set ratio and should be configurable

### ISSUE THREAD

**Issue by lolsteamroller** [beyond-all-reason/spring#376]
Shift is a very used key - mostly for
- making queues
- using gridmenu
- different hotkeys

Engine is also using Shift directly, by increasing the speed of both camera movement and the scroll/pan speed (by mostly x3 speed). This results in players zooming in and out very fast (especially those who already play on high zoom/scroll speeds) and creates a lot of frustration.

My suggestion is to first start by not removing the functionality, but instead allow player to tweak the effect by externalizing hardcoded values found here in:

**OverheadController.cpp**

https://github.com/beyond-all-reason/spring/blob/a76549fee939ef3ce51481cfdd598097197d5620/rts/Game/Camera/OverheadController.cpp#L86-L87
https://github.com/beyond-all-reason/spring/blob/a76549fee939ef3ce51481cfdd598097197d5620/rts/Game/Camera/OverheadController.cpp#L105

**SpringController.cpp**

https://github.com/beyond-all-reason/spring/blob/a76549fee939ef3ce51481cfdd598097197d5620/rts/Game/Camera/SpringController.cpp#L61
https://github.com/beyond-all-reason/spring/blob/a76549fee939ef3ce51481cfdd598097197d5620/rts/Game/Camera/SpringController.cpp#L77
https://github.com/beyond-all-reason/spring/blob/a76549fee939ef3ce51481cfdd598097197d5620/rts/Game/Camera/SpringController.cpp#L88

And by providing an option in the BAR settings to change that setting (personally I would like to see same speed, regardless if I use the modifier keys - 1 or 1.0f)

**Comment by WatchTheFort** [comment]
Can we expand the scope? The engine should not be setting _any_ hardcoded keyboard functionality, with the possible exception of interacting with the console.

**Comment by marcushutchings** [comment]
Here is a negative experience on the player's experience associated with this particular case, which changes the priority on this issue in relation to other places where the engine hardcodes key presses. So expanding the scope of this ticket to include lower priority items is not appropriate. I'll raise a separate ticket to allow those other cases to be captured.

**Comment by badosu** [comment]
Instructions for a contributor interested in making movefast and moveslow multipliers configurable:

- On cameracontroller.cpp include the modifier configuration definitions, e.g.:

```
CONFIG(float, CameraMoveFastMult)
	.defaultValue(3f)
	.minimumValue(1f)
	.description("The multiplier applied to speed when camera is in movefast state.");
```

- Add fields to cameracontroller.h and set them on initialization, e.g.  `moveFastMult = configHandler->GetFloat("CameraMoveFastMult")`
- Replace the occurrences of the multiplier in Spring and OverHead controllers, e.g. replacing

```
	pos.x += (move.x * pixelSize * (1 + moveFast * 3) * scrollSpeed);
```

with:

```
	pos.x += (move.x * pixelSize * (1 + moveFast * moveFastMult) * scrollSpeed);
```

- (Optional) Make this setting reloadable in runtime by figuring out how to use ConfigNotify and AddConfigListener, see https://github.com/badosu/spring/blob/fdb444430a16d3021206a95842f9c97837704d41/rts/Game/Camera/FPSController.cpp#L34-L46 as an example

**Comment by badosu** [comment]
> And by providing an option in the BAR settings to change that setting (personally I would like to see same speed, regardless if I use the modifier keys - 1 or 1.0f)

Already possible in next engine release by removing `movefast` and `moveslow` from bindings

**Comment by badosu** [comment]
If the issue is just movefast and moveslow bindings not being respected (the user can avoid those modifiers by not having them defined in the keybindings) this issue was resolved in https://github.com/beyond-all-reason/spring/pull/406.

If the issue is being able to configure the modifier speed, instructions above resolve it for an interested contributor

**Comment by badosu** [comment]
slow and fast modifiers are also applied here:

https://github.com/badosu/spring/blob/fdb444430a16d3021206a95842f9c97837704d41/rts/Game/Camera.cpp#L658-L659

**Comment by kaldamae** [comment]
Should be fixed with https://github.com/beyond-all-reason/spring/pull/475

**Comment by badosu** [comment]
Thank you @kaldamae
