### ISSUE TITLE
Invalid effect quad (1177)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/spring#378]
Reproduce: 
1. Spawn 50 Banshee (armkam)
2. Force attack the ground.

Error: [AddEffectsQuad] Internal Error: invalid effect quad winding/order, projectile type (CLaserProjectile)

Bug was introduced between 1150 and 1158 engines versions.
Valid on 105.1.1-1177

**Comment by lhog** [comment]
Perhaps you can recall yourself what unit caused this message to pop up? Or perhaps you can share the replay, so I could check myself.

**Comment by 6AKU66** [comment]
Updated.

**Comment by Beherith** [comment]
Indeed, the armkam lasercannon causes it:
![image](https://user-images.githubusercontent.com/109391/190576853-d1c66eb4-05ad-47ff-b320-febc589064d4.png)

Worth noting, that the projectile does not have texture 1-4 defined

**Comment by lhog** [comment]
Can't repro on 1186.
Anyways the particles rendering will need to be redone as a mean to fix https://github.com/beyond-all-reason/spring/issues/384 and the new implementation will unlikely to rely on implied vertices order, so closing.
Thanks for digging in though.
