### ISSUE TITLE
Selecting air units that going to different air repaid pod crash the game (1177)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/spring#379]
Reproduce: 
1. Build 2 air units and 2 air pods
2. Damage air units to retreat repair level.
3. Force units fly to different air pods.
4. After retreat order was issued select those 2 flying units.

https://youtu.be/7W79CRAPsuw
[infolog.txt](https://github.com/beyond-all-reason/spring/files/9571319/infolog.txt)

Bug was introduced.
Between 1011 and 1039 engines versions.

Valid in 1177.

**Comment by lhog** [comment]
Will have a look at the stack trace.
Note you don't have `/debuggl 1` enabled in your infolog

**Comment by lhog** [comment]
`And condition for crash need to use player camera`

**Comment by 6AKU66** [comment]
@lhog Updated reproduce steps.

**Comment by Beherith** [comment]
Indeed can repro here:
![image](https://user-images.githubusercontent.com/109391/190431919-f50d4dfb-cddd-40fc-9ade-9c6cd1501fda.png)
Lemme try in debug build

**Comment by Beherith** [comment]
Infolog with debuggl 1 : 
[infolog.txt](https://github.com/beyond-all-reason/spring/files/9576175/infolog.txt)

**Comment by Beherith** [comment]
module	address	file	line
spring.exe	0x00007ff63323d1e0	/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/bits/stl_iterator.h 	1011
spring.exe	0x00007ff6331d6ed4	rts/Game/UI/CursorIcons.cpp 	117
spring.exe	0x00007ff6331d80b8	/mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/bits/stl_construct.h 	151
spring.exe	0x00007ff63364c7b5	rts/Rendering/WorldDrawer.cpp 	401
spring.exe	0x00007ff63364d185	rts/Rendering/WorldDrawer.cpp 	286
spring.exe	0x00007ff63317f07c	rts/Game/Game.cpp 	1448
spring.exe	0x00007ff6336f03d3	rts/System/SpringApp.cpp 	828
spring.exe	0x00007ff6336f3668	rts/System/SpringApp.cpp 	862

**Comment by Beherith** [comment]
Here is the stack trace under msvc debug build:
![image](https://user-images.githubusercontent.com/109391/190456643-3a2f650f-7fc4-4d97-b7d0-91dcddb217d5.png)

**Comment by Beherith** [comment]
So it seems that the cursor for this command, whichever this active command is, is a null pointer:
![image](https://user-images.githubusercontent.com/109391/190457688-a81a38e8-7a46-48cb-aeb8-0f17eb362954.png)

Because getcursor seems to return null

**Comment by lhog** [comment]
Please test if it doesn't crash in the next version.

**Comment by 6AKU66** [comment]
I cannot reproduce anymore. Looks like it's was fixed.
