### ISSUE TITLE
FPS drop spike after picking position in pre-game (1105)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/spring#382]
https://youtu.be/cdxVQLKL7B4

Sometimes it's happen, sometimes it's not.

Low priority bug, i need more details.

**Comment by Beherith** [comment]
Indeed: 
![image](https://user-images.githubusercontent.com/109391/190433219-acff09fc-f584-4549-8d5a-e29afe46456a.png)
So its caused by unsynced lua, on the exact frame placement happens.  That is a good start.

**Comment by Beherith** [comment]
My hunch is the ai startpoint guesser doing a lot of metal map reading.

**Comment by 6AKU66** [comment]
This bug need more investigation. For some reason i can't reproduce it now.

**Comment by 6AKU66** [comment]
Seems it's started from version 1105.

**Comment by 6AKU66** [comment]
Here 1214 with reverted commit that probably cause this. If someone have this problem you can test if this fix the problem.
https://discord.com/channels/549281623154229250/724924957074915358/1028035561065287750
