### ISSUE TITLE
UnitDamaged: pass attacker info for spectators LuaUI

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#391]
Currently neither players nor spectators get attackerID etc info in LuaUI. For players this is important (since it would leak information that is potentially hidden) but there's little reason not to allow it for spectators.

Low priority since both ZK and BAR already reimplemented this via LuaRules relaying info, but it would be elegant if that could be dropped.

**Comment by lhog** [comment]
Yeah good idea to fix it.

**Comment by badosu** [comment]
Would it be acceptable to receive attackerId if damage results from allied aoe?

**Comment by sprunk** [comment]
Displaying the ID of attackers who are visible (which includes all units from the allyteam) sounds fine. Also the same also applies to UnitDestroyed.

**Comment by sprunk** [comment]
Works, forgot to close.
