### ISSUE TITLE
1214 Visual glitches in lobby on Linux/AMD

### ISSUE THREAD

**Issue by p2004a** [beyond-all-reason/spring#396]
There are multiple visual glitches visible in the lobby on Linux/AMD:

![Screenshot_282](https://user-images.githubusercontent.com/2212599/191720853-68adc9f2-1760-4c42-9715-1775b9d6dd6a.png)
![Screenshot_283](https://user-images.githubusercontent.com/2212599/191720732-136001f9-0a1c-462b-ada1-c6b4b45dcab5.png)

And this one is the most obvious one:

![Screenshot_284](https://user-images.githubusercontent.com/2212599/191720749-402e31ba-1ab9-46c3-8297-b82d80faad9f.png)

**Comment by p2004a** [comment]
I did git bisect, looking at

![Screenshot_284](https://user-images.githubusercontent.com/2212599/191720749-402e31ba-1ab9-46c3-8297-b82d80faad9f.png)

and:

bad: 0aff04d40210f346a6d288ca097c69b57c954feb
bood: 2cdfccf8a8a6c590adfc7b45ee958ce5e0080def

**Comment by Beherith** [comment]
My brain paused for a minute on bood. Ima keep that one :D

**Comment by lhog** [comment]
Hopefully fixed at last with https://github.com/beyond-all-reason/spring/commit/d2541c745a019f88ccf457ac6245bbffa94b53a8
