### ISSUE TITLE
1214 FPS Regression if game was started not in window mode

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/spring#397]
Starting game (or demo) in borderless or fullscreen mode leads to FPS regression. MSI afterburner shows low GPU loading.
Reproduce:
1. Start my demo in bordeless/fullscreen mode (changing it during the game will not help cause this!).
2. Do: pause the game, /skip 600, press TAB (it's will change camera pos).
3. Record FPS and GPU loading.
4. Compare it to game started in window mode (Changing it during the game will help reproduce it!)

P.S For me GPU loading only ~60% if it's bugged and 99% if not.

1440x900 window
1920x1080 borderless/fullscreen
[20220930_203823_Neurope_Remake 4_105.1.1-1214-gcf8d087 BAR105.zip](https://github.com/beyond-all-reason/spring/files/9690795/20220930_203823_Neurope_Remake.4_105.1.1-1214-gcf8d087.BAR105.zip)

Win 7
GTX 1060 3gb

**Comment by 6AKU66** [comment]
I deleted 3840x2160 and 5568x3132 resolution from my pool. Seems it's solved this problem. P.S My native screen resolution 1920x1080.

**Comment by lhog** [comment]
TODO: Reverse the erroneous change here: https://github.com/beyond-all-reason/spring/commit/0c6442b36c79719b7099ceae322ebff698b1f48e#diff-cffcc39c88c29dc1a956ce68ef42e69dd03ba3ccdfa47d4853cbbdc7e5a2cca2L1009-R1005

I.e.
`if (SDL_SetWindowFullscreen(window, (borderless ? SDL_WINDOW_FULLSCREEN : SDL_WINDOW_FULLSCREEN_DESKTOP) * fullScreen) != 0)`
should have `SDL_WINDOW_FULLSCREEN` and `SDL_WINDOW_FULLSCREEN_DESKTOP` flipped in ternary operator
