### ISSUE TITLE
Add action for 'say' specifying ally, spec or public chat

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/spring#400]
Example:

`sayw a Hi!` -> says Hi to allies
`sayw s Hey` -> says Hey to specs
`sayw p Ho` -> says Ho to public
`sayw speak` -> says speak to public, in this case the first argument is not a single letter is not one of s/a/p

The implementation should be straightforward, basically reimplementing [this](https://github.com/beyond-all-reason/spring/blob/94b38a9e4bcffd535c79339680083f02f8484bc6/rts/Game/UnsyncedGameCommands.cpp#L466-L475) but parsing the action args and sending 'a', 's' or '' to game->SendNetChat.

Alternatively can be extended to allow for playerId as the first arg.

Alternatively SayPrivateActionExecutor (action `w`) can be extended

**Comment by sprunk** [comment]
What happens currently with `say a: Hi!` or `say s: Hey`?

**Comment by badosu** [comment]
I think it just says the literal according to the code [here](https://github.com/beyond-all-reason/spring/blob/94b38a9e4bcffd535c79339680083f02f8484bc6/rts/Game/UnsyncedGameCommands.cpp#L472) `game->SendNetChat(action.GetArgs())`

**Comment by badosu** [comment]
Actually and chat action is handled for `a:` `s:`. Which is ridiculous, but that's life

https://github.com/beyond-all-reason/spring/blob/94b38a9e4bcffd535c79339680083f02f8484bc6/rts/Game/UnsyncedGameCommands.cpp#L472

**Comment by badosu** [comment]
Thank you @kaldamae

**Comment by badosu** [comment]
I don't remember the user use case that I wasn't able to resolve with the existing action
