### ISSUE TITLE
105.1.1-1212-g94b38a9 White squares at waypoints

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#401]
From esoteria (VentureSatchel#4598).

![image](https://user-images.githubusercontent.com/1318249/191893510-3ed77f52-d8d3-4ab1-9d57-0468bcc6de6f.png)
"This is probably not a new bug, since I see these squares on Linux all the time anyway, but it's new that they're at selection target, I think."
![image](https://user-images.githubusercontent.com/1318249/191893505-ff7f0b3a-44cb-496d-80a4-e865d6a79c02.png)
"Same thing. But, maybe it was that I hadn't set my icon zoom levels in this new engine? Does config carry over?"

"I did get the squares to turn magenta holding shift, which was cool, but not something I had tried before."

**Comment by lhog** [comment]
The rule of thumb for reports like that is to:
1) Provide infolog
2) Run the game with `/debuggl 1`. In case the issue is intermittent - please say something in the chat so it's easier to track it down in infolog
3)  Disable LuaUI first, LuaRules in second step and confirm the issue is still there

**Comment by Beherith** [comment]
Please retest on https://github.com/beyond-all-reason/spring/releases/tag/spring_bar_%7BBAR105%7D105.1.1-1231-g4fae6f5 @GoogleFrog

**Comment by lhog** [comment]
Probably fixed
