### ISSUE TITLE
105.1.1-1212-g94b38a9 Wrecks, nanoframes and unit shadows disappeared

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#402]
At some point in the game my wrecks, nanoframes and unit shadows disappeared. 
[infolog.txt](https://github.com/beyond-all-reason/spring/files/9630774/infolog.txt)
![screen00003](https://user-images.githubusercontent.com/1318249/191893809-c558fb13-1f24-4a51-bafb-1e885394ad8e.png)

Using a widget that draws features with a shader:

![screen00004](https://user-images.githubusercontent.com/1318249/191893825-54c33036-73b9-473f-b466-d8e7ceb5fac3.png)

**Comment by lhog** [comment]
Nothing interesting in the infolog except a ton of `\0` characters that hanged my Notepad++.
Next time it happens please enable `/debuggl 1` during these events.
