### ISSUE TITLE
105.1.1-1212-g94b38a9 Terrible performance

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#403]
Helwor took a long time to join the game and had terrible performance.
![image](https://user-images.githubusercontent.com/1318249/191893952-a162daba-d20d-4d91-baf6-c5dfc0044706.png)
![image](https://user-images.githubusercontent.com/1318249/191893964-1da7eeb9-4223-4442-9d17-ea256acd19ca.png)

Apparently it got a bit better when he closed the chobby Spring and did something in Avast, so perhaps this report is just for completeness. The high thread related usage is new though given the recent advances.

**Comment by marcushutchings** [comment]
What's the performance change like for him in a single player game? This could be a multi-player specific issue: I suspect that his machine is falling behind the pack sooner and faster now because his machine has fewer cores than the median-performing machine in that network game.

**Comment by icexuick** [comment]
I've seen some more people with some strange lags or worse performance. It's being investigated as i type.

**Comment by Beherith** [comment]
Based on the screenshot's minimap, there are only ~200 units in this game

**Comment by marcushutchings** [comment]
The thread workalod does look unbalanced. This is an intel processor?

**Comment by marcushutchings** [comment]
Can we have the infolog for that? Those draw times look rather high.

**Comment by lhog** [comment]
Any progress here?
Can Helwor test latest version I'm going to release in a few hours?

**Comment by lhog** [comment]
No progress - closing.
