### ISSUE TITLE
105.1.1-1212-g94b38a9 Missing bullets and rocket trails.

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#404]
From esoteria (VentureSatchel#4598).

![image](https://user-images.githubusercontent.com/1318249/191894718-d1428732-1d76-4174-924e-75156f126c99.png)

The Nimbus (gunshipheavyskirm) is firing here and the bullets are invisible. The Recluse (spiderskirm) missile can be seen but it is missing its trail and CEG.

**Comment by lhog** [comment]
It's unusual. Did it start immediately or after some time?
Other than that see https://github.com/beyond-all-reason/spring/issues/401#issuecomment-1256010022

**Comment by Beherith** [comment]
Please retest on https://github.com/beyond-all-reason/spring/releases/tag/spring_bar_%7BBAR105%7D105.1.1-1231-g4fae6f5 @GoogleFrog

**Comment by lhog** [comment]
@GoogleFrog need your feedback here, otherwise we can't keep this issue open indefinitely
