### ISSUE TITLE
AMD beta drivers log showing the broken shaders

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#410]
[t=00:00:00.264945] 	SDL version : 2.0.18 (linked) / 2.0.18 (compiled)
[t=00:00:00.264951] 	GL version  : 4.6.0 Compatibility Profile Context 22.9.1.220915
[t=00:00:00.264956] 	GL vendor   : ATI Technologies Inc.
[t=00:00:00.264961] 	GL renderer : AMD Radeon RX 5700 XT
[t=00:00:00.264966] 	GLSL version: 4.60
[t=00:00:00.264970] 	GLEW version: 2.1.0
[t=00:00:00.264974] 	GPU memory  : 24208MB (total) / 24208MB (available)
[t=00:00:00.265020] 	SDL swap-int: 0
[t=00:00:00.265027] 	SDL driver  : windows

[20220923090558_infolog(1).txt](https://github.com/beyond-all-reason/spring/files/9633882/20220923090558_infolog.1.txt)

Noteable excerpts:

```
[t=00:00:23.906597][f=-000001] [Shader] Warning: [GLSL-SO::CompileShaderObject] shader-object name: GLSL/ModelFragProg.glsl, compile-log:
WARNING: 0:119: '#extension' : extension not supported: GL_ARB_texture_query_levels
WARNING: 0:120: '#extension' : extension not supported: GL_ARB_fragment_layer_viewport
ERROR: 0:41: 'scalar swizzle' : not supported for this version or the enabled extensions 
ERROR: 0:41: '' : missing #endif 
ERROR: 0:41: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.
```

```
[t=00:00:52.908965][f=-000001] [Shader] Warning: [GLSL-SO::CompileShaderObject] shader-object name: GLSL/bumpWaterFS.glsl, compile-log:
WARNING: 0:119: '#extension' : extension not supported: GL_ARB_texture_query_levels
WARNING: 0:120: '#extension' : extension not supported: GL_ARB_fragment_layer_viewport
ERROR: 0:10092: 'scalar swizzle' : not supported for this version or the enabled extensions 
ERROR: 0:10092: '' : missing #endif 
ERROR: 0:10092: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.
```

**Comment by lhog** [comment]
When you think it can't be worse than it's, they make a new version of driver...

**Comment by lhog** [comment]
Ah, it's 1199. I fixed a few things AMD thinks were not ok in these shaders.
Retest on later version.

**Comment by lhog** [comment]
Should be fine after shaders have been worked around

**Comment by davie504** [comment]
Could you say, what's wrong with the shaders? We have similar problem with AMD drivers

**Comment by lhog** [comment]
Oh I don't remember by now, but usually when you have a PC reproducing the issue, fixing the shader code is a matter of several minutes.
