### ISSUE TITLE
Windows/Intel regression 1073 -> 1082: Broken rendering

### ISSUE THREAD

**Issue by p2004a** [beyond-all-reason/spring#417]
Rendering of map and UI got broken on integrated Intel GPUs on Windows:

- Works 1073 f015444 [20220925204344_infolog.txt](https://github.com/beyond-all-reason/spring/files/9641785/20220925204344_infolog.txt)
- Doesn't work 1082 4e8c064 [20220925204105_infolog.txt](https://github.com/beyond-all-reason/spring/files/9641783/20220925204105_infolog.txt)

Unfortunatelly commits between don't compile: but it looks like it's only headless that fails to compile looking at commit messages, so probably it's possible to get better range if you need.

![2022-09-25 22_45_47-Beyond All Reason (Spring 105 1 1-1083-gb5309d4 HEAD)](https://user-images.githubusercontent.com/2212599/192165384-3db39fac-d2c7-425b-a1dd-fd15428e2a1c.png)

**Comment by badosu** [comment]
Link for easier comparison: https://github.com/beyond-all-reason/spring/compare/f015444...4e8c064e5bbafde0476eae8112e84cc13ea0f251

**Comment by lhog** [comment]
Interesting.. my first assumption was VRAM OOM, but the commit range doesn't have the change I thought was responsible for that.
So perhaps it's possible to find the cause and fix it.

**Comment by lhog** [comment]
@p2004a let's revert some potentially affecting commits and see if it helps

**Comment by lhog** [comment]
Can you check the status with builds made at 5ac169b774838cab5f69764128fcabc166e8244b and one commit before?

**Comment by p2004a** [comment]
Did a test:
- 5ac169b774838cab5f69764128fcabc166e8244b doesn't work
- parent commit f0154446622d639d70df30cf909d805e86aa9d80 works

**Comment by Beherith** [comment]
i tested 1073 on the above map with reloading via chobby and it works.

With 1082 and chobby I get something a bit different:
![image](https://user-images.githubusercontent.com/109391/193558102-4089fb7a-3106-4636-8f8f-92b68bd63f84.png)


![image](https://user-images.githubusercontent.com/109391/193558135-6b417046-fdd6-433b-a31a-a4148c009926.png)

**Comment by Beherith** [comment]
testing 1083 without chobby just straight up gives:

![image](https://user-images.githubusercontent.com/109391/193558691-042d1ca7-403d-42ab-b9d8-f30e8a321e57.png)

**Comment by Beherith** [comment]
Fixed in 4fae6f51860e831ef27b84800ba2f244e779408b ! YAY!
