### ISSUE TITLE
TraceScreenRay fails to hit map on areas that are flattened by buildings being built on them. 

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#42]
Quite a few things are now known about this issue:

1. The oldest engine I tested this also had the bug, it was in engine 1486. 
2. When a building is built by a constructor, the edges of the flattened area randomly miss on TraceScreenRay
3. If the buildings are /give-en, then the bug is not present
4. If the terrain is restored underneath /given buildings, the bug becomes visible. 
5. Explosions and craters do not show this behaviour
6. The issue can relatively easily be checked by this widget that traces the screen along a regular grid, and draws a red rectangle if the trace fails. 

```
function widget:GetInfo()
    return {
        name      = "ScreenTrace",
        desc      = "Trace the screen along a regular grid, drawing a red rectangle on any ray that does not hit the ground",
        author    = "beheriht",
        date      = "2021 summer heat",
        license   = "Bacon",
        layer     = 10000,
        enabled   = true  --  loaded by default?
    }
end

local resolution = 10

local vsx, vsy
function widget:ViewResize(newX,newY)
	vsx, vsy = Spring.GetViewGeometry()
end

function widget:Initialize()
	widget:ViewResize()
end

function widget:DrawScreen()
	gl.Color(1.0, 0.0, 0.0, 0.75)  --red
	for x = 1, vsx, resolution do
		for y = 1, vsy, resolution do
			local _ , coords = Spring.TraceScreenRay(x, y, true) 
			if coords and coords[2] and coords[2] > -1000 then
				--gl.Color(0.0, 1.0, 0.0, 0.5) -- green
				--gl.Rect(x, y, x+ resolution/2, y+resolution/2) -- x y w h
			else
				--gl.Color(1.0, 0.0, 0.0, 0.75)  --red
				gl.Rect(x, y, x+ resolution, y+ resolution) -- x y w h
			end
		end
	end
end
```

**Comment by Beherith** [comment]
[dbg_screentrace.lua.txt](https://github.com/beyond-all-reason/spring/files/6715512/dbg_screentrace.lua.txt)
![screen01112](https://user-images.githubusercontent.com/109391/123410964-367c2c80-d5b0-11eb-8d5c-53c32097c610.jpg)

**Comment by Beherith** [comment]
Yes, these bugs still happen, and lead to wierd useability issues where selection boxes, and issued commands fail

**Comment by Beherith** [comment]
Need help with making the widget trace more stuff on screen for better debuggability?

**Comment by lhog** [comment]
This is something I'll look into in the next bugfix sprint.

**Comment by lhog** [comment]
This bug is surprisingly fix resistant.

**Comment by lhog** [comment]
I was unable to fix the synced part of it. The amount of processed data is too vast to trace things in the debugger.
The function itself deals with `synced = false` data obtained at:
```
float CGround::LineGroundCol(float3 from, float3 to, bool synced)
{
	const float* hm  = readMap->GetSharedCornerHeightMap(synced);
	const float3* nm = readMap->GetSharedFaceNormals(synced);
```

TODO: tap out first array and check if triangle normals from the second array match bruteforce recalculation.

**Comment by Beherith** [comment]
Would using the supplied widget while zoomed in, the breaking on a failed trace, and then have the widget trace the same ray again work?

**Comment by Beherith** [comment]
1. Add a cpp line to the engine side of the code that check wether the return of the trace's Y coord is <-1000
2. Change the widget above, to 
```
function widget:DrawScreen()
	gl.Color(1.0, 0.0, 0.0, 0.75)  --red
	for x = 1, vsx, resolution do
		for y = 1, vsy, resolution do
			local _ , coords = Spring.TraceScreenRay(x, y, true) 
			if coords and coords[2] and coords[2] > -1000 then
				--gl.Color(0.0, 1.0, 0.0, 0.5) -- green
				--gl.Rect(x, y, x+ resolution/2, y+resolution/2) -- x y w h
			else
                                
	          		local _ , coords = Spring.TraceScreenRay(x, y, true)  -- ADD ANOTHER TRACE HERE
				--gl.Color(1.0, 0.0, 0.0, 0.75)  --red
				gl.Rect(x, y, x+ resolution, y+ resolution) -- x y w h
			end
		end
	end
end
```

3. Go ingame, center the camera on the top of throne, build some wind farms
4. Enable the widget to see if there are any red rectangles. 
5. Set a breakpoint in engine to 1. 
6. Wait for it to break on a failed trace
7. Add a breakpoint to the start of the tracescreenray (since it will now trace the same screen ray it previously did)
8. Resume execution and walk the stack of this new tracescreenray, that is now guaranteed to fail the same way.

**Comment by lhog** [comment]
I think it's fixed
