### ISSUE TITLE
Intel GFX nanoparticles not drawn, decals binary thresholded bisected to 1140-1142

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#425]
Nano particles are no longer drawn from 1142 and up. Still works in 1140.  The offending commit is probably: https://github.com/beyond-all-reason/spring/commit/b8c286f3a29ba6caae3f9c5b8d5aa16eda9d2951

Decals also look binary thresholded, see the explosion decal spawned under the commander at game start.

Please state if you desire comparative /debuggl 1 logs between the two versions.

**Comment by lhog** [comment]
debuggl is unlikely to help here. Are you sure it's https://github.com/beyond-all-reason/spring/commit/b8c286f3a29ba6caae3f9c5b8d5aa16eda9d2951 ? Looks quite benign to me. Let's revert it in some local build and try it on an Intel PC.

**Comment by Beherith** [comment]
Indeed it looks benign, so ill look at it again,

**Comment by Beherith** [comment]
I was wrong, its already broken in 1134

good in 1133

So the offender is: https://github.com/beyond-all-reason/spring/commit/1627379d765abb2473031da92974bb5d32a08567

**Comment by Beherith** [comment]
This is what i mean by decals looking 'strange'
![image](https://user-images.githubusercontent.com/109391/192870579-6f5e7e97-b8df-4017-a7c2-c45c816f21f5.png)

**Comment by Beherith** [comment]
Fixed in 4fae6f51860e831ef27b84800ba2f244e779408b ! Thanks!
