### ISSUE TITLE
Minimap only top right quadrant shows projectiles and shaders 

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#432]
In the minimap, I can only draw via shaders to the top left quadrant of the minimap, and projectiles are also only drawn there. Other, old methods like the stippled line drawn by customformations onto the minimap can draw over the entire thing. 

Note that this is 'fixed' in the point tracker widget (which draws little crosshairs onto mapmarks placed by players) by setting:

```  
gl.ClipDistance ( 1, false)
gl.ClipDistance ( 3, false)
```
in https://github.com/beyond-all-reason/Beyond-All-Reason/blob/31cf2caaa51d046ab3358eb05b54377393f3c1ab/luaui/Widgets/gui_point_tracker.lua#L301 

However, this does not fix it for projectiles. I tried adding these clipdistance calls to the widget:drawminimapbackground, but that did not fix it either. 

https://github.com/beyond-all-reason/spring/blob/4fae6f51860e831ef27b84800ba2f244e779408b/rts/Game/UI/MiniMap.cpp#L1121

**Comment by lhog** [comment]
Does it only happen on AMD GPU?

**Comment by Beherith** [comment]
Yes, AMD + Linux only combo, afaik. (tested on steam deck)

**Comment by lhog** [comment]
Seems like minimap code should be rewritten from scratch as
```
gl.ClipDistance ( 1, false)
gl.ClipDistance ( 3, false)
```
Makes little sense

**Comment by lhog** [comment]
N2S: These are the offending lines: https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Game/UI/MiniMap.cpp#L1695-L1696

**Comment by lhog** [comment]
@badosu  can you test if minimap events show fully with latest commit.

**Comment by lhog** [comment]
Solved in HEAD?

**Comment by badosu** [comment]
Yes, thank you for reminding.
