### ISSUE TITLE
Texture array support

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#439]
When I tried to implement cascaded shadow maps, I found out that the convenient way to do this is via texture arrays. They are useful for a large number of other tasks too, essential for modern graphics.
I think this feature is nearly a must-have and a good candidate for addition.

*Who are unfamiliar with the texture arrays, these are own type of object, not just an array of samplers inside your shader. (GL_TEXTURE_2D_ARRAY/GL_TEXTURE_3D_ARRAY target)

Edit:
To say truthfully, I may not be right about cascaded shadow maps specifically, it can be (probably even should be, in some cases?) done without arrays, easily. The point is, many modern techniques use this feature as is and straightforward, when needed. Would be nice to have it.

**Comment by lhog** [comment]
@Krogoth100 try putting something together drawing inspiration from recently added support for 3D textures.

**Comment by lhog** [comment]
Not even sure if `GL_TEXTURE_3D_ARRAY` is needed, but if needed I expect a PR similar to that https://github.com/beyond-all-reason/spring/commit/441a1f851151367898bc11b77b5b06b6a26d7e99

**Comment by lhog** [comment]
Oh lol `GL_TEXTURE_3D_ARRAY` doesn't even exist :)
