### ISSUE TITLE
math.random(x, y) returning float instead of int

### ISSUE THREAD

**Issue by WatchTheFort** [beyond-all-reason/spring#45]
Calling `math.random(x, y)` inside a unitDef file is returning a float, as if it was a call to `math.random()`. It should be returning an int in the range (x, y).

Calls inside widgets, gadgets, and menu work as expected.

**Comment by lhog** [comment]
I'll try to attend this, but mayI have some simple unitDef to reproduce please?

**Comment by WatchTheFort** [comment]
See the override being used in https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/unitbasedefs/lootboxes/lootboxnano.lua#L2

Example unit that uses this to build its unitDef: https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/units/other/lootboxes/lootboxnano_t1_var1.lua

**Comment by lhog** [comment]
https://github.com/beyond-all-reason/spring/pull/57 when BAR to spring merge is sorted out
