### ISSUE TITLE
Air constuctors idle animation problems

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/spring#451]
There's two problems with current idle animations for air constuctors:
1. Animation doesn't stop playing if aircraft landed (should check if it's landed).
2. Animation playing depands only of absolute height over map (should work at all heights).
https://youtu.be/9G2goLMk4O8

**Comment by marcushutchings** [comment]
My mistake. Zecrus' investigation wasn't engine-side. This likely a BAR-related issue. Transfered to https://github.com/beyond-all-reason/Beyond-All-Reason/issues/1360

**Comment by Beherith** [comment]
Fixed, thanks for the great video and conclusion of abs map height, helped me tracked down and fix the bug!
