### ISSUE TITLE
/keydebug does not show scan codes anymore

### ISSUE THREAD

**Issue by verybadsoldier** [beyond-all-reason/spring#460]
When enabling `keydebug` then there is no information anymore about the scan code when pressing a key:
```
[t=00:03:52.746794][f=0014964] [KeyBindings] GetActions: codeChain="" scanChain="":
[t=00:03:52.746812][f=0014964] [KeyBindings] Action List:
[t=00:03:52.746820][f=0014964] [KeyBindings]    1.  action="stop"  rawline="stop"  shortcut="s"  index="115"
```

The vanilla spring engine give this:
```
[t=00:00:29.159397][f=0000000] [KeyBindings] GetActions: hex=0x0D acii="0x00D":
[t=00:00:29.159397][f=0000000] [KeyBindings]    1. action="chat"  rawline="chat"  shortcut="Any+enter"
```

When you want to bind an action to a key on e.g. a german keyboard you need to find out the scan code because the key symbols are not obvious. So it was nice when `keydebug` actually showed those scan codes.

`codeChain` and `scanChain` being just the empty string might be a bug:
```
[t=00:03:52.746794][f=0014964] [KeyBindings] GetActions: codeChain="" scanChain="":
```

**Comment by lhog** [comment]
@badosu have a look, please

**Comment by badosu** [comment]
@verybadsoldier Please check the linked PR, let me know if this is satisfactory

**Comment by verybadsoldier** [comment]
@badosu Thanks alot for the quick fix, looks good!
