### ISSUE TITLE
Dedicated server crashes after kicking a player

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#469]
[t=00:00:00.000000] ============== <User System> ==============
[t=00:00:00.000070]   Spring Engine Version: 105.1.1-1214-gcf8d087 BAR105 (Dedicated)
[t=00:00:00.000078]       Build Environment: gcc libstdc++ version 20210427
[t=00:00:00.000084]        Compiler Version: gcc-11.1.0
[t=00:00:00.000097]        Operating System: Linux 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 (x86_64)
[t=00:00:00.000185]         Hardware Config: Intel Core Processor (Haswell, no TSX); 7761MB RAM
[t=00:00:00.000193]        Binary Word Size: 64-bit (native)
[t=00:00:00.000199]           Process Clock: std::chrono::high_resolution_clock
[t=00:00:00.000423]      Physical CPU Cores: 1
[t=00:00:00.000442]       Logical CPU Cores: 2
[t=00:00:00.000452] ============== </User System> ==============

[t=00:00:00.053845] [DataDirLocater::FindWriteableDataDir] using writeable data-directory "/home/ubuntu/spads/var/ClusterManager/[teh]clusterEU2[02]/"
[t=00:00:00.053892] Using writeable configuration source: "/home/ubuntu/spads/var/spring/springsettings.cfg"
[t=00:00:00.054173] LogOutput initialized. Logging to /home/ubuntu/spads/var/ClusterManager/[teh]clusterEU2[02]/infolog.txt
[t=00:00:00.113196] [DataDirLocater::FindWriteableDataDir] using writeable data-directory "/home/ubuntu/spads/var/ClusterManager/[teh]clusterEU2[02]/"
[t=00:00:00.116530] [DataDirLocater::Check] Portable Mode!
[t=00:00:00.116551] [DataDirLocater::FilterUsableDataDirs] using read-write data directory: /home/ubuntu/spads/var/ClusterManager/[teh]clusterEU2[02]/
[t=00:00:00.116561] [DataDirLocater::FilterUsableDataDirs] using read-only data directory: /home/ubuntu/spads/var/spring/spring_bar_.BAR105.105.1.1-1214-gcf8d087_linux-64-minimal-portable/
[t=00:00:00.116574] [DataDirLocater::FilterUsableDataDirs] using read-only data directory: /home/ubuntu/spads/var/spring/data/
[t=00:00:00.168841] Scanning: /home/ubuntu/spads/var/spring/data/maps
[t=00:00:00.169770] Scanning: /home/ubuntu/spads/var/spring/data/packages
[t=00:00:00.171147] Scanning: /home/ubuntu/spads/var/spring/spring_bar_.BAR105.105.1.1-1214-gcf8d087_linux-64-minimal-portable/base
[t=00:00:00.171284] Scanning: /home/ubuntu/spads/var/spring/spring_bar_.BAR105.105.1.1-1214-gcf8d087_linux-64-minimal-portable/maps
[t=00:00:00.171318] Scanning: /home/ubuntu/spads/var/spring/spring_bar_.BAR105.105.1.1-1214-gcf8d087_linux-64-minimal-portable/games
[t=00:00:00.179025] [DedicatedServer] report any errors to Mantis or the forums.
[t=00:00:00.179043] [DedicatedServer] loading script from file: /home/ubuntu/spads/var/ClusterManager/[teh]clusterEU2[02]/startscript.txt
[t=00:00:00.191933] [GameSetup::Init]
	mapHashHexStr=""
	modHashHexStr=""
[t=00:00:00.191968] Warning: [GameSetup::Init] DS map-hash string "" should contain 128 characters
[t=00:00:00.191995] Warning: [GameSetup::Init] DS mod-hash string "" should contain 128 characters
[t=00:00:00.210172] [DedicatedServer] [script-checksums]
	map=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
	mod=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[t=00:00:00.227405] [DedicatedServer] starting server...
[t=00:00:00.227869] [UDPListener::TryBindSocket] binding UDP socket to IPv6-address :: () on port 53202
[t=00:00:00.227889] [UDPListener] successfully bound socket on port 53202
[t=00:00:00.228049] [GameServer] Connecting to autohost on port 53102
[t=00:00:00.228078] [GameServer] Server started on port 53202
[t=00:00:00.240809] [DedicatedServer] recording demo: /home/ubuntu/spads/var/ClusterManager/[teh]clusterEU2[02]/demos-server/20221020_203521_Greenest Fields 1_105.1.1-1214-gcf8d087 BAR105.sdfz
[t=00:00:00.240838] [DedicatedServer] using mod: Beyond All Reason test-21175-94f86e3
[t=00:00:00.240849] [DedicatedServer] using map: Greenest Fields 1.3
[t=00:00:00.240874] [DedicatedServer] GameID: 09b15163a494ad557eed2f4a371cf3cb
[t=00:00:00.362384] [GameServer] Connection attempt from Teifion
[t=00:00:00.362425] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Linux 64-bit (native)]
[t=00:00:00.362461] [GameServer]  -> Address: [::ffff:86.162.39.103]:56405
[t=00:00:00.362495] [GameServer]  -> Connection established (given id 20)
[t=00:00:00.441765] [GameServer] Connection attempt from SmokeTime
[t=00:00:00.441836] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.441867] [GameServer]  -> Address: [::ffff:2.24.255.78]:59289
[t=00:00:00.441910] [GameServer]  -> Connection established (given id 25)
[t=00:00:00.457386] [GameServer] Connection attempt from Flash512
[t=00:00:00.458420] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.458452] [GameServer]  -> Address: [::ffff:195.66.1.228]:64861
[t=00:00:00.458510] [GameServer]  -> Connection established (given id 28)
[t=00:00:00.458640] [GameServer] Connection attempt from eL_bArTo
[t=00:00:00.458657] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Linux 64-bit (native)]
[t=00:00:00.458680] [GameServer]  -> Address: [::ffff:86.9.50.108]:37764
[t=00:00:00.458721] [GameServer]  -> Connection established (given id 24)
[t=00:00:00.489294] [GameServer] Connection attempt from koziej
[t=00:00:00.489348] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Linux 64-bit (native)]
[t=00:00:00.489374] [GameServer]  -> Address: [::ffff:46.205.140.205]:63846
[t=00:00:00.489416] [GameServer]  -> Connection established (given id 9)
[t=00:00:00.489606] [GameServer] Connection attempt from DOUKNOUKKEM
[t=00:00:00.489632] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.489654] [GameServer]  -> Address: [::ffff:88.120.219.156]:28436
[t=00:00:00.489694] [GameServer]  -> Connection established (given id 18)
[t=00:00:00.520437] [GameServer] Connection attempt from pedro_bruce
[t=00:00:00.520508] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.520535] [GameServer]  -> Address: [::ffff:81.187.179.151]:49692
[t=00:00:00.520581] [GameServer]  -> Connection established (given id 4)
[t=00:00:00.536267] [GameServer] Connection attempt from busdriver
[t=00:00:00.536307] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.536332] [GameServer]  -> Address: [::ffff:45.137.226.207]:57002
[t=00:00:00.536367] [GameServer]  -> Connection established (given id 21)
[t=00:00:00.582993] [GameServer] Connection attempt from [Z]erpiederp
[t=00:00:00.583035] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.583053] [GameServer]  -> Address: [::ffff:82.197.199.123]:63196
[t=00:00:00.583087] [GameServer]  -> Connection established (given id 0)
[t=00:00:00.614491] [GameServer] Connection attempt from supernewb
[t=00:00:00.614561] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.614589] [GameServer]  -> Address: [::ffff:73.213.237.19]:58859
[t=00:00:00.614644] [GameServer]  -> Connection established (given id 3)
[t=00:00:00.632730] [GameServer] Connection attempt from [Drunk]iHateMyElos
[t=00:00:00.632834] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.632875] [GameServer]  -> Address: [::ffff:84.80.234.107]:63564
[t=00:00:00.632932] [GameServer]  -> Connection established (given id 29)
[t=00:00:00.633219] [GameServer] Connection attempt from [teh]Beherith
[t=00:00:00.633247] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.633316] [GameServer]  -> Address: [::ffff:94.21.172.224]:65163
[t=00:00:00.633362] [GameServer]  -> Connection established (given id 26)
[t=00:00:00.649227] [GameServer] Connection attempt from nallaj
[t=00:00:00.649288] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.649309] [GameServer]  -> Address: [::ffff:92.3.107.199]:50067
[t=00:00:00.649367] [GameServer]  -> Connection established (given id 11)
[t=00:00:00.649755] [GameServer] Connection attempt from ROBOTRONIC
[t=00:00:00.649904] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.649921] [GameServer]  -> Address: [::ffff:89.210.196.179]:52207
[t=00:00:00.649954] [GameServer]  -> Connection established (given id 6)
[t=00:00:00.650271] [GameServer] Connection attempt from EvolvedMonkey
[t=00:00:00.650301] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.650327] [GameServer]  -> Address: [::ffff:71.71.130.50]:54162
[t=00:00:00.650377] [GameServer]  -> Connection established (given id 15)
[t=00:00:00.667709] [GameServer] Connection attempt from ondreyson
[t=00:00:00.668302] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.668383] [GameServer]  -> Address: [::ffff:98.127.125.233]:57383
[t=00:00:00.668439] [GameServer]  -> Connection established (given id 30)
[t=00:00:00.668988] [GameServer] Connection attempt from Bowser
[t=00:00:00.669016] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.669038] [GameServer]  -> Address: [::ffff:47.199.241.158]:61609
[t=00:00:00.669072] [GameServer]  -> Connection established (given id 8)
[t=00:00:00.669855] [GameServer] Connection attempt from Eltherion
[t=00:00:00.669895] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.669918] [GameServer]  -> Address: [::ffff:188.154.157.104]:55201
[t=00:00:00.669940] [GameServer]  -> User name not authorized to connect
[t=00:00:00.669995] [GameServer] Connection attempt from Legendary
[t=00:00:00.670018] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.670041] [GameServer]  -> Address: [::ffff:92.180.8.163]:20708
[t=00:00:00.670135] [GameServer]  -> Connection established (given id 19)
[t=00:00:00.703413] [GameServer] Connection attempt from tecla
[t=00:00:00.703455] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.703473] [GameServer]  -> Address: [::ffff:73.60.225.185]:52044
[t=00:00:00.703532] [GameServer]  -> Connection established (given id 22)
[t=00:00:00.734825] [GameServer] Connection attempt from IGame4FUN
[t=00:00:00.734868] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.734888] [GameServer]  -> Address: [::ffff:82.76.245.112]:55295
[t=00:00:00.734935] [GameServer]  -> Connection established (given id 23)
[t=00:00:00.768086] [GameServer] Connection attempt from KING_HASSAN
[t=00:00:00.768147] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.768172] [GameServer]  -> Address: [::ffff:91.43.241.71]:57525
[t=00:00:00.768217] [GameServer]  -> Connection established (given id 10)
[t=00:00:00.785037] [GameServer] Connection attempt from [teh]Flow
[t=00:00:00.785080] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.785097] [GameServer]  -> Address: [::ffff:83.85.130.155]:65120
[t=00:00:00.785135] [GameServer]  -> Connection established (given id 27)
[t=00:00:00.785582] [GameServer] Connection attempt from Erun
[t=00:00:00.785604] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.785619] [GameServer]  -> Address: [::ffff:45.10.128.242]:57339
[t=00:00:00.785655] [GameServer]  -> Connection established (given id 7)
[t=00:00:00.865755] [GameServer] Connection attempt from Moth
[t=00:00:00.865807] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.865826] [GameServer]  -> Address: [::ffff:194.113.151.190]:64884
[t=00:00:00.865868] [GameServer]  -> Connection established (given id 13)
[t=00:00:00.881919] [GameServer] Connection attempt from Car
[t=00:00:00.881962] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.881984] [GameServer]  -> Address: [::ffff:190.2.131.205]:33918
[t=00:00:00.882047] [GameServer]  -> Connection established (given id 17)
[t=00:00:00.901669] [GameServer] Connection attempt from Flash
[t=00:00:00.901772] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.901849] [GameServer]  -> Address: [::ffff:87.124.244.238]:61409
[t=00:00:00.901920] [GameServer]  -> Connection established (given id 14)
[t=00:00:00.984289] [GameServer] Connection attempt from [DE]Drivver44
[t=00:00:00.984345] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:00.984364] [GameServer]  -> Address: [::ffff:75.237.194.186]:52644
[t=00:00:00.984461] [GameServer]  -> Connection established (given id 5)
[t=00:00:01.146708] [GameServer] Connection attempt from [DE]LSR
[t=00:00:01.146761] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:01.146803] [GameServer]  -> Address: [::ffff:87.110.52.222]:60987
[t=00:00:01.146883] [GameServer]  -> Connection established (given id 1)
[t=00:00:01.430898] [GameServer] Connection attempt from deltars
[t=00:00:01.430976] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:01.431003] [GameServer]  -> Address: [::ffff:88.109.82.89]:52676
[t=00:00:01.431140] [GameServer]  -> Connection established (given id 16)
[t=00:00:01.541567] [GameServer] Connection attempt from [DE]CJ_reborn
[t=00:00:01.541637] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:01.541668] [GameServer]  -> Address: [::ffff:49.36.89.97]:53707
[t=00:00:01.542115] [GameServer]  -> Connection established (given id 2)
[t=00:00:02.208458] [GameServer] Connection attempt from AKU
[t=00:00:02.208783] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:00:02.208996] [GameServer]  -> Address: [::ffff:85.140.114.208]:51665
[t=00:00:02.209969] [GameServer]  -> Connection established (given id 12)
[t=00:00:20.377488] [GameServer] Player Teifion finished loading and is now ingame
[t=00:00:27.734842] [GameServer] Player AKU finished loading and is now ingame
[t=00:00:30.081110] [GameServer] Player supernewb finished loading and is now ingame
[t=00:00:30.551575] [GameServer] Player deltars finished loading and is now ingame
[t=00:00:30.760598] [GameServer] Player ROBOTRONIC left the game:  timeout
[t=00:00:31.189922] [GameServer] Spectator Flash512 finished loading and is now ingame
[t=00:00:32.490613] [GameServer] Player eL_bArTo finished loading and is now ingame
[t=00:00:32.722917] [GameServer] Player SmokeTime finished loading and is now ingame
[t=00:00:33.874097] [GameServer] Player koziej finished loading and is now ingame
[t=00:00:34.289973] [GameServer] Player [DE]LSR finished loading and is now ingame
[t=00:00:34.922327] [GameServer] Spectator [Drunk]iHateMyElos finished loading and is now ingame
[t=00:00:36.491267] [GameServer] Player busdriver finished loading and is now ingame
[t=00:00:36.538515] [GameServer] Spectator [teh]Beherith finished loading and is now ingame
[t=00:00:37.981109] [GameServer] Player Legendary finished loading and is now ingame
[t=00:00:39.266020] [GameServer] Player tecla finished loading and is now ingame
[t=00:00:40.559581] [GameServer] Player EvolvedMonkey finished loading and is now ingame
[t=00:00:40.684902] [GameServer] Player [Z]erpiederp finished loading and is now ingame
[t=00:00:41.580345] [GameServer] Player IGame4FUN finished loading and is now ingame
[t=00:00:41.696107] [GameServer] Player DOUKNOUKKEM finished loading and is now ingame
[t=00:00:44.240514] [GameServer] Player pedro_bruce finished loading and is now ingame
[t=00:00:44.850895] [GameServer] Player [DE]CJ_reborn finished loading and is now ingame
[t=00:00:45.474418] [GameServer] Spectator ondreyson finished loading and is now ingame
[t=00:00:47.572491] [GameServer] Spectator [teh]Flow finished loading and is now ingame
[t=00:00:50.170416] [GameServer] Player [DE]Drivver44 finished loading and is now ingame
[t=00:00:50.775074] [GameServer] Player KING_HASSAN finished loading and is now ingame
[t=00:00:51.584089] [GameServer] Player Flash finished loading and is now ingame
[t=00:00:53.027642] [GameServer] Player Bowser finished loading and is now ingame
[t=00:00:56.511571] [GameServer] Player Moth finished loading and is now ingame
[t=00:01:01.674348] [GameServer] Player nallaj finished loading and is now ingame
[t=00:01:06.699861] [GameServer] Player Erun finished loading and is now ingame
[t=00:01:21.598150] [GameServer] Player Car finished loading and is now ingame
[t=00:02:07.893091] [GameServer] Connection attempt from ROBOTRONIC
[t=00:02:07.893179] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:02:07.893207] [GameServer]  -> Address: [::ffff:89.210.196.179]:60426
[t=00:02:07.895637] [GameServer]  -> Connection established (given id 6)
[t=00:02:48.918903] [GameServer] Player ROBOTRONIC finished loading and is now ingame
[t=00:03:01.100445] [GameServer] [PushAction] added spectator "Fire[Z]torm_" with password "5728425893" to team 0
[t=00:03:01.690187] [GameServer] Connection attempt from Fire[Z]torm_
[t=00:03:01.690251] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:03:01.690275] [GameServer]  -> Address: [::ffff:83.87.245.49]:52027
[t=00:03:01.692965] [GameServer]  -> Connection established (given id 31)
[t=00:03:54.007148] [GameServer] Spectator Fire[Z]torm_ finished loading and is now ingame
[t=00:05:36.358799] [GameServer] [PushAction] added spectator "Ascendante" with password "6411222447" to team 0
[t=00:05:36.605882] [GameServer] Connection attempt from Ascendante
[t=00:05:36.605923] [GameServer]  -> Version: 105.1.1-1214-gcf8d087 BAR105 [Windows 64-bit (native)]
[t=00:05:36.605941] [GameServer]  -> Address: [::ffff:94.16.160.87]:23209
[t=00:05:36.614682] [GameServer]  -> Connection established (given id 32)
[t=00:06:18.676469] [GameServer] Spectator Ascendante finished loading and is now ingame
[t=00:08:20.086659] [GameServer] Player busdriver left the game: kicked
[t=00:08:20.086702] Kill: client disconnecting...
[t=00:08:20.225574] [CrashHandler] Error: Segmentation fault in Spring 105.1.1-1214-gcf8d087 BAR105 (Dedicated)
[t=00:08:20.225640] [CrashHandler] Error: Halted Stacktrace for Spring 105.1.1-1214-gcf8d087 BAR105 (Dedicated) (SIGSEGV) using libunwind:
[t=00:08:20.414517] [CrashHandler] Error:   <00>            .../spring-dedicated(+0x137fd1) [0x55750cd92fd1]  log_util_prepareSection
[t=00:08:20.414561] [CrashHandler] Error: [00]                                                      0x137fd1  ??:?
[t=00:08:20.414571] [CrashHandler] Error:   <01>            .../spring-dedicated(+0x1385a3) [0x55750cd935a3]  log_util_prepareSection
[t=00:08:20.414580] [CrashHandler] Error: [01]                                                      0x1385a3  ??:?
[t=00:08:20.414589] [CrashHandler] Error:   <02>  /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f181bcca520]  __sigaction
[t=00:08:20.414597] [CrashHandler] Error: [02]                                                       0x42520  ??:?
[t=00:08:20.414606] [CrashHandler] Error:   <03>            .../spring-dedicated(+0x196be0) [0x55750cdf1be0]  std::vector<unsigned char, std::allocator<unsigned char> >::_M_default_append(unsigned long)
[t=00:08:20.414619] [CrashHandler] Error: [03]                                                      0x196be0  ??:?
[t=00:08:20.414628] [CrashHandler] Error:   <04>            .../spring-dedicated(+0x19840d) [0x55750cdf340d]  std::vector<unsigned char, std::allocator<unsigned char> >::_M_default_append(unsigned long)
[t=00:08:20.414636] [CrashHandler] Error: [04]                                                      0x19840d  ??:?
[t=00:08:20.414645] [CrashHandler] Error:   <05>            .../spring-dedicated(+0x309990) [0x55750cf64990]  std::error_code::default_error_condition() const
[t=00:08:20.414653] [CrashHandler] Error:   <05>                                                    0x309990  ??:?
[t=00:08:20.414661] [CrashHandler] Error:   <06>  /lib/x86_64-linux-gnu/libc.so.6(+0x94b43) [0x7f181bd1cb43]  pthread_condattr_setpshared
[t=00:08:20.414681] [CrashHandler] Error: [06]                                                       0x94b43  ??:?
[t=00:08:20.414689] [CrashHandler] Error:   <07> /lib/x86_64-linux-gnu/libc.so.6(+0x126a00) [0x7f181bdaea00]  __xmknodat
[t=00:08:20.414701] [CrashHandler] Error:   <07>                                                    0x126a00  ??:?
[t=00:08:20.414724] Error: [ExitSpringProcess] errorMsg="/home/ubuntu/spads/var/ClusterManager/[teh]clusterEU2[02]/infolog.txt.

**Comment by marcushutchings** [comment]
Yikes! Any chance you can get a debug build and use gdb to generate a back trace on that? @Beherith

**Comment by lhog** [comment]
In principle we have necessary debug symbols for 1214 dedicated in github release artifacts.

**Comment by marcushutchings** [comment]
I don't know if that has influence on this problem @Beherith, but I have seen and addressed a potential issue if a game participate is 'killed' a second time within the connection delay.

**Comment by marcushutchings** [comment]
Fixed in https://github.com/beyond-all-reason/spring/commit/5d375c931cdb7e287e1dc382892a1ab162f71906
