### ISSUE TITLE
1272 Flying pieces rotate around the off-center axis

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/spring#470]
https://youtu.be/ZlyvoXyi-hQ
Seems all units affected.

**Comment by lhog** [comment]
Guilty commit https://github.com/beyond-all-reason/spring/commit/fdb444430a16d3021206a95842f9c97837704d41#diff-8af164ccc902dbe773dcf56c9fd8923d4ebd162338600acfbc4fa6044fe7e075
