### ISSUE TITLE
Vector uniform arrays support

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#473]
gl.UniformArray currently supports only an array of floats.
The code, responsive for this, is roughly here:
https://github.com/beyond-all-reason/spring/blob/473b7087d0d8f93f24c47f6f69df8b3c0ab8d58b/rts/Lua/LuaShaders.cpp#L229
The proposition is to extend its usage for vector arrays as well, as that is handy in some situations. Might say, an array of vectors is a basic thing, just like floats.
It would execute, similarly, glUniform2fv/glUniform3fv/glUniform4fv for vec2/vec3/vec4 accordingly.
Right now gl.UniformArray takes a "type" argument which can be 1 - int, 2 - float, 3 - float array. There are 2 solutions regarding the interface, as I see it:
1. Add another type for vectors and extend switch for something like UNIFORM_TYPE_FLOAT_VECTOR. (And maybe int too, but I usually don't use int uniforms at all)
2. Insert a check inside UNIFORM_TYPE_INT and UNIFORM_TYPE_FLOAT switch cases whether the element is number or table, and if it's a table, run the upload for vectors, basing conclusion on the size of the first vector.

I think, I like the second option more, because it won't flood existing interface.

**Comment by lhog** [comment]
I suggest you switch to UBOs and in case of units/features to per object "uniform" SSBO vector.

**Comment by lhog** [comment]
UBO should be fine for complex arrays. Not gonna implement.
