### ISSUE TITLE
1283 Crash

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/spring#477]
Reproduce: 
1. Spawn armmship.
2. Start firing rockets.
[CRASH.txt](https://github.com/beyond-all-reason/spring/files/9896097/CRASH.txt)

**Comment by marcushutchings** [comment]
Unfortunately that infolog is truncated.

**Comment by 6AKU** [comment]
@marcushutchings I think i sent wrong log. I reattached log, check again.

**Comment by lhog** [comment]
I know what is wrong, don't worry.
