### ISSUE TITLE
105.1.1-1283-g43ae1fc Cannot tilt camera

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#481]
In 841 I hold Ctrl then scrollwheel and the camera tilts. In 1283 the camera does not tilt when I do this. What changed? I am using "Overhead (TA) style camera".

I also noticed that Shift and Alt no longer do anything either. Shift used to make the camera zoom in and out super fast, which I would like to be able to remove, but I want it removed in a way that seems intentional. If a bug has caused it to stop working then a bugfix would reasonably readd the undesired behaviour. Alt seems to replicate switching between overhead tab view. I hadn't noticed it existed before, but having it continue to exist seems good.

**Comment by sprunk** [comment]
These are now bindable:
```
	{ "Any+ctrl",  "moveslow"  },
	{ "Any+shift", "movefast"  },

	{ "Any+alt",   "movereset" },
	{ "Any+ctrl",  "movetilt"  }
```

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/a41a73f563a82566cdd67395036d90cc7baf28fa
