### ISSUE TITLE
1283 Hang in graphics driver

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#483]
Froze when I zoomed out and did Ctrl+A while spectating CAI vs. CAI.

[infolog.txt](https://github.com/beyond-all-reason/spring/files/9942768/infolog.txt)

**Comment by lhog** [comment]
Yes, it's a case of a rare deadlock in multi-threaded models loader.
Must be solved before the release.

**Comment by lhog** [comment]
Probably fixed with https://github.com/beyond-all-reason/spring/commit/580a5485ddafaae341c2cfd73ff354d0dc37bcaf
I added explicit exception that'd crash spring in case it happens again. So we will soon know if it's fixed or not.
