### ISSUE TITLE
Look into minimap sharpness

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#494]
![image](https://user-images.githubusercontent.com/1476261/201109196-295b00de-c4c8-42ca-891e-96bfad4d4666.png)

![image](https://user-images.githubusercontent.com/1476261/201109235-13725f4d-e354-4b03-9c5a-2f6ba3cd7767.png)

**Comment by 6AKU** [comment]
First screenshot anisotropic filtering applied via nvidia panel.
Second screenshot anisotropic filtering applied via game itself with SMFTexAniso = 16, SSMFTexAniso = 16 in springsettings.cfg.

**Comment by lhog** [comment]
Test when new engine is released.
