### ISSUE TITLE
glDepthClamp

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#498]
I have noticed that glDepthClamp is not available to me, due to this line:
https://github.com/beyond-all-reason/spring/blob/201672a273ab1b9ba5e74f44e8b84f7607b5ff91/rts/Lua/LuaOpenGL.cpp#L302
Spring's implementation refers to DepthClamp as an NVIDIA extension specifically, and I am not NVIDIA user.
DepthClamp as a tool, however, is available on majority of non-NV devices as well, using single GL API.
As my understanding goes, GL_DEPTH_CLAMP_NV flag (0x864F)  was generalized and became GL_DEPTH_CLAMP (also 0x864F).
I have no trouble using DepthClamp via gl.UnsafeState(0x864F), which works all properly, but it would not hurt to have a proper API entry.

**Comment by lhog** [comment]
Nice find https://github.com/beyond-all-reason/spring/commit/00a04d41aa8800c27deae0aaed24fb72313471b6
