### ISSUE TITLE
1359 Weird smudges and shadows on map, that move with camera

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#514]
The first full game I tested on this engine had quite a few weird things related to the map texture.
- Ground decals clipped through the terrain to a much greater extent than usual.
- There were smudges on the texture that would move around with the camera.
- At one point I saw what looked like a large version of the shadows cast by units, but off to the side in the fog of war. I could not reproduce this one.

Video of the first two: https://youtu.be/_foURT6jJeo

Replay: https://zero-k.info/Battles/Detail/1501018

**Comment by GoogleFrog** [comment]
This map may have misbehaving lava in it, but perhaps it is a good canary. Also relevant to #513.

**Comment by GoogleFrog** [comment]
I spectated a game with /specfullview and didn't see any similar issues.

**Comment by lhog** [comment]
I spectated that game as `/team 0` and didn't see anything like that either.

**Comment by lhog** [comment]
Likely fixed in https://github.com/beyond-all-reason/spring/commit/5450b20d03067b0db5e9cb21ecdc01fe243990ca , but I'll keep this one open.

**Comment by lhog** [comment]
I consider it fixed. Reopen if not.
