### ISSUE TITLE
Reinstate feature ghosts

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#515]
Wrecks that left LOS previously left a ghost, much like a structure ghost. This ghost would persist until the position of the wreck reentered LOS (to hide what happens to the feature while it is not scouted). These existed in 104.0.1-1656-gad7994a but seem to have disappeared as early as 105+841.

This is what they looked like:
![image](https://user-images.githubusercontent.com/1318249/203546789-678b3526-8d9a-49a1-b8d7-0b9f62917f52.png)

**Comment by lhog** [comment]
Hmm seems like Zero-K wants only gaia features to be always visible:
https://github.com/ZeroK-RTS/Zero-K/blob/master/gamedata/modrules.lua#L118-L125

Are you sure it's not a widget that we broke somehow?

**Comment by lhog** [comment]
I checked how it looks on 105.0. The feature ghost is indeed there, but disappeared after I disabled luaui.

**Comment by lhog** [comment]
Actually it works same on 1355.
![screen02244](https://user-images.githubusercontent.com/1476261/203783524-c003f9b8-761d-4ca6-a6be-a0ad07295a49.jpg)
![screen02245](https://user-images.githubusercontent.com/1476261/203783532-0f115e23-7970-4bbd-acc0-f4e2fb014308.jpg)

**Comment by lhog** [comment]
So no change is needed as per my screenshots or ... ?

**Comment by GoogleFrog** [comment]
No change. They came back somehow.

**Comment by lhog** [comment]
Good
