### ISSUE TITLE
1359: Changing lighting values breaks something

### ISSUE THREAD

**Issue by Arch-Shaman** [beyond-all-reason/spring#516]
Replication: https://youtu.be/3eZwXAXcUJo

Sorry, I don't know what that is called. Reported in [#Engine on zk discord](https://discordapp.com/channels/278805140708786177/911790552687730689/1045190524048519178).

**Comment by lhog** [comment]
Fixed https://github.com/beyond-all-reason/spring/commit/5450b20d03067b0db5e9cb21ecdc01fe243990ca
