### ISSUE TITLE
EngineCrash [105.1.1-1354-g72b2d55 bar] at [rts/Rendering/Fonts/glFont.cpp:187]

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#523]
**URL of infolog.txt**
https://server3.beyondallreason.info/teiserver/reports/infolog/8117

**Engine Version**
105.1.1-1354-g72b2d55 bar

This is an OOM crash!

**Translated Stack Trace with links**
<html><body>
<a href="http://imolarpg.dyndns.org/bar/stacktrace_translator/frontend/index.php" target="_blank"></a>
	<h1>translated with links to github source ('Spring 105.1.1-1354-g72b2d55 BAR105' detected)</h1>

module | address | file
-- | -- | --
b2d55 bar\spring.exe | 0x00007ff72820852c | rts/System/Platform/Win/CrashHandler.cpp :253 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/System/Platform/Win/CrashHandler.cpp#L253)
b2d55 bar\spring.exe | 0x00007ff728208f94 | rts/System/Platform/Win/CrashHandler.cpp :419 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/System/Platform/Win/CrashHandler.cpp#L419)
b2d55 bar\spring.exe | 0x00007ff7288d9843 | strsafe.c :1
b2d55 bar\spring.exe | 0x00007ff7280e62cf | /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/bits/vector.tcc :79
b2d55 bar\spring.exe | 0x00007ff7280e730d | /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/bits/unique_ptr.h :173
b2d55 bar\spring.exe | 0x00007ff7280e209a | rts/Rendering/Fonts/glFont.cpp :187 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/Rendering/Fonts/glFont.cpp#L187)
b2d55 bar\spring.exe | 0x00007ff7280e25f6 | /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/bits/vector.tcc :112
b2d55 bar\spring.exe | 0x00007ff727d989b8 | /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/bits/basic_string.h :195
b2d55 bar\spring.exe | 0x00007ff7282aab48 | rts/lib/lua/src/ldo.cpp :321 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/lib/lua/src/ldo.cpp#L321)
b2d55 bar\spring.exe | 0x00007ff7282bcb29 | rts/lib/lua/src/lvm.cpp :620 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/lib/lua/src/lvm.cpp#L620)
b2d55 bar\spring.exe | 0x00007ff7282aafad | rts/lib/lua/src/ldo.cpp :378 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/lib/lua/src/ldo.cpp#L378)
b2d55 bar\spring.exe | 0x00007ff7282ab3a7 | rts/lib/lua/src/ldo.cpp :119 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/lib/lua/src/ldo.cpp#L119)
b2d55 bar\spring.exe | 0x00007ff7282a3860 | rts/lib/lua/src/lapi.cpp :833 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/lib/lua/src/lapi.cpp#L833)
b2d55 bar\spring.exe | 0x00007ff7282a64ef | rts/lib/lua/src/lbaselib.cpp :378 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/lib/lua/src/lbaselib.cpp#L378)
b2d55 bar\spring.exe | 0x00007ff7282aab48 | rts/lib/lua/src/ldo.cpp :321 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/lib/lua/src/ldo.cpp#L321)
b2d55 bar\spring.exe | 0x00007ff7282bcb29 | rts/lib/lua/src/lvm.cpp :620 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/lib/lua/src/lvm.cpp#L620)
b2d55 bar\spring.exe | 0x00007ff7282aafad | rts/lib/lua/src/ldo.cpp :378 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/lib/lua/src/ldo.cpp#L378)
b2d55 bar\spring.exe | 0x00007ff7282ab3a7 | rts/lib/lua/src/ldo.cpp :119 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/lib/lua/src/ldo.cpp#L119)
b2d55 bar\spring.exe | 0x00007ff7282a3860 | rts/lib/lua/src/lapi.cpp :833 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/lib/lua/src/lapi.cpp#L833)
b2d55 bar\spring.exe | 0x00007ff727d9b7b6 | rts/Lua/LuaHandle.cpp :330 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/Lua/LuaHandle.cpp#L330)
b2d55 bar\spring.exe | 0x00007ff727da02e6 | rts/Lua/LuaHandle.cpp :424 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/Lua/LuaHandle.cpp#L424)
b2d55 bar\spring.exe | 0x00007ff727dac024 | rts/lib/lua/include/LuaInclude.h :220 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/lib/lua/include/LuaInclude.h#L220)
b2d55 bar\spring.exe | 0x00007ff728135d36 | /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/bits/stl_vector.h :919
b2d55 bar\spring.exe | 0x00007ff727be4ae8 | rts/Game/Game.cpp :1517 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/Game/Game.cpp#L1517)
b2d55 bar\spring.exe | 0x00007ff727bf1d1c | rts/Game/Game.cpp :1580 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/Game/Game.cpp#L1580)
b2d55 bar\spring.exe | 0x00007ff728175883 | rts/System/SpringApp.cpp :828 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/System/SpringApp.cpp#L828)
b2d55 bar\spring.exe | 0x00007ff728178b08 | rts/System/SpringApp.cpp :862 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/System/SpringApp.cpp#L862)
b2d55 bar\spring.exe | 0x00007ff72815ae6c | rts/System/Main.cpp :48 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/System/Main.cpp#L48)
b2d55 bar\spring.exe | 0x00007ff727bb13c1 | /mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c :323
b2d55 bar\spring.exe | 0x00007ff727bb14d6 | /mxe/tmp-gcc-x86_64-w64-mingw32.static/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c :178
s\SYSTEM32\ntdll.dll | 0x00000000000526a1 | ?? :0

</body>
</html>

**Comment by lhog** [comment]
OOM crash
