### ISSUE TITLE
I think movement pushing regressed from 841 to 1367

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#525]
Static units used to resist being pushed around. Now units move through/past static units without noticing that they are there. This lets units push anything at full speed, which is a clear problem, but I think it looks bad at smaller scales too. Not being able to walk right through units was a nice nod to realism which gives players a bit of a reason to consider a very forgiving version of "traffic jamming" while arranging their units. I think the new pushing may make pathing too smooth, and it results in must faster skids.

See examples: https://www.youtube.com/watch?v=Jbne6xuky0g

**Comment by GoogleFrog** [comment]
Setting modrules.movement.maxCollisionPushMultiplier=1 seems to almost entirely block push boosting, but doesn't solve the underlying issue of units being able to walk right through static units. The push multiplier just lets the units walk right through without causing the static unit to slide rapidly to the side.

maxCollisionPushMultiplier does not prevent push boosting for units that have slowed movement. Try my test but with a few Constables (jumpcon) attacking the unit that is being pushed.

**Comment by marcushutchings** [comment]
Fxied by https://github.com/beyond-all-reason/spring/commit/cdd7063361dcd9efc6f6fe5c22eb4703f9111069
