### ISSUE TITLE
EngineCrash [105.1.1-1354-g72b2d55 bar] at [ts/Sim/Path/TKPFS/PathManager.h :45]

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#528]
**URL of infolog.txt**
https://server3.beyondallreason.info/teiserver/reports/infolog/8162

**Engine Version**
105.1.1-1354-g72b2d55 bar

**Translated Stack Trace with links**
<html><body>
<h1>translated with links to github source ('Spring 105.1.1-1354-g72b2d55 BAR105' detected)</h1>

module | address | file
-- | -- | --
b2d55 bar\spring.exe | 0x00007ff6f5f9852c | rts/System/Platform/Win/CrashHandler.cpp :253 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/System/Platform/Win/CrashHandler.cpp#L253)
b2d55 bar\spring.exe | 0x00007ff6f5f98edd | rts/System/Platform/Win/CrashHandler.cpp :419 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/System/Platform/Win/CrashHandler.cpp#L419)
\System32\msvcrt.dll | 0x000000000002adfb | ?? :0
\System32\msvcrt.dll | 0x000000000002f1fb | ?? :0
b2d55 bar\spring.exe | 0x00007ff6f64ac38a | strsafe.c :1
b2d55 bar\spring.exe | 0x00007ff6f637ebd6 | strsafe.c :1
b2d55 bar\spring.exe | 0x00007ff6f66607e3 | strsafe.c :1
b2d55 bar\spring.exe | 0x00007ff6f666a0d8 | strsafe.c :1
b2d55 bar\spring.exe | 0x00007ff6f6498620 | rts/Sim/Path/TKPFS/PathManager.h :45 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/Sim/Path/TKPFS/PathManager.h#L45)
b2d55 bar\spring.exe | 0x00007ff6f621b586 | rts/Sim/Path/TKPFS/PathManager.h :235 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/Sim/Path/TKPFS/PathManager.h#L235)
b2d55 bar\spring.exe | 0x00007ff6f61bea4c | rts/Sim/MoveTypes/GroundMoveType.cpp :1790 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/Sim/MoveTypes/GroundMoveType.cpp#L1790)
b2d55 bar\spring.exe | 0x00007ff6f63afa29 | rts/Sim/MoveTypes/GroundMoveType.cpp :2187 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/Sim/MoveTypes/GroundMoveType.cpp#L2187)
b2d55 bar\spring.exe | 0x00007ff6f62cea19 | /mxe/usr/lib/gcc/x86_64-w64-mingw32.static/11.2.0/include/c++/bits/atomic_base.h :402
b2d55 bar\spring.exe | 0x00007ff6f5f20dc5 | rts/System/Threading/ThreadPool.h :139 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/System/Threading/ThreadPool.h#L139)
b2d55 bar\spring.exe | 0x00007ff6f5f2146e | rts/System/Threading/ThreadPool.cpp :228 (https://github.com/beyond-all-reason/spring/blob/72b2d55/rts/System/Threading/ThreadPool.cpp#L228)
b2d55 bar\spring.exe | 0x00007ff6f666a4d1 | strsafe.c :1
b2d55 bar\spring.exe | 0x00007ff6f636be9d | thread.c :1
\System32\msvcrt.dll | 0x000000000003af5a | ?? :0
\System32\msvcrt.dll | 0x000000000003b02c | ?? :0
S\SYSTEM32\ntdll.dll | 0x00000000000526a1 | ?? :0

</body>
</html>

**Additional context**

**Comment by marcushutchings** [comment]
Is this a one-off case or do we have multiple reports of this?

**Comment by marcushutchings** [comment]
Also, what was the crash reason? OOM or segfault?

**Comment by Beherith** [comment]
`[t=02:17:51.025285][f=0227005] Error: Spring received an ABORT signal
[t=02:17:51.025340][f=0227005] Error: Error handler invoked for Spring 105.1.1-1354-g72b2d55 BAR105.
[t=02:17:51.065846][f=0227005] Error: DLL information:`

This one ive yet to see, so one-off

**Comment by marcushutchings** [comment]
An abort signal? It is highly unlikely that the issue is where the back trace is pointing to - it is likely the symptom. Likely memory corruption has happened and this is where we've stubbled upon it.

**Comment by marcushutchings** [comment]
I don't think we can progress this issue without seeing a pattern emerge.
