### ISSUE TITLE
Race conditions(?) during construction lead to multiple units being produced in the same place

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#529]
http://zero-k.info/Forum/Thread/35868

**Comment by lhog** [comment]
Let's consider it complete. There could still be issues related to synced/unsynced changes, but these should be addressed separately.

**Comment by marcushutchings** [comment]
I need to take a closer look at this one.

**Comment by lhog** [comment]
Any specific concerns?

**Comment by marcushutchings** [comment]
The fix for this stops buildings from blocking movement and pathing. I've soted out the blocking issue for pathing/movement, but the fix for this issue is going to need a little more work. I'll look to get it sorted for the next engine release after this one.

**Comment by marcushutchings** [comment]
Okay. It seems that the bit I'm looking at doesn't impact this issue.
