### ISSUE TITLE
1388 Circuit AI crash on load

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#536]
The circuit AI built for 1344 worked fine up until 1367. Then I tried updating past 1367 (either 1373 or 1375) and it crashed. Just now I used the version built for 1388 on 1388, and it still crashed.

[infolog_full.txt](https://github.com/beyond-all-reason/spring/files/10122252/infolog_full.txt)

**Comment by badosu** [comment]
I removed weapondefid indexing changes from history, will fix this properly and in a timely manner since it's a sensible core part of the engine and entangled API from CircuitAI
