### ISSUE TITLE
Feature request: standalone GetModelPieceList

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#540]
### What currently exists

There's a handful of functions to get piece information about a thing's model:
 * `Spring.GetUnitPieceList(unitID)` → `{ [1] = "base", [2] = "turret", ... }`
 * `Spring.GetUnitPieceMap(unitID)` → `{ .base = 1, .turret = 2, ... }`
 * `Spring.GetFeaturePieceList(featureID)` → `{ [1] = "base", [2] = "turret", ... }`
 * `Spring.GetFeaturePieceMap(featureID)` → `{ .base = 1, .turret = 2, ... }`

Note that the current state of affairs technically allows individual units using the same model (regardless of unit type) to have different piece mappings. For example if Peewees use the model `peewee.s3o` which has pieces `left_arm`, `right_arm` and `torso`, maybe one Peewee could have a mapping like `{ .left_arm = 1, .right_arm = 2, .torso = 3 }` as its pieces but another Peewee could have  `{ .torso = 1, .right_arm = 2, .left_arm = 3 }`.

Note also that `Spring.GetUnit/FeaturePieceInfo` exists and returns parent/children of the piece, but also geometry size etc.

### Feature request

The request is, first, to give a guarantee that each unit using a model has the same piece to ID mapping (in a given Spring session - it doesn't need to stay constant if you run the engine another time). AFAIK this already essentially happens, but it might be worth thinking whether that closes some doors to interesting stuff in the future (units somehow mixing pieces from different models? idk).

The substantial part of the request is to expose standalone functions that don't require a unit/feature to exist, and take a model as an argument instead (ideally such that passing `UnitDefs[x].modelname` or `.modelpath` works). So for example:
 * `Spring.GetModelPieceList("tank.s3o")` → `{ [1] = "base", [2] = "turret", ... }`
 * `Spring.GetModelPieceMap(UnitDefNames.tank.modelname)` → `{ .base = 1, .turret = 2, ... }`

`Spring.GetModelPieceInfo` is **not** in the scope of this request. I'd expect the parent/children part to be trivial if the two functions above existed but I don't know about the geometry part (which can legitimately differ per unit instance) and not having the same set of returned values for Model and Unit/Feature would be inelegant.

**Comment by lhog** [comment]
Untested, but should work

**Comment by lhog** [comment]
Reopen in case it doesn't
