### ISSUE TITLE
Enable VAO run with an empty VBO

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#551]
Recently a check was added, whether the corresponding VBO has enough elements:
https://github.com/beyond-all-reason/spring/blob/ddd24c64f03a419e3976e2ef9dbde257721b0d91/rts/Lua/LuaVAOImpl.cpp#L284
Which made me unable to run a VAO with an empty VBO (such as a dummy VBO, that is meant to fail abovementioned check of course).
Particularly I used it with tessellation, where actual vertices are generated in a shader based on a vertex index (and the number of instances itself is good to be flexible). I think, this is a common technique, that has several merits.
As a quick solution, I propose to reduce this error to warning.

**Comment by lhog** [comment]
https://github.com/beyond-all-reason/spring/commit/48ebbca6f71479d0d174dac6815f6f8bfae5ab12 should have fixed it.
We're just picking a right time to make a release.
