### ISSUE TITLE
Can't compile with docker

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/spring#560]
Since https://github.com/beyond-all-reason/spring/pull/448 has been discontinued I have switched back to the upstream docker build system and after `./init_container.sh`, on `./build.sh` I get:

```
CMake Error at rts/build/cmake/PreferStaticLibs.cmake:12 (message):
  You cannot toggle `static linked` once you run cmake! You have to use a
  cmake `toolchain` file to enable this flag!
Call Stack (most recent call first):
  CMakeLists.txt:25 (include)
  ```
 
You can find the detailed logs [here](https://gist.github.com/badosu/9115e1bff018f305ff1b183d6c47aaf0).

This section of `CMakeError.log` seems particularly relevant:

```
FAILED: cmTC_dc577 
: && /usr/bin/gcc -DCHECK_FUNCTION_EXISTS=vorbis_bitrate_addblock -rdynamic CMakeFiles/cmTC_dc577.dir/CheckFunctionExists.c.o -o cmTC_dc577  -Wl,-rpath,/conan/.conan/data/ogg/1.3.5/_/_/package/1748639999ed79b998e4fe4a6d292ed8e874736a/lib:/conan/.conan/data/vorbis/1.3.7/_/_/package/690443e5418de45fba363cc58b7a7e5cdf0e5a55/lib  -lvorbis  /conan/.conan/data/ogg/1.3.5/_/_/package/1748639999ed79b998e4fe4a6d292ed8e874736a/lib/libogg.so  /conan/.conan/data/vorbis/1.3.7/_/_/package/690443e5418de45fba363cc58b7a7e5cdf0e5a55/lib/libvorbis.so  /conan/.conan/data/vorbis/1.3.7/_/_/package/690443e5418de45fba363cc58b7a7e5cdf0e5a55/lib/libvorbisfile.so  /conan/.conan/data/vorbis/1.3.7/_/_/package/690443e5418de45fba363cc58b7a7e5cdf0e5a55/lib/libvorbisenc.so && :
/usr/bin/ld: cannot find -lvorbis: No such file or directory
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

**Comment by lhog** [comment]
Works for me in general, try deleting `bar-spring:latest` container image and cache files.
I had to restart `./build.sh` once, because of some weird errors, but on the second run it worked just fine. For both Windows and Linux builds. Most likely because of OOM due to a limited VM RAM space.

**Comment by p2004a** [comment]
You are doing something wrong, delete all the build directories, any existing containers etc. In your build log there is 

```
/usr/bin/g++   -march=i686 -o CMakeFiles/cmTC_ec4e4.dir/DummyCXXFile.cxx.o -c /usr/share/cmake-3.24/Modules/DummyCXXFile.cxx
```

which sounds incorrect because in docker image the cmake is only 3.16: https://github.com/beyond-all-reason/spring/blob/BAR105/docker-build/Dockerfile#L51

**Comment by badosu** [comment]
Thanks for the responses, I pruned everything in docker and removed anything that might interfere with the build process, seems to be working properly now.
