### ISSUE TITLE
(Low priority) UBO(glsl):drawSeconds and GetDrawSeconds()

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#561]
Current Spring's UBO provides following time info:
`    vec4 timeInfo;     //gameFrame, gameSeconds, drawFrame, frameTimeOffset`
_As far as I understood_, gameSeconds is nothing more than a gameFrame multiplied by a constant.
I propose to replace gameSeconds there with _drawSeconds_.
_drawSeconds_ will be a total time since the launch, or first lua draw, or it could also be reset upon lua reload to 0 (which may be good), doesn't matter.
The point is to have a value that is useful for GUI animations and such stuff, similarly as we obtain World time (gameFrame+frameTimeOffset)/30.

To accompany that, Lua will also need a GetDrawSeconds() function, providing exact same value.

**Comment by lhog** [comment]
Yes, `gameSeconds` is not super useful, but equally uncertain how use `drawSeconds` would be as as far as the game is concerned `drawFrame + frameTimeOffset` should give you what you're looking for.

**Comment by Krogoth100** [comment]
> Yes, `gameSeconds` is not super useful, but I'm equally uncertain how useful `drawSeconds` would be as as far as the game is concerned: `drawFrame + frameTimeOffset` should give you what you're looking for.

drawFrame is a (sequential) number of the frame. If we lock an animation of some GUI element to a drawFrame, that will mean that animation will slow down significantly whenever FPS drops (prolonging each frame perceptually).
This is not how you like to animate the most GUI elements, because unlike simulation events, it should be tied to perceptual, actual time, rather than preserving continuity of states as what is important for World time.
If an FPS drops to a low value, a simple highlight of a button should not take more time, but rather light up quicker.
To clarify on an example of a highlight, you take Current draw frame, substract highlight Start draw frame and get the brightness of a highlight.
If we were to base it off drawFrame, it would all feel sluggish and _unresponsive_, so a feed of actual draw time is needed.

**Comment by Beherith** [comment]
I agree that a separate real world seconds is more useful than a const multiplied ganeframe, but whenever i need stuff like this, i just pass in a uniform.

**Comment by Krogoth100** [comment]
It's not a matter of finding solution, I was thinking of improving existing interface for more comfort, but I think it's not the right time, because the more I work, the more candidates appear for inclusion like this, so it is not conclusive.
Maybe we should revisit this question a few months or a year later when more actual code has been written and proven, and we might refine Spring's UBO to make it most useful in accord to what's people been using. I am putting myself a Low priority tag on this, so you may not lose time on this, or close for now.

**Comment by lhog** [comment]
I'm yet to have a look at a possible implementation, but if anyone has seen something like `drawSeconds` already existing in the engine, let me know.

**Comment by lhog** [comment]
Let's consider it done. @Krogoth100 pls reopen if it doesn't work.
