### ISSUE TITLE
1455 Black ground decals, no outline on some units

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#569]
![image](https://user-images.githubusercontent.com/1318249/210928584-6147c388-e8bc-4ff5-9ae4-f901a1bbfd1a.png)
[infolog.txt](https://github.com/beyond-all-reason/spring/files/10357274/infolog.txt)

This happened on about the 20th game I launched and we had about 100 player-launches without anyone reporting this.

**Comment by Beherith** [comment]
Just a side note, but you may want to switch to ground ao plates gl4 instead of engine ground decals

**Comment by GoogleFrog** [comment]
I am not sure what you mean. Are you saying the engine has dropped support for ground decals? I don't use them only for ao plates. Is the ao plates gl4 compatible with everyone and ready to go? Because engine ground decals are.

**Comment by lhog** [comment]
I'm not able to reproduce that.
Any reports about the graphical glitches should have `/debuggl 1` when such glitch appear, because the log gives no hint what went wrong.

Send a replay please.

**Comment by GoogleFrog** [comment]
The replay is trivial as it is at the very start of the game. Do you have a dev mode ZK campaign? Planets can be autounlocked in chobby with dev mode enabled. The spawn is planet Bluebell on Normal, which is near the top of the galaxy.

**Comment by GoogleFrog** [comment]
[20230107_010515_Calamity 1_105.1.1-1455-gd1eaabf BAR105.sdfz.txt](https://github.com/beyond-all-reason/spring/files/10365224/20230107_010515_Calamity.1_105.1.1-1455-gd1eaabf.BAR105.sdfz.txt)

**Comment by lhog** [comment]
Good, I tested this demo on the later version with unhardcoded LoadingMT and it's related to that setting.
Tagging as an engine bug.
