### ISSUE TITLE
Unit Weapon and scripts lag

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/spring#573]
Reproduce:
1. Set weapon range multiplier to 5 in modoption.
2. Spawn 500 armjanus and select it.
3. Attack the ground.
4. Start changing locations of attack on ground until it's start to lag.

https://youtu.be/QGf2RdyIExs

Bug was introduced in spring-105.0 (spring_104.0 immune).
As i understand lag is happening every 0.5 seconds.

**Comment by 6AKU** [comment]
Personally i suspect something off in cob/bos scripts

**Comment by sprunk** [comment]
Try with lua states disabled? This may well be a gameside issue.

**Comment by 6AKU** [comment]
@sprunk lua states? How to disable lua states?

**Comment by sprunk** [comment]
In general you do `/luaui disable` and `/luarules disable`. You can do just one of them if this breaks too much, but ideally you'd do both. I don't know if that is sufficient for BAR or whether you would have to do something more (if it's not sufficient then somebody from BAR could know what else you need to do). This disables a lot of game mechanics and UI but shooting units and the engine debug view should be fine. You can bring lua states back with `/luaui enable` and/or `/luarules enable`.

**Comment by 6AKU** [comment]
Ok, i tried. No effect at all on this problem.

**Comment by 6AKU** [comment]
Replay
[20230213_074039_All That Glitters v1_105.1.1-1525-g4f26ffc BAR105.zip](https://github.com/beyond-all-reason/spring/files/10719795/20230213_074039_All.That.Glitters.v1_105.1.1-1525-g4f26ffc.BAR105.zip)

**Comment by 6AKU** [comment]
![Снимок](https://user-images.githubusercontent.com/116835691/218472246-3deb610f-9629-4291-9e16-8f10b546b2df.PNG)

**Comment by p2004a** [comment]
I've reproduced this and this is caused primarily by the aiming COB threads piling up a lot in this scenario. Then there are command like SIGNAL that have to iterate over a very long list of threads and update each one by one. The number of active threads for 500 janus can spike to > 100000. The storage of threads is also a one big flat hash map, and operations on it are very slow.

This is *why* it happens, but I'm yet to figure out how to exactly optimize it, I'm still ramping up on the semantics of COB threads, what is expected behavior with them, what isn't, what is the high level algorithm of their management...

**Comment by KyleAnthonyShepherd** [comment]
I'll take a look at the Janus BOS/COB, see if there is something causing a thread pileup

**Comment by KyleAnthonyShepherd** [comment]
Hmmm... The armjanus script could be tuned a little bit. It is a bit weird with the 2 weapons, but the second one slaved to the first. 

Lag every 0.5 seconds makes sense, as the AimPrimary/Secondary functions are called every 15 frames for armjanus. 

Only conflict point I see is both Aim functions are trying to turn the turret to different headings at the same time, but not sure how that would cause a thread explosion

**Comment by 6AKU** [comment]
P.S Armjanus is not only unit that affected by this problem. For example armguard is also affected.

**Comment by KyleAnthonyShepherd** [comment]
FirePrimary and FireSecondary have unnecessary sleep statements, causing those threads to spawn and exist for 0.15 seconds, 4-5 frames, so SIGNAL could be iterating over those unnecessarily.

**Comment by KyleAnthonyShepherd** [comment]
Ah, I was gonna ask if Armjanus was unique, or if units like armstump also has this issue.

armguard also has two weapons, for high/low trajectory stuff, but should break out of the "extra" aimweapon thread very quicky.

**Comment by 6AKU** [comment]
Another example: corint. It's also have it

**Comment by pandaro** [comment]
have to do with very long range weapons?

**Comment by sprunk** [comment]
> The number of active threads for 500 janus can spike to > 100000.

This sounds like either a bug with thread handling or a mistake in Janus script. An individual Janus should never have 200 threads! It should never really have more than 4 threads active at a time (aim weapon 1, aim weapon 2, smoke, plus one for whichever event is currently being handled).
