### ISSUE TITLE
Explosion may trigger unit start wander across map without explicit command

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/spring#574]
Reproduce:
1. Spawn 100 corkorg
2. Spawn 1 armcom somewhere between corkorg units.
3. Explode armcom.
4. Repeat if didn't work.

Terrain deformation option have no affect on this bug.

https://www.youtube.com/watch?v=n3-v0I3IN7o

**Comment by marcushutchings** [comment]
Fixed in https://github.com/beyond-all-reason/spring/commit/8c81a5d96d6928fce03c35921e0348c5408477f6
