### ISSUE TITLE
Spring-dedicated and anything using unitsync gets its core affinity set to last CPU core

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#575]
This has surfaced in SPADS, where even the spads process itself gets its CPU affinity set to the last core. Spring-dedicated is also set to use the last core. 

Yaribz has investigated : FYI I managed to reproduce your problem just by switching to BAR engine, so I can confirm this is the BAR engine which reduces the CPU affinity mask of any component calling the unitsync library and it's not related to SPADS, so I will stop investigating this problem

See the discussion here for details on taskset etc. https://discord.com/channels/549281623154229250/564591092360675328/1061178093408104478

TK if you could perhaps take a look at this one?

**Comment by marcushutchings** [comment]
So to confirm, the request is that the spring dedicated doesn't set CPU affinity?

**Comment by marcushutchings** [comment]
I'll investigate unitsync.

**Comment by Beherith** [comment]
Yes, spring-dedicated and unitsync shouldnt set cpu affinity, as they now all pack onto one core.

**Comment by marcushutchings** [comment]
Fixed https://github.com/beyond-all-reason/spring/commit/321a7f140f934858703626ba6eb5d7f62a9398c7
