### ISSUE TITLE
Mex extraction calculation issues

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/spring#578]
At least for the moment a pathological case has been observed with the SetUnitMetalExtraction API after the extraction change on activation changes: f9679c363b17e3391255c18de7be095be6de1c9e and 801cd6d1a5c61140a478607e03997384ad9feabb

This can be reproduced with running metal faction $VERSION, giving mex and turning them on and off. Most likely either due to the API usage at https://github.com/springraaar/metal_factions/blob/master/luarules/gadgets/unit_mex_radius.lua or https://github.com/springraaar/metal_factions/blob/master/luarules/gadgets/unit_power_grid.lua

**Comment by badosu** [comment]
@springraaar I hear you've been able to reproduce a pathological case with luarules disabled?

**Comment by springraaar** [comment]
I think the issue requires luarules enabled with calls to SetUnitMetalExtraction, but after the bug happens, disabling luarules and destroying the offending units won't fix it.

If i spawn another mex nearby it'll inherit the crazy extraction rate (+millions/s, or nan)

**Comment by badosu** [comment]
Yes, I have an idea of what causes it. Unfortunately I'm having difficulties getting a build going, but I should be able to fix it. In the end we can just revert mex on activation instead of creation on the worst case scenario.

**Comment by badosu** [comment]
I'm rebuilding now, will address this today. Thanks for the patience @lhog

**Comment by badosu** [comment]
Fixed on https://github.com/beyond-all-reason/spring/commit/52579c2c037b02198e564339cb63ea174de5f1f3
