### ISSUE TITLE
1478 check pathfinding

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#585]
Maybe an existing bug. I only saw the marker at the end. The game is short.

![image](https://user-images.githubusercontent.com/1318249/212519627-52053f9a-5619-4cd1-85d6-33b5011be91d.png)

[20230115_021427_Mercurial v1_105.1.1-1478-gbc6400c BAR105.sdfz.txt](https://github.com/beyond-all-reason/spring/files/10419332/20230115_021427_Mercurial.v1_105.1.1-1478-gbc6400c.BAR105.sdfz.txt)

**Comment by GoogleFrog** [comment]
For about 30 seconds before:

![image](https://user-images.githubusercontent.com/1318249/212520142-4d04c713-8fa7-466d-bb78-ea01eb24414b.png)

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/212520538-3fd4b5ea-551d-45c4-9fe5-d8ee857c3b16.png)

Now with an engine command (Fight)
![image](https://user-images.githubusercontent.com/1318249/212520551-d6b4198a-1dc5-4015-9961-3dea87d2af58.png)
They give up about halfway through.

Open side
![image](https://user-images.githubusercontent.com/1318249/212520593-17b3e3a5-173c-4030-953f-3faeb7844bcc.png)

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/212520688-80ec4c6e-5eb1-46cd-a762-2b3c4f0354dd.png)

Fight seems to be dropped next SlowUpdate
![image](https://user-images.githubusercontent.com/1318249/212520706-db840a05-c8e9-4172-8303-749c59c4e203.png)

Open side
![image](https://user-images.githubusercontent.com/1318249/212520730-0a4cdf98-bfbd-4e40-9130-b1e90b7dca40.png)

**Comment by GoogleFrog** [comment]
Being stuck like this for 5 or so seconds reproduces.
![image](https://user-images.githubusercontent.com/1318249/212520847-8dd44b0b-3190-4d36-90a5-12d3b70f1584.png)

**Comment by GoogleFrog** [comment]
I suspect structures are not showing up as blocking to some types of pathfinding check. Possibly just checks around whether to do raw move. My move command replacement checks for structures and falls back to non-raw move. I didn't check what lua can see.

**Comment by marcushutchings** [comment]
Yes, I noticed this yesterday. You are on the right track. The pathing system is not updating the mid/low res routes when buildings are placed. I am working on a fix for that (and that should also address this issue.)

**Comment by marcushutchings** [comment]
Should be fixed by https://github.com/beyond-all-reason/spring/commit/d69fb498bed99f075f37df480ea970ceb3c7c686
