### ISSUE TITLE
1478 Nanoframes no longer have outlines (ZK)

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#586]
They have outlines in 1393. This will be to do with what gets to be drawn with the special buffer thingy. I am more worried about there being an unintended change than the effect of the change (that I know of) itself.

**Comment by lhog** [comment]
What kind of outline shader you use these days?

**Comment by lhog** [comment]
Are you sure about that?

This is on 1392:
![screen02281](https://user-images.githubusercontent.com/1476261/212535969-858b87ab-037e-449d-b4a7-fb7c9aa47427.png)
![screen02280](https://user-images.githubusercontent.com/1476261/212535965-4637b873-893b-46db-947e-e732f08ae524.png)

**Comment by GoogleFrog** [comment]
Ah I remember. I thought nanoframes had outlines before because they "do" in some factories, by vitue of the factory having the outline and being masked by the nanoframe.
