### ISSUE TITLE
Replace manual commands with `make install`

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#59]
Good first issue if you're into devops is refactoring the build to remove all these cp and rm's: https://github.com/beyond-all-reason/spring/blob/BAR/.github/workflows/build.yml#L348-L435

This is supposed to be replaced with make install, so a few things need to happen:
* Install prefix needs to be supplied during cmake configuration
* manual cp/mkdir commands replaced with make install
* the whole thing needs to be tested, so at first probably inside a docker container, secondly on github runner: the file has commented section that allows to log in into the running (&paused) workflow, so the section must be moved before or after make install step, un-commented, and upon login tested if it does everything as expected (installs into correct directory, the files structure is consistent with status quo, etc). The last step can be done at your own github fork of BAR/spring.

**Comment by lhog** [comment]
AFAIK done by @verybadsoldier

**Comment by verybadsoldier** [comment]
Yes, confirmed.
