### ISSUE TITLE
Metal Extraction radius reverts to map defaults after turning OFF then ON

### ISSUE THREAD

**Issue by springraaar** [beyond-all-reason/spring#592]
engine : BAR105 1478
game : metal factions v1.99  
(calls Spring.SetUnitMetalExtraction(...) to extend extraction radius to 100 for mex and 130 for adv mex on UnitFinished)
map : shallow straits v1 (extraction radius = 55)

to reproduce, build a metal extractor, then use /showmetalmap to view the extraction radius. Then turn it OFF then ON : the extraction radius should remain the same but instead shrinks back to the map default.

Another gadget also calls Spring.SetUnitMetalExtraction(...) but it doesn't specify the radius, so it shouldn't affect it. Disabling that gadget doesn't prevent the issue so it seems just turning the mex on/off is enough.

This issue doesn't happen on 105.0

**Comment by badosu** [comment]
Ok good, I know what it is, thanks for reporting!

**Comment by badosu** [comment]
Unclear yet whether `::PostLoad` or `::PostInit` are more suitable candidates in the lifecycle to be used, if you have an idea let me know. At least i know `::PreInit` sets the unitDef so I used it after all parents `::PreInit`.

cc @lhog @marcushutchings
