### ISSUE TITLE
1485 Probably new save crash, possibly AI related

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#598]
Apparently these save games crash within five minutes of loading them. http://zero-k.info/Forum/Thread/36102?postID=256649

Almost all singleplayer ZK involves circuit, so it could be AI related.

**Comment by lhog** [comment]
I'll try their savegames and see where it crashes.

**Comment by lhog** [comment]
>I tried loading a few new save games after the update, and the game did not crash once. I will test out some more to see if it is indeed fixed. Thank you for your help. 

I also fixed invalid decals happening during the savegame load with `LoadingMT = 1` here https://github.com/beyond-all-reason/spring/commit/6fb5cff57978de43fbd319ad75319bc38e860dcb
With that I think `LoadingMT = 1` is almost ready for production use.
