### ISSUE TITLE
Investigate why reflection map has unit shadows and remove them if it's costly to have.

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#6]

**Comment by icexuick** [comment]
Good plan!

Also might as well try to find out why the cubemap order is wrong.

**Comment by lhog** [comment]
Wdym by "order"?

**Comment by icexuick** [comment]
i meant the order/alignment of the 6 sides in the reflection.

**Comment by marcushutchings** [comment]
This has seen no updates for a year. Is it still something that needs attention?

**Comment by lhog** [comment]
It's what it is. Reflection pass uses the same shader as regular forward pass to do terrain shading. By that time unit shadows are part of the shadow map, so not much can be done.
