### ISSUE TITLE
Prefer dedicated GPU over integrated on Windows

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#60]
See https://springrts.com/mantis/view.php?id=6437 (I figured nobody looks there) and also https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2758 .

If there is both an integrated and a dedicated graphics card, it seems that the integrated card often gets used by default. Apparently sticking the following somewhere changes the default to the dedicated one:
```cpp
/* If both an integrated and a dedicated graphics card are found,
 * make the dedicated one used by default (usually superior).
 * nVidia and AMD achieve this via the presence of a magic var. */
extern "C"
{
  __declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 1; // AMD
  __declspec(dllexport) unsigned long NvOptimusEnablement = 0x00000001; // nVidia
}
```

**Comment by lhog** [comment]
Kinda there already, but probably don't do much (at least I haven't seen any evidences they do)
https://github.com/beyond-all-reason/spring/blob/BAR/rts/System/Main.cpp#L26-L28

**Comment by lhog** [comment]
But I should mention these symbols only became exported in BAR branch. Vanilla spring doesn't do that.

**Comment by sprunk** [comment]
Cool, thanks.
