### ISSUE TITLE
(Feature request) Font:GetTextWidth: return maximum number of visible characters in a line as well

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#606]
Currently GetTextWidth returns width of the text, and GetTextHeight returns height, descender and number of lines of the text.
The proposition is for GetTextWidth to return a maximum number of visible characters in a line, as a second return value.
A common thing in design is to use an extra char spacing for a font. It makes a text element stand out, for example, a title, and generally gives more ways to use a font. Often it goes with the letters all-caps, like: S O M E _ T I T L E.
It would be convenient if a Spring function provided an easy way for calculation of such text's boundaries (because this is what often defines the width of a text element), such as the proposed number of characters for a line which you can multiply by spacing factor and add up to default width to receive corrected text width. (The draw itself is practically no problem and done trivially, because these texts are generally one-liners)

**Edit:**
I should clarify, this has relevance at all because a text may combine invisible symbols and operators, like color/style operator. If a text was simple and one-liner, you could just take the length of a string, but this doesn't apply to all texts of course. So you parse it in Lua yourself, unless you get a function for that.

**Comment by Krogoth100** [comment]
Actually, scrap it. Current Font's API is badly compatible with this task.
I will be writing a Lua wrapper that can render multi-line text with arbitrary extra char spacing and line interval.
Most likely I will be converting fonts to signed distance fields (SDF), because SDF allows to control thickness.
All this came out as necessity when I tried to use a bunch of free fonts, and it appears that none of them look right, and the places where they are showed and look good, actually use better rendering techniques than what we have here.
It is nearly impossible to make a text (at least among selection of free fonts) look good without this "extra" freedom.
I shall re-visit this complicated task in future when I have something to show.

**Comment by lhog** [comment]
I quickly tested the SDF option of FreeType a few months ago and the result was way below the expectations.
If you can make it work, it'd make for an awesome PR.
