### ISSUE TITLE
Fill-up construction wireframe has changed.

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#61]
![image](https://user-images.githubusercontent.com/1318249/127317744-6fad5d0a-f1de-4b14-b795-63a87cbc13bc.png)

The construction wireframe for energysolar in ZK does not show any switches suddenly between the three construction animation states with no fill-up in between. I recall there being some underground piece hax involved to make the construction blueprint of the unit show as open rather than closed, which is probably the cause. Regardless, this works in the engine ZK is on.

I have come across this issue before and suggested tags to set the maximum and minimum heights that the build animation should range over, the save the engine from trying to deal with edge cases.

**Comment by lhog** [comment]
Interesting case. I don't recall any changes that might have caused that directly.
Could be some extra GL state I set in BAR. I'll investigate.

As for the second I'm in the middle of near complete rewriting of {Unit,Feature,Projectile} drawers so they have GL4 backend. Right now the build stages are all hardcoded, so it's a good time to raise special feature requests like the one you listed.

**Comment by sprunk** [comment]
Solar starts off with its "real" pieces 90000 elmos high in the sky which are moved back to the ground in `script.Create` such that the model again fits in 50 or so elmos. It sounds as if the BAR engine caches the initial height while the old maintenance (ZK) engine takes the changes from `script.Create` into account. Maybe [throbbing Dantes](https://www.youtube.com/watch?v=wCfmtbODQ5I) could be compared to see how it works at runtime?

**Comment by lhog** [comment]
Hmm, I've checked the behavior in both BAR and 1544 maintenance on upstream ZK and found no difference in the way things look.

![screen01979](https://user-images.githubusercontent.com/1476261/127348132-b5f0d930-05d0-4013-85a3-a4badf8196a7.png)
![screen01980](https://user-images.githubusercontent.com/1476261/127348140-bb3011ef-d802-46ec-a1ee-845beafd2715.png)
![screen01981](https://user-images.githubusercontent.com/1476261/127348145-cf8debab-5713-4d64-ad39-7bbce0e01836.png)

Things switch looks at 33% and 66% completion as it should. The reason you don't see smooth transition is linked to the fact that model is 90k+ elmos high and height is part of the rendering formula: https://github.com/spring/spring/blob/master/rts/Rendering/UnitDrawer.cpp#L1466

But that is again same in both engines.

**Comment by sprunk** [comment]
How about changing that line from `CalcDrawHeight` to `GetDrawHeight`? Then we could just set Solar height to 50 in the .s3o file.

**Comment by lhog** [comment]
That'll likely be a breaking change and I'm yet sticking to the approach that nothing should get broken (although temptation is high to do otherwise). 

Comment here says that min/max bounds could be overridden, but I found no means to do so, except via supplying special table for AssImp models. So perhaps an extra callout similar to Spring.SetUnitRadiusAndHeight / Spring.SetFeatureRadiusAndHeight can safe the day.

**Comment by lhog** [comment]
Yeah not bad.

![screen01988](https://user-images.githubusercontent.com/1476261/127362541-1a774c1a-22b2-4ed9-ad00-1d80390bccf9.png)

The further investigation is needed though how many games touch `height` and potentially set it to some incorrect value.

**Comment by sprunk** [comment]
IIRC that height is where healthbars are drawn so most units will have a correct value there.

**Comment by lhog** [comment]
Ok, as we are in the process of review all minor or new items are stashed in the feature branches. The one replacing `Calc` with `Get` for the purpose of construction rendering is one of them now. Last screenie is made with this branch code.

Let me know if there is anything else needed here.

**Comment by sprunk** [comment]
To me this looks done, maybe @GoogleFrog should say something though (especially since he said it worked on ZK 1544?)

**Comment by GoogleFrog** [comment]
I must have been mistaken.
