### ISSUE TITLE
Recruiting for engine articles/guides

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/spring#610]
Recruiting anyone interested into writing:

- Guides on parts or the whole of the involved effort into building a game using the engine (maps, models, unit scripts, gadgets, widgets, etc..)
- Technical deep-dives on how the engine works (for new contributors and promotion)
- News (?)
- Any content that improves on current text or expands into what makes sense for the site

See [this page](https://beyond-all-reason.github.io/spring/) and [its source](https://raw.githubusercontent.com/beyond-all-reason/spring/BAR105/doc/site/index.markdown), create a new file with similar structure and [refer to the documentation on utilities](https://just-the-docs.github.io/just-the-docs/docs/ui-components).

The page should be automatically added, let me know if you want to and is having problems to build locally and test. Generally having a recent ruby version and running `bundle && bundle jekyll build && bundle jekyll serve` inside `doc/site` should do the trick.

Content updates everyday at midnight (on whatever timezone github actions uses), the workflow can be manually triggered to update site if necessary (Publish Site).

cc (but not exclusive to) @Beherith @lhog @p2004a @marcushutchings @sprunk @rlcevg

**Comment by badosu** [comment]
In particular I think an updated version of ["The Complete Guide..."](https://springrts.com/wiki/The_Complete_Guide_To_Making_A_Spring_Game) with a guide for each step would be extremely useful to showcase the engine (and easier to digest/write in a reasonable pace).

**Comment by marcushutchings** [comment]
I have some articles in mind:
1. Overview of how the pathing system works
2. How the dynamic smooth mesh works

**Comment by badosu** [comment]
I added some sample files, see [an article](https://github.com/beyond-all-reason/spring/blob/BAR105/doc/site/articles/pathfinding.markdown) and [a guide](https://github.com/beyond-all-reason/spring/blob/BAR105/doc/site/guides/widgets.markdown). Notice the `published: false`.

**Comment by sprunk** [comment]
The samples are just some metadata for unpublished files, how do I make a proper article? How do I check if the formatting etc is ugly before the page is merged?

**Comment by badosu** [comment]
Type markdown below the metadata table.

See https://just-the-docs.github.io/just-the-docs/docs/index-test/ and sibling links.

For testing, have a reasonably recent ruby version, run `bundle && bundle jekyll build && bundle jekyll server` inside `doc/site`, access https://localhost:4000/spring

**Comment by badosu** [comment]
You can use [this article](https://github.com/beyond-all-reason/spring/compare/badosu/article?expand=1) I am writing as a reference.

**Comment by sprunk** [comment]
Thanks, the reference looks sufficient for me so far.
