### ISSUE TITLE
1485 Intel driver crash

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#613]
Not sure if these are reportable, but here it is http://zero-k.info/Forum/Thread/36128

**Comment by lhog** [comment]
This on in particular is not something we can deal with. It's probably some sort of VRAM OOM. Usual advises here are first of all to update their driver, and then activate potatoe mode: disable shadows, deferred rendering for map and units, disable MSAA, choose smaller resolution etc.

There's another issue with Intel graphics though. Some of them crashes in font shader creation code or around that. if we can track a capable user who can debug it interactively with me, we should be able to work it around.
