### ISSUE TITLE
Camera tracking disabling if try rotate camera

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/spring#626]
1. Switch to spring camera (Ctrl+F3).
2. Start tracking unit with key T.
3. Hold Alt+middle mouse button start to drag with mouse.

If mouse cursor is hidden, tracking is working (click middle mouse button for hiding mouse cursor)

https://youtu.be/U1FXV7HxEcQ

**Comment by 6AKU66** [comment]
So we had a fix for one year and it's never was merged? @lhog any blockers for merging this?
