### ISSUE TITLE
Inconsistent zooming speed at bottom of the map

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/spring#627]
1. Switch to spring camera.
2. Move camera to bottom of the map.
3. Start zooming out and zooming in.

P.S Pay attention on minimap and also bugged with /luaui disable.

https://youtu.be/1gJh8QAj2WQ

**Comment by lhog** [comment]
Is only spring camera affected by this one?

**Comment by 6AKU** [comment]
> Is only spring camera affected by this one?

Overhead TA is not affected for sure.

**Comment by dzosz** [comment]
When zooming-in to a point outside the map instead of height ground on the boundary the SpringController uses map height average. This is most likely what's causing the inconsistency in zoom speed.
