### ISSUE TITLE
[Feature request] ForceSmoothMeshUpdate

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#635]
Currently, afaik, smooth mesh is auto-updated with quite a large time period to save the game from quite expensive operation.
However, it is very useful to perform a map-wide smooth mesh update right after uploading the height map via SetHeightMapFunc, so a proper air simulation can begin instantly.
I propose a simple function call for this like ForceSmoothMeshUpdate().

**Comment by sprunk** [comment]
As a workaround you can use these alongside the ones for the heightmap https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Lua/LuaSyncedCtrl.cpp#L306-L312

**Comment by Krogoth100** [comment]
> As a workaround you can use these alongside the ones for the heightmap https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Lua/LuaSyncedCtrl.cpp#L306-L312

I've seen those, but I don't understand how to use them to apply proper smooth height values. The only function working on an area is SetSmoothMeshFunc and that seems to apply exact smooth height values, right? I would have to replicate smooth mesh generation algorithm, if I am understanding it correctly.

**Comment by Krogoth100** [comment]
> As a workaround you can use these alongside the ones for the heightmap https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Lua/LuaSyncedCtrl.cpp#L306-L312

I've seen those, but I don't understand how to use them for a proper smooth mesh generation. These seem to add a layer of height that corresponds to deformation and can be reverted. But if I use RevertSmoothMesh, that will just give me a plane, because my initial map is a plane. If I used SetSmoothMeshHeightFunc, I would have to replicate smooth mesh generation algorithm then, if I am understanding correctly.

**Comment by marcushutchings** [comment]
I'm finishing up some other tasks, but I will get to this. I think adding a full update function seems like a reasonable addition. I had thought about the smooth mesh update adjusting it's update rate dynamically, but I think a function on demand makes sense.

**Comment by marcushutchings** [comment]
Your understanding is correct about updating the smooth mesh. Those Lua update functions are there for completeness sake in case someone has a good need for it. I haven't seen one yet. I wouldn't recommend trying to re-implement the smooth mesh, so a force update-all function sounds good.

> > As a workaround you can use these alongside the ones for the heightmap https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Lua/LuaSyncedCtrl.cpp#L306-L312
> 
> I've seen those, but I don't understand how to use them for a proper smooth mesh generation. These seem to add a layer of height that corresponds to a deformation and can be reverted. But if I use RevertSmoothMesh, that will just give me a plane, because my initial map is a plane. If I used SetSmoothMeshHeightFunc, I would have to replicate smooth mesh generation algorithm then, if I am understanding it correctly.

**Comment by marcushutchings** [comment]
Awesome. Raise a PR and I'll review it when I get back on a few weeks.
