### ISSUE TITLE
Crash While Loading Saved Game

### ISSUE THREAD

**Issue by jlyon87** [beyond-all-reason/spring#64]
While loading a saved game. The game crashed.

The game was saved last night, (8/8), and I'm loading it today on 8/9.

![image](https://user-images.githubusercontent.com/9729366/128796868-b5193ef4-f394-4aed-9b8a-2e7cd53912a9.png)

![image](https://user-images.githubusercontent.com/9729366/128796878-71dff546-c846-4b12-b25d-9df0faa06907.png)

[infolog.txt](https://github.com/beyond-all-reason/spring/files/6958401/infolog.txt)

The save file
[20210808_222436.zip](https://github.com/beyond-all-reason/spring/files/6958405/20210808_222436.zip)

Discord Thread for Context
https://discord.com/channels/549281623154229250/549282926596980738/874468382018240564

**Comment by Beherith** [comment]
I took a look at the stack trace, but didnt get much smarter.

C:\Games\BAR\Beyond-All-Reason\data\engine\104.0.1-1956-g0092498 bar\spring.exe 0x0085C047 rts/System/creg/SerializeLuaState.cpp:1043
C:\Games\BAR\Beyond-All-Reason\data\engine\104.0.1-1956-g0092498 bar\spring.exe 0x00863DA6 rts/System/creg/Serializer.cpp:596
C:\Games\BAR\Beyond-All-Reason\data\engine\104.0.1-1956-g0092498 bar\spring.exe 0x0081F45F rts/System/LoadSave/CregLoadSaveHandler.cpp:186
C:\Games\BAR\Beyond-All-Reason\data\engine\104.0.1-1956-g0092498 bar\spring.exe 0x00435FE2 rts/Game/Game.cpp:430
C:\Games\BAR\Beyond-All-Reason\data\engine\104.0.1-1956-g0092498 bar\spring.exe 0x0045256A rts/Game/LoadScreen.cpp:138
C:\Games\BAR\Beyond-All-Reason\data\engine\104.0.1-1956-g0092498 bar\spring.exe 0x00452B20 rts/Game/LoadScreen.cpp:183
C:\Games\BAR\Beyond-All-Reason\data\engine\104.0.1-1956-g0092498 bar\spring.exe 0x0045D359 /usr/lib/gcc/x86_64-w64-mingw32/9.3-posix/include/c++/bits/basic_string.h:222
C:\Games\BAR\Beyond-All-Reason\data\engine\104.0.1-1956-g0092498 bar\spring.exe 0x0045E45D rts/Game/PreGame.cpp:200
C:\Games\BAR\Beyond-All-Reason\data\engine\104.0.1-1956-g0092498 bar\spring.exe 0x0083E3FC rts/System/SpringApp.cpp:765
C:\Games\BAR\Beyond-All-Reason\data\engine\104.0.1-1956-g0092498 bar\spring.exe 0x00841520 rts/System/SpringApp.cpp:804
C:\Games\BAR\Beyond-All-Reason\data\engine\104.0.1-1956-g0092498 bar\spring.exe 0x0082B04F rts/System/Main.cpp:48
C:\Games\BAR\Beyond-All-Reason\data\engine\104.0.1-1956-g0092498 bar\spring.exe 0x00F15E49 rts/System/Main.cpp:100
C:\Games\BAR\Beyond-All-Reason\data\engine\104.0.1-1956-g0092498 bar\spring.exe 0x004013B4 x86_64-w64-mingw32-x86_64-w64-mingw32-crt/./mingw-w64-crt/crt/crtexe.c:341
C:\Games\BAR\Beyond-All-Reason\data\engine\104.0.1-1956-g0092498 bar\spring.exe 0x004014DB x86_64-w64-mingw32-x86_64-w64-mingw32-crt/./mingw-w64-crt/crt/crtexe.c:197
C:\Windows\SYSTEM32\ntdll.dll 0x00052651 ??:0

**Comment by lhog** [comment]
Attn @ashdnazg

**Comment by ashdnazg** [comment]
should be fixed here: https://github.com/spring/spring/commit/4ec5ce918e4f2e3980889833830dd5d0e2fe0e40

**Comment by lhog** [comment]
No one verified, but let's assume this closed for now.
