### ISSUE TITLE
`/iconsasui 1` and ghosts are hax and spill information

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#640]
When `/iconsasui 1` is enabled, ghosts also show radar icons. Icons for ghosts should render if and only if the ghost does. Right now it represents the true state of the unit. Additionally, the ghost of a dead building is rotated differently so also reveals the unit died (but not so blatantly).

Zoomed out enough to see icons. The icon for the left building should still be there (because the ghost is still there):
![image](https://user-images.githubusercontent.com/2573076/218312192-bbd2fecb-8a3c-4a8d-aa1c-4d201406e127.png)

Zoomed in to see the ghost. The ghost of the dead building should not be rotated compared to the live one (they were both rotated like the live one):
![image](https://user-images.githubusercontent.com/2573076/218312249-af7feead-c19d-4ee0-8e7a-5754ac45523a.png)

**Comment by sprunk** [comment]
Thanks!

**Comment by lhog** [comment]
Hopefully I resolved what you meant. I.e. live ghosts showing icons when out of LoS and radar coverage.

**Comment by sprunk** [comment]
Actually I asked for the dead ghost to keep showing the icon:

> Icons for ghosts should render if and only if the ghost does. 

Showing icons on ghosts is good for visibility and is a SupCom feature so people often ask for it.

But this patch is still useful! If it disables icons for ghosts (regardless if they are live or not) then it means the request in #640 (toggling icons for ghosts) is basically implemented.

**Comment by lhog** [comment]
> If it disables icons for ghosts (regardless if they are live or not) 

Not quite like that. Out of all possibilities it will only show an icon when the ghost is alive and in continuous radar coverage, which makes sense - we know it's there. In all other cases (with ghosts) the icon is not displayed.

**Comment by lhog** [comment]
> Here's a bunch of charts so we're on the same page.

Correct. Moreover "live ghost (no radar)" == "live ghost (in radar, but no continuous radar coverage since the ghost was created)"

> Ideal, if https://github.com/beyond-all-reason/spring/issues/641 is implemented (assuming the new setting is called ghostIcons arbitrarily)

Ok this is probably something we can do when the merge window is re-opened.

**Comment by sprunk** [comment]
Ask the BAR game devs then, perhaps they would rather this fix was reverted for the time being since a feature was just lost. I wouldn't mind waiting a bit longer.

**Comment by lhog** [comment]
It used to leak alive vs dead information via showing an icon, that was not correct.
It should consistently either render or not render icons in both cases. I'll ask around.
