### ISSUE TITLE
WindowBorderless=1 may cause low GPU loading (hence low FPS)

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/spring#648]
For some reason WindowBorderless=1 causing low GPU loading on my system.

**Comment by 6AKU** [comment]
This ticket lack of data, i will fill up more data later. For now i created this ticket to not forget about pretty important problem.

**Comment by badosu** [comment]
Borderless indeed is less performant than 'real' full screen. Reason for that is that the screen is composited together with the operating system, as opposed to fullscreen non borderless.

Now as for the reason you might be seeing significant differences that's a mystery without more data.
