### ISSUE TITLE
Cegs obscure other cegs too much

### ISSUE THREAD

**Issue by icexuick** [beyond-all-reason/spring#65]
So a videopreview of what i mean is clearly seen here: https://discord.com/channels/549281623154229250/551411485901979659/876260266357186640

Lots of smoke-ceg particles obscure other cegs behind them.
So there seems like max ammount of cegs to be 'layered'.

Problem is in big battles, with lots of explosions and smoke, the smoke is generally larger/higher up, and this obscures all other flashes/explosions/flames that are happening on the ground/below.

This is something that has been plaguing Spring games in general for quite some time.
This limitation/bug is what makes intense battles a lot less intense as they are, since smoke will hide all the fire-y explosions.
But since the smoke remains transparant, you can see the terrain/units behind it, but it seems if explosions/projectiles 'just don't work anymore' (or that the particle system partly broke) since there is just nothing happening behind the smoke.

Idea/Suggestions:

1. Increase amount of layered cegs to be displayed. If performance allows it, i'd increase this a lot.
2. Make it somehow possible to set a limit to 'smokey' cegs and keep room for other explosions behind smoke-cegs
3. Have some cegs have priority/always show, like flames/sparks/flashes/etc.

![explosion-ceg-limit-layers](https://user-images.githubusercontent.com/23189106/130606834-dce4fac2-fc4c-4ad6-bef2-4735d13723c2.png)

**Comment by lhog** [comment]
An attempt to make issue a bit less pronounced (probably at expense of other new issues):
https://github.com/beyond-all-reason/spring/tree/BAR-CEG-DO

**Comment by icexuick** [comment]
Latest engine update with "drawOrder" value (the higher the number, the higher the layer/visibility) works perfectly.
All cegs are default to layer = 0.
With some subtle/varied (smaller) smoke/explosions on layer = 1, and the very visible explo heatwaves/sparks and sometimes glow for bigger explosions, this is solved!
