### ISSUE TITLE
Weird SIGSEGVs with DEBUG builds

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/spring#651]
If I enable tcmalloc I get this backtrace when starting game:

https://gist.github.com/badosu/c436f9bcf165782b0e7cd9e8e43b7fc7

However if I disable tcmalloc then I get another kind of sigsegv inside `DrawCommon` when invoking a calllist. `LuaUtils::LuaStackDumper` does not help much, just gives me the arguments for the calllist invocation (the calllist index).

I have no idea what I'm doing wrong. I used to be able to run debug builds locally. If anyone can assist I appreciate.

cmake line:

```
cmake \                                                                                                                        
        -DCMAKE_TOOLCHAIN_FILE="../toolchain/gcc_x86_64-pc-linux-gnu.cmake" \                                                                                                                  
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
        -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-O1 -g -fcolor-diagnostics -ffile-prefix-map=/spring/=" \
        -DCMAKE_C_FLAGS_RELWITHDEBINFO="-O1 -g -fcolor-diagnostics -ffile-prefix-map=/spring/=" \
        -DCMAKE_BUILD_TYPE=DEBUG \
        -DDEBUG_MAX_WARNINGS=OFF \
        -DAI_TYPES=NATIVE \
        -DINSTALL_PORTABLE=ON \
        -DCMAKE_USE_RELATIVE_PATHS:BOOL=1 \
        -DBINDIR:PATH=./ \
        -DLIBDIR:PATH=./ \
        -DDATADIR:PATH=./ \
        -DCMAKE_INSTALL_PREFIX=install \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -G Ninja \
        ..
        
❯ cat ../toolchain/gcc_x86_64-pc-linux-gnu.cmake
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_C_COMPILER "gcc")
SET(CMAKE_CXX_COMPILER "g++")
SET(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld")
SET(CMAKE_MODULE_LINKER_FLAGS_INIT "-fuse-ld=lld")
SET(CMAKE_SHARED_LINKER_FLAGS_INIT "-fuse-ld=lld")
```

**Comment by badosu** [comment]
A few people seem to hit this issue when there's some memory corruption: 

- https://stackoverflow.com/questions/34146880/segfault-on-tcmalloc-releasetocentralcache
- https://github.com/gperftools/gperftools/issues/231

**Comment by marcushutchings** [comment]
We get the odd sigabort from time-to-time in the released engine, which is usually a memheap corruption. I haven't been able to reproduce it, but the comes in from time to time so it wasn't some weird one-off. I hope this investigation may help to get to the cause.

**Comment by badosu** [comment]
Ok valgrind gave up after 1000 different errors were reported, before I reproduced, I attached the report to the [gist](https://gist.github.com/badosu/c436f9bcf165782b0e7cd9e8e43b7fc7).

Will run again without error limit

**Comment by badosu** [comment]
Ok I fucked up the type specs on the cmake invocation above, trying to identify if that was the issue.

**Comment by badosu** [comment]
Meanwhile, one can see a few actual memory errors, even with the limited run I did of these kind:

> Use of uninitialised value or Conditional jump or move depends on uninitialised value(s) The program read the value of a memory location that was not previously written to, i.e. uses random junk. The second more specifically indicates the read occurred in the test expression in an if/for/while. Make sure to initialize all of your variables! Remember that just declaring a variable doesn't put anything in its contents--if you want an int to be 0 or a pointer to be NULL, you must explicitly state so. Note that Valgrind will silently allow a program to propagate an uninitialized value along from variable to variable; the complaint will only come when(if) it eventually uses the value which may be far removed from the root of the error. When tracking down an uninitialized value, run Valgrind with the additional flag --track-origins=yes and it will report the entire history of the value back to the origin which can be very helpful.

**Comment by badosu** [comment]
> We get the odd sigabort from time-to-time in the released engine, which is usually a memheap corruption. I haven't been able to reproduce it, but the comes in from time to time so it wasn't some weird one-off. I hope this investigation may help to get to the cause.

@marcushutchings  I reproduced a sigabrt related to pathfinding:

```
spring: /home/badosu/Code/spring/rts/Sim/Path/TKPFS/PathManager.cpp:82: void TKPFS::CPathManager::InitStatic(): Assertion `ThreadPool::GetNumThreads() != 1' failed.
zsh: IOT instruction (core dumped)  valgrind --error-limit=no --track-origins=yes --leak-check=yes  ./spring   
```

You can find the valgrind report [here](https://www.dropbox.com/s/j32jdevkx13di8l/valgrind.rpt?dl=0). I can also upload the core dumb (3.5GB) if you need.

**Comment by badosu** [comment]
I'm closing this issue, as I have no idea how to handle anything, I can't even reproduce the original issue as I'm now stopping at that assertion.

If I ever am able to run the game and get back to that state I'll publish a valgrind and reopen.

**Comment by marcushutchings** [comment]
I've removed that assertion now, it is not needed.
