### ISSUE TITLE
Auto-groups are forgotten after loading a saved game

### ISSUE THREAD

**Issue by marcushutchings** [beyond-all-reason/spring#655]
As reported by Signis: Loading the saved game made the auto-groups disappear (alt 1,2,3...)

**Comment by lhog** [comment]
I think auto-groups are handled by gameside widget: https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/Widgets/unit_auto_group.lua

**Comment by badosu** [comment]
There is an issue with engine updates (although less common now) where settings would be lost between versions.

I'm not sure how engine could be related to this issue, except if VFS is not loading/saving on some circumstances.

You can find where bar specific widgetmanager saves/loads widgets settings [here](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/e3a6f44613f5ab02cee0007779e00651a5567840/luaui/barwidgets.lua#L241-L278)

**Comment by badosu** [comment]
If an infolog is available one can assess whether there was an issue with loading the settings or whether the widget operation has failed (errored).

**Comment by badosu** [comment]
```
[GameStart](https://springrts.com/wiki/Lua:Callins#GameStart)()

    Called upon the start of the game. From 104.0 onwards, will not be called when a saved game is loaded.
```

This can be closed, not an engine issue. Unless a game start callin that works on loads and gameframe > 0 is desirable.

**Comment by badosu** [comment]
I've faced this issue myself where I desired a `GameStart`-like callin that works on loads.

**Comment by badosu** [comment]
Once this is moved to BAR repo, (or closed) I'll leave it a week for a potential new contributor to address it (the fix is quite trivial). Otherwise I'll fix it myself.

**Comment by badosu** [comment]
A feature request for a new callin that works on load as well should be done on a separate issue.

**Comment by sprunk** [comment]
Why a new callin, isn't `Initialize` sufficient?

**Comment by lhog** [comment]
IIRC recall correctly @ashdnazg once told me an ordinary widget should just work upon a savegame load, because Lua state is dumped on disk and restored respectively.

**Comment by badosu** [comment]
> Why a new callin, isn't `Initialize` sufficient?

Initialize happens at Lua Unsynced entrypoint, the intended functionality is for at LoadGame gameframe>0 or GameStart

**Comment by ashdnazg** [comment]
IIRC unsynced lua is not dumped, only synced.

**Comment by ashdnazg** [comment]
I think @sprunk is correct - you want to use Initialize

**Comment by badosu** [comment]
Does Initialize happen at pregame start? If so, not (I'd be surprised if that was the case).

Implementation is widget manager dependent and on BAR it happens on [first `Update()`](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/e3a6f44613f5ab02cee0007779e00651a5567840/luaui/Widgets/dbg_widget_profiler.lua#L299-L301), which is ran at pregamestart.

**Comment by badosu** [comment]
More specifically, the widget authors intention is to run a certain piece of code only when the simulation starts. Which in this case, is to activate autogroup and fetch some other information - you don't really need to have game runtime widgets working during pregame.

More broadly, this necessity is a common theme among widgets that either you only want running during games (and not on pregamestart) or that manage both sides (like buildmenu). The threshold between gameframe 0 and gameframe > 0 in this case being what you want to capture - and what gamestart provides for regular games but not for save game loads. The workaround in this case to be hooking up `GameFrame` and deregistering the dead code after the threshold has been captured.

**Comment by sprunk** [comment]
>  the intended functionality is for at Load save gameframe>0 or GameStart (...) More specifically, the widget authors intention is to run a certain piece of code only when the simulation starts.

I think in the case of autogroups that's just a confused implementational kludge, because it doesn't matter whether the widget is active before game start since there are no units then. But I also think this is still doable with `Initialize`, see below.

> The threshold between gameframe 0 and gameframe > 0 in this case being what you want to capture - and what GameStart provides for regular games but not for save game loads.

Do `GetGameFrame` in `Initialize`. If it's `== 0` then you're in pre-game and will receive the `GameStart` event normally at some point. If it's `> 0` then you know you are past that point and can act accordingly (for example, setting the `gameStart = true` in auto groups).

Check if this does what you want: https://github.com/beyond-all-reason/Beyond-All-Reason/commits/sprunk-patch-2

**Comment by badosu** [comment]
Sure, if you that's deemed acceptable, that's completely fine.

Personally, I'm not a fan. There's a gap in the game lifecyle management callin set, and while not ideal capturing that gap with a workaround is more to my taste.

**Comment by ashdnazg** [comment]
I disagree - loading a game is equivalent to doing `/luaui reload` and you should aim anyway for everything working after a `/luaui reload`.

**Comment by sprunk** [comment]
A wupget manager can also do this:
```lua
function wupgetManager:LoadWupget()
  wupget:Initialize()
  if Spring.GetGameFrame() > 0 then
    wupget:GameStart()
  end
  if Spring.IsGameOver() then
    local winners = Spring.GetWinningAllyteams()
    wupget:GameOver(winners)
  end
  -- any other "missing" callins
end
```

**Comment by ashdnazg** [comment]
I wouldn't recommend a blanket implementation like this...
Too easy to misuse.

**Comment by sprunk** [comment]
Yea, I'd be very careful if going that route due to hidden assumptions (for example existing widgets might assume `GameStart` always happens at frame 0, which is currently the case), but it's a tradeoff a gamedev can make (for example can no longer assume the former, but can now instead assume that `GameStart` has always been called if the game is ongoing).

**Comment by badosu** [comment]
Does not need to reuse the same name (e.g.` GameStarted`). In many frameworks there are permissive callbacks (something has already happened triggers again on initialization) and retaining the specific threshold callbacks. Depends on how much you care about certain aspects of the lifecycle.
