### ISSUE TITLE
Fix strange behavior strategic icons (low angle camera = floating icons in sky)

### ISSUE THREAD

**Issue by icexuick** [beyond-all-reason/spring#66]
Probably found in :
https://github.com/beyond-all-reason/spring/blob/fdebe587b90eac92790e2c55a5198e6a4a57d2a6/rts/Rendering/UnitDrawer.cpp
and
https://github.com/beyond-all-reason/spring/blob/fdebe587b90eac92790e2c55a5198e6a4a57d2a6/rts/Rendering/UnitDrawer.h
and
https://github.com/beyond-all-reason/spring/blob/fdebe587b90eac92790e2c55a5198e6a4a57d2a6/rts/Rendering/UnitDrawer.h

Behavior is a glitchy on low angle camera shots

**Reproduce**
1. Start map (Colorado V2 f.e.)
2. Place some scattered units across map to see the icons go wrong
3. Use Spring Cam / CTRL-F3
4. Hold Middle Mouse + ALT + Move mouse to get lower angles and look around
5. Move camera position around the map
= you will see some strange floating icons in the sky

See a quick video here: https://discord.com/channels/549281623154229250/549282926596980738/877336995163176961

![floatingicons](https://user-images.githubusercontent.com/23189106/130612481-4e146188-a7d6-44c6-842f-d37c0c235064.png)

**Comment by lhog** [comment]
@Kevsnz pinging in case you might want to fix it up. Otherwise help is welcome.

**Comment by Kevsnz** [comment]
Maybe but unlikely. I have almost no free time atm.

**Comment by lhog** [comment]
Its ok, t.y.

**Comment by lhog** [comment]
https://cdn.discordapp.com/attachments/549282926596980738/877336991459573820/flyingicons_1.mp4

**Comment by lhog** [comment]
Please test in some coming build (with the fix inside) and reopen if something it pops up again.
