### ISSUE TITLE
Slow gl text processing on Linux

### ISSUE THREAD

**Issue by moreginger** [beyond-all-reason/spring#662]
I was investigating a lag spike caused by `gui_reclaim_field_highlight.lua` in Zero-K, and activated the benchmarking:

```
[t=09:58:37.828096][f=0014792] ##################################### Average Time (ms) #####################################
[t=09:58:37.828100][f=0014792] Optics:Run (while next(unprocessed) do) <====> 0
[t=09:58:37.828104][f=0014792] MonotoneChain <====> 0
[t=09:58:37.828107][f=0014792] Optics:Run (self:_CoreDistance(point, neighbors)) <====> 0
[t=09:58:37.828110][f=0014792] UpdateFeatures <====> 0
[t=09:58:37.828113][f=0014792] Optics:_CoreDistance <====> 0
[t=09:58:37.828117][f=0014792] ClustersToConvexHull 1st Part <====> 0
[t=09:58:37.828121][f=0014792] ClustersToConvexHull 3rd Part <====> 0.02173913
[t=09:58:37.828124][f=0014792] UpdateFeatures 1loop <====> 0
[t=09:58:37.828128][f=0014792] Optics:_Neighbors <====> 0
[t=09:58:37.828131][f=0014792] ClusterizeFeatures <====> 0
[t=09:58:37.828135][f=0014792] Optics:Run (while seedsPQ:peek() do) <====> 0
[t=09:58:37.828138][f=0014792] ClustersToConvexHull <====> 0.82608694
[t=09:58:37.828142][f=0014792] GameFrame UpdateFeatures <====> 28.333334
[t=09:58:37.828146][f=0014792] Optics:_Update <====> 0
[t=09:58:37.828149][f=0014792] featuresUpdated or drawFeatureConvexHullSolidList == nil <====> 0
[t=09:58:37.828152][f=0014792] ClustersToConvexHull 2nd Part <====> 0.01086957
[t=09:58:37.828156][f=0014792] featuresUpdated or clusterMetalUpdated or drawFeatureClusterTextList == nil <====> 27
[t=09:58:37.828159][f=0014792] UpdateFeatures 2loop <====> 0
[t=09:58:37.828163][f=0014792] Optics:_Setup <====> 0
[t=09:58:37.828166][f=0014792] Optics:Run Main Body <====> 0
[t=09:58:37.828169][f=0014792] opticsObject:Clusterize(minDistance) <====> 0
[t=09:58:37.828171][f=0014792] opticsObject:Run() <====> 0
```

Impressively it's nothing to do with the clustering algorithm, and all the work is in "featuresUpdated or clusterMetalUpdated or drawFeatureClusterTextList == nil". At the point where I am seeing this, the widget is processing about 40 hulls. Eventually I believe I tracked it down to one line:

```
font:Print(metalText, 0, 0, BASE_FONT_SIZE, "cv")
```

I tried "n" modifier and printing without the transform matrix, but it was no different. Also the line `glText(metalText, 0, 0, fontSize, "cv")` (which was commented out) is just as slow.

This is on Linux/AMD (curses, I know!). I'll see if I can get someone to verify whether the issue exists on Windows.

**Comment by moreginger** [comment]
Note the widget does...

```
		font:Begin()
			font:SetTextColor(r, g, b, 1.0)
			font:Print(metalText, 0, 0, BASE_FONT_SIZE, "cv")
		font:End()
```

...on each loop. I don't know the rules of gl.BeginText/EndText, but if I move Begin/End to outside the loop then it's substantially faster (30ms -> 5ms). However I've no idea if it looks right as for some reason this widget does not render the highlight fields as a local widget - I assume it's using a callin for draw that isn't actually available to local widgets. Can test if someone tells me how to work with it.

**Comment by moreginger** [comment]
Minimal case. It takes about 75ms on my machine, to call gl.Text 100 times.

[slowtextwidget.zip](https://github.com/beyond-all-reason/spring/files/10833612/slowtextwidget.zip)

**Comment by lhog** [comment]
Ok a few things:
1) AMD has special (slower) code path for fonts rendering. Since you're on Linux, where their driver is more or less good, it might not be needed. Share infolog.txt to see if AMDHacks are active or not.
2) Try measuring `glText("hello", 100, 100, 10, "cv")` calls without display lists, it's our near future of doing things anyway. As "display lists" are deprecated.
3) In general prefer using https://springrts.com/wiki/Lua_Fonts instead of `gl.Text`

**Comment by moreginger** [comment]
Thanks for replay @lhog.

1. Looks like it isn't? `[t=00:00:00.175319] 	enable AMD-hacks : 0` Have attached.
2. OK, modified slowtextwidget to call gl.Text directly in a loop, without the displayLists stuff, it still takes 75ms.
3. Thanks, will do, was just trying to keep things simple.

I've tried expanding the Begin/End block in the widget but I ran into issues with the font height (y-displacement). Tried to use PrintWorld instead but that orients to the viewing plane by default: https://github.com/ZeroK-RTS/Zero-K/pull/4825

[infolog.txt](https://github.com/beyond-all-reason/spring/files/10834455/infolog.txt)

**Comment by lhog** [comment]
Ok, let me see if I can reproduce and measure where it bottlenecks on my end.
P.S. Try AMD hacks (`AtiHacks = 1` in `springsettings.cfg`)

**Comment by moreginger** [comment]
> P.S. Try AMD hacks (AtiHacks = 1 in springsettings.cfg)

Well, whaddya know, slowtextwidget takes 1ms with that on. That's kind of sad. I wonder how it affects things overall - I'm assuming you lose various goodness all over.

Also confirmed that I'm not seeing the stuttering with mid-late game when highlight reclaim widget is running.

**Comment by lhog** [comment]
The display lists are black boxes we have no control about, but native calls (without wrapping them into DLs) shows good perf for @moreginger
