### ISSUE TITLE
Map-side unittextures dont override game-side ones

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#666]
So one interesting thing, when trying to override the textures of features, in this case features defined (both lua and .s3o) are gameside, and they have textures gameside.

If I try to override the texture map-side, by adding the same filename into map unittextures/ it does not override the game-side version.

**Comment by sprunk** [comment]
Textures use `VFS.RAW_FIRST`, whose precedence is [user local] > game > map.

https://github.com/beyond-all-reason/spring/blob/BAR105/rts/System/FileSystem/VFSModes.h#L17

**Comment by Beherith** [comment]
Ok, this can be closed, thank you for the explanation.
