### ISSUE TITLE
[RFC] Change the "n" in GetSelectedUnitsX

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#669]
`Spring.GetSelectedUnitsSorted` and `Spring.GetSelectedUnitsCounts` return a table with this format:
```lua
{
  [unitDefID] = stuff, -- unit array for Sorted, or number for Counts
  [unitDefID] = stuff,
  ...
  n = 123, -- how many different unitDefIDs there are in the table
}
```
This is silly because the "n" is not that useful but makes it very inconvenient to iterate over the table since you can no longer rely on all entries having a valid unit def ID as a key (and, for Sorted, an array as the value). As far as I can tell, in all existing code the "n" is either essentially not handled when this assumption isn't really needed[1] or has specific handling to get rid of it or ignore it [2]. I couldn't find a widget that makes use of it, and I'd expect such widget to still get rid of the "n" after use just for convenience. I don't think it's completely useless though, for example a GUI widget might want to prepare N slots on a command panel or something and fill them as it goes.

The proposal is to change the return value from `{ stuff, n }` to `{ stuff }, n`. This would be a breaking change, but given actual use most (all known?) games wouldn't need to do anything.

[1] https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/Widgets/cmd_default_set_target.lua#L71-L73

https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/Widgets/unit_show_selected_range.lua#L112-L113

[2] https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/Widgets/cmd_rclick_quick_build_resource_extractor.lua#L147

https://github.com/ZeroK-RTS/Zero-K/blob/master/LuaUI/debug.lua#L38

https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/Widgets/cmd_onoff.lua#L29

https://github.com/MaDDoXbr/TAPrime/blob/master/luaui/Widgets_TAP/cmd_buildsplit.lua#L83

https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/Widgets/gui_given_units.lua#L105

https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/luaui/Widgets/cmd_factoryqmanager.lua#L275

https://github.com/SplinterFaction/SplinterFaction/blob/master/LuaUI/Widgets_Evo/gui_selected_units_buttons.lua#L584-L586

**Comment by badosu** [comment]
I mostly agree, this is a very ugly spec that needs to be often worked around instead of used.
