### ISSUE TITLE
Crash on loading the new Tabula map with AMD ([t=00:00:06.866775][f=-000001] Error: [TexMemPool::AllocRaw] failed to allocate bitmap of size 268435456u from pool of total size 268435456u)

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/spring#67]
Infolog paste: https://pastebin.com/gJbFyWjm

Stack Trace:
C:\Users\user\Documents\My Games\Spring\engine\104.0.1-1956-g0092498\spring.exe 0x0071CA55 /usr/lib/gcc/x86_64-w64-mingw32/9.3-posix/include/c++/bits/stl_vector.h:1496
C:\Users\user\Documents\My Games\Spring\engine\104.0.1-1956-g0092498\spring.exe 0x007CCAEA /usr/lib/gcc/x86_64-w64-mingw32/9.3-posix/include/c++/bits/atomic_base.h:419
C:\Users\user\Documents\My Games\Spring\engine\104.0.1-1956-g0092498\spring.exe 0x0042C7FC rts/Rendering/MatrixUploader.h:20
C:\Users\user\Documents\My Games\Spring\engine\104.0.1-1956-g0092498\spring.exe 0x00436BB2 rts/Game/Game.cpp:291
C:\Users\user\Documents\My Games\Spring\engine\104.0.1-1956-g0092498\spring.exe 0x00436DCE rts/Game/Game.cpp:302
C:\Users\user\Documents\My Games\Spring\engine\104.0.1-1956-g0092498\spring.exe 0x0083C631 rts/System/SafeUtil.h:24
C:\Users\user\Documents\My Games\Spring\engine\104.0.1-1956-g0092498\spring.exe 0x0083624A /usr/lib/gcc/x86_64-w64-mingw32/9.3-posix/include/c++/thread:138
C:\Users\user\Documents\My Games\Spring\engine\104.0.1-1956-g0092498\spring.exe 0x008417E4 rts/System/SpringApp.cpp:807
C:\Users\user\Documents\My Games\Spring\engine\104.0.1-1956-g0092498\spring.exe 0x0082B04F rts/System/Main.cpp:48
C:\Users\user\Documents\My Games\Spring\engine\104.0.1-1956-g0092498\spring.exe 0x00F15E49 rts/System/Main.cpp:100
C:\Users\user\Documents\My Games\Spring\engine\104.0.1-1956-g0092498\spring.exe 0x004013B4 x86_64-w64-mingw32-x86_64-w64-mingw32-crt/./mingw-w64-crt/crt/crtexe.c:341
C:\Users\user\Documents\My Games\Spring\engine\104.0.1-1956-g0092498\spring.exe 0x004014DB x86_64-w64-mingw32-x86_64-w64-mingw32-crt/./mingw-w64-crt/crt/crtexe.c:197
C:\Windows\SYSTEM32\ntdll.dll 0x00052651 ??:0

**Comment by lhog** [comment]
Closing as unreproducible for now.

**Comment by badosu** [comment]
As of 105-582 this is fixed :+1:
