### ISSUE TITLE
Have Spring find textures in a "unittextures" subfolder

### ISSUE THREAD

**Issue by Fjoersteller** [beyond-all-reason/spring#673]
If textures, that are applied to, and defined in, a .s3o 3Dmodel file, are put in (for example) the folder \unittextures\chickens, it seems they will not be loaded. Could it be made so that they would be loaded, regardless of being in a subfolder of \unittextures?

Relevant BAR discord conversation:
https://discordapp.com/channels/549281623154229250/724924957074915358/1080917703436537937

**Comment by sprunk** [comment]
Can't you just edit the paths to be `chickens/xyz`?

What should happen if the .s3o path is defined to be `xyz` but there exist both `unittextures/chickens/xyz` and `unittextures/ducks/xyz`?

What should happen if the game has `unittextures/chickens/xyz` but no `unittextures/xyz`, but the player has `unittextures/xyz` locally?

**Comment by Fjoersteller** [comment]
im under the impression just texture filenames are defined in .s30, not including a file path

If that were possible though, i think that would be a less than ideal solution regarding the wish for subfolders (for various reasons). 

im proposing to treat files in subfolders as if they weren't in subfolders, and could be found by Spring like file that aren't. As long as files names are unique it would solve examples about conflicting file paths/folder names, not create them i think.

"object3d" can have file sin subfolders with no issue. "units" can have files in subfolders with no issue. it would make sense to me if it were the same for "unittextures"

**Comment by sprunk** [comment]
> im under the impression just texture filenames are defined in .s30, not including a file path

This is incorrect, an s3o file contains the full path.

> "object3d" can have file sin subfolders with no issue.

This is incorrect. Note that BAR is specifying full paths (e.g. it's `units/armpw.s3o` and not just `armpw.s3o`) https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/units/ArmBots/armpw.lua#L26

> "units" can have files in subfolders with no issue.

This is incorrect. Engine doesn't even handle those files, BAR is specifically doing a recursive search: https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/gamedata/unitdefs.lua#L71 Unit defs don't even fundamentally work on filenames, they work on whatever Lua tables these files return, so a duplicate filename may well be fine here. A game can code any precedence for handling duplicate unit def names it likes in `unitdefs.lua`.

**Comment by Fjoersteller** [comment]
okay. i seem to have misunderstood how it works. thank you for explaining : )

however, i still do not understand how to specify the full path in a .s3o then.
(Since it is, as far as i know, not possible in Upspring, i was under the impression it refers to file name only.) Browsing and applying a texture in a located (only) in a subfolder of "untitextures" in Upspring still cause the texture not to be loaded in-game.

**Comment by sprunk** [comment]
Yes, looks like UpSpring can't handle full paths. You can just edit the file in notepad though, the paths are at the very end.
![image](https://user-images.githubusercontent.com/2573076/222920676-ded45add-061b-4538-a653-0dc5345c0617.png)

**Comment by sprunk** [comment]
Yes, UpSpring can't make it a full file path. You have to fake a path and then edit the file in notepad. For example if you want `some/path/xyz` then make it point to a file called `some_path_xyz` and then edit the `_` to `/`
![image](https://user-images.githubusercontent.com/2573076/222920943-5496c07a-1fea-464f-83e4-8dcdabcf54a2.png)

**Comment by Fjoersteller** [comment]
hmm, less than ideal, but thank you for showing regardless.
(i'll close the issue)
