### ISSUE TITLE
105.1.1-1594-g7d210e3 Almost nothing drawn for a player

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#675]
This won't be a particularly useful report, but it is good to keep track of blockers. The player czesio sees the game as the following screenshot most of the time.

![image](https://user-images.githubusercontent.com/1318249/222880727-849629bf-6675-4d2a-808a-0f31baa010ea.png)

Sometimes the correct visuals flicker onto his screen. It works fine on 105.1.1-1485-g78f9a2c.

The following is NOT an infolog from the game, but one doesn't appear to exist. It just shows settings and hardware etc. It looks a bit like a lua crash or a bad state inserted somewhere in the drawing thing when lua tries to do drawing. Note that units in ZK are not "drawn by the engine", in some particular way, so they can have a shader.

[infolog_full.txt](https://github.com/beyond-all-reason/spring/files/10887660/infolog_full.txt)

**Comment by marcushutchings** [comment]
@lhog have you seen this issue ticket?

**Comment by lhog** [comment]
I have, no idea what it could be. Also no logs. He's on a very bad Intel iGPU, which could easily ran out of resources or something.
If that is repeatable for `czesio` I can only advise to bisect between `1544` and `1594`

**Comment by lhog** [comment]
There're no evidences this is any massive, but rather just a local issue of `czesio`'s PC or prehistoric Intel. I'm gonna remove the release blocker from this one. A single bad PC can't hold the rest of us back.

At any rate if `czesio` makes themselves available for online debug session, I'm here to help.

**Comment by GoogleFrog** [comment]
> [16:39] czesio: borken for me
[16:40] GoogleFrog: czesio you have to do something to make it work
[16:40] czesio: buy new pc
[16:40] czesio: !start
[16:40] GoogleFrog: sure
[16:40] chaplol: you said it
