### ISSUE TITLE
CPUID logging on engine start is invalidating the correctness of output of some engine command-line commands

### ISSUE THREAD

**Issue by marcushutchings** [beyond-all-reason/spring#683]
These lines:
```
[t=00:00:00.000000] [CpuId] found 6 cores and 12 logical cpus (mask: 0xfff) of type general
[t=00:00:00.000061] [CpuId] setting logical cpu affinity mask to 0xfff
```
Are always generated when the engine exe is started. Some invocations of the engine just acquire data output and on't need to know about the cpu detection. These logs cause applications parsing the output to fail data validation checks. The logs should be deferred to a time where the engine knows that a game will be running.

**Comment by lhog** [comment]
I think these lines above normally go into `stderr`, while the output goes / should go to `stdout`
