### ISSUE TITLE
Investigate crash in 6e473161205c6381c703411de7f09d8a

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#70]
https://www.beyondallreason.info/replays?gameId=6e473161205c6381c703411de7f09d8a has crashed for some and desynced for others.

Investigation showed crash happened here:

```
void CCommandAI::WeaponFired(CWeapon* weapon, const bool searchForNewTarget)
{
	if (!inCommand)
		return;

	const Command& c = commandQue.front();
```
unit in question is stiletto (id = 27371), gameFrame = 62697

commandQue was empty, which caused the crash.

The unit was in the middle of releasing its salvo against a former enemy unit that that has just been captured (has become allied).

Additional check for non `commandQue.empty()` fixes the crash but I'm not sure it's a proper fix.

**Comment by rtri** [comment]
[barspring-patch-70.diff.txt](https://github.com/beyond-all-reason/spring/files/7109425/barspring-patch-70.diff.txt)
