### ISSUE TITLE
Slow game load with archive checksum calculation

### ISSUE THREAD

**Issue by rlcevg** [beyond-all-reason/spring#701]
Can be referred as:
* slow 1st time loading with cold OS caches
* freeze on Start button
* crash (same as above) on 1st start

HDDs are most affected (SSDs feel better)

**Comment by rlcevg** [comment]
`$ vmtouch -v ".../Beyond All Reason/pool/"`
1st time load with checksum calculation:
```
Files: 17264
Directories: 257
Resident Pages: 314639/371916  1G/1G  84.6%
Elapsed: 0.32352 seconds
```
1st time load without checksum calculation:
```
Files: 17264
Directories: 257
Resident Pages: 80123/371916  312M/1G  21.5%
Elapsed: 0.26864 seconds
```
Only 21.5% is actually used on load when checksum is already calculated.
Whole game archive is 84.6% (14500 files) of `pool` directory.

Why checksum is calculated at all when next messages are in infolog (and it doesn't stop game):
```
[t=00:02:55.662740][f=-000001] Warning: [PreGame::GameDataReceived] Archive cc441d641cbc664e12ac20950af9ce1f.sdp (checksum 6c219e06f97ada5da8058661932177d2b66c288109753e29334805c33b45582d266f9b8b8cc0506dfa1ca731be88f91a76bd40e0e8b9edecebb1209a41043189) differs from the host's copy (checksum ef4acd0211707eb8f0346e6d86eb0c0a571383d18416fdb9c8d5f899e7ebda51468edda0b2f743a3f9699327bae0e96eb046fa2768024ccaa7b9bbf7f814b858). This may be caused by a corrupted download or there may even be two different versions in circulation. Make sure you and the host have installed the chosen archive and its dependencies and consider redownloading it.
```

**Comment by p2004a** [comment]
If we do precaching, it have to be in memory type that can be dropped by OS at any moment as needed, and it have to be portable on Linux and Windows.

For this issue, I recommend profiling the game load with tracy, to get the timeline and figure where we exactly spend time, etc etc. There can be a lot of inefficient things there.

**Comment by lhog** [comment]
It's in MT section and it's calculating CRC of the files IIRC. Not too long ago I made this section process window events, so in theory it shouldn't lock up the engine window and respectively not cause the OS wanting to kill it.
That said the customer experience is still terrible. That customer sees is a static picture and nothing is seemingly going on.
I'll see if I can find a commit, so you can continue from there.

**Comment by marcushutchings** [comment]
CRC is quite a slow algorithm, maybe we need to consider alternatives. Didn't you add a new/fast checksum lib recently that may help?

**Comment by lhog** [comment]
Internally it does `MD5`.
Perhaps we can go for an alternative, even non-cryptographic hash might suffice, but I believe the whole procedure is mostly IO bound.

**Comment by rlcevg** [comment]
Must be IO: i forced checksum calculation with filled page cache and it took 2-3 seconds

**Comment by lhog** [comment]
In that case MT can be harmful on systems with spinning drives. Loading say 8 files in parallel there is gonna perform worse than loading one file at the time. So perhaps the way to rewrite it is to place an IO mutex/semaphore to limit the IO concurrency.

**Comment by rlcevg** [comment]
Naive "make ST great again" isn't working solution:
```
[t=00:00:52.418058][f=-000001] Warning: [PreGame::GameDataReceived] Archive Comet Catcher Remake 1.8 (checksum 55afda3a108510936ee9d03f349736ce50a479f8bd592c58b692ee6f9d47dca69e3d087698799130b0bd1b64de5e8afebc3f9b9e9d3bd56148f115e1cc4d218c) differs from the host's copy (checksum 69944c5da1b99a8eadbef5772a800acef6590969cb9d701ba47be0c9daf2e4d713cb26cc450f948d46fdd3973bfc0899f4dcedb233ee8893bc724fda8a1617ed). This may be caused by a corrupted download or there may even be two different versions in circulation. Make sure you and the host have installed the chosen archive and its dependencies and consider redownloading it.
[t=00:03:33.597013][f=-000001] [~CPoolArchive] archiveFile="/home/bob/Documents/Beyond All Reason/packages/b2f1eda7a66bcd3bd5ac0d5772a4608d.sdp" numZipFiles=14873 sumInflSize=2021968kb sumReadTime=151344ms
[t=00:03:33.597036][f=-000001] 	file="anims/icexuick_100/cursornormal_21.png" indx=466 inflSize=2kb readTime=251ms
[t=00:03:33.597041][f=-000001] 	file="anims/icexuick_100/cursorattack_4.png" indx=93 inflSize=2kb readTime=212ms
[t=00:03:33.597046][f=-000001] 	file="luaui/images/raptor_scum/alien_guts_normalspec.dds" indx=8190 inflSize=21845kb readTime=183ms
[t=00:03:33.597051][f=-000001] 	file="music/legacy/warlow/professorkliq - youhavebeenchosen.ogg" indx=8594 inflSize=18385kb readTime=161ms
[t=00:03:33.597056][f=-000001] 	file="music/legacy/warhigh/lunyalex - a pixel is born.ogg" indx=8573 inflSize=2523kb readTime=156ms
[t=00:03:33.597061][f=-000001] 	file="luaui/images/decals_gl4/groundscars/t_groundcrack_09_a.tga" indx=7956 inflSize=16384kb readTime=151ms
[t=00:03:33.597066][f=-000001] 	file="unittextures/arm_color.dds" indx=14041 inflSize=21845kb readTime=143ms
[t=00:03:33.597070][f=-000001] 	file="anims/icexuick_133/cursorreclamate_57.png" indx=1868 inflSize=2kb readTime=142ms
[t=00:03:33.597075][f=-000001] 	file="luaui/images/raptor_scum/alien_guts_colorheight.tga" indx=8189 inflSize=16384kb readTime=138ms
[t=00:03:33.597080][f=-000001] 	file="luaui/images/raptor_scum/alien_guts_normalspec.tga" indx=8191 inflSize=16384kb readTime=133ms
[t=00:03:33.598032][f=-000001] Warning: [PreGame::GameDataReceived] Archive b2f1eda7a66bcd3bd5ac0d5772a4608d.sdp (checksum 03678592bcb3acf4e12cb6479b8c22541a25a9e212be04c21552afd2e063c805c2a763b01abf605bb831eee667eaf709e35c3ace80fadfdb6220a7e34b1a26be) differs from the host's copy (checksum ef4acd0211707eb8f0346e6d86eb0c0a571383d18416fdb9c8d5f899e7ebda51468edda0b2f743a3f9699327bae0e96eb046fa2768024ccaa7b9bbf7f814b858). This may be caused by a corrupted download or there may even be two different versions in circulation. Make sure you and the host have installed the chosen archive and its dependencies and consider redownloading it.
```
it reduced loading time by 1 minutes, but it is still 2:30, and server InitialNetworkTimeout=1:30.
gz reading must be re-done maybe (read in batches or all gzs' at once)

**Comment by lhog** [comment]
It's naturally a big task that will take some time.
WRT "make ST great again", do the check-summed files situate on a spinning disk on your system?

**Comment by rlcevg** [comment]
Yes, my system has only HDD (spinning disk), and all prior results are from testing with HDD, with manually clearing "page cache" before test.

**Comment by rlcevg** [comment]
placing `std::lock_guard<spring::mutex> lck(archiveLock2);` on top of `CPoolArchive::GetFileImpl` gave me same result as prior naive ST (2:33).

Next will be just thoughts:
Maybe the key is sequential reading of whole directory?..

**Comment by marcushutchings** [comment]
> In that case MT can be harmful on systems with spinning drives. Loading say 8 files in parallel there is gonna perform worse than loading one file at the time. So perhaps the way to rewrite it is to place an IO mutex/semaphore to limit the IO concurrency or make it a producer - consumer type of interaction.

OSes are designed to optimize these situations. They know the geometry of the hard disk platters, and order the blocks to allow the magentic disk to sweep a set of blocks going in one direction. You won't slow an HDD down by requesting multiple files via multiple threads.

**Comment by marcushutchings** [comment]
If you're on linux, then you check whether different IO schedulers change the performance results.

`cat /sys/block/{DEVICE-NAME}/queue/scheduler`

Will tell you which scheduler is in use. It will list the avaialble ones and put square brackets around the one in use.

You can change the scheduler (using the values reported in the previous command) with:

`echo {SCHEDULER-NAME} > /sys/block/{DEVICE-NAME}/queue/scheduler`

**Comment by marcushutchings** [comment]
Yes, sorry, you are correct. The advantage of sequential read cannot be understated.

**Comment by rlcevg** [comment]
```
$ cat /sys/block/sda/queue/scheduler 
none [mq-deadline] kyber bfq
```
----
Current plan is to:
1) place archiveLock234 mutex similar to https://github.com/beyond-all-reason/spring/blob/BAR105/rts/System/FileSystem/Archives/BufferedArchive.cpp#L24 (it has to be new, otherwise lockup on boot).
2) force checksum calculation on engine-loading, and after new-game-update-event in lobby.

**Comment by lhog** [comment]
> place archiveLock234 mutex similar to https://github.com/beyond-all-reason/spring/blob/BAR105/rts/System/FileSystem/Archives/BufferedArchive.cpp#L24 (it has to be other than archiveLock, otherwise lockup on boot).

I'm not sure it's the best way from the software architecture perspective. Rather than doing that I'd rework the access patterns in MT sections.

> force checksum calculation on engine-loading

That is gonna hurt if a user/player has many archive files stemming from many versions of a game or games. I think the original author split the process deliberately to address that concern and only calculate checksums where required.

**Comment by rlcevg** [comment]
> That is gonna hurt if a user/player has many archive files stemming from many versions of a game or games. I think the original author split the process deliberately to address that concern and only calculate checksums where required.

Checksum calculation is not re-done if it's already saved in `cache/105dev-BAR105/ArchiveCache16.lua`. So it's 1 hit when loading screen has actual timer and process is responding, vs hang and disconnect when starting battle.

**Comment by lhog** [comment]
> I'm narrowing issue from general improvements of HDD load speed to only checksum calculation because that's the only thing that reads whole archive (maybe preload=1 also works like this? didn't check), and yet i still don't know where that checksum being used and is it required at all.

I also searched in that direction and also didn't find anything, though I didn't try hard enough I admit. I'm assuming the checksum is used to report divergence as we sometimes see in infologs, like "the host reported your checksum is not my checksum..."

**Comment by p2004a** [comment]
IMHO: if we do optimizations here, they should not come at expense of users with SSDs, this is the primary platform that should be optimized for. So any opitmizaion for HDD performance should be also benched on SSDs to check that there aren't regressions there.

**Comment by lhog** [comment]
> Now the wrong part is that i have "the host reported your checksum is not my checksum..." for almost everything, even after fresh pool redownload, like if checksum calculation is order dependent, and MT kills order.

That is a terrible bug if true. As far as I'm aware the checksums are done per-file, respectively it shouldn't depend on MT order of execution.

**Comment by rlcevg** [comment]
So with https://wiki.archlinux.org/title/Anything-sync-daemon
```
$ time sudo systemctl start asd.service

real    0m44.538s
user    0m0.023s
sys     0m0.018s
```
and i'm good to go.
This works great for me when i don't want cache to be unloaded between game sessions.

How about "warm up cache" checkbox in launcher that would just read `pool` folder (and then discard result)?

**Comment by p2004a** [comment]
> While you guys measure ST vs MT performance on SSD how about "warm up cache" checkbox (off by default) in launcher that would just read pool folder (and then discard result)?

This was already a proposed mitigation, to read pool:
- in the background process
- with low IO priority
- when detecting fresh boot/some timeout since last scan 
after launcher is done with updating.

I would approve such PR to spring launcher, so task up for grabs.

**Comment by lhog** [comment]
Precaching looks redundant to me and it creates external dependencies not all launchers will want or can support. if anything we can see if the slow background scanning thread can be integrated instead (and most importantly integrated into existing asset desync reports) or if we can put together a "scan in progress" dialog.

**Comment by rlcevg** [comment]
A bit more onto the fan.
MT checksum
```
[t=00:00:43.364595][f=-000001] Warning: [PreGame::GameDataReceived] Archive c569dfd92ee95804e915fe214f33f29a.sdp (checksum 6c219e06f97ada5da8058661932177d2b66c288109753e29334805c33b45582d266f9b8b8cc0506dfa1ca731be88f91a76bd40e0e8b9edecebb1209a41043189) differs from the host's copy (checksum ef4acd0211707eb8f0346e6d86eb0c0a571383d18416fdb9c8d5f899e7ebda51468edda0b2f743a3f9699327bae0e96eb046fa2768024ccaa7b9bbf7f814b858). This may be caused by a corrupted download or there may even be two different versions in circulation. Make sure you and the host have installed the chosen archive and its dependencies and consider redownloading it.
```
ST checksum
```
[t=00:00:44.320321][f=-000001] Warning: [PreGame::GameDataReceived] Archive c569dfd92ee95804e915fe214f33f29a.sdp (checksum 03678592bcb3acf4e12cb6479b8c22541a25a9e212be04c21552afd2e063c805c2a763b01abf605bb831eee667eaf709e35c3ace80fadfdb6220a7e34b1a26be) differs from the host's copy (checksum ef4acd0211707eb8f0346e6d86eb0c0a571383d18416fdb9c8d5f899e7ebda51468edda0b2f743a3f9699327bae0e96eb046fa2768024ccaa7b9bbf7f814b858). This may be caused by a corrupted download or there may even be two different versions in circulation. Make sure you and the host have installed the chosen archive and its dependencies and consider redownloading it.
```

----
ST made by running
```
	for (size_t i = 0; i < fileNames.size(); ++i) {
		ComputeHashesTask(fileNames[i], fileHashes[i]);
#if !defined(DEDICATED) && !defined(UNITSYNC)
		spring::UnfreezeSpring(WDT_MAIN);
#endif
	}
```
other code that doesn't invoke ComputeHashesTask was unchanged.

**Comment by lhog** [comment]
I fixed missing checksums, but it doesn't solve the problem of lower perf of concurrent files access. This will need a separate look. I'm gonna investigate what can be done.

**Comment by rlcevg** [comment]
I don't expect further improvements specifically with this ticket.
Chobby pre-cache game files, i'd expect similar behaviour from new lobby (skylobby probably doesn't know about issue?).
Closing in a few days if no new info.
