### ISSUE TITLE
Cameras: Option to not track ground height on camera position change

### ISSUE THREAD

**Issue by badosu** [beyond-all-reason/spring#708]
In most cameras, switching camera x,z also moves y/distance/height with the ground level. This is a quirky behavior and provides some jerky/weird interactions when used for cinematic/gameplay purposes.

Proposal is to offer a config setting for not tracking groundlevel but clamping to a sane minimum height if groundlevel is too close to camera.

**Comment by PtaQQ** [comment]
Another idea would be to make it track the airmesh instead of the ground, so that it smoothens out the motion over uneven terrain significantly but still somewhat follows the ground altitude.

**Comment by dzosz** [comment]
https://streamable.com/bru49f
1. TA camera with old behavior (height to ground) - noticable camera spike.
2. Spring RTS camera with airmesh camera height - much more smooth but still noticable.
3. Example how camera behaves when terrain height influences camera height with 50% weight. This extra slider can be added to camera options.

**Comment by badosu** [comment]
Looks great!
