### ISSUE TITLE
New AMD driver causes Error on map generation

### ISSUE THREAD

**Issue by Krogoth100** [beyond-all-reason/spring#719]
Got a blocker after recent AMD driver update, related to map generation (that one which is done by Spring by supplying a MapSeed to start script), receiving this error:
(Excerpt from infolog:)
`[t=00:00:04.704666][f=-000001] Error: [ExitSpringProcess] errorMsg="Error generating map - texture generation not supported" msgCaption="Spring: caught content_error: " mainThread=1`

As a temporary solution I am using a blank map of much smaller size. This is obviously bad option, because playable map dimensions for my game are quite big and mapconvs do not do well with that. My usual procedure is to generate a large blank map via mapgen and render it with my own resources (not using texturemap).

This is the Spring code which throws the error:
https://github.com/beyond-all-reason/spring/blob/6814ef95af8eb704ede4a333cb006487594e6964/rts/Map/Generation/MapGenerator.cpp#L236

And these are my laptop's GL specs, provided by infolog:
```
[t=00:00:00.627129] 	Initialized OpenGL Context: 4.6 (Compat)
[t=00:00:00.627138] 	GLSL shader support       : 1
[t=00:00:00.627146] 	GL4 support               : 1
[t=00:00:00.627153] 	FBO extension support     : 1
[t=00:00:00.627173] 	NVX GPU mem-info support  : 0
[t=00:00:00.627182] 	ATI GPU mem-info support  : 1
[t=00:00:00.627203] 	NPOT-texture support      : 1 (1)
[t=00:00:00.627220] 	S3TC/DXT1 texture support : 1/0
[t=00:00:00.627241] 	texture query-LOD support : 0 (0)
[t=00:00:00.627250] 	MSAA frame-buffer support : 1 (1)
[t=00:00:00.627257] 	Z-buffer depth            : 24 (-)
[t=00:00:00.627274] 	primitive-restart support : 1 (1)
[t=00:00:00.627281] 	clip-space control support: 1 (1)
[t=00:00:00.627289] 	seamless cube-map support : 1 (1)
[t=00:00:00.627298] 	frag-depth layout support : 1 (1)
[t=00:00:00.627305] 	persistent maps support   : 1 (1)
[t=00:00:00.627312] 	explicit attribs location : 1 (1)
[t=00:00:00.627328] 	multi draw indirect       : 1 (-)
[t=00:00:00.627336] 	array textures            : 1 (-)
[t=00:00:00.627345] 	
[t=00:00:00.627353] 	max. FBO samples              : 8
[t=00:00:00.627360] 	max. FS/program texture slots : 32/160
[t=00:00:00.627369] 	max. texture size             : 16384
[t=00:00:00.627380] 	max. texture anisotropy level : 16.000000
[t=00:00:00.627388] 	max. vec4 varyings/attributes : 16/32
[t=00:00:00.627395] 	max. draw-buffers             : 8
[t=00:00:00.627402] 	max. rec. indices/vertices    : 536870911/536870911
[t=00:00:00.627421] 	max. uniform buffer-bindings  : 84
[t=00:00:00.627428] 	max. uniform block-size       : 4096KB
[t=00:00:00.627437] 	max. storage buffer-bindings  : 32
[t=00:00:00.627443] 	max. storage block-size       : 2047MB
```

My assumption is that the absence of DXT1 texture support is the culprit, because this line in MapGenerator.cpp
https://github.com/beyond-all-reason/spring/blob/6814ef95af8eb704ede4a333cb006487594e6964/rts/Map/Generation/MapGenerator.cpp#L220
uses DXT1 extension.

Ultimately this, or possibly something else (though unlikely), generates an error.

My request is to have a workaround without DXT1 if this is indeed the root of the problem, and get more concrete GL error in case something else does this.

**Comment by lhog** [comment]
Oh wow do you use map generation? I thought it was broken and I was even going to remove it.
Try replacing the call above with `glCompressedTexImage2D()`. This one is going to be hard to fix remotely without AMD GPU at hand.

**Comment by Krogoth100** [comment]
> Oh wow do you use map generation? I thought it was broken and I was even going to remove it. Try replacing the call above with `glCompressedTexImage2D()`. This one is going to be hard to fix remotely without AMD GPU at hand.

Oh yes, it is very useful in my particular case.

I shall be able to make some work for engine in about a week, I may start with this one, but if someone knows this stuff, you are welcome : )

**Comment by lhog** [comment]
As a side note: ZK recreated random maps Lua side. See if you can reuse their technology, because I heard engine's is truly bad http://zero-k.info/Maps/Detail/61184

**Comment by Krogoth100** [comment]
> As a side note: ZK recreated random maps Lua side. See if you can reuse their technology, because I heard engine's is truly bad http://zero-k.info/Maps/Detail/61184

Thanks! That's a useful code there.
But I use mapgenerator for creating _blank_ map only: SimpleMapGenerator:MapGenerator just plains out whole map at a height of 50.
This is useful because my game uses quite big maps of about 40x40 size and potentially more (it is tested, works fine so far), so I do not want to _load_ any resources. While feeding Spring an empty height map is not such a problem, it seems that a map has to have a texturemap (SMT), which would require very large resolution; supplying that, which is not gonna be used at all, would be redundant.
For example, take a look at that ZK generated map (Random Plateaus v1.1). It is 10x10, and SMF takes about 2MB, SMT - about 16 MB. For a map of 40x40 that is gonna be about 32+256 ~= 300 MB.

**Comment by Krogoth100** [comment]
Also that same Random Plateaus map could be halved in size and made of flexible size, because new_map_x and new_map_y apparently can be set as a map option.

**Comment by lhog** [comment]
The code is removed in https://github.com/beyond-all-reason/spring/commit/23642157d1405e352a1a8bc232066ad5635c6460

**Comment by TheDubiousLittleGoober** [comment]
i have the same problem but does anyone here know how to fix this i made a github acc just for this

**Comment by Krogoth100** [comment]
> i have the same problem but does anyone here know how to fix this i made a github acc just for this

For clarity, can you state the problem and which Spring version do you use

**Comment by TheDubiousLittleGoober** [comment]
nvm im not really into zero k map creatoin anymore

________________________________

**Comment by Krogoth100** [comment]
Apparently I removed not enough.
lhog's changes should fix it completely.
