### ISSUE TITLE
Loading of certain maps + games fail under debian linux distros

### ISSUE THREAD

**Issue by tizbac** [beyond-all-reason/spring#724]
Tested:
Debian 11
Debian 12

Version:
spring_bar_{BAR105}105.1.1-1654-g476f32b

GPU:
RTX 3060 12GB

Map:
Techno Lands Final 13.7

Game:
Tech Annihilation test-10963-ae5080b"

Some suspect errors at start include 
[t=00:00:11.044005][f=-000001] [gadgets.lua] Error: Failed to load: map_disable_buildoptions.lua  ([string "LuaRules/Gadgets/map_disable_buildoptions.lua"]:16: attempt to index field 'armsp' (a nil value))
[t=00:00:11.511655][f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=LoadCode trace=[Internal Lua error: Call failure] [LuaVFS::Include(synced=true)][pcall] file=LuaRules/gadgets.lua error=2 ([string "luarules/gadgets/include/mex_utilities.lua"]:17: attempt to perform arithmetic on field 'm' (a nil value)) ptop=3 cenv=false vfsmode=Mmb
stack traceback:
	[C]: in function 'Include'
	[string "LuaRules/main.lua"]:9: in main chunk

After that if playing solo you end up without COM, if online immediately desynced
Doing bisect too if i find a working revision

**Comment by lhog** [comment]
Do other people play on the same map and same game normally?

**Comment by tizbac** [comment]
Yes they do, also had another report from another player "murtagon" having exactly same issue , also map checksum is different , but lobby says synced
https://pastebin.com/ctjcjX20

**Comment by tizbac** [comment]
Bisect unfortunately is a failure because older revision don't compile at all and the ones that compile all have the problem, what i know for certain is that with  original 105 it is ok

**Comment by p2004a** [comment]
A few hundred of the last engine versions are on https://engine-builds.beyondallreason.dev/index.html and some sporadic older on https://github.com/beyond-all-reason/spring/releases You can try bisecting using that.

**Comment by tizbac** [comment]
Ok from what've been able to test so far it seems map options are not loaded at all, the metal being nil on mex_helper is because map_metal option is completely missing

**Comment by tizbac** [comment]
Ok update, it seems to be caused by uninitialized variable

Replaying the demo works
Replaying the demo and connecting to it works
Joining game as spectator does not work
Debug build WORKS

**Comment by lhog** [comment]
So let me recap. You've installed a clean Debian 11 and TechA + TechA map just didn't load for you?

**Comment by lhog** [comment]
FWIW, I have the same error as you on Windows 10:
`[LuaVFS::Include(synced=true)][pcall] file=LuaRules/gadgets.lua error=2 ([string "luarules/gadgets/include/mex_utilities.lua"]:17: attempt to perform arithmetic on field 'm' (a nil value)) ptop=3 cenv=false vfsmode=Mmb`

`sram` is just nil here: https://github.com/techannihilation/TA/blob/master/luarules/gadgets/system_info.lua#L139

My only conclusion is that TechA should fix it. Not an engine issue.

**Comment by tizbac** [comment]
> FWIW, I have similar error to yours on Windows 10: `[LuaVFS::Include(synced=true)][pcall] file=LuaRules/gadgets.lua error=2 ([string "luarules/gadgets/include/mex_utilities.lua"]:17: attempt to perform arithmetic on field 'm' (a nil value)) ptop=3 cenv=false vfsmode=Mmb`
> 
> My only conclusion is that TechA should fix it. Not an engine issue.

That was me trying to load map without options, the issue is the above infolog which does not have said error, and i pinpointed it to be related to compilation in debug mode , so most likely uninitialized variable, trying running with valgrind but takes ages

**Comment by lhog** [comment]
That is a game-side / map-side issue, I'm 99% sure, perhaps related to small changes (likely bugfixes) happened between 105 and Recoil. Unpack the map and game with 7z/zip and fix the gadget there.

**Comment by tizbac** [comment]
It's not possible because with same game / map / start script, sometimes it works others not, when slowed down by debug mostly works

**Comment by tizbac** [comment]
Also another thing to point out, happens with deltasiegedry too , which has not the mentioned gadgets

**Comment by lhog** [comment]
So I've just done what I said you should have done:

`[LuaVFS::Include(synced=true)][pcall] file=LuaRules/gadgets.lua error=2 ([string "luarules/gadgets/include/mex_utilities.lua"]:17: attempt to perform arithmetic on field 'm' (a nil value)) ptop=3 cenv=false vfsmode=Mmb`

Points to
```
local mex = {
	set = function(mexSpots)
		for i = 1, #mexSpots do
			local x = mexSpots[i].x / 16
			local z = mexSpots[i].z / 16
			local m = 255 * mexSpots[i].m
			SetMetalAmount(x, z, m)
		end
	end,
....
```

Dig deeper where `mex.set()` is called:
```
	function gadget:Initialize()
		PlayerGeoVents = {}
		PlayerMetalSpots = {}
		mex.set(constMexSpots)
		vent.set(constVentsSpots)
	end
```
`constMexSpots = VFS.Include("luarules/configs/metalSpots.lua")`

```
local mAmount = tonumber(Spring.GetMapOptions().map_metal)
local middleMexes = {}

frontMexes = {
		{m = mAmount, 	x = 4922, 	z = 6318},
```

`Spring.GetMapOptions()` returns empty list during the default run, thus `mAmount` is nil.
What should have been done there instead is to either poison/redefine `Spring.GetMapOptions()` call game side and adding defaults or modify the call above `tonumber(Spring.GetMapOptions().map_metal or <somenumber>)`. As said it's a map side / game side issue.

**Comment by tizbac** [comment]
> So I've just done what I said you should have done:
> 
> `[LuaVFS::Include(synced=true)][pcall] file=LuaRules/gadgets.lua error=2 ([string "luarules/gadgets/include/mex_utilities.lua"]:17: attempt to perform arithmetic on field 'm' (a nil value)) ptop=3 cenv=false vfsmode=Mmb`
> 
> Points to
> 
> ```
> local mex = {
> 	set = function(mexSpots)
> 		for i = 1, #mexSpots do
> 			local x = mexSpots[i].x / 16
> 			local z = mexSpots[i].z / 16
> 			local m = 255 * mexSpots[i].m
> 			SetMetalAmount(x, z, m)
> 		end
> 	end,
> ....
> ```
> 
> Dig deeper where `mex.set()` is called:
> 
> ```
> 	function gadget:Initialize()
> 		PlayerGeoVents = {}
> 		PlayerMetalSpots = {}
> 		mex.set(constMexSpots)
> 		vent.set(constVentsSpots)
> 	end
> ```
> 
> `constMexSpots = VFS.Include("luarules/configs/metalSpots.lua")`
> 
> ```
> local mAmount = tonumber(Spring.GetMapOptions().map_metal)
> local middleMexes = {}
> 
> frontMexes = {
> 		{m = mAmount, 	x = 4922, 	z = 6318},
> ```
> 
> `Spring.GetMapOptions()` returns empty list during the default run, thus `mAmount` is nil. What should have been done there instead is to either poison/redefine `Spring.GetMapOptions()` call game side and adding defaults or modify the call above `tonumber(Spring.GetMapOptions().map_metal or <somenumber>)`. As said it's a map side / game side issue.

This is another issue, map fault of not loading defaults but i did the test wrong, has nothing to do with this issue 
Can you please disregard Techno lands widgets ? it happens even with speedball with simple AI vs Human script, sometimes it loads, mostly doesn't on debian

**Comment by lhog** [comment]
> Can you please disregard Techno lands widgets ?

Ok what other issue has left?

**Comment by tizbac** [comment]
To summarize:
That with tech annihilation on debian ( 11, 12 tested ) game most of the time will not even spawn commanders with no errors on infolog 
Replaying the same replay works but only if i compile spring myself 
Debug build greatly increases chances of it working , all that without touching game files ( map / mod )

**Comment by lhog** [comment]
Please attach an infolog from the run where you have no commander, but no errors were reported.

**Comment by tizbac** [comment]
[infolog.txt](https://github.com/beyond-all-reason/spring/files/11072567/infolog.txt)
[script.txt](https://github.com/beyond-all-reason/spring/files/11072570/script.txt)

About compilation it is actually the opposite... , the compiled engine works more reliably than the official binary

**Comment by lhog** [comment]
You have LuaRules crash in that infolog. Not the same crash I traced, but another one.
```
[t=00:00:08.748037][f=-000001] Error: [LuaRules::RunCallInTraceback] error=2 (LUA_ERRRUN) callin=LoadCode trace=[Internal Lua error: Call failure] [LuaVFS::Include(synced=false)][pcall] file=LuaRules/gadgets.lua error=2 ([string "LuaRules/Gadgets/system_info.lua"]:139: bad argument #1 to 'gsub' (string expected, got nil)) ptop=3 cenv=false vfsmode=Mmeb
stack traceback:
	[C]: in function 'Include'
	[string "LuaRules/draw.lua"]:9: in main chunk
```
https://github.com/techannihilation/TA/blob/master/luarules/gadgets/system_info.lua#L139
Which means `s_ram` is nil, which means the line above `s_ram = string.match(line, '([0-9]*MB RAM)')` failed for you. Clone TechA as a game directory, place Spring.Echo(line) before the line above and see what it wrong.

**Comment by lhog** [comment]
Actually I can tell that infolog is not always get flushed synchronously for performance reasons, so what this gadget does is straight unreliable and wrong. Never do stuff like that.

**Comment by tizbac** [comment]
Well yes you were right , but here comes the funny part 

/home/tiziano/bar/spring --isolation-dir /home/tiziano/bar2 --write-dir /home/tiziano/.spring /home/tiziano/.spring/script.txt # Works

/home/tiziano/bar/spring --isolation-dir /home/tiziano/.spring/engine/spring_bar_.BAR105.105.1.1-1654-g476f32b_linux-64-minimal-portable.7z --write-dir /home/tiziano/.spring /home/tiziano/.spring/script.txt # Lua rules error

bar2 is created with 
cp -rv .spring/engine/spring_bar_.BAR105.105.1.1-1654-g476f32b_linux-64-minimal-portable.7z/ bar2
Being the files the same i didn't do that test, that's why sometimes i had different results

**Comment by lhog** [comment]
Well the debug build overrides some of the logging constants, maybe it forces flushing.
At any rate you don't want to play racing games with infolog.txt

**Comment by tizbac** [comment]
The above commands are both with official release, it has something to do with data path... , will reopen issue if i figure out it can't be fixed mod side

**Comment by lhog** [comment]
> it can't be fixed mod side

It certainly can be and should be. The information about memory amount of a player is not critical, checking if the `s_ram == nil` and replacing it with `unknown` is trivial. If the information about memory amounts is needed, TechA devs should open up a request so the data is available as one of the Lua constant tables.

**Comment by tizbac** [comment]
> > it can't be fixed mod side
> 
> It certainly can be and should be. The information about memory amount of a player is not critical, checking if the `s_ram == nil` and replacing it with `unknown` is trivial. If the information about memory amounts is needed, TechA devs should open up a request so the data is available as one of the Lua constant tables.

Figured out and fixing dirty for now, then i'll make a pull request to add lua api for that, because fetching sys info this way is really ugly
