### ISSUE TITLE
Changing of timezone (e.g. daylight savings time) forces archives rescan on Windows 

### ISSUE THREAD

**Issue by p2004a** [beyond-all-reason/spring#725]
What title says "Changing of timezone (e.g. daylight savings time) forces archives rescan on Windows ". It doesn't happen on Linux, only on Windows. It happened last autumn, and happened also today then we switched timezones.

**Comment by sprunk** [comment]
Apparently it also means distributing a pre-cached `archiveCache.lua` (to avoid scanning everything after install) does not actually help (except if you happen to be in the same timezone as the machine that prepared the install package).
