### ISSUE TITLE
Crash 105.1.1-1544-g058c8ea

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/spring#727]
[Stacktrace translated.txt](https://github.com/beyond-all-reason/spring/files/11073227/Stacktrace.translated.txt)
[Stacktrace.txt](https://github.com/beyond-all-reason/spring/files/11073228/Stacktrace.txt)
[20230326_142334_Koom Valley 3 3_105.1.1-1544-g058c8ea BAR105.zip](https://github.com/beyond-all-reason/spring/files/11073230/20230326_142334_Koom.Valley.3.3_105.1.1-1544-g058c8ea.BAR105.zip)
31:34 timestamp (f=0056840)

**Comment by 6AKU** [comment]
![image](https://user-images.githubusercontent.com/116835691/227891960-b1373adc-9af0-45fb-a7c2-e8052de24ffc.png)
seems correap units cause crash here at 31:34

**Comment by marcushutchings** [comment]
Fixed by https://github.com/beyond-all-reason/spring/commit/71dcca8df6209caa5dc46f50d7403140e313bb67
