### ISSUE TITLE
105-1682 Some players have invisible ground

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#736]
![image](https://user-images.githubusercontent.com/1318249/229333108-0da1dfdd-a6a4-49c2-800d-dd5fb1dfcf08.png)

![image](https://user-images.githubusercontent.com/1318249/229333130-9af5776a-ba86-4208-8458-80ee1cf2beb5.png)

This is what /advmapshading 0 looks like to me.

![image](https://user-images.githubusercontent.com/1318249/229333153-971a0cf7-af37-491f-a535-bc2179640f32.png)

https://zero-k.info/Maps/DetailName?name=Faultline v1.0

**Comment by lhog** [comment]
The next generation of map mesh generators can no longer work without shaders. Two possible solutions:
1) Remove `/advmapshading` switch - best way possible
2) Emulate `/advmapshading 0` with simplified shader - might improve the performance a little bit.

**Comment by sprunk** [comment]
> The next generation of map mesh generators can no longer work without shaders. 

Does that mean people with no shader support are screwed? Previously they could muddle along just see ugly versions of things due to fallbacks, but missing terrain is another thing.

**Comment by lhog** [comment]
Secretly 99% of the engine uses shaders: UI, fonts, projectiles, effects, etc. The option to disable shaders has been removed long ago too.

So for the most part my only concern is that the engine terrain rendering binds like 16 textures and sample from all of them. I think this part can be dumbed down to bare minimum so potato PCs can enjoy the bleak map visuals they're so used to.

**Comment by GoogleFrog** [comment]
So are you effectively saying that removing the advmapshading toggle would break things for barely anyone, since secretly the engine uses so many shaders that the people who it would break map rendering for have already been filtered out?

**Comment by lhog** [comment]
Yes, the engine won't even run if OpenGL reports no shaders support. "Shaders support" is a broad term though and mostly depends on the reported (and actually supported) maximum version of GLSL. I try to keep the version for engine provided GLSL code as low as possible for non-GL4 code (GL4 code has non-GL4 fallback so it's not a big deal). The map shader also uses GLSL version 1.30 (released in Nov 2009). So basically yes, I'm not concerned about additional dropouts, but indeed GPUs handle the "advanced" map shading with lower perf than basic shading, so keeping shader emulated `/addvmapshading 0` makes some sense.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/230709800-91edc539-afe5-4844-a7b7-a286c534a8db.png)

Something very similar just happened for me with /advmapshading 0. Titan Duel.
