### ISSUE TITLE
No textures are bound with 3do FlyingPiece models (aka ShatteredPieces)

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#755]

**Comment by lhog** [comment]
Should be fixed in the next stable. Reopen if it doesn't.

**Comment by lhog** [comment]
@springraaar ^^

**Comment by springraaar** [comment]
Thanks, is there a build where i could try this? The test i'll do is simply reenable the self-destruct, /give all units, and self-destruct them.

MF triggers "shatter" explosions on a few pieces on nearly all units. If it doesn't crash then it's very likely a safe change.

**Comment by springraaar** [comment]
seems to work fine on build 1742
