### ISSUE TITLE
units will path through footprints to attempt to get to their intended destination

### ISSUE THREAD

**Issue by drivver44** [beyond-all-reason/spring#761]
![image](https://user-images.githubusercontent.com/75929927/232166332-3b2e5340-cdb9-4167-a2bd-0113d2f4d12d.png)
this shows off the bugger off for the t2 kbot factory

https://youtu.be/0qXBjWyYmc8
this was originally done for tarnished but might be worth for others to see

**Comment by drivver44** [comment]
this is also on the QTPFS pathfinding system

**Comment by sprunk** [comment]
@marcushutchings another ticket I think was recently fixed.

**Comment by marcushutchings** [comment]
Yes. This has been fixed. It will be available in the next engine release.
