### ISSUE TITLE
Make terrain blocking affect drawed range rings

### ISSUE THREAD

**Issue by drivver44** [beyond-all-reason/spring#762]
currently if terrain blocks shots, the rings displayed are only modified on their effective draw range instead of taking into account the terrain. 
i think this is the right place atleast.
![image](https://user-images.githubusercontent.com/75929927/232172923-c08a635b-2e0b-4274-bdab-a3707e9701aa.png)

**Comment by lhog** [comment]
That's very computationally expensive especially for a ballistic weaponry, but even for lasers. Basically for every pixel inside the range the simulation needs to run on whether it is not blocked.
Even doing it on a massively parallel GPU is going to be quite expensive, but possible (see a radar placement widget of BAR). I'm afraid we can't include that option as a default UI element.
