### ISSUE TITLE
1696 - Sync erorr for me

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#763]
I had a sync error. Write what sort of stuff you'd like for it.

[syncError.zip](https://github.com/beyond-all-reason/spring/files/11238229/syncError.zip)

Battle with replay (or attached): http://zero-k.info/Battles/Detail/1609547

[autohostReplay.sdfz.txt](https://github.com/beyond-all-reason/spring/files/11238230/autohostReplay.sdfz.txt)

**Comment by lhog** [comment]
You can do a few things:

1) Watch both replays and see if the engine agrees with your checksum during the play (you can share both infologs so we can have a look)
2) Do https://github.com/beyond-all-reason/spring/wiki/Engine-Settings-Config-File on your server hosts. This will cause desyncs to dump state on all clients, then you can upload two files, one from a desyncee and one from a non-desyncee. The files will have the following filename pattern `ClientGameState-<random number>-<desync detection frame>-<desync detection frame>.txt`

@marcushutchings for viz.

**Comment by GoogleFrog** [comment]
[infolog.txt](https://github.com/beyond-all-reason/spring/files/11302968/infolog.txt)
[infolog_full.txt](https://github.com/beyond-all-reason/spring/files/11302969/infolog_full.txt)

Watching the replay from the server.

**Comment by GoogleFrog** [comment]
[infolog.txt](https://github.com/beyond-all-reason/spring/files/11303000/infolog.txt)
[infolog_full.txt](https://github.com/beyond-all-reason/spring/files/11303001/infolog_full.txt)

Watching the replay I saved again.

**Comment by marcushutchings** [comment]
GoogleFrog's machine agrees with the server on both of those replay logs - i.e. his machine doesn't agree with the checksum his machine produced during the live match.

**Comment by lhog** [comment]
Ok, another presentation of a heisenbug then.

**Comment by sprunk** [comment]
Looks like nothing could be done here.
