### ISSUE TITLE
QTPFS order does not get canceled when unit cannot path into footprint

### ISSUE THREAD

**Issue by drivver44** [beyond-all-reason/spring#772]
![screen00168](https://user-images.githubusercontent.com/75929927/232259635-a4b24e65-5b7a-42b0-a816-acbd4b32e279.png)
footprint of the factory with corhrk selected

https://youtu.be/z4OwSc_F8cU

**Comment by sprunk** [comment]
@marcushutchings wasn't this fixed recently?

**Comment by marcushutchings** [comment]
Yes, I believe that was been fixed. @drivver44 would you double check on the test server?

**Comment by marcushutchings** [comment]
No indication that the issue persists. Closing.
