### ISSUE TITLE
1696 - Cegs have ugly flickery lines at the edges

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#773]
![spring_2023-04-16_16-07-06](https://user-images.githubusercontent.com/1318249/232277520-704f9712-b45c-40d6-ad4c-c2abb26a3a88.gif)

This stuff
![image](https://user-images.githubusercontent.com/1318249/232277537-aeb747fb-8b71-410f-bf99-43aa1b319069.png)

The unit turretaafar seems to be particularly good at making it.
![image](https://user-images.githubusercontent.com/1318249/232277638-fd18accf-8830-4bbc-b060-359af6bf6c55.png)

Setting MaxTextureAtlasSizeX and Y to 4096 did nothing to the issue. 1485 works fine.

[infolog.txt](https://github.com/beyond-all-reason/spring/files/11241429/infolog.txt)

**Comment by lhog** [comment]
Same effect on previous stable (1544):

![screen02361](https://user-images.githubusercontent.com/1476261/232940449-ce80d9ba-ddc1-4e4d-8f54-e97eb29823ca.png)
![screen02362](https://user-images.githubusercontent.com/1476261/232940457-9d19abd9-be22-4a1a-bc65-035092c51674.png)
