### ISSUE TITLE
addon:UnitIdle is being called right after issuing a command

### ISSUE THREAD

**Issue by MaDDoXbr** [beyond-all-reason/spring#775]
This is really confusing, and makes it very hard to track when a unit is really "idle". I noticed Floris checks for 'fullbuildqueue' on his idlebuilders widget. Apparently when I add a queue of commands (move, etc), it does fire up the event as expected at the end of the queue (in spite of firing up multiple times for each shift+rightclick), as you can see in the gif attached. 
PS: Skylobby isnt saving a replay for single player games, not sure why.. anyways, all you need to replicate is the below code added to any widget:

```
function widget:UnitIdle(unitID, unitDefID, unitTeam)
      Spring.Echo("\nUnitIdle fired for: "..unitID)
end

function widget:CommandNotify(cmdID, params, options)
    Spring.Echo("CommandID registered: "..(cmdID or "nil"))
end

```    

Engine: 105.1.1-1544 BAR
Game: Total Atomic Power 3.4.5

![widget_unitidle_fail](https://user-images.githubusercontent.com/265085/232345053-83c8675d-8780-4794-b5e1-f9ca336b4f14.gif)

**Comment by sprunk** [comment]
Try also
```
function widgetHandler:UnitCommand(unitID, unitDefID, unitTeam, cmdID)
  Spring.Echo("UnitCommand", unitID, cmdID)
end
```
since it seems to be getting (and immediately finishing) some "invisible" command (like stop, or state change) before the move command and in that fleeting moment it is idle.

**Comment by MaDDoXbr** [comment]
Found my error. I had a function to remove a bunch of command types, and giveOrderToUnit(unitID, CMD_REMOVE, ...) doesn't fire up UnitIdle, but for whatever reason I let a giverOrderToUnit(unitID, CMDSTOP,...) there. Damn. 
Ok, let's shut this issue down, thanks for the help @sprunk ^_^
