### ISSUE TITLE
unit sharing/transferring fails

### ISSUE THREAD

**Issue by Ruwetuin** [beyond-all-reason/spring#791]
Here is a replay where unit sharing manually and also via gadget wont work for a player
https://www.beyondallreason.info/replays?gameId=24374a645626c0173ea3d979ccd174a2

At 7:13 ZmejGorianin attempts to share a t2 constructor to Big_Dolfy a coupel of times.
Later that t2 con will upgrade Big_Dolfy's t1 mexes. The gadget that transferres the t2 mex on completion doesnt transfer it either.

![image](https://user-images.githubusercontent.com/11016921/234834033-52add6ae-34c4-4942-8db4-4e99211faf9d.png)

**Comment by Beherith** [comment]
Could perhaps the allowunittransfer gadget, the one that does the no-ally-capture be interfering?

**Comment by Ruwetuin** [comment]
no, that gadget is extremely simple and only acts o nthe capture cmd

**Comment by sprunk** [comment]
Replay expired
