### ISSUE TITLE
Destroying geovent features with Spring.DestroyFeature doesn't work

### ISSUE THREAD

**Issue by ForbodingAngel** [beyond-all-reason/spring#824]
```
local featureList = Spring.GetAllFeatures()
for i = 1, #featureList do
    local fID = featureList[i]
    local fDefID = Spring.GetFeatureDefID(fID)
    local fDef = FeatureDefs[fDefID]

    if fDef.geoThermal and (fDef.name ~= 'geovent') then
	    Spring.DestroyFeature(fID)
    end
end
```

As an example. This will not destroy geovent features. It seems to work on anything else, but not geovents. 

Relevant code:
https://github.com/SplinterFaction/SplinterFaction/blob/master/LuaRules/Configs/MetalSpots/defaultLayout.lua#L94

**Comment by sprunk** [comment]
The `fDef.name ~= 'geovent'` check that prevents reaching the `DestroyFeature` call looks like it might be relevant.

**Comment by ForbodingAngel** [comment]
Removing the if statement results in all features being removed EXCEPT vanilla featuredefs.

https://github.com/beyond-all-reason/spring/blob/92a5b9dcaa3006a771e0905fab3cc10b8ca126f8/rts/Sim/Features/FeatureDefHandler.cpp#L224

**Comment by sprunk** [comment]
Don't remove the whole `if`, only the `and fDef.name ~= 'geovent'` part. Or change the whole `if` into `if fDef.name == 'geovent'`.

Make sure the way you check for geovents actually takes the removal into account. Most highlight widgets just cache the list at start and never update it.

**Comment by ForbodingAngel** [comment]
I'm a little confused. Highlight widget? I mean yes I use one, but what is
actually happening is the attempt to remove map placed geovents and place
my own at the beginning of the match. I can easily place my own, but I
cannot remove the map geovents.

Probably the best way to verify that they don't get removed would be to
make a 5 line gadget and attempt to remove them in ZK or another project,
wouldn't it?

Maybe I'm misunderstanding you?

**Comment by sprunk** [comment]
> Probably the best way to verify that they don't get removed would be to
make a 5 line gadget and attempt to remove them in ZK or another project,
wouldn't it?

Yes, I tried and it works in ZK.

During the week I can grab SF and test I guess.

**Comment by sprunk** [comment]
Seems resolved with no engine change required

**Comment by lhog** [comment]
Seems it's time to close it then.
