### ISSUE TITLE
setting missilelauncher flare texture to null no longer disables it

### ISSUE THREAD

**Issue by springraaar** [beyond-all-reason/spring#825]
game : metal factions v2.19
map : any
engine : recoil 1757 (1544 works fine)

Can be reproduced by spawning "aven_weaver" and ordering it to attack ground, pause to check the flare/trail for the missiles. The default flare should be omitted as weapondef has texture1=null but a whiteish square is drawn instead  

![image](https://github.com/beyond-all-reason/spring/assets/11828472/435bfbad-d41a-47ce-80db-03762ecfa910)

![image](https://github.com/beyond-all-reason/spring/assets/11828472/6fb4eeff-5ac6-4f08-ae76-867cd4995ee9)

**Comment by lhog** [comment]
Bisected to this commit https://github.com/beyond-all-reason/spring/commit/9333020dd617e8b90faa87080a3842c628837639
