### ISSUE TITLE
Shadow projection matrix is culled wrongly

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/spring#83]
Happens on small maps or when camera angle is unusual
![screen02016](https://user-images.githubusercontent.com/1476261/133862207-1724a890-ebe1-459e-aad8-7bff8ab64787.png)
![screen02017](https://user-images.githubusercontent.com/1476261/133862210-99e983e1-36e3-463b-a3ad-1a031b89447a.png)
.

**Comment by Beherith** [comment]
Yes ive seen this quite often, its not that hard to trigger on smaller maps, thanks for ticketing it.

**Comment by lhog** [comment]
I tinkered with this one a little bit and haven't seen a single failure case since then.
Reopen if this will happen again on latest BAR105
