### ISSUE TITLE
Fog of war stripes stays even it's in radar area

### ISSUE THREAD

**Issue by 6AKU** [beyond-all-reason/spring#830]
Reproduce:
1. Have fog of war enabled.
2. Build radar.
3. Observe that stripes didn't disappear completely.
Appendix: disabling and enabling FOW via key L fixing issue.

https://youtu.be/eHjsg1VDmrY

**Comment by 6AKU** [comment]
> Aren't the stripes a BAR thing?

I can do /luaui and stripes still exist.

**Comment by sprunk** [comment]
Yes, it's not a part of LuaUI because it's the LoS shader, but is still BAR specific. Check what happens with the default LoS shader.

**Comment by 6AKU** [comment]
> Check what happens with the default LoS shader.
I don't know how to to this.

**Comment by lhog** [comment]
https://github.com/beyond-all-reason/Beyond-All-Reason/blob/master/shaders/GLSL/infoLOS.lua#L127

**Comment by 6AKU** [comment]
Ok, i need move it to gameside bugtracker later.
