### ISSUE TITLE
Loading a saved scenario is broken

### ISSUE THREAD

**Issue by Born2Crawl** [beyond-all-reason/spring#84]
When playing a scenario, you can save a game (by pressing a button, I did it in a paused state), but after loading it, the following game-breaking issues make it useless:

1. Some units can't fire. This means neither automatically, nor when pointing them at an enemy.
2. Animations for many units stop working. They move, but the walking animation doesn't play.
3. Ghosts of the units you start a scenario with, appear in their original positions, but can't be selected.
4. It looks like all wrecks become invisible. They can still be found by area Resurrect or Reclaim.

Video: https://www.youtube.com/watch?v=PCbbHlaui3Y
Savefile: [Save.zip](https://github.com/beyond-all-reason/spring/files/7214284/Save.zip)

This behavior is observed for at least a month. Current version: Beyond All Reason (Spring 105.1.1-475-gd112b9e BAR105).

**Comment by lhog** [comment]
Attn @ashdnazg ^^

**Comment by Beherith** [comment]
It was my fault, dont spawn units in initialize, but use gadget:GamePreLoad(), as that does not get called on loading a savegame!

Fixed

**Comment by Beherith** [comment]
I only fixed number 3 :/

**Comment by ashdnazg** [comment]
The initialise thing is a bug, units existing on startups should be cleaned, including ghosts

**Comment by Born2Crawl** [comment]
So it looks like the ghost units and the broken shooting + animation for units like Maverick are fixed now. The only issue I still noticed, are invisible wrecks after reload of a saved game. My rezzer was even resurrecting one at the moment of the load, was continuing to resurrect the invisible wreck :)

**Comment by Born2Crawl** [comment]
In addition to invisible wrecks, I just discovered that after loading a saved game, constructors refuse to reclaim trees in order to build something and just get stuck waiting for the area to clear: [image](https://media.discordapp.net/attachments/549282926596980738/895029366323572786/Screenshot_2021-10-05_04-23-13.png)

**Comment by marcushutchings** [comment]
Is this still an issue or do changes to the save system after this last post resolve the issue?

**Comment by lhog** [comment]
Data here is outdated. If new save/load issues are found, we should open new issue.
