### ISSUE TITLE
Move goals to impassible areas is non-functional in heavily modified terain.

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#849]
See https://github.com/ZeroK-RTS/Zero-K/issues/4925

The screenshot below demonstrates that the engine default Fight command has the same bug as the ticket above.

![image](https://github.com/beyond-all-reason/spring/assets/1318249/70f4e908-6264-4498-a6ae-743fee567a04)

**Comment by GoogleFrog** [comment]
104.0.1-1681-gc5724ef works and 105.1.1-1088-gc6f1723 does not work.

Engines in between tend to crash or are otherwise broken. Eg here is the best picture I could get of 105.1.1-767-gfdd38be. Units seem to be unable to path up cliffs with a default engine command.
![image](https://github.com/beyond-all-reason/spring/assets/1318249/dba094c2-363d-4750-89f9-9af94c618ee9)

**Comment by GoogleFrog** [comment]
- 104.0.1-1978-gcd328de works. It is the last build of 104.
- 105.1-475-gd112b9e works.
- 105.1.1-653-g954b191 does not work.
- 105.1.1-822-ga2f88fe does not work, but at least constructors can walk up cliffs onto passable terrain.

**Comment by marcushutchings** [comment]
Pushed a fix to the mainline that should address this issue: https://github.com/beyond-all-reason/spring/commit/6e72d021ec54726c9cb0333cbfb7165e9f43ef4f
