### ISSUE TITLE
Stale quadtree for projectile collisions

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#85]
Copied from mantis:
![image](https://user-images.githubusercontent.com/1318249/134766475-cc37b11f-f8e1-4ecf-b252-eb531337abaf.png)
Apparently the unit here is considered to be exclusively in quad 870 at the time of this screenshot. This causes projectiles and rays that do collision tests without considering quad 870 to erroneously not collide with it. This has been noticed by players of ZK in two situations:
- Widow missing units with its short range LightningCannon.
- Anti-Air missiles penetrating bombers.

It probably happens a lot more, but doesn't impact gameplay in a hugely noticeable way. With some investigation I'd expect to find it impacting balance in a few ways. Now that I think of it, high duration beam lasers sometimes flicker through mobile units for a frame. This may well be related.

On the mantis ticket esainane claims that quad membership updates at 2Hz, barring any sudden changes in position. There are two suggested fixes so far.
- The hacky performant method: When projectiles check for collision, add the target of the projectile to the units to be checked in addition to the units found via the quadtree search.
- The perfect but potentially slow method: Update the quadtree at 30Hz rather than 2Hz.

See:
- https://springrts.com/mantis/view.php?id=6421 Ticket about Widow
- https://github.com/ZeroK-RTS/Zero-K/issues/4522 LightningCannon ticket, not that hard to reproduce.
- https://github.com/ZeroK-RTS/Zero-K/commit/a02b8015e6102111ad840d6463f37aa25f3f3782 Commit that works around the issue by increasing projectile radius.
-

**Comment by marcushutchings** [comment]
Running the update every frame rather than slowupdate does increase the stress on the system, but we are talking about going from 0.0-0.1% to 0.4-0.6% in a 3v3 BARB game onDWorld V3 (a huge 28x28 map.) That seems acceptable.

**Comment by GoogleFrog** [comment]
How does it compare to adding a fudge factor to unit radius? Probably just asking for trouble though, given the low cost of the proper fix.

**Comment by marcushutchings** [comment]
It probably is. To do it probperly, the quad field system would have to be fed the delay interval and be able to figure out the maximum speed of the unit in question - that breaks down if the unit uses a custom movement script. At least here, we are covered. If we suspect that cost gets too much then we can revisit it.

**Comment by marcushutchings** [comment]
Change made:

https://github.com/beyond-all-reason/spring/commit/62fead6794ae9558fb34707a525b7298c45806ca

**Comment by GoogleFrog** [comment]
What do you mean by custom movement script? When lua teleports units the quadtree is recalculated instantly. This is used for some hax that works around the bug.
