### ISSUE TITLE
1774 Graphics crash with reasonable graphics card

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#863]
[message(1).txt](https://github.com/beyond-all-reason/spring/files/11788481/message.1.txt)

From freewarstylehorror here: https://discord.com/channels/278805140708786177/398080676525506560/1120339284818411610

It has happened twice, and started after he installed the graphics card a few days ago (so probably new drivers, but it's not quite clear).
- msi rtx 4060 ti
- geforce game ready driver version 536.23 release date 06/14/2023

**Comment by GoogleFrog** [comment]
Hm or maybe its the spring_lua_alloc_log_error.

**Comment by sprunk** [comment]
```
[t=00:44:27.712433][f=0044942] Error: [LuaRules::RunCallInTraceback] error=4 (LUA_ERRMEM) callin=GameFrame trace=[Internal Lua error: Call failure] not enough memory
[t=00:44:27.826380][f=0044942] Fatal: [spring_lua_alloc_log_error][handle=LuaRules][OOM] synced=1 {alloced,maximum}={2684354821,2684354560}bytes
```
