### ISSUE TITLE
TrajectoryHeight MissileLauncher too timid about firing with terrain in the way.

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#869]
Here is a unit firing with a completely clear line of fire, the terrain is in the background, not in the way in any way.
![image](https://github.com/beyond-all-reason/spring/assets/1318249/d5f40093-6b69-45e5-9637-0af6279b3968)

I then built out the terrain. Weirdly the original shooting unit continues to shoot, but no new unit can be told to shoot.
![image](https://github.com/beyond-all-reason/spring/assets/1318249/b1046069-97b7-4aea-9007-47ff2cbc44fa)

Giving the shooting unit two wait orders interrupts it, and it can no longer shoot.
![image](https://github.com/beyond-all-reason/spring/assets/1318249/8df38e02-382d-42ac-abd2-642868ab1b8f)
This quirk isn't that important, I was mostly firing a consistent way to reproduce the bug I care about, which is that the MissileLaunchers should shoot if they have a clear line of fire according to their TrajectoryHeight. This may mess up homing MissileLaunchers, so perhaps there should be a parameter for how much leeway they leave around their trajectory.

**Comment by GoogleFrog** [comment]
This came up investigating why the tank here won't fire.
![image](https://github.com/beyond-all-reason/spring/assets/1318249/a41ec83f-46c7-41c6-961b-aa6db7f7c5e6)

It's trajectory height gives it a clear shot, but the small amount of terrain below the Crab stops it. More generally the issue hurts units with trajectory firing onto highground.

**Comment by KyleAnthonyShepherd** [comment]
What I am running into testing this is that TrajectoryHeight MissileLauncher seem feature-incomplete.
TrajectoryHeight MissileLauncher has a hard time targeting anything too high.
And there is no accommodation for missiles with acceleration.

Probably just need to copy over more Cannon code.

**Comment by GoogleFrog** [comment]
Which parts are incomplete? I am by default happy with how they aim and fire in cases where they actually aim and fire. Anything is fine as an option, we just shouldn't have forced balance changes for things like projectile physics and aiming.

**Comment by KyleAnthonyShepherd** [comment]
armsptk had an issue in BAR, where its missiles would accelerate up to a speed, but the trajectory prediction code assumes the missile is traveling at full speed the whole time, causing unnecessary terrain collisions. 

And the way TrajectoryHeight is done, to get the nice curved missile paths, essentially puts super high gravity on the missiles when fired at targets at short horizontal ranges (so a missile fired at a 45 degree angle upward TrajectoryHeight =1 can curve fast enough to be at a 45 degree angle downward at the target). So in the vs crab screenshot, that short of range is putting super high gravity on the missile (to get it to arc enough when shot at nearby targets), but that super high gravity makes the unit assume it cannot fire the missile high enough to reach the target. 

So some option will be needed to clarify what is the intended behavior when firing at targets with a much greater elevation difference than horizontal difference.

**Comment by GoogleFrog** [comment]
![image](https://github.com/beyond-all-reason/spring/assets/1318249/dba14734-534d-4ba2-8fe5-d6cf646ec800)
The unit in the screenshot (tankriot) has no trouble shooting very high. This is a screenshot after I told the unit to ignore terrain while aiming.

I am happy with how the ZK Recluse missile acceleration causes the peak of its trajectory to shift closer to Recluse than the target. But it is also unable to shoot more than ~200 elmos above itself. That is about the effective height of its trajectory so perhaps that makes sense.

**Comment by KyleAnthonyShepherd** [comment]
https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Sim/Weapons/MissileLauncher.cpp#L76
https://github.com/beyond-all-reason/spring/blob/BAR105/rts/Sim/Weapons/Cannon.cpp#L88

Comparing the ground collision check code, and it looks like cannons do not check collision for the last 10 elmos of horizontal distance `xzTargetDist - 10.0f` while MissileLauncher is checking the full distance.
So it might be getting false positives at the very end of the trajectory. 

And from this image (Gave BAR armsptk the same weapon parameters as ZK tankriot), the predicted trajectory [green arrows from /debugtraceray], is not accurate to the real trajectory. 
![image](https://github.com/beyond-all-reason/spring/assets/44480662/f527c168-ce7a-47f9-9bb2-5bc47b635240)

**Comment by sprunk** [comment]
> cannons do not check collision for the last 10 elmos of horizontal distance, while MissileLauncher is checking the full distance

This could be a weaponDef tag (defaulting to 10 for Cannons, 0 for MissileLauncher etc for backward compatibility).

**Comment by KyleAnthonyShepherd** [comment]
![image](https://github.com/beyond-all-reason/spring/assets/44480662/15fd6b7d-17d7-44f8-b1a9-862dba4b6283)
![image](https://github.com/beyond-all-reason/spring/assets/44480662/6f94d9ae-7ba0-4fcf-939d-7a70f6681a1f)

Missiles with trajectoryheight are *weird*.
You can get interesting trajectories with them, depending on trajectoryheight, maxspeed, initial speed, and acceleration. But I am pretty sure there is no simple equation to describe the trajectory. So it makes predicting their path, and checking for friendly fire and ground collisions difficult.

**Comment by KyleAnthonyShepherd** [comment]
![image](https://github.com/beyond-all-reason/spring/assets/44480662/741bb54f-af4b-4fbf-94e8-ad27856bb678)
Ok, figuring out how to predict trajectoryheight missiles. 
Green arrows is current erroneous predicted path (triggering false positives on friendlies, and terrain when aiming upwards)
And red line is current fixed prediction path.
I'll make the PR once I am sure the new method does not murder performance.

**Comment by sprunk** [comment]
eeb94e348dec92352a091402ed63a0a329edb074
