### ISSUE TITLE
FR: inline color codes for outline/shadow color

### ISSUE THREAD

**Issue by Arch-Shaman** [beyond-all-reason/spring#884]
https://discordapp.com/channels/278805140708786177/278908415756206080/1124240846259240971

**Comment by lhog** [comment]
TODO: Add alpha and shadow/outline color codes as option

**Comment by lhog** [comment]
Please try this version of the engine:
https://github.com/beyond-all-reason/spring/releases/tag/spring_bar_%7BBAR105%7D105.1.1-1923-gbd815da

As can be seen in the https://github.com/beyond-all-reason/spring/commit/ccc1fe7a9285e9bfa1b65e79adb3d19e87720eda you specify the primary and secondary colors as follows:
"\254<Rp><Gp><Bp><Ap><Rs><Gs><Bs><As>", where RGBAp is the primary font color and RGBAs - the secondary one.

**Comment by sprunk** [comment]
Done in ccc1fe7a9285e9bfa1b65e79adb3d19e87720eda
