### ISSUE TITLE
1821 Specfullview 0 cannot drag select units

### ISSUE THREAD

**Issue by GoogleFrog** [beyond-all-reason/spring#894]
![spring_cXYXPadz3Y](https://github.com/beyond-all-reason/spring/assets/1318249/9a7ccaa4-4941-4dd6-9953-d0b25fe635ff)
- Spectate a nullAI vs nullAI game
- /specfullview 0
- /luaui disable
- Attempt to select things. Drag select does not work.

Works fine on 1774. The issue replicates with ZK lua enabled. Not sure about BAR since I hear it somewhat reimplements selection rather than use the engine API for it.

**Comment by sprunk** [comment]
I bisected and it seems that 1780 is fine but 1781 is not. 294097ff7a224900a46504d08c3a22393bad4130

**Comment by lhog** [comment]
I'm on 1780, local build, drag select doesn't work in aforementioned circumstances too.

**Comment by lhog** [comment]
Same behavior with 1774.
One note though that I start a game vs NullAI and then `/cheat` `/spectator`, the rest is same as in your instruction. Does it matter?

**Comment by GoogleFrog** [comment]
![spring_NvGAU4fQHu](https://github.com/beyond-all-reason/spring/assets/1318249/21545eee-4988-4aa2-a42b-e7f821015fb0)

1774 works for me. Either with cheat spectator or just starting the game as a spectator.

**Comment by sprunk** [comment]
I've been using the builds at https://engine-builds.beyondallreason.dev/index.html

**Comment by lhog** [comment]
@sprunk, can you share NullAI-NullAI start script here, please.

**Comment by sprunk** [comment]
[script_qewqweqwe.txt](https://github.com/beyond-all-reason/spring/files/11995346/script_qewqweqwe.txt)

**Comment by sprunk** [comment]
actually hold on, I just re-rested to be sure and it also fails on 1780

**Comment by sprunk** [comment]
Now it fails for me on 1774 as well.

**Comment by sprunk** [comment]
I'll try going backwards to see if there's some old commit that works, probably I wasn't rigorous enough the first time.

**Comment by sprunk** [comment]
I think I found it and should be able to make a fix
