### ISSUE TITLE
Bugger off: add a "move radially" option and put it on structures

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#905]
Currently bugger-off makes units just pick a random spot outside the area:
![image](https://github.com/beyond-all-reason/spring/assets/2573076/86262335-1f90-47bd-973e-3c210448df79)

The first part of the request is to add the technical possibility for units to just escape radially outwards towards the closest edge:
![image](https://github.com/beyond-all-reason/spring/assets/2573076/25a0ae53-6540-4278-ac54-ac021235849f)

The second part of the request is to apply it builders who want to place a building:
https://github.com/beyond-all-reason/spring/blob/067bb79c01158c68058e8d589348e3d017ed02fe/rts/Sim/Units/CommandAI/BuilderCAI.cpp#L682-L689

Note that for factories this would be undesired because the buildpad is almost always in the same spot relative to the bugger-off area so units exiting factories without a rally queue would stack up in the same spot. For Lua bugger off API this would be controlled by another bool.

**Comment by marcushutchings** [comment]
Sounds like a great idea.

**Comment by GoogleFrog** [comment]
Sounds good. Bugger off retries might need to be randomly positioned though to deal with units trying to build something stuck in a corner.
![image](https://github.com/beyond-all-reason/spring/assets/1318249/c63bd85e-3134-42d6-9594-0d59855b0671)

Having the bugger off eventually work in all cases is more important than optimal.
