### ISSUE TITLE
Visible quads/tiles excessive related to camera frustum

### ISSUE THREAD

**Issue by dzosz** [beyond-all-reason/spring#932]
Use ingame command `/DebugVisibility` to mark visible quads.
Visible quads do not match the camera frustum as seen on screenshot from the minimap. 
![image](https://github.com/beyond-all-reason/spring/assets/13596691/b60aa643-3777-4bf1-891b-0d85f152182b)
![Screenshot from 2023-07-26 12-08-35](https://github.com/beyond-all-reason/spring/assets/13596691/112d406a-3043-4688-854b-55eccba0affc)

**Comment by sprunk** [comment]
Stuff in the outer quads can still cast shadows into the visible area; or just have a model bigger than its nominal radius (because a small radius has gameplay benefits); or maybe terrain can have dramatic height changes (check on a map with tall spikes or deep holes).

**Comment by dzosz** [comment]
> Stuff in the outer quads can still cast shadows

sounds about right. the direction of light influences the range of visible quads. Still, it seems a bit excessive.
Eight Horses 1.0:
![Screenshot from 2023-07-26 13-58-50](https://github.com/beyond-all-reason/spring/assets/13596691/425e8180-2aca-4d41-9561-85549443e73b)

**Comment by lhog** [comment]
Hold on, shadows have its own frustum and it can be seen with `/debugshadowfrustum`. `/debugvisibility` is supposed to cover only the frustum of player's camera, no relation to shadows/sunlight direction.

**Comment by dzosz** [comment]
Does not occur on main branch.

**Comment by lhog** [comment]
Hmm perhaps make a second instance of `DebugVisibilityDrawer` class for shadows pass, if you need it.
