### ISSUE TITLE
Nanoframe Build Stacking - Release 1901

### ISSUE THREAD

**Issue by KyleAnthonyShepherd** [beyond-all-reason/spring#952]
![image](https://github.com/beyond-all-reason/spring/assets/44480662/76c0c1fd-50bd-40cb-9388-781e0acef337)
Told 16 builders (BAR corfast) to build a wall. 
6 walls were built on top of each other.

I suspect this bug was introduced with the change that causes builders to consider unit radius when placing nanoframes. 
https://github.com/beyond-all-reason/spring/commit/2069e3ab81e386c6723dd998e9aaa70f2f8f2f1e

**Comment by lhog** [comment]
Is https://github.com/beyond-all-reason/spring/commit/2069e3ab81e386c6723dd998e9aaa70f2f8f2f1e guilty for sure?

**Comment by 6AKU66** [comment]
Bisected to https://github.com/beyond-all-reason/spring/commit/5467729b57d8d30375bf1910d1b7ed493c7d75eb
105.1.1-1871-g5467729
https://youtu.be/YsF1qrstVrc
