### ISSUE TITLE
[FR] Making a big-resolution screenshot

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#955]
The request is to allow making a screenshot in a resolution larger than the current screen, for example for beauty shots in news posts etc. See @ForbodingAngel for details.

**Comment by lhog** [comment]
We can add 1001st springsetting to disable embedded window geometry sanity checks (very much relaxed from the initial ones), but the task doesn't feel worthy enough to do so.

For now I'd say use social means (ask people with 4k displays or write a widget that syncs spectators cameras to your current camera position and orientation, so they can make screenshots on their 4k displays).

Also I've heard Nvidia control panel allow to run a game in the super resolution mode.

In the future it **might** become possible to untie rendering and presentation geometries, but I assume it'd be mostly relevant to support things like AMD SSR. This could also coincide with the introduction of HDR rendering framebuffers. But frankly it's all so distant, I wouldn't bet on that much.
