### ISSUE TITLE
Altering basic game mechanics without LUA 

### ISSUE THREAD

**Issue by tizbac** [beyond-all-reason/spring#960]
This is not actually an issue but more like a topic to discuss an aspect of customization
I was thinking about customizing for example resource types, how resources are consumed, how unit attack speed varies based on other parameter, or for example the capture speed which is all hardcoded in engine for performance reasons.
The list could go on a lot...
Lua of course would be too slow to handle even energy/metal usage or single damages to units

Would be acceptable for the devs doing something like that:

1. Allow adding C++ files inside mods themselves
2. Use LLVM to compile them to binary code at game launch 
3. Use existing vtable mechanism or something similiar to swap function calls to such methods provided by the mod/game 
4. Implement some sort of cache to compile these CPP files inside the mod only once if not changed 

I could do it ( or at least try to , for now don't know when ) if it has at least potential to be merged 
On the dark side LLVM will add something like 60MB of engine footprint if not more

**Comment by sprunk** [comment]
> Lua of course would be too slow to handle even energy/metal usage or single damages to units

Have you seen what existing games do? ZK reimplements resource incomes and has every single projectile and damage event go through multiple lua gadgets and it's not really a perf problem. It even uses AllowUnitBuildStep which is considered one of the worst lua callins as far as performance goes. The engine could expose things there but they should be targeted interfaces.

> attack speed varies based on other parameter, or for example the capture speed which is all hardcoded in engine for performance reasons.

There's lua calls to alter these, ZK has slows which change attack speed.

> C++

Sounds like a nightmare to debug if somebody sends a desync report.

**Comment by lhog** [comment]
This one is very futuristic, I don't think it's doable in any observable future, unless the author @tizbac wants to lead the effort.

**Comment by marcushutchings** [comment]
I think this would need a full design proposal and review. Effort in this area would need guidance lest it smashes into many of the gotchas around the engine.

**Comment by sprunk** [comment]
Here's some questions that a design proposal would ideally address:
* how do you handle people shooting themselves in the foot (memleak, desync, accessing what shouldn't be visible, etc)?
* how do you make sure engine devs don't waste their precious time debugging gamedev issues when people do inevitably shoot themselves in the foot and blame the engine?
* how do you make sure game development remains reasonably easy to get into? Lua makes it easy for newbie modders to work with snippets from various games. Won't major games ruin that by making their core gameplay code C++? Precedent: BAR using BOS/COB over LUS.

Reopen if there's a design.

**Comment by keithharvey** [comment]
I'm not sure I would open this up to the modding world in any way for quite some time. We could keep it signed and internal modules only at first. I think the "public mods need native code" isn't as strong or as an easy of a problem to solve as "we need native code ourselves".  

> how do you handle people shooting themselves in the foot (memleak, desync, accessing what shouldn't be visible, etc)?
> how do you make sure engine devs don't waste their precious time debugging gamedev issues when people do inevitably shoot themselves in the foot and blame the engine?

hard caps on the module sandbox, strict API contracts, good logging/telemetry at the edges, offload as much of the API as we can to push events. For core BAR modules I would sign them, test them with performance smokescreen tests that do real and ridiculous things, then hard cap memory consumption on the sandbox, and see if it deviates from master branch baselines in module PR CI.

> how do you make sure game development remains reasonably easy to get into?

I honestly think this would make it easier for us. We don't have to explain all of the runtime constraints of our vm and lua 5.1 to seasoned developers. There will be less performance finger wagging and expertise necessary for gameside PRs. Our connection points with the engine will be strongly typed and generated in whatever language. It's worth pointing out that UNTIL our tooling like hot module swapping and probably some cacophonous cousin of docker-build-v2 were up to speed, this would be less true. But we could just not move on this until we had the tooling done to current standards.

> Lua makes it easy for newbie modders to work with snippets from various games.

Yea but the tooling, runtime, ecosystem and language features are pretty big downsides of lua 5.1, even in the context of game development. Especially if you want to take the DX beyond real time manual testing in-engine, where LUA shines.

> Won't major games ruin that by making their core gameplay code C++? Precedent: BAR using BOS/COB over LUS.

I think this would actually fix that problem and would be one of the biggest wins of a transpiler. BAR could switch to LUA 5.4. Bar could switch to C#. Whatever gives us the tooling we want and lets us borrow from the biggest ecosystem of game devs.  We could unify that entire engine API at the cost of a single breaking migration. We would have the ability to make bulletproof and integration tested modules in BAR exemplars that could then be shared easily with COB and visa versa. We could replace the broken lua examples in this way during the migration.

**Comment by lostsquirrel1** [comment]
My biggest concern is desyncs. Game devs are ill equipped to deal with this class of error. Engine devs have often been called in during desync investigations. It takes a lot of our time, and our policy is to remove all means by which the game devs are able to cause desyncs, which is only possible by restricting them to an interpreted language such as Lua.

The moment any game starts writing their own native code, then they take full responsibility for all desync investigations on their own game. I've seen several tasks/projects abandoned in the engine space because the desyncs couldn't be resolved before the dev's mana ran out. I wouldn't want to see the curse of desyncs filter so freely into game dev side of the project.

I'm also concerned that the programming burden will increase on the game devs and introducing native modules will reduce collaboration with the contributors who have to stick to Lua.

Side note/reminder on Lua versions: ALL previous attempts to move to a different version of Lua have failed.
