### ISSUE TITLE
Get rid of changelog redundancy

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#966]
There's currently two: a ticket at #171 and a txt file at https://github.com/beyond-all-reason/spring/blob/BAR105/doc/changelog.txt . There's also what's effectively a "breaking changes and how to work around them" page at https://beyond-all-reason.github.io/spring/migrating-from-spring/ which has some overlap but fulfils a different purpose and should stay regardless. Then there's https://github.com/beyond-all-reason/spring/wiki/Recoil-RTS-engine-changes which only really contains the link to #171.

* the txt must exist because that is where the Picassos of the world will look for 105 -> R migration, since it's where it has always been. But it doesn't necessarily have to contain anything other than a link to some proper content (be that #171, a github.io docs page or anything else) for that case.
* I originally made #171 because I had no write access to the repo, I didn't want to make a ton of PRs for the txt every time somebody forgot to add a line with a change, most of the changes at the time were outside my areas of expertise where I had to settle for a \<FIXME\> note, and there was the general turmoil around the time of the fork when maintaining a changelog was not really a primary concern. All of these concerns are now moot, for me specifically, though some still apply to anybody else who would want to volunteer to maintain the changelog.
* I feel like the authoritative changelog should still be in the repo, because everything else is transient. What if something happens to github, or just the ticket? What if there's another fork (putting people back in the role of the aforementioned picasso)?
* the txt file is ugly though, while the ticket has nice formatting and structure and all. But remember we aren't limited to the two, perhaps there could be a github.io page since that's where the rest of the documentation is supposed to be at some point?
* I think one of the original reasons for having an explicit txt file may have been for GPL v2 § 2a compliance ("prominent notice how the files were changed") since I've seen a lot of projects from the 00's to have a changelog file for that reason. But I believe this has always been moot thanks to git version control, mentioning this just for Chesterton's fence reasons.

In that vein how about this plan:
* add a github.io site page in parallel to the "migrating from Spring" page.
* populate it with the contents of the ticket and remove the ticket.
* populate the txt with links to github.io pages and stop maintaining that.

**Comment by lhog** [comment]
All good thoughts. Ideally it should exists in the repo and have a reference at github.io.
I'm super bad at updating `changelog.txt` because I always forget to touch it during each PR and later on I often find it's easier to update https://github.com/beyond-all-reason/spring/discussions/171

P.S. I know other projects manage to collect all PRs per release in a github release page (e.g. https://github.com/containerd/containerd/releases ), but idk if they do it automatically.

**Comment by sprunk** [comment]
Article added, redirection in oldschool `changelog.txt` added. Also added a note to #171. We will see how it goes.

**Comment by p2004a** [comment]
@sprunk 2 questions:
- I see ticket is closed, but I believe that https://github.com/beyond-all-reason/spring/discussions/171 was not migrated to neither `changelog.txt` nor the site, above you wrote "populate it with the contents of the ticket and remove the ticket", you changed your mind, or?
- What is the procedure when I'm making the changes? I was told in the past that pr-downloader changes should also be added to the engine changelog as that's where it's distributed, should I add them now under new section in [running-changelog](https://github.com/beyond-all-reason/spring/blob/BAR105/doc/site/changelogs/running-changelog.markdown) or something else?

**Comment by sprunk** [comment]
1) Migrating #171 is not yet complete but #171 is still open, and you can add more entries there.

2) It's best to add to the new `running-changelog`, but so far there hasn't been an "official" procedure change so people can still add to either `changelog.txt` or #171 since I monitor those two (and the commit log in case people skip changelog completely) and populate the running changelog.

My experience is that engine devs tend to be fairly crap at writing changelogs in the way that is most useful for game devs so ideally the final changelog should be written by somebody who is to some extent both (this currently means myself). I'm fairly happy with the current state of affairs where there's somebody responsible for managing it and I plan to let the current "people can be gently directed to running changelog, but can also write elsewhere (or nowhere at all) and I handle this" state of affairs stay for a while to see how people approach it.

**Comment by p2004a** [comment]
Ack, thanks for explanation!

**Comment by sprunk** [comment]
Articles for older versions created (migrated from 171).

**Comment by lhog** [comment]
How do we enter new items properly?

**Comment by sprunk** [comment]
Two basic choices:
* write to the article (`site/changelogs/running-changelog`) directly.
* write in #171. It's still open, I monitor it and format it nicely in the article.


The article is (supposed to be) the final official changelog so in theory it's the better one to use. But I would want to keep the article written in a way most useful to game devs, and I wouldn't want engine devs burdened with writing prose, so I'm not yet sure whether the article should be encouraged. If I get hit by a bus you should probably write to the article but for now feel free to do whichever way is the most convenient to you, I'm happy to maintain it regardless.

If you do it the oldschool way (i.e. either put them in `changelog.txt` or just completely forget to write anything at all) it's also fine, I monitor the txt and the commit log as well, but these are discouraged.
