### ISSUE TITLE
Buildings stack with each other (1871)

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/spring#975]
Bisected to https://github.com/beyond-all-reason/spring/commit/5467729b57d8d30375bf1910d1b7ed493c7d75eb
105.1.1-1871-g5467729
https://youtu.be/YsF1qrstVrc

**Comment by 6AKU66** [comment]
Probably dublicate of https://github.com/beyond-all-reason/spring/issues/952

**Comment by lhog** [comment]
Probably fixed. Reopen if not.
