### ISSUE TITLE
Boned .dae crash

### ISSUE THREAD

**Issue by sprunk** [beyond-all-reason/spring#998]
[bones.zip](https://github.com/beyond-all-reason/spring/files/12591496/bones.zip)

Here's a model:
 * `bones.dae` is a model with bones. It crashes Recoil on load with an unhandled exception.
 * `nobones.dae` is the same model, with bones removed. It loads fine.
 * `tex.dds` is the texture in case it's needed (it has compression artifacts, don't worry about them).

**Comment by sprunk** [comment]
[bomberheavy.zip](https://github.com/beyond-all-reason/spring/files/12599180/bomberheavy.zip)
Unit def (ZK `bomberheavy.lua` except `objectName` is changed to the new model) and script (also ZK `bomberheavy` except all logic uses piece `1` because there is a different hierarchy than the previous model)

**Comment by lhog** [comment]
The model is not 100% correct, https://github.com/beyond-all-reason/spring/commit/b0494c91b358495281cfb7f65b47bb2d35abfe7c should remediate the issue a little bit.
